"use strict";

// test/erzaehler.ts
var import_jsdom = require("jsdom");
var import_fs = require("fs");

// src/text-utils.ts
function clean(s) {
  return (s ?? "").toString().trim().replace(/\s+/g, " ");
}
var MONATE = /^(?:Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember|Jahrhunderts?|Jh\.|Hälfte|Auflage|Band|Kapitel|Absatz|Teil)\b/u;
var ORDNUNGSZAHL = /\d\.$/;
var ABKUERZUNG = /(?:^|\s)(?:[A-Za-zÄÖÜäöü]|ca|bzw|bspw|evtl|ggf|inkl|Nr|St|Dr|Prof|Abs|Art|Bd|Hrsg|usw|etc)\.$/u;
function keineGrenze(vor, nach) {
  if (ABKUERZUNG.test(vor)) return true;
  if (!ORDNUNGSZAHL.test(vor)) return false;
  return MONATE.test(nach) || /^\d/.test(nach);
}
function splitSentences(txt) {
  const flach = txt.replace(/\s+/g, " ").trim();
  const roh = flach.split(/(?<=[.!?…])\s+/).filter(Boolean);
  const raus = [];
  for (const teil of roh) {
    const vor = raus[raus.length - 1];
    if (vor && keineGrenze(vor, teil)) raus[raus.length - 1] = vor + " " + teil;
    else raus.push(teil);
  }
  return raus;
}

// src/generation/verbconj.data.ts
var VERB_CONJ = {
  "bemerkt": {
    "ich": "bemerke",
    "du": "bemerkst",
    "wir": "bemerken",
    "ihr": "bemerkt"
  },
  "nimmt": {
    "ich": "nehme",
    "du": "nimmst",
    "wir": "nehmen",
    "ihr": "nehmt"
  },
  "steht": {
    "ich": "stehe",
    "du": "stehst",
    "wir": "stehen",
    "ihr": "steht"
  },
  "h\xE4lt": {
    "ich": "halte",
    "du": "h\xE4ltst",
    "wir": "halten",
    "ihr": "haltet"
  },
  "sucht": {
    "ich": "suche",
    "du": "suchst",
    "wir": "suchen",
    "ihr": "sucht"
  },
  "versucht": {
    "ich": "versuche",
    "du": "versuchst",
    "wir": "versuchen",
    "ihr": "versucht"
  },
  "will": {
    "ich": "will",
    "du": "willst",
    "wir": "wollen",
    "ihr": "wollt"
  },
  "kann": {
    "ich": "kann",
    "du": "kannst",
    "wir": "k\xF6nnen",
    "ihr": "k\xF6nnt"
  },
  "muss": {
    "ich": "muss",
    "du": "musst",
    "wir": "m\xFCssen",
    "ihr": "m\xFCsst"
  },
  "darf": {
    "ich": "darf",
    "du": "darfst",
    "wir": "d\xFCrfen",
    "ihr": "d\xFCrft"
  },
  "mag": {
    "ich": "mag",
    "du": "magst",
    "wir": "m\xF6gen",
    "ihr": "m\xF6gt"
  },
  "soll": {
    "ich": "soll",
    "du": "sollst",
    "wir": "sollen",
    "ihr": "sollt"
  },
  "m\xF6chte": {
    "ich": "m\xF6chte",
    "du": "m\xF6chtest",
    "wir": "m\xF6chten",
    "ihr": "m\xF6chtet"
  },
  "ist": {
    "ich": "bin",
    "du": "bist",
    "wir": "sind",
    "ihr": "seid"
  },
  "wird": {
    "ich": "werde",
    "du": "wirst",
    "wir": "werden",
    "ihr": "werdet"
  },
  "geht": {
    "ich": "gehe",
    "du": "gehst",
    "wir": "gehen",
    "ihr": "geht"
  },
  "kommt": {
    "ich": "komme",
    "du": "kommst",
    "wir": "kommen",
    "ihr": "kommt"
  },
  "bleibt": {
    "ich": "bleibe",
    "du": "bleibst",
    "wir": "bleiben",
    "ihr": "bleibt"
  },
  "\xF6ffnet": {
    "ich": "\xF6ffne",
    "du": "\xF6ffnest",
    "wir": "\xF6ffnen",
    "ihr": "\xF6ffnet"
  },
  "schlie\xDFt": {
    "ich": "schlie\xDFe",
    "du": "schlie\xDFt",
    "wir": "schlie\xDFen",
    "ihr": "schlie\xDFt"
  },
  "fragt": {
    "ich": "frage",
    "du": "fragst",
    "wir": "fragen",
    "ihr": "fragt"
  },
  "f\xFChrt": {
    "ich": "f\xFChre",
    "du": "f\xFChrst",
    "wir": "f\xFChren",
    "ihr": "f\xFChrt"
  },
  "begreift": {
    "ich": "begreife",
    "du": "begreifst",
    "wir": "begreifen",
    "ihr": "begreift"
  },
  "bricht": {
    "ich": "breche",
    "du": "brichst",
    "wir": "brechen",
    "ihr": "brecht"
  },
  "kippt": {
    "ich": "kippe",
    "du": "kippst",
    "wir": "kippen",
    "ihr": "kippt"
  },
  "l\xF6scht": {
    "ich": "l\xF6sche",
    "du": "l\xF6schst",
    "wir": "l\xF6schen",
    "ihr": "l\xF6scht"
  },
  "tut": {
    "ich": "tue",
    "du": "tust",
    "wir": "tun",
    "ihr": "tut"
  },
  "macht": {
    "ich": "mache",
    "du": "machst",
    "wir": "machen",
    "ihr": "macht"
  },
  "sieht": {
    "ich": "sehe",
    "du": "siehst",
    "wir": "sehen",
    "ihr": "seht"
  },
  "gibt": {
    "ich": "gebe",
    "du": "gibst",
    "wir": "geben",
    "ihr": "gebt"
  },
  "tr\xE4gt": {
    "ich": "trage",
    "du": "tr\xE4gst",
    "wir": "tragen",
    "ihr": "tragt"
  },
  "h\xF6rt": {
    "ich": "h\xF6re",
    "du": "h\xF6rst",
    "wir": "h\xF6ren",
    "ihr": "h\xF6rt"
  },
  "findet": {
    "ich": "finde",
    "du": "findest",
    "wir": "finden",
    "ihr": "findet"
  },
  "ber\xFChrt": {
    "ich": "ber\xFChre",
    "du": "ber\xFChrst",
    "wir": "ber\xFChren",
    "ihr": "ber\xFChrt"
  },
  "beobachtet": {
    "ich": "beobachte",
    "du": "beobachtest",
    "wir": "beobachten",
    "ihr": "beobachtet"
  },
  "kennt": {
    "ich": "kenne",
    "du": "kennst",
    "wir": "kennen",
    "ihr": "kennt"
  },
  "nennt": {
    "ich": "nenne",
    "du": "nennst",
    "wir": "nennen",
    "ihr": "nennt"
  },
  "sp\xFCrt": {
    "ich": "sp\xFCre",
    "du": "sp\xFCrst",
    "wir": "sp\xFCren",
    "ihr": "sp\xFCrt"
  },
  "wei\xDF": {
    "ich": "wei\xDF",
    "du": "wei\xDFt",
    "wir": "wissen",
    "ihr": "wisst"
  },
  "braucht": {
    "ich": "brauche",
    "du": "brauchst",
    "wir": "brauchen",
    "ihr": "braucht"
  },
  "w\xFCnscht": {
    "ich": "w\xFCnsche",
    "du": "w\xFCnschst",
    "wir": "w\xFCnschen",
    "ihr": "w\xFCnscht"
  },
  "hofft": {
    "ich": "hoffe",
    "du": "hoffst",
    "wir": "hoffen",
    "ihr": "hofft"
  },
  "tr\xE4umt": {
    "ich": "tr\xE4ume",
    "du": "tr\xE4umst",
    "wir": "tr\xE4umen",
    "ihr": "tr\xE4umt"
  },
  "plant": {
    "ich": "plane",
    "du": "planst",
    "wir": "planen",
    "ihr": "plant"
  },
  "f\xFCrchtet": {
    "ich": "f\xFCrchte",
    "du": "f\xFCrchtest",
    "wir": "f\xFCrchten",
    "ihr": "f\xFCrchtet"
  },
  "wartet": {
    "ich": "warte",
    "du": "wartest",
    "wir": "warten",
    "ihr": "wartet"
  },
  "glaubt": {
    "ich": "glaube",
    "du": "glaubst",
    "wir": "glauben",
    "ihr": "glaubt"
  },
  "denkt": {
    "ich": "denke",
    "du": "denkst",
    "wir": "denken",
    "ihr": "denkt"
  },
  "f\xFChlt": {
    "ich": "f\xFChle",
    "du": "f\xFChlst",
    "wir": "f\xFChlen",
    "ihr": "f\xFChlt"
  },
  "verlangt": {
    "ich": "verlange",
    "du": "verlangst",
    "wir": "verlangen",
    "ihr": "verlangt"
  },
  "erwartet": {
    "ich": "erwarte",
    "du": "erwartest",
    "wir": "erwarten",
    "ihr": "erwartet"
  },
  "riskiert": {
    "ich": "riskiere",
    "du": "riskierst",
    "wir": "riskieren",
    "ihr": "riskiert"
  },
  "wagt": {
    "ich": "wage",
    "du": "wagst",
    "wir": "wagen",
    "ihr": "wagt"
  },
  "flieht": {
    "ich": "fliehe",
    "du": "fliehst",
    "wir": "fliehen",
    "ihr": "flieht"
  },
  "jagt": {
    "ich": "jage",
    "du": "jagst",
    "wir": "jagen",
    "ihr": "jagt"
  },
  "folgt": {
    "ich": "folge",
    "du": "folgst",
    "wir": "folgen",
    "ihr": "folgt"
  },
  "verfolgt": {
    "ich": "verfolge",
    "du": "verfolgst",
    "wir": "verfolgen",
    "ihr": "verfolgt"
  },
  "rettet": {
    "ich": "rette",
    "du": "rettest",
    "wir": "retten",
    "ihr": "rettet"
  },
  "verr\xE4t": {
    "ich": "verrate",
    "du": "verr\xE4tst",
    "wir": "verraten",
    "ihr": "verratet"
  },
  "vergisst": {
    "ich": "vergesse",
    "du": "vergisst",
    "wir": "vergessen",
    "ihr": "vergesst"
  },
  "hatte": {
    "ich": "hatte",
    "du": "hattest",
    "wir": "hatten",
    "ihr": "hattet"
  },
  "war": {
    "ich": "war",
    "du": "warst",
    "wir": "waren",
    "ihr": "wart"
  },
  "wollte": {
    "ich": "wollte",
    "du": "wolltest",
    "wir": "wollten",
    "ihr": "wolltet"
  },
  "tat": {
    "ich": "tat",
    "du": "tatest",
    "wir": "taten",
    "ihr": "tatet"
  },
  "machte": {
    "ich": "machte",
    "du": "machtest",
    "wir": "machten",
    "ihr": "machtet"
  },
  "kam": {
    "ich": "kam",
    "du": "kamst",
    "wir": "kamen",
    "ihr": "kamt"
  },
  "ging": {
    "ich": "ging",
    "du": "gingst",
    "wir": "gingen",
    "ihr": "gingt"
  },
  "f\xFChrte": {
    "ich": "f\xFChrte",
    "du": "f\xFChrtest",
    "wir": "f\xFChrten",
    "ihr": "f\xFChrtet"
  },
  "schloss": {
    "ich": "schloss",
    "du": "schlossest",
    "wir": "schlossen",
    "ihr": "schlosst"
  },
  "fragte": {
    "ich": "fragte",
    "du": "fragtest",
    "wir": "fragten",
    "ihr": "fragtet"
  },
  "begriff": {
    "ich": "begriff",
    "du": "begriffst",
    "wir": "begriffen",
    "ihr": "begrifft"
  },
  "stellt": {
    "ich": "stelle",
    "du": "stellst",
    "wir": "stellen"
  },
  "erkennt": {
    "ich": "erkenne",
    "du": "erkennst",
    "wir": "erkennen"
  },
  "zeigt": {
    "ich": "zeige",
    "du": "zeigst",
    "wir": "zeigen"
  },
  "greift": {
    "ich": "greife",
    "du": "greifst",
    "wir": "greifen"
  },
  "legt": {
    "ich": "lege",
    "du": "legst",
    "wir": "legen"
  },
  "betrachtet": {
    "ich": "betrachte",
    "du": "betrachtest",
    "wir": "betrachten"
  },
  "setzt": {
    "ich": "setze",
    "du": "setzt",
    "wir": "setzen"
  },
  "merkt": {
    "ich": "merke",
    "du": "merkst",
    "wir": "merken"
  },
  "pr\xFCft": {
    "ich": "pr\xFCfe",
    "du": "pr\xFCfst",
    "wir": "pr\xFCfen"
  }
};
var INFINITIVE_VERBS = /* @__PURE__ */ new Set(["entdecken", "finden", "verstehen", "erreichen", "verlassen", "retten", "zerst\xF6ren", "beweisen", "\xFCberleben", "fliehen", "gewinnen", "verlieren", "\xF6ffnen", "schlie\xDFen", "verschwinden", "sterben", "bleiben", "ankommen", "entkommen", "aufwachen", "vergessen", "lernen", "ver\xE4ndern", "kontrollieren", "sch\xFCtzen", "befreien", "heilen", "erschaffen", "reparieren", "beenden", "anfangen", "beginnen", "erinnern", "wissen", "glauben", "tr\xE4umen", "hoffen", "k\xE4mpfen", "siegen", "sprechen", "schweigen", "warten", "folgen", "fragen", "antworten", "erkl\xE4ren", "gehen", "kommen"]);

// src/generation/nouns.data.ts
var NOUN_GENDER = {
  "abdruck": "m",
  "abend": "m",
  "abgrund": "m",
  "absatz": "m",
  "abschalten": "n",
  "abstand": "m",
  "acker": "m",
  "ader": "f",
  "adressbuch": "n",
  "adresse": "f",
  "ahnung": "f",
  "airpod": "m",
  "akku": "m",
  "akte": "f",
  "aktendeckel": "m",
  "aktennotiz": "f",
  "allee": "f",
  "alptraum": "m",
  "altar": "m",
  "alte": "f",
  "alter": "n",
  "amt": "n",
  "amulett": "n",
  "angebot": "n",
  "angst": "f",
  "anker": "m",
  "antenne": "f",
  "antrag": "m",
  "antwort": "f",
  "apfel": "m",
  "applaus": "m",
  "archiv": "n",
  "arm": "m",
  "armband": "n",
  "armbrust": "f",
  "art": "f",
  "arzt": "m",
  "asche": "f",
  "ast": "m",
  "atelier": "n",
  "atem": "m",
  "atmosph\xE4re": "f",
  "aufkleber": "m",
  "aufnahme": "f",
  "auftrag": "m",
  "auge": "n",
  "augenblick": "m",
  "augenlid": "n",
  "ausdehnung": "f",
  "ausgang": "m",
  "ausnahme": "f",
  "ausrede": "f",
  "ausweis": "m",
  "axiom": "n",
  "baby": "n",
  "bach": "m",
  "backup": "n",
  "badeanstalt": "f",
  "bahn": "f",
  "bahnkarte": "f",
  "balkon": "m",
  "ball": "m",
  "ballade": "f",
  "band": "n",
  "bank": "f",
  "banner": "n",
  "basecap": "n",
  "bau": "m",
  "bauch": "m",
  "bauer": "m",
  "baum": "m",
  "becher": "m",
  "befehl": "m",
  "begriff": "m",
  "beil": "n",
  "bein": "n",
  "benachrichtigung": "f",
  "berg": "m",
  "bergfried": "m",
  "bericht": "m",
  "bescheid": "m",
  "beschluss": "m",
  "besen": "m",
  "besitz": "m",
  "bestand": "m",
  "besuch": "m",
  "betonprobe": "f",
  "bett": "n",
  "beutel": "m",
  "beweis": "m",
  "bibel": "f",
  "bibliothek": "f",
  "biene": "f",
  "bild": "n",
  "bildschirm": "m",
  "binde": "f",
  "birne": "f",
  "blatt": "n",
  "blechb\xFCchse": "f",
  "blechdose": "f",
  "blechkanne": "f",
  "blechtrompete": "f",
  "blei": "n",
  "bleistift": "m",
  "blende": "f",
  "blick": "m",
  "blitz": "m",
  "blume": "f",
  "blumenstrau\xDF": "m",
  "bluse": "f",
  "bl\xFCte": "f",
  "boden": "m",
  "bohne": "f",
  "bohrkern": "m",
  "bohrprobe": "f",
  "boje": "f",
  "bonbon": "n",
  "boot": "n",
  "bote": "m",
  "botschaft": "f",
  "braten": "m",
  "braue": "f",
  "brett": "n",
  "brief": "m",
  "briefumschlag": "m",
  "brille": "f",
  "brot": "n",
  "brotdose": "f",
  "brotlaib": "m",
  "bruch": "m",
  "bruder": "m",
  "brunnen": "m",
  "brust": "f",
  "br\xFCcke": "f",
  "br\xFChe": "f",
  "buch": "n",
  "buchstabe": "m",
  "bucht": "f",
  "bug": "m",
  "burg": "f",
  "bus": "m",
  "busch": "m",
  "butter": "f",
  "b\xE4r": "m",
  "b\xFChne": "f",
  "b\xFCndel": "n",
  "b\xFCrde": "f",
  "cache": "m",
  "cadtablet": "n",
  "caf": "n",
  "caf\xE9": "n",
  "chat": "m",
  "clown": "m",
  "computer": "m",
  "container": "m",
  "couch": "f",
  "dach": "n",
  "dachboden": "m",
  "dame": "f",
  "damm": "m",
  "dashboard": "n",
  "datei": "f",
  "dattel": "f",
  "datum": "n",
  "daumen": "m",
  "deck": "n",
  "decke": "f",
  "deckel": "m",
  "denkmalschutz": "m",
  "deo": "n",
  "detail": "n",
  "detektor": "m",
  "detektorkopf": "m",
  "dewar": "m",
  "diagramm": "n",
  "dichter": "m",
  "dieb": "m",
  "dienst": "m",
  "direktor": "m",
  "dnaspirale": "f",
  "dokument": "n",
  "dolch": "m",
  "donner": "m",
  "dorf": "n",
  "dorn": "m",
  "dose": "f",
  "draht": "m",
  "droschke": "f",
  "druck": "m",
  "duell": "n",
  "duft": "m",
  "durchsage": "f",
  "durchschlag": "m",
  "d\xE4mmerung": "f",
  "ebbe": "f",
  "ebene": "f",
  "echo": "n",
  "ecke": "f",
  "ehre": "f",
  "ei": "n",
  "eid": "m",
  "einspruch": "m",
  "eis": "n",
  "eisen": "n",
  "elch": "m",
  "elend": "n",
  "ellbogen": "m",
  "emoji": "n",
  "engel": "m",
  "enkel": "m",
  "ente": "f",
  "entwurf": "m",
  "ephemeride": "f",
  "erbe": "n",
  "erbse": "f",
  "erdbeben": "n",
  "erde": "f",
  "erinnerung": "f",
  "etikett": "n",
  "eule": "f",
  "ewigkeit": "f",
  "fabel": "f",
  "fabrik": "f",
  "fackel": "f",
  "faden": "m",
  "fahne": "f",
  "fahrschein": "m",
  "fahrt": "f",
  "falle": "f",
  "falte": "f",
  "farbe": "f",
  "farbenscheibe": "f",
  "fass": "n",
  "faust": "f",
  "feder": "f",
  "federkiel": "m",
  "fee": "f",
  "fehlercode": "m",
  "feile": "f",
  "feind": "m",
  "feld": "n",
  "feldbesteck": "n",
  "felder": "n",
  "fell": "n",
  "fellhandschuh": "m",
  "fels": "m",
  "felsen": "m",
  "fenster": "n",
  "fensterplatz": "m",
  "ferkel": "n",
  "ferne": "f",
  "fernglas": "n",
  "fernrohr": "n",
  "ferse": "f",
  "fessel": "f",
  "festung": "f",
  "feuer": "n",
  "feuerzeug": "n",
  "fibel": "f",
  "fieber": "n",
  "filter": "m",
  "finger": "m",
  "fingerhut": "m",
  "fisch": "m",
  "fischer": "m",
  "flakon": "m",
  "flasche": "f",
  "flaute": "f",
  "fleisch": "n",
  "fliege": "f",
  "flo\xDF": "n",
  "fluch": "m",
  "flucht": "f",
  "flur": "m",
  "fluss": "m",
  "flut": "f",
  "fl\xE4che": "f",
  "fl\xF6te": "f",
  "fl\xFCstern": "n",
  "formel": "f",
  "formular": "n",
  "fossil": "n",
  "fossilie": "f",
  "foto": "n",
  "fotografie": "f",
  "frachtbrief": "m",
  "frage": "f",
  "frau": "f",
  "freude": "f",
  "freund": "m",
  "frist": "f",
  "frost": "m",
  "frucht": "f",
  "fr\xFChling": "m",
  "fuchs": "m",
  "fuge": "f",
  "fund": "m",
  "fundament": "n",
  "funke": "m",
  "funkger\xE4t": "n",
  "furcht": "f",
  "furt": "f",
  "fu\xDF": "m",
  "f\xE4hrmann": "m",
  "f\xE4hrplan": "m",
  "f\xE4sser": "n",
  "f\xFCrst": "m",
  "gabe": "f",
  "gabel": "f",
  "gabelung": "f",
  "galaxie": "f",
  "gang": "m",
  "gans": "f",
  "garn": "n",
  "garten": "m",
  "gasse": "f",
  "gast": "m",
  "gebet": "n",
  "gebetbuch": "n",
  "gebete": "n",
  "gebetsschale": "f",
  "gebirge": "n",
  "geb\xE4lk": "n",
  "geb\xE4ude": "n",
  "gedanke": "m",
  "gedanken": "m",
  "gedicht": "n",
  "gedichte": "n",
  "geduld": "f",
  "gefahr": "f",
  "gef\xFChl": "n",
  "gef\xFChlen": "n",
  "gegend": "f",
  "gegensatz": "m",
  "gegenstand": "m",
  "gegens\xE4tze": "m",
  "gegenteil": "n",
  "gegenwart": "f",
  "gegners": "m",
  "geheimnis": "n",
  "gehirn": "n",
  "geh\xE4use": "n",
  "geige": "f",
  "geist": "m",
  "geleitbrief": "m",
  "gel\xE4nde": "n",
  "gel\xFCbde": "n",
  "gemach": "n",
  "gem\xE4lde": "n",
  "gem\xFCse": "n",
  "gep\xE4ck": "n",
  "gericht": "n",
  "geruch": "m",
  "ger\xE4t": "n",
  "ger\xE4usch": "n",
  "ger\xE4usche": "n",
  "ger\xF6ll": "n",
  "ger\xFCcht": "n",
  "ger\xFCchte": "n",
  "ger\xFCst": "n",
  "gesangbuch": "n",
  "geschenk": "n",
  "geschichte": "f",
  "geschichten": "f",
  "geschmack": "m",
  "gesetz": "n",
  "gesetze": "n",
  "gesetzen": "n",
  "gesetzes": "n",
  "gesetzestext": "m",
  "gesicht": "n",
  "gesichter": "n",
  "gespr\xE4ch": "n",
  "gestalt": "f",
  "gestalten": "f",
  "geste": "f",
  "gestein": "n",
  "gesteinsschichten": "f",
  "getreide": "n",
  "getreidek\xF6rner": "n",
  "gewand": "n",
  "gewebe": "n",
  "gewehr": "n",
  "gewehre": "n",
  "geweih": "n",
  "gewicht": "n",
  "gewichte": "n",
  "gewissen": "n",
  "gew\xF6lbe": "n",
  "gezeiten": "f",
  "gier": "f",
  "gie\xDFkanne": "f",
  "gift": "n",
  "gipfel": "m",
  "gitter": "n",
  "glas": "n",
  "glasplatte": "f",
  "glaube": "m",
  "gleichung": "f",
  "gletscher": "m",
  "glocke": "f",
  "gl\xFCck": "n",
  "gold": "n",
  "gott": "m",
  "grab": "n",
  "graben": "m",
  "granitblock": "m",
  "grenze": "f",
  "grotte": "f",
  "grund": "m",
  "grundrissplan": "m",
  "gruppe": "f",
  "gruppenchat": "m",
  "gurke": "f",
  "g\xF6tter": "m",
  "g\xF6ttin": "f",
  "g\xFCrtel": "m",
  "haar": "n",
  "haarnadel": "f",
  "hafen": "m",
  "hagel": "m",
  "hahn": "m",
  "hain": "m",
  "haken": "m",
  "halde": "f",
  "hall": "m",
  "halle": "f",
  "hals": "m",
  "halter": "m",
  "hammer": "m",
  "hand": "f",
  "handbuch": "n",
  "handkarren": "m",
  "handschuh": "m",
  "handschuhspitze": "f",
  "handvoll": "f",
  "handy": "n",
  "hang": "m",
  "harfe": "f",
  "harpune": "f",
  "hase": "m",
  "hass": "m",
  "haus": "n",
  "haut": "f",
  "hecke": "f",
  "heft": "n",
  "held": "m",
  "helm": "m",
  "hemd": "n",
  "henne": "f",
  "herbst": "m",
  "herd": "m",
  "herr": "m",
  "herrscherstab": "m",
  "herz": "n",
  "herzschlag": "m",
  "heuer": "f",
  "hexe": "f",
  "hierarchie": "f",
  "himmel": "m",
  "hintergrund": "m",
  "hintert\xFCr": "f",
  "hirn": "n",
  "hirsch": "m",
  "hirtenstab": "m",
  "hof": "m",
  "hoffnung": "f",
  "holz": "n",
  "honig": "m",
  "hoodie": "m",
  "horn": "n",
  "hose": "f",
  "huhn": "n",
  "hund": "m",
  "hut": "m",
  "h\xE4user": "n",
  "h\xF6henmesser": "m",
  "h\xF6hle": "f",
  "h\xFCfte": "f",
  "h\xFCgel": "m",
  "h\xFCtte": "f",
  "igel": "m",
  "index": "m",
  "insekt": "n",
  "insel": "f",
  "instanz": "f",
  "instastory": "f",
  "instrument": "n",
  "interferometer": "n",
  "jacke": "f",
  "jazz": "m",
  "junge": "m",
  "justiergewicht": "n",
  "j\xE4ger": "m",
  "kabel": "n",
  "kaffee": "m",
  "kai": "m",
  "kaiser": "m",
  "kalb": "n",
  "kalender": "m",
  "kamin": "m",
  "kaminfeuer": "n",
  "kammer": "f",
  "kampf": "m",
  "kanal": "m",
  "kaninchen": "n",
  "kanister": "m",
  "kanne": "f",
  "kanten": "m",
  "kapelle": "f",
  "kapit\xE4n": "m",
  "karawane": "f",
  "karotte": "f",
  "karte": "f",
  "karteikarte": "f",
  "kartoffel": "f",
  "kassenbuch": "n",
  "kathedrale": "f",
  "katze": "f",
  "kaugummi": "m",
  "kehle": "f",
  "kelch": "m",
  "kelle": "f",
  "keller": "m",
  "kerze": "f",
  "kessel": "m",
  "kette": "f",
  "kettenhemd": "n",
  "kiefer": "m",
  "kiel": "m",
  "kies": "m",
  "kilometer": "m",
  "kind": "n",
  "kinder": "n",
  "kinderspielzeug": "n",
  "kinn": "n",
  "kirche": "f",
  "kirsche": "f",
  "kissen": "n",
  "kiste": "f",
  "klammer": "f",
  "klang": "m",
  "klaue": "f",
  "klavier": "n",
  "kleid": "n",
  "kleidersack": "m",
  "kleingeldfach": "n",
  "kleinod": "n",
  "klinge": "f",
  "klingel": "f",
  "klippe": "f",
  "klopfen": "n",
  "knabe": "m",
  "knie": "n",
  "knochen": "m",
  "knopf": "m",
  "knospe": "f",
  "knoten": "m",
  "kn\xE4uel": "n",
  "kn\xF6chel": "m",
  "koffer": "m",
  "kohleneimer": "m",
  "kohleschale": "f",
  "kollege": "m",
  "kollegheft": "n",
  "kollektiv": "n",
  "kolonie": "f",
  "komet": "m",
  "kommentar": "m",
  "kommissar": "m",
  "kompass": "m",
  "kompressor": "m",
  "konstante": "f",
  "konto": "n",
  "kontobuch": "n",
  "kontor": "n",
  "kontorbuch": "n",
  "kontostand": "m",
  "kopf": "m",
  "kopfh\xF6rer": "m",
  "kopie": "f",
  "korb": "m",
  "korken": "m",
  "korn": "n",
  "kraft": "f",
  "kran": "m",
  "krater": "m",
  "kreide": "f",
  "kreis": "m",
  "kreuz": "n",
  "kreuzung": "f",
  "kribbeln": "n",
  "krieg": "m",
  "krieger": "m",
  "kristall": "m",
  "krone": "f",
  "krug": "m",
  "kr\xE4he": "f",
  "kuchen": "m",
  "kuh": "f",
  "kupfer": "n",
  "kuppel": "f",
  "kurbel": "f",
  "kurve": "f",
  "kuss": "m",
  "kutsche": "f",
  "kuvert": "n",
  "k\xE4fer": "m",
  "k\xE4lte": "f",
  "k\xE4se": "m",
  "k\xF6nig": "m",
  "k\xF6nigin": "f",
  "k\xF6rper": "m",
  "k\xFCche": "f",
  "k\xFChlbox": "f",
  "k\xFChlfalle": "f",
  "k\xFCken": "n",
  "k\xFCste": "f",
  "labyrinth": "n",
  "ladebalken": "m",
  "ladekabel": "n",
  "ladeliste": "f",
  "lager": "n",
  "lagune": "f",
  "laib": "m",
  "lamm": "n",
  "lampe": "f",
  "land": "n",
  "lanze": "f",
  "laterne": "f",
  "laub": "n",
  "laufzettel": "m",
  "laute": "f",
  "lawine": "f",
  "leder": "n",
  "lederbeutel": "m",
  "legende": "f",
  "lehen": "n",
  "lehrer": "m",
  "leid": "n",
  "leine": "f",
  "leitdetail": "n",
  "leitung": "f",
  "leuchten": "n",
  "leuchtturm": "m",
  "licht": "n",
  "lichtstreifen": "m",
  "lider": "n",
  "liebe": "f",
  "lied": "n",
  "lilie": "f",
  "lineal": "n",
  "linie": "f",
  "lippe": "f",
  "liste": "f",
  "loch": "n",
  "locke": "f",
  "log": "n",
  "logbuch": "n",
  "logfile": "n",
  "los": "n",
  "lot": "n",
  "luft": "f",
  "lupe": "f",
  "lust": "f",
  "l\xE4cheln": "n",
  "l\xE4nder": "n",
  "l\xE4rm": "m",
  "l\xF6cher": "n",
  "l\xF6ffel": "m",
  "l\xF6we": "m",
  "l\xFCcke": "f",
  "l\xFCge": "f",
  "macht": "f",
  "magen": "m",
  "mala": "f",
  "maler": "m",
  "manege": "f",
  "manifest": "n",
  "mann": "m",
  "mantel": "m",
  "manuskript": "n",
  "mappe": "f",
  "marmelade": "f",
  "masche": "f",
  "maschine": "f",
  "maske": "f",
  "mast": "m",
  "matte": "f",
  "mauer": "f",
  "maus": "f",
  "ma\xDF": "n",
  "ma\xDFband": "n",
  "ma\xDFstab": "m",
  "medaillon": "n",
  "meer": "n",
  "mehl": "n",
  "mei\xDFel": "m",
  "melodie": "f",
  "meme": "n",
  "menge": "f",
  "merkblatt": "n",
  "messer": "n",
  "messprotokoll": "n",
  "messreihe": "f",
  "messung": "f",
  "metall": "n",
  "meter": "m",
  "metronom": "n",
  "miene": "f",
  "mikrofon": "n",
  "mikroskop": "n",
  "milch": "f",
  "millimeter": "m",
  "minute": "f",
  "mitleid": "n",
  "mittag": "m",
  "mittel": "n",
  "mitternacht": "f",
  "modell": "n",
  "modellplaneten": "m",
  "moment": "m",
  "monat": "m",
  "mond": "m",
  "moor": "n",
  "morgen": "m",
  "moschee": "f",
  "motor": "m",
  "mus": "n",
  "muschel": "f",
  "muskel": "m",
  "muster": "n",
  "mut": "m",
  "mutter": "f",
  "m\xE4dchen": "n",
  "m\xE4hne": "f",
  "m\xF6hre": "f",
  "m\xF6nch": "m",
  "m\xF6rder": "m",
  "m\xF6we": "f",
  "m\xFCcke": "f",
  "m\xFChle": "f",
  "m\xFCller": "m",
  "m\xFCnze": "f",
  "m\xFCtze": "f",
  "nachbar": "m",
  "nachbarort": "m",
  "nachlass": "m",
  "nachmittag": "m",
  "nachricht": "f",
  "nacht": "f",
  "nachtigall": "f",
  "nacken": "m",
  "nadel": "f",
  "nadelkissen": "n",
  "nagel": "m",
  "naht": "f",
  "name": "m",
  "napf": "m",
  "narbe": "f",
  "nase": "f",
  "nebel": "m",
  "neffe": "m",
  "neid": "m",
  "neigung": "f",
  "neigungsmesser": "m",
  "nelke": "f",
  "nest": "n",
  "nester": "n",
  "netz": "n",
  "nische": "f",
  "nonne": "f",
  "note": "f",
  "notenblatt": "n",
  "notiz": "f",
  "notizblock": "m",
  "notizbuch": "n",
  "nummer": "f",
  "nuss": "f",
  "nymphe": "f",
  "n\xE4he": "f",
  "obst": "n",
  "ofen": "m",
  "ohr": "n",
  "oma": "f",
  "omen": "n",
  "onkel": "m",
  "opfer": "n",
  "opferschale": "f",
  "opiumdose": "f",
  "orakel": "n",
  "orange": "f",
  "organ": "n",
  "orgel": "f",
  "ort": "m",
  "ozean": "m",
  "paar": "n",
  "paket": "n",
  "pakt": "m",
  "papier": "n",
  "paradoxon": "n",
  "paragraph": "m",
  "parameter": "m",
  "park": "m",
  "passagier": "m",
  "passierschein": "m",
  "pegelstab": "m",
  "peilstock": "m",
  "peitsche": "f",
  "pendel": "n",
  "pergamentrolle": "f",
  "perle": "f",
  "perlmuttknopf": "m",
  "person": "f",
  "petrischale": "f",
  "petroleumlampe": "f",
  "pfad": "m",
  "pfand": "n",
  "pfandschein": "m",
  "pfeffer": "m",
  "pfeife": "f",
  "pferd": "n",
  "pfirsich": "m",
  "pflaster": "n",
  "pflaume": "f",
  "pflug": "m",
  "pf\xFCtze": "f",
  "phiole": "f",
  "photoplatte": "f",
  "pickel": "m",
  "pilz": "m",
  "ping": "m",
  "pinzette": "f",
  "pipette": "f",
  "plakat": "n",
  "plan": "m",
  "plane": "f",
  "planet": "m",
  "planke": "f",
  "platte": "f",
  "platz": "m",
  "platzhalter": "m",
  "poller": "m",
  "port": "m",
  "portal": "n",
  "postkarte": "f",
  "powerbank": "f",
  "priester": "m",
  "prisma": "n",
  "probe": "f",
  "programm": "n",
  "protokoll": "n",
  "prozess": "m",
  "puls": "m",
  "pulver": "n",
  "punkt": "m",
  "puppe": "f",
  "qualle": "f",
  "quelle": "f",
  "quittung": "f",
  "rad": "n",
  "rampe": "f",
  "rand": "m",
  "randnotiz": "f",
  "ranke": "f",
  "ranzen": "m",
  "ratte": "f",
  "rauch": "m",
  "raumkapsel": "f",
  "rausch": "m",
  "rauschen": "n",
  "rechentafel": "f",
  "recht": "n",
  "regal": "n",
  "regel": "f",
  "regen": "m",
  "regenmesser": "m",
  "register": "n",
  "reh": "n",
  "reich": "n",
  "reif": "m",
  "reigen": "m",
  "reihe": "f",
  "reinraumhaube": "f",
  "reise": "f",
  "reisemantel": "m",
  "rei\xDFverschluss": "m",
  "reklame": "f",
  "rest": "m",
  "rettung": "f",
  "rezept": "n",
  "richter": "m",
  "riegel": "m",
  "riff": "n",
  "rinde": "f",
  "ring": "m",
  "rippe": "f",
  "riss": "m",
  "ritter": "m",
  "ritterhelm": "m",
  "rohr": "n",
  "roman": "m",
  "rose": "f",
  "ruder": "n",
  "ruf": "m",
  "ruine": "f",
  "rumpf": "m",
  "r\xE4tsel": "n",
  "r\xFCcken": "m",
  "saal": "m",
  "sachbearbeiter": "m",
  "sack": "m",
  "saft": "m",
  "sage": "f",
  "sahne": "f",
  "saite": "f",
  "salat": "m",
  "salz": "n",
  "samen": "m",
  "sammlung": "f",
  "sand": "m",
  "sandsack": "m",
  "sanduhr": "f",
  "sarg": "m",
  "satellit": "m",
  "sattel": "m",
  "sattelgurt": "m",
  "satz": "m",
  "saum": "m",
  "savanne": "f",
  "schacht": "m",
  "schaf": "n",
  "schale": "f",
  "schalter": "m",
  "scham": "f",
  "schatten": "m",
  "schatulle": "f",
  "schaufel": "f",
  "schere": "f",
  "schicht": "f",
  "schicksal": "n",
  "schiff": "n",
  "schiffssextanten": "m",
  "schiffszwieback": "m",
  "schild": "n",
  "schirm": "m",
  "schlaf": "m",
  "schlag": "m",
  "schlamm": "m",
  "schlange": "f",
  "schleife": "f",
  "schloss": "n",
  "schlucht": "f",
  "schl\xFCssel": "m",
  "schl\xFCsselbund": "m",
  "schmerz": "m",
  "schmied": "m",
  "schmiede": "f",
  "schminkkasten": "m",
  "schnecke": "f",
  "schnee": "m",
  "schneiderpuppe": "f",
  "schnitt": "m",
  "schnittbogen": "m",
  "schnittstelle": "f",
  "schnur": "f",
  "schokolade": "f",
  "schrank": "m",
  "schrei": "m",
  "schreiber": "m",
  "schrein": "m",
  "schrift": "f",
  "schritt": "m",
  "schuh": "m",
  "schuld": "f",
  "schuldschein": "m",
  "schule": "f",
  "schulter": "f",
  "schuppen": "m",
  "schuss": "m",
  "schwamm": "m",
  "schwein": "n",
  "schwelle": "f",
  "schwert": "n",
  "schwertgriff": "m",
  "schwertgurt": "m",
  "schwester": "f",
  "schw\xE4che": "f",
  "sch\xE4del": "m",
  "sch\xE4rpe": "f",
  "sch\xFCrze": "f",
  "sch\xFCssel": "f",
  "screenshot": "m",
  "see": "m",
  "seekarte": "f",
  "seele": "f",
  "seesack": "m",
  "segel": "n",
  "segeltuch": "n",
  "segen": "m",
  "sehne": "f",
  "sehnsucht": "f",
  "seidenfaden": "m",
  "seil": "n",
  "seismograph": "m",
  "seismographen": "m",
  "seite": "f",
  "sekunde": "f",
  "senf": "m",
  "sensor": "m",
  "sessel": "m",
  "sieb": "n",
  "siegel": "n",
  "siegelring": "m",
  "signal": "n",
  "signalflagge": "f",
  "silbe": "f",
  "silber": "n",
  "sinn": "m",
  "sirene": "f",
  "skala": "f",
  "skalpell": "n",
  "skelett": "n",
  "skizze": "f",
  "smartphone": "n",
  "socke": "f",
  "sofa": "n",
  "sohn": "m",
  "soldat": "m",
  "sommer": "m",
  "sonne": "f",
  "sonnenbrille": "f",
  "so\xDFe": "f",
  "spalt": "m",
  "speicher": "m",
  "spektrogramm": "n",
  "spektrometer": "n",
  "sperre": "f",
  "spiegel": "m",
  "spiegelscherben": "m",
  "spiel": "n",
  "spinne": "f",
  "sporn": "m",
  "sprache": "f",
  "sprung": "m",
  "spule": "f",
  "spur": "f",
  "stab": "m",
  "stadt": "f",
  "stahlstrebe": "f",
  "stamm": "m",
  "standarte": "f",
  "stapel": "m",
  "statue": "f",
  "staub": "m",
  "stecknadel": "f",
  "steg": "m",
  "steig": "m",
  "steigb\xFCgel": "m",
  "steigeisen": "n",
  "stein": "m",
  "stelle": "f",
  "stempel": "m",
  "stempelger\xE4usch": "n",
  "stempelhalter": "m",
  "steppe": "f",
  "stern": "m",
  "sternbilder": "n",
  "sternwarte": "f",
  "stethoskop": "n",
  "stiefel": "m",
  "stier": "m",
  "stille": "f",
  "stimme": "f",
  "stirn": "f",
  "stock": "m",
  "stoff": "m",
  "stollen": "m",
  "stolz": "m",
  "story": "f",
  "strand": "m",
  "strauch": "m",
  "stra\xDFe": "f",
  "streichholzschachtel": "f",
  "streit": "m",
  "strich": "m",
  "strom": "m",
  "strophe": "f",
  "str\xF6mung": "f",
  "stube": "f",
  "stufe": "f",
  "stuhl": "m",
  "stunde": "f",
  "stundenplan": "m",
  "sturm": "m",
  "sturmlaterne": "f",
  "st\xE4rke": "f",
  "st\xFCck": "n",
  "sumpf": "m",
  "suppe": "f",
  "suppenkelle": "f",
  "symbol": "n",
  "symptom": "n",
  "system": "n",
  "s\xE4ge": "f",
  "s\xE4ule": "f",
  "tabelle": "f",
  "tafel": "f",
  "tafelrunde": "f",
  "tag": "m",
  "takt": "m",
  "tal": "n",
  "talar": "m",
  "tante": "f",
  "tanz": "m",
  "tasche": "f",
  "taschenradio": "n",
  "tasse": "f",
  "tau": "n",
  "taube": "f",
  "tee": "m",
  "teer": "m",
  "teeschale": "f",
  "teich": "m",
  "teil": "m",
  "telefon": "n",
  "teleskop": "n",
  "teller": "m",
  "teppich": "m",
  "termin": "m",
  "terminal": "n",
  "terminzettel": "m",
  "teufel": "m",
  "thermometer": "n",
  "thermoskanne": "f",
  "thron": "m",
  "ticket": "n",
  "tier": "n",
  "tiger": "m",
  "tiktoksound": "m",
  "tintenfass": "n",
  "tisch": "m",
  "tochter": "f",
  "tod": "m",
  "tomate": "f",
  "ton": "m",
  "tonband": "n",
  "tonschale": "f",
  "tontafel": "f",
  "topf": "m",
  "tor": "n",
  "torte": "f",
  "trapezhaken": "m",
  "traube": "f",
  "trauer": "f",
  "traum": "m",
  "trend": "m",
  "treppe": "f",
  "treue": "f",
  "trillerpfeife": "f",
  "trinkhorn": "n",
  "trommel": "f",
  "truhe": "f",
  "tr\xE4ne": "f",
  "tuch": "n",
  "tulpe": "f",
  "tunnel": "m",
  "turm": "m",
  "turnbeutel": "m",
  "turnier": "n",
  "turnierplatz": "m",
  "turnierstab": "m",
  "t\xFCr": "f",
  "t\xFCte": "f",
  "ufer": "n",
  "uhr": "f",
  "umriss": "m",
  "umschlag": "m",
  "ungl\xFCck": "n",
  "untergrund": "m",
  "unterschrift": "f",
  "untersuchungsliege": "f",
  "update": "n",
  "urne": "f",
  "urteil": "n",
  "vater": "m",
  "verdacht": "m",
  "verfahren": "n",
  "vergangenheit": "f",
  "vermerk": "m",
  "vers": "m",
  "verstand": "m",
  "vertrag": "m",
  "vertrauen": "n",
  "video": "n",
  "virus": "n",
  "visier": "n",
  "vogel": "m",
  "vollmacht": "f",
  "vordruck": "m",
  "vorhang": "m",
  "vormund": "m",
  "vorrat": "m",
  "vorratsgl\xE4ser": "n",
  "vulkan": "m",
  "wachs": "n",
  "wachstuch": "n",
  "wagen": "m",
  "wahrheit": "f",
  "waisenjunge": "m",
  "wal": "m",
  "wald": "m",
  "waldhorn": "n",
  "wand": "f",
  "wanderstab": "m",
  "wanderstock": "m",
  "wanderung": "f",
  "wange": "f",
  "wappen": "n",
  "wappenschild": "n",
  "warnung": "f",
  "warnweste": "f",
  "wartemarke": "f",
  "warze": "f",
  "wasser": "n",
  "wasserflasche": "f",
  "wasserhahn": "m",
  "weg": "m",
  "wegmarke": "f",
  "weide": "f",
  "wein": "m",
  "weite": "f",
  "wei\xDF": "n",
  "welle": "f",
  "werk": "n",
  "werkstatt": "f",
  "werkzeug": "n",
  "wert": "m",
  "wespe": "f",
  "wetter": "n",
  "wetterfahne": "f",
  "widerstand": "m",
  "wiese": "f",
  "wille": "m",
  "wimper": "f",
  "wind": "m",
  "windhauch": "m",
  "windsto\xDF": "m",
  "winter": "m",
  "witz": "m",
  "woche": "f",
  "wolf": "m",
  "wolke": "f",
  "wollschal": "m",
  "wort": "n",
  "wrack": "n",
  "wunde": "f",
  "wunder": "n",
  "wunsch": "m",
  "wurm": "m",
  "wurzel": "f",
  "wut": "f",
  "w\xE4chter": "m",
  "w\xE4lder": "m",
  "w\xE4rme": "f",
  "w\xE4rmestein": "m",
  "w\xE4schekorb": "m",
  "w\xF6rter": "n",
  "w\xFCrfel": "m",
  "w\xFCste": "f",
  "zahl": "f",
  "zahn": "m",
  "zange": "f",
  "zauberbesen": "m",
  "zaun": "m",
  "zeh": "m",
  "zeichen": "n",
  "zeile": "f",
  "zeit": "f",
  "zeitgeber": "m",
  "zeitmarke": "f",
  "zelle": "f",
  "zelt": "n",
  "zentimeter": "m",
  "zepter": "n",
  "zettel": "m",
  "zeuge": "m",
  "ziffer": "f",
  "zigarettenstummel": "m",
  "zigarre": "f",
  "zimmer": "n",
  "zirkel": "m",
  "zitrone": "f",
  "zittern": "n",
  "zorn": "m",
  "zucker": "m",
  "zug": "m",
  "zukunft": "f",
  "zunderbeutel": "m",
  "zunge": "f",
  "zweifel": "m",
  "zweig": "m",
  "zweitschl\xFCssel": "m",
  "zwieback": "m",
  "zwiebel": "f",
  "z\xE4hlrahmen": "m",
  "z\xF6gern": "n",
  "\xE4rmel": "m",
  "\xE4rztin": "f",
  "\xF6l": "n",
  "\xF6llampe": "f",
  "\xF6llaterne": "f",
  "\xF6lschl\xFCssel": "m"
};

// src/generation/verben.ts
var STARK = {
  // sein · haben · werden · wissen · tun · Modalverben
  ist: ["bin", "bist", "sind", "seid"],
  hat: ["habe", "hast", "haben", "habt"],
  wird: ["werde", "wirst", "werden", "werdet"],
  wei\u00DF: ["wei\xDF", "wei\xDFt", "wissen", "wisst"],
  tut: ["tue", "tust", "tun", "tut"],
  kann: ["kann", "kannst", "k\xF6nnen", "k\xF6nnt"],
  muss: ["muss", "musst", "m\xFCssen", "m\xFCsst"],
  will: ["will", "willst", "wollen", "wollt"],
  soll: ["soll", "sollst", "sollen", "sollt"],
  darf: ["darf", "darfst", "d\xFCrfen", "d\xFCrft"],
  mag: ["mag", "magst", "m\xF6gen", "m\xF6gt"],
  // a → ä
  h\u00E4lt: ["halte", "h\xE4ltst", "halten", "haltet"],
  f\u00E4llt: ["falle", "f\xE4llst", "fallen", "fallt"],
  tr\u00E4gt: ["trage", "tr\xE4gst", "tragen", "tragt"],
  l\u00E4uft: ["laufe", "l\xE4ufst", "laufen", "lauft"],
  schl\u00E4ft: ["schlafe", "schl\xE4fst", "schlafen", "schlaft"],
  f\u00E4ngt: ["fange", "f\xE4ngst", "fangen", "fangt"],
  l\u00E4sst: ["lasse", "l\xE4sst", "lassen", "lasst"],
  w\u00E4chst: ["wachse", "w\xE4chst", "wachsen", "wachst"],
  gr\u00E4bt: ["grabe", "gr\xE4bst", "graben", "grabt"],
  schl\u00E4gt: ["schlage", "schl\xE4gst", "schlagen", "schlagt"],
  r\u00E4t: ["rate", "r\xE4tst", "raten", "ratet"],
  bl\u00E4st: ["blase", "bl\xE4st", "blasen", "blast"],
  st\u00F6\u00DFt: ["sto\xDFe", "st\xF6\xDFt", "sto\xDFen", "sto\xDFt"],
  f\u00E4hrt: ["fahre", "f\xE4hrst", "fahren", "fahrt"],
  w\u00E4scht: ["wasche", "w\xE4schst", "waschen", "wascht"],
  l\u00E4dt: ["lade", "l\xE4dst", "laden", "ladet"],
  s\u00E4uft: ["saufe", "s\xE4ufst", "saufen", "sauft"],
  // e → i / ie
  gibt: ["gebe", "gibst", "geben", "gebt"],
  nimmt: ["nehme", "nimmst", "nehmen", "nehmt"],
  spricht: ["spreche", "sprichst", "sprechen", "sprecht"],
  bricht: ["breche", "brichst", "brechen", "brecht"],
  sieht: ["sehe", "siehst", "sehen", "seht"],
  liest: ["lese", "liest", "lesen", "lest"],
  isst: ["esse", "isst", "essen", "esst"],
  frisst: ["fresse", "frisst", "fressen", "fresst"],
  misst: ["messe", "misst", "messen", "messt"],
  vergisst: ["vergesse", "vergisst", "vergessen", "vergesst"],
  hilft: ["helfe", "hilfst", "helfen", "helft"],
  stirbt: ["sterbe", "stirbst", "sterben", "sterbt"],
  wirft: ["werfe", "wirfst", "werfen", "werft"],
  trifft: ["treffe", "triffst", "treffen", "trefft"],
  gilt: ["gelte", "giltst", "gelten", "geltet"],
  tritt: ["trete", "trittst", "treten", "tretet"],
  birgt: ["berge", "birgst", "bergen", "bergt"],
  quillt: ["quelle", "quillst", "quellen", "quellt"],
  schilt: ["schelte", "schiltst", "schelten", "scheltet"],
  ficht: ["fechte", "fichtst", "fechten", "fechtet"],
  flicht: ["flechte", "flichtst", "flechten", "flechtet"],
  verdirbt: ["verderbe", "verdirbst", "verderben", "verderbt"],
  wirbt: ["werbe", "wirbst", "werben", "werbt"],
  erschrickt: ["erschrecke", "erschrickst", "erschrecken", "erschreckt"],
  sticht: ["steche", "stichst", "stechen", "stecht"],
  schmilzt: ["schmelze", "schmilzt", "schmelzen", "schmelzt"],
  befiehlt: ["befehle", "befiehlst", "befehlen", "befehlt"],
  stiehlt: ["stehle", "stiehlst", "stehlen", "stehlt"],
  empfiehlt: ["empfehle", "empfiehlst", "empfehlen", "empfehlt"],
  geschieht: ["geschehe", "geschiehst", "geschehen", "gescheht"],
  gebiert: ["geb\xE4re", "gebierst", "geb\xE4ren", "geb\xE4rt"],
  schwillt: ["schwelle", "schwillst", "schwellen", "schwellt"]
};
var PRAEFIXE = [
  "zusammen",
  "zur\xFCck",
  "wieder",
  "gegen",
  "hinter",
  "durch",
  "unter",
  "\xFCber",
  "voran",
  "vorbei",
  "heraus",
  "herein",
  "hinaus",
  "hinein",
  "herum",
  "hinauf",
  "hinab",
  "herab",
  "empor",
  "fort",
  "los",
  "weg",
  "fest",
  "her",
  "hin",
  "ver",
  "ent",
  "emp",
  "miss",
  "zer",
  "be",
  "er",
  "ge",
  "an",
  "ab",
  "auf",
  "aus",
  "ein",
  "mit",
  "nach",
  "vor",
  "zu",
  "um",
  "bei",
  "da",
  "wider"
];
var KEIN_VERB = /* @__PURE__ */ new Set([
  "alt",
  "kalt",
  "laut",
  "bunt",
  "hart",
  "zart",
  "satt",
  "glatt",
  "weit",
  "breit",
  "rot",
  "tot",
  "gut",
  "sp\xE4t",
  "echt",
  "leicht",
  "dicht",
  "recht",
  "schlecht",
  "nackt",
  "fest",
  "letzt",
  "jetzt",
  "sanft",
  "ernst",
  "wert",
  "seit",
  "statt",
  "samt",
  "nicht",
  "mit",
  "seid",
  "zuletzt",
  "zuerst",
  "oft",
  "fast",
  "erst",
  "sonst",
  "meist",
  "direkt",
  "dort",
  "fort",
  "sofort",
  "selbst",
  "vielleicht",
  "\xFCberhaupt",
  "bereit",
  "gerecht",
  "perfekt",
  "exakt",
  "absolut",
  "gesamt",
  "komplett",
  "verr\xFCckt",
  "bekannt",
  "geschickt",
  "welt",
  "zeit",
  "nacht",
  "stadt",
  "acht",
  "licht",
  "wort",
  "ort",
  "blut",
  "brot",
  "mut",
  "hut",
  "gebet",
  "geist",
  "gott",
  "kraft",
  "luft",
  "haut",
  "haft",
  "gift",
  "schrift",
  "frucht",
  "flucht",
  "sicht",
  "pflicht",
  "angst",
  "kunst",
  "dienst",
  "frost",
  "post",
  "ost",
  "west",
  "rest",
  "test",
  "text",
  "w\xFCst",
  "getrennt",
  "gemischt",
  "gebrannt",
  "verschwunden",
  "gewohnt",
  "gelaunt",
  "ber\xFChmt",
  "geliebt",
  "gelebt",
  "gedacht",
  "gemacht",
  "gebracht",
  "gesagt",
  "gesucht",
  "gehabt",
  "gewusst",
  "gekannt",
  "genannt",
  "benannt",
  "gewollt",
  "verboten",
  "ge\xF6ffnet",
  "ungeahnt",
  "gestern",
  "heut",
  "abrupt",
  "ad\xE4quat",
  "privat",
  "intakt",
  "korrekt",
  "konkret",
  "moderat",
  "elegant",
  "brillant",
  "tolerant",
  "relevant",
  "markant",
  "rasant",
  "galant",
  "latent",
  "dezent",
  "prominent",
  "kompetent",
  "konsequent",
  "permanent",
  "evident",
  "eloquent",
  "intelligent",
  "gespannt",
  "entspannt",
  "gewandt",
  "verwandt",
  "bewusst",
  "unbewusst",
  "robust",
  "abstrakt",
  "kompakt",
  "exakt",
  "defekt",
  "perfekt",
  "insgesamt",
  "total"
]);
var GE_VERBEN = /^ge(ht|nügt|hört|horcht|lingt|winnt|langt|schieht|steht|rät|nießt|wöhnt|fährdet|währt|stattet|staltet|denkt|bietet|braucht|hörcht|nest|reicht|dulde?t|fällt|deiht|lobt|leitet|langt|winnt|behrt|bärt|fried[e]?t|fällt|lüstet|mahnt|rinnt|hört)$/;
function starkMitPraefix(form) {
  if (STARK[form]) return ["", STARK[form]];
  for (const p of PRAEFIXE) {
    if (form.startsWith(p) && form.length > p.length + 2) {
      const rest = form.slice(p.length);
      if (STARK[rest]) return [p, STARK[rest]];
    }
  }
  return null;
}
function istVerbform(wort) {
  const w = wort.toLowerCase();
  if (starkMitPraefix(w)) return true;
  if (KEIN_VERB.has(w)) return false;
  if (!/^[a-zäöüß]{3,}t$/.test(w)) return false;
  if (/^ge[a-zäöüß]{2,}t$/.test(w)) return GE_VERBEN.test(w);
  return true;
}

// src/generation/nouns2.data.ts
var NOUN_GENDER_2 = {
  // ── Häufigste ──
  ende: "n",
  jahr: "n",
  mal: "n",
  anfang: "m",
  leben: "n",
  auskunft: "f",
  welt: "f",
  fr\u00FChjahr: "n",
  fall: "m",
  arbeit: "f",
  sache: "f",
  zufall: "m",
  form: "f",
  ziel: "n",
  kontrolle: "f",
  reihenfolge: "f",
  wissen: "n",
  post: "f",
  ernte: "f",
  geld: "n",
  mund: "m",
  schweigen: "n",
  wette: "f",
  schminke: "f",
  kurs: "m",
  original: "n",
  text: "m",
  gras: "n",
  warten: "n",
  ruhe: "f",
  mitte: "f",
  seide: "f",
  familie: "f",
  tiefe: "f",
  norden: "m",
  s\u00FCden: "m",
  osten: "m",
  westen: "m",
  blut: "n",
  horizont: "m",
  ursache: "f",
  absicht: "f",
  wirt: "m",
  jagd: "f",
  herkunft: "f",
  essen: "n",
  r\u00FCckkehr: "f",
  rahmen: "m",
  w\u00FCrde: "f",
  w\u00E4sche: "f",
  miete: "f",
  verlangen: "n",
  marke: "f",
  griff: "m",
  wache: "f",
  vernunft: "f",
  markt: "m",
  pegel: "m",
  halbdunkel: "n",
  rolle: "f",
  grad: "m",
  streben: "n",
  fach: "n",
  weise: "f",
  wipfel: "m",
  kohle: "f",
  lehne: "f",
  tide: "f",
  ru\u00DF: "m",
  idee: "f",
  gemeinde: "f",
  jahrhundert: "n",
  ernst: "m",
  betrag: "m",
  unterschied: "m",
  material: "n",
  annahme: "f",
  merkmal: "n",
  radio: "n",
  hitze: "f",
  herold: "m",
  grat: "m",
  kasse: "f",
  zoll: "m",
  heimweh: "n",
  laden: "m",
  f\u00E4hre: "f",
  herzog: "m",
  inhalt: "m",
  titel: "m",
  problem: "n",
  sicht: "f",
  beh\u00F6rde: "f",
  winkel: "m",
  hilfe: "f",
  pass: "m",
  viertel: "n",
  jahrzehnt: "n",
  anrede: "f",
  rost: "m",
  ekel: "m",
  tat: "f",
  methode: "f",
  zwang: "m",
  heimkehr: "f",
  umkehr: "f",
  norm: "f",
  leere: "f",
  umlauf: "m",
  flamme: "f",
  einsicht: "f",
  messing: "n",
  personal: "n",
  widerspruch: "m",
  schluss: "m",
  stroh: "n",
  rang: "m",
  vieh: "n",
  garderobe: "f",
  g\u00FCte: "f",
  anlass: "m",
  anwalt: "m",
  rat: "m",
  code: "m",
  bad: "n",
  handgelenk: "n",
  scheibe: "f",
  zustand: "m",
  eile: "f",
  saatgut: "n",
  fracht: "f",
  automat: "m",
  lehre: "f",
  ding: "n",
  verzicht: "m",
  zweck: "m",
  waffe: "f",
  blech: "n",
  trost: "m",
  versuch: "m",
  ironie: "f",
  d\u00FCrre: "f",
  fest: "n",
  aufsicht: "f",
  kapitel: "n",
  aussicht: "f",
  absinth: "m",
  parf\u00FCm: "n",
  schmutz: "m",
  knick: "m",
  andacht: "f",
  spitze: "f",
  szene: "f",
  erfolg: "m",
  ausguck: "m",
  bord: "m",
  sieg: "m",
  klausel: "f",
  haupttext: "m",
  sachverhalt: "m",
  tinte: "f",
  stand: "m",
  wortlaut: "m",
  klinke: "f",
  kanzel: "f",
  verrat: "m",
  mulde: "f",
  februar: "m",
  parasit: "m",
  pr\u00E4parat: "n",
  wesen: "n",
  lava: "f",
  schwefel: "m",
  lauf: "m",
  spa\u00DF: "m",
  m\u00F6bel: "n",
  b\u00FCro: "n",
  hauptsache: "f",
  saat: "f",
  fehde: "f",
  portr\u00E4t: "n",
  reue: "f",
  konfetti: "n",
  trapez: "n",
  narr: "m",
  truppe: "f",
  pudel: "m",
  jugend: "f",
  abschied: "m",
  bronze: "f",
  tempel: "m",
  geschlecht: "n",
  stra\u00DFenanfang: "m",
  brauch: "m",
  wiederkehr: "f",
  h\u00E4lfte: "f",
  pappe: "f",
  kante: "f",
  eintrag: "m",
  format: "n",
  giebel: "m",
  heimat: "f",
  armenkasse: "f",
  materie: "f",
  mensch: "m",
  glied: "n",
  betrieb: "m",
  m\u00FCll: "m",
  kleingeld: "n",
  ruhm: "m",
  ritt: "m",
  sch\u00E4rfe: "f",
  ankunft: "f",
  symmetrie: "f",
  adressat: "m",
  kreislauf: "m",
  aufstieg: "m",
  f\u00FClle: "f",
  bitte: "f",
  brand: "m",
  waise: "f",
  gesang: "m",
  subjekt: "n",
  objekt: "n",
  moral: "f",
  schilf: "n",
  diagnose: "f",
  gr\u00F6\u00DFe: "f",
  wahl: "f",
  sturz: "m",
  gischt: "f",
  ekstase: "f",
  becken: "n",
  putz: "m",
  minze: "f",
  samt: "m",
  pause: "f",
  knauf: "m",
  apotheke: "f",
  kost\u00FCm: "n",
  versto\u00DF: "m",
  satzanfang: "m",
  sprint: "m",
  beule: "f",
  banane: "f",
  tapete: "f",
  galerie: "f",
  kl\u00F6ppel: "m",
  predigt: "f",
  zierrat: "m",
  wachwechsel: "m",
  wimpel: "m",
  rah: "f",
  streitfall: "m",
  docht: "m",
  wundmal: "n",
  pforte: "f",
  gebot: "n",
  fl\u00FCgel: "m",
  l\u00E4nge: "f",
  kamel: "n",
  achse: "f",
  schlegel: "m",
  affe: "m",
  nirwana: "n",
  alkohol: "m",
  instinkt: "m",
  balance: "f",
  aushub: "m",
  kalk: "m",
  r\u00F6hre: "f",
  basalt: "m",
  salzs\u00E4ure: "f",
  erdkruste: "f",
  schichtfolge: "f",
  sohle: "f",
  profil: "n",
  schneeschmelze: "f",
  orbit: "m",
  funkspruch: "m",
  meteorit: "m",
  stromausfall: "m",
  theorie: "f",
  nervengeflecht: "n",
  bodenprofil: "n",
  senke: "f",
  gebiet: "n",
  phase: "f",
  honorar: "n",
  kordel: "f",
  spind: "m",
  tonfall: "m",
  tempo: "n",
  schattenkante: "f",
  stahl: "m",
  graupappe: "f",
  st\u00FCtze: "f",
  perspektive: "f",
  tank: "m",
  stillstand: "m",
  pumpe: "f",
  debatte: "f",
  bahre: "f",
  fackelru\u00DF: "m",
  kerbe: "f",
  t\u00FCrsturz: "m",
  groll: "m",
  seuche: "f",
  lunge: "f",
  pferdegeschirr: "n",
  zeltgest\u00E4nge: "n",
  marsch: "m",
  schaumgummi: "m",
  knall: "m",
  zeltmitte: "f",
  trick: "m",
  wurf: "m",
  pult: "n",
  pentagramm: "n",
  handel: "m",
  r\u00FCcktritt: "m",
  zimt: "m",
  akt: "m",
  schatz: "m",
  betrug: "m",
  kopfende: "n",
  parkett: "n",
  lack: "m",
  leib: "m",
  efeu: "m",
  anstand: "m",
  schafwolle: "f",
  milde: "f",
  wiege: "f",
  schar: "f",
  gunst: "f",
  volk: "n",
  staat: "m",
  antlitz: "n",
  fleck: "m",
  alibi: "n",
  kamera: "f",
  vorfall: "m",
  quelltext: "m",
  ritual: "n",
  schl\u00E4fe: "f",
  wetterwechsel: "m",
  anzeige: "f",
  jahresende: "n",
  weile: "f",
  t\u00FCll: "m",
  schleppe: "f",
  b\u00FCgel: "m",
  dampf: "m",
  kragen: "m",
  kerzenstummel: "m",
  klasse: "f",
  monatsende: "n",
  tausendstel: "n",
  durchlauf: "m",
  jahrtausend: "n",
  scheu: "f",
  taxi: "n",
  mittwoch: "m",
  erz: "n",
  diebstahl: "m",
  nachtwache: "f",
  schleuse: "f",
  \u00FCbernahme: "f",
  luke: "f",
  sp\u00FCle: "f",
  ampel: "f",
  sperrm\u00FCll: "m",
  speiche: "f",
  henkel: "m",
  routine: "f",
  mai: "m",
  wolle: "f",
  schluck: "m",
  biologie: "f",
  geologie: "f",
  astrologie: "f",
  philosophie: "f",
  krise: "f",
  trag\u00F6die: "f",
  urknall: "m",
  stift: "m",
  mine: "f",
  abwehr: "f",
  mole: "f",
  zerfall: "m",
  masse: "f",
  handbreit: "f",
  verfall: "m",
  tischkante: "f",
  beute: "f",
  rache: "f",
  font\u00E4ne: "f",
  zuversicht: "f",
  unruhe: "f",
  energie: "f",
  enge: "f",
  april: "m",
  rekord: "m",
  normalzustand: "m",
  h\u00F6he: "f",
  abstieg: "m",
  requisit: "n",
  schwindel: "m",
  orakelspruch: "m",
  erlass: "m",
  aufstand: "m",
  gehorsam: "m",
  blackbox: "f",
  silhouette: "f",
  mode: "f",
  not: "f",
  urform: "f",
  ruhestand: "m",
  schaden: "m",
  anlauf: "m",
  dienstjahr: "n",
  witwe: "f",
  ensemble: "n",
  kommune: "f",
  sekte: "f",
  rettungstrupp: "m",
  exil: "n",
  zentrale: "f",
  zensurbeh\u00F6rde: "f",
  doktortitel: "m",
  naturschutzgebiet: "n",
  boulevard: "m",
  hotel: "n",
  kino: "n",
  verkehr: "m",
  kellerclub: "m",
  kabine: "f",
  auto: "n",
  kaserne: "f",
  internat: "n",
  wahlkabine: "f",
  anstalt: "f",
  mittagspause: "f",
  choleraepidemie: "f",
  monarchie: "f",
  hungersnot: "f",
  null: "f",
  route: "f",
  kampagne: "f",
  karriere: "f",
  neuanfang: "m",
  sorte: "f",
  verhandlungssache: "f",
  folge: "f",
  ablauf: "m",
  strategie: "f",
  apparat: "m",
  psychopath: "m",
  variable: "f",
  empathie: "f",
  amsel: "f",
  schneefall: "m",
  abendrot: "n",
  wechsel: "m",
  // ── Nachschlag: Alltag, Körper, Haus, Natur, Amt ──
  auge: "n",
  name: "m",
  glaube: "m",
  wille: "m",
  gedanke: "m",
  friede: "m",
  funke: "m",
  k\u00E4se: "m",
  junge: "m",
  kunde: "m",
  l\u00F6we: "m",
  hase: "m",
  bote: "m",
  zeuge: "m",
  riese: "m",
  rabe: "m",
  falke: "m",
  ochse: "m",
  bursche: "m",
  knabe: "m",
  neffe: "m",
  erbe: "m",
  buchstabe: "m",
  same: "m",
  schatten: "m",
  wagen: "m",
  boden: "m",
  garten: "m",
  ofen: "m",
  regen: "m",
  faden: "m",
  haken: "m",
  hafen: "m",
  morgen: "m",
  tropfen: "m",
  kissen: "n",
  zeichen: "n",
  kuchen: "m",
  knochen: "m",
  r\u00FCcken: "m",
  segen: "m",
  bogen: "m",
  balken: "m",
  riegel: "m",
  ballen: "m",
  fels: "m",
  haus: "n",
  glas: "n",
  bus: "m",
  fluss: "m",
  kuss: "m",
  guss: "m",
  gru\u00DF: "m",
  fu\u00DF: "m",
  hass: "m",
  kompass: "m",
  atlas: "m",
  kreis: "m",
  preis: "m",
  eis: "n",
  reis: "m",
  gleis: "n",
  flei\u00DF: "m",
  geheimnis: "n",
  ergebnis: "n",
  zeugnis: "n",
  bed\u00FCrfnis: "n",
  verh\u00E4ltnis: "n",
  ereignis: "n",
  erlebnis: "n",
  b\u00FCndnis: "n",
  hindernis: "n",
  gef\u00E4ngnis: "n",
  wildnis: "f",
  finsternis: "f",
  fenster: "n",
  zimmer: "n",
  wasser: "n",
  messer: "n",
  feuer: "n",
  kupfer: "n",
  silber: "n",
  pulver: "n",
  wetter: "n",
  alter: "n",
  ufer: "n",
  lager: "n",
  opfer: "n",
  muster: "n",
  kloster: "n",
  register: "n",
  theater: "n",
  fieber: "n",
  leder: "n",
  futter: "n",
  gitter: "n",
  ruder: "n",
  wunder: "n",
  orchester: "n",
  zepter: "n",
  semester: "n",
  polster: "n",
  pflaster: "n",
  laster: "n",
  meter: "m",
  liter: "m",
  zentrum: "n",
  datum: "n",
  museum: "n",
  t\u00FCr: "f",
  hand: "f",
  stern: "m",
  schritt: "m",
  brief: "m",
  weg: "m",
  stimme: "f",
  spur: "f",
  lippe: "f",
  frage: "f",
  perle: "f",
  glocke: "f",
  uhr: "f",
  herz: "n",
  dach: "n",
  stra\u00DFe: "f",
  regel: "f",
  vorrat: "m",
  schicht: "f",
  schaf: "n",
  nummer: "f",
  schuh: "m",
  grenze: "f",
  gutachten: "n",
  satz: "m",
  wort: "n",
  seele: "f",
  teil: "m",
  blume: "f",
  richtung: "f",
  monat: "m",
  zahn: "m",
  ort: "m",
  wand: "f",
  vorhang: "m",
  umstand: "m",
  sandsack: "m",
  kraft: "f",
  bein: "n",
  kanal: "m",
  sinn: "m",
  netz: "n",
  pflasterstein: "m",
  handschuh: "m",
  protokoll: "n",
  system: "n",
  kreidestrich: "m",
  bruchteil: "m",
  tor: "n",
  kran: "m",
  beweis: "m",
  nacht: "f",
  stadt: "f",
  grund: "m",
  zug: "m",
  riff: "n",
  plakat: "n",
  baum: "m",
  erbgang: "m",
  exemplar: "n",
  symptom: "n",
  plan: "m",
  umriss: "m",
  riss: "m",
  bahngleis: "n",
  regal: "n",
  blick: "m",
  bergpass: "m",
  faust: "f",
  stuhl: "m",
  freund: "m",
  stamm: "m",
  tanzschuh: "m",
  dienst: "m",
  ma\u00DF: "n",
  arm: "m",
  kinderhand: "f",
  tisch: "m",
  seil: "n",
  frachtbrief: "m",
  termin: "m",
  formular: "n",
  messwert: "m",
  gegenstand: "m",
  vogel: "m",
  exponat: "n",
  fahrgast: "m",
  meer: "n",
  anruf: "m",
  vorschlag: "m",
  punkt: "m",
  boot: "n",
  paar: "n",
  gast: "m",
  stein: "m",
  stunde: "f",
  minute: "f",
  tag: "m",
  woche: "f",
  seite: "f",
  farbe: "f",
  papier: "n",
  nachbar: "m",
  wolke: "f",
  zeug: "n",
  kind: "n",
  mann: "m",
  frau: "f",
  vater: "m",
  mutter: "f",
  bruder: "m",
  schwester: "f",
  sohn: "m",
  tochter: "f",
  herr: "m",
  dame: "f",
  lehrer: "m",
  arzt: "m",
  pfarrer: "m",
  priester: "m",
  k\u00F6nig: "m",
  k\u00F6nigin: "f",
  kaiser: "m",
  soldat: "m",
  bauer: "m",
  fischer: "m",
  b\u00E4cker: "m",
  schneider: "m",
  schmied: "m",
  m\u00FCller: "m",
  j\u00E4ger: "m",
  hirte: "m",
  knecht: "m",
  magd: "f",
  w\u00E4chter: "m",
  richter: "m",
  h\u00E4ndler: "m",
  fremde: "m",
  kurier: "m",
  agent: "m",
  spion: "m",
  dieb: "m",
  r\u00E4uber: "m",
  m\u00F6rder: "m",
  opferlamm: "n",
  engel: "m",
  teufel: "m",
  geist: "m",
  gott: "m",
  g\u00F6ttin: "f",
  heiliger: "m",
  m\u00F6nch: "m",
  nonne: "f",
  abt: "m",
  bischof: "m",
  papst: "m",
  ritter: "m",
  knappe: "m",
  graf: "m",
  gr\u00E4fin: "f",
  f\u00FCrst: "m",
  prinz: "m",
  prinzessin: "f",
  zauberer: "m",
  hexe: "f",
  drache: "m",
  zwerg: "m",
  elf: "m",
  troll: "m",
  wolf: "m",
  b\u00E4r: "m",
  fuchs: "m",
  hirsch: "m",
  reh: "n",
  pferd: "n",
  hund: "m",
  katze: "f",
  maus: "f",
  ratte: "f",
  schlange: "f",
  fisch: "m",
  m\u00F6we: "f",
  taube: "f",
  kr\u00E4he: "f",
  eule: "f",
  biene: "f",
  fliege: "f",
  spinne: "f",
  k\u00E4fer: "m",
  schmetterling: "m",
  wurm: "m",
  ameise: "f",
  frosch: "m",
  kr\u00F6te: "f",
  eidechse: "f",
  schwan: "m",
  ente: "f",
  gans: "f",
  huhn: "n",
  hahn: "m",
  kuh: "f",
  stier: "m",
  ziege: "f",
  esel: "m",
  schwein: "n",
  lamm: "n",
  // Schwache Maskulina auf -e, die die -e→f-Regel sonst fälschlich fängt
  kollege: "m",
  experte: "m",
  matrose: "m",
  pate: "m",
  sklave: "m",
  laie: "m",
  insasse: "m",
  gatte: "m",
  bulle: "m",
  schurke: "m",
  geselle: "m",
  gef\u00E4hrte: "m",
  genosse: "m",
  komplize: "m",
  jude: "m",
  zar: "m",
  franzose: "m",
  chinese: "m",
  russe: "m",
  grieche: "m",
  t\u00FCrke: "m",
  ire: "m",
  schwede: "m",
  d\u00E4ne: "m",
  psychologe: "m",
  biologe: "m",
  geologe: "m",
  soziologe: "m",
  arch\u00E4ologe: "m",
  philosoph: "m",
  // Neutra auf -e
  interesse: "n",
  geb\u00E4ude: "n",
  gem\u00E4lde: "n",
  gebirge: "n",
  getreide: "n",
  gefolge: "n",
  gel\u00E4nde: "n",
  gewebe: "n",
  gew\u00F6lbe: "n",
  getriebe: "n",
  gef\u00FCge: "n",
  gelage: "n",
  gerede: "n",
  gehege: "n",
  gewerbe: "n"
};

// src/generation/declension.ts
var NOUN_GENDER2 = { ...NOUN_GENDER_2, ...NOUN_GENDER };
function istSubstantivierterInfinitiv(w) {
  if (!/^[a-zäöüß]{4,}en$/.test(w)) return false;
  const stamm = w.slice(0, -2);
  return istVerbform(stamm + "t") || istVerbform(stamm + "et");
}
var E_AUSNAHME = /^(ge[a-zäöüß]+e|.*(auge|ende|käse|junge|erbe|interesse))$/;
function guessGender(noun) {
  const w = (noun || "").toLowerCase().replace(/[^a-zäöüß]/g, "");
  const known = NOUN_GENDER2[w];
  if (known === "m" || known === "f" || known === "n") return known;
  let best = "";
  for (const k in NOUN_GENDER2) {
    if (k.length >= 3 && w.length >= k.length + 2 && w.endsWith(k) && k.length > best.length) best = k;
  }
  if (best) return NOUN_GENDER2[best];
  if (/(ung|heit|keit|schaft|tät|ion|ik|enz|anz|ei|ade|age|üre|itis|ur)$/.test(w)) return "f";
  if (/(chen|lein|ment|tum|um|nis|ma)$/.test(w)) return "n";
  if (/(ling|ismus|ant|ent|ist|eur|or|ich|ig|ast)$/.test(w)) return "m";
  if (istSubstantivierterInfinitiv(w)) return "n";
  if (/^ge[a-zäöüß]{3,}e$/.test(w)) return "n";
  if (/e$/.test(w) && w.length >= 4 && !E_AUSNAHME.test(w)) return "f";
  if (/er$/.test(w)) return "m";
  return void 0;
}

// src/generation/verbconj.ts
var VERB_TOKEN_RE = new RegExp("\\b(" + Object.keys(VERB_CONJ).join("|") + ")\\b", "i");

// src/generation/wordcls.ts
var NOT_INFINITIVE = /* @__PURE__ */ new Set([
  "einen",
  "keinen",
  "seinen",
  "ihren",
  "deinen",
  "unseren",
  "euren",
  "diesen",
  "jenen",
  "denen",
  "welchen",
  "allen",
  "vielen",
  "beiden",
  "manchen",
  "jeden",
  "solchen",
  "anderen",
  "eigenen",
  "letzten",
  "ersten",
  "oben",
  "unten",
  "innen",
  "au\xDFen",
  "hinten",
  "vorn",
  "vorne",
  "neben",
  "eben",
  "gegen",
  "wegen",
  "gegen\xFCber",
  "morgen",
  "\xFCbermorgen",
  "wochen",
  "stunden",
  "sieben",
  "zehn",
  "trotzen",
  "w\xE4hrend",
  "dessen",
  "deren",
  "hinein"
]);
var NICHT_VERB_T = /* @__PURE__ */ new Set([
  "nicht",
  "jetzt",
  "erst",
  "fast",
  "sonst",
  "meist",
  "zuerst",
  "zuletzt",
  "selbst",
  "sogar",
  "seit",
  "samt",
  "statt",
  "mit",
  "zeit",
  "trotz",
  "laut",
  "gerecht",
  "sanft",
  "dicht",
  "leicht",
  "schlecht",
  "recht",
  "direkt",
  "echt",
  "exakt",
  "strikt",
  "perfekt",
  "konkret",
  "komplett",
  "kaputt",
  "sacht",
  "glatt",
  "platt",
  "nackt",
  "satt",
  "breit",
  "bereit",
  "weit",
  "sp\xE4t",
  "hart",
  "zart",
  "kalt",
  "alt",
  "bunt",
  "rot",
  "gut",
  "oft",
  "still",
  "halt",
  "gesamt",
  "insgesamt",
  "bekannt",
  "verwandt",
  "ber\xFChmt",
  "sofort",
  "vielleicht",
  "\xFCberhaupt",
  "zumindest",
  "h\xF6chst",
  "\xE4u\xDFerst",
  "mindest",
  "bestimmt",
  "unbedingt",
  "ernst",
  "einst",
  "l\xE4ngst",
  "j\xFCngst",
  "umsonst",
  "weltweit",
  "korrekt",
  "intakt",
  "kompakt",
  "prompt",
  "getrennt",
  // vierbuchstabige Adjektive und Adverbien auf -t
  "bunt",
  "echt",
  "fest",
  "hart",
  "kalt",
  "laut",
  "matt",
  "nett",
  "satt",
  "weit",
  "zart",
  "fett",
  "halt",
  "wert",
  "dort",
  "fort",
  "stet",
  "sart"
]);
function wirktFinit(w) {
  if (w.length < 4 || NICHT_VERB_T.has(w)) return false;
  if (/^ge[a-zäöüß]+t$/.test(w)) return false;
  return /^[a-zäöüß]+[^aeiouäöü]t$/.test(w) || /^[a-zäöüß]+et$/.test(w);
}
function looksLikeInfinitive(w) {
  if (INFINITIVE_VERBS.has(w)) return true;
  if (w.length < 5 || NOT_INFINITIVE.has(w) || NOUN_GENDER[w]) return false;
  return /(?:[a-zäöüß]{3,})(?:en|ern|eln)$/.test(w);
}
function extractLeadVerb(text) {
  const s = clean(text);
  if (!s) return { verb: null, rest: s };
  const m0 = s.match(/^([A-Za-zÄÖÜäöüß]+)(,?)\s+(.+)$/);
  if (!m0) return { verb: null, rest: s };
  const m = [m0[0], m0[1], (m0[2] ? ", " : "") + m0[3]];
  const raw = m[1];
  const w = raw.toLowerCase();
  if (VERB_CONJ[w]) return { verb: raw, rest: m[2] };
  if (/^[a-zäöüß]/.test(raw) && looksLikeInfinitive(w)) {
    return { verb: null, rest: `${m[2]} ${w}`, isInfinitiveLed: true };
  }
  if (/^[a-zäöüß]+iert$/.test(w)) return { verb: raw, rest: m[2] };
  const dritte = ICH_DU_ZU_ER[w];
  if (dritte && /^[a-zäöüß]/.test(raw)) return { verb: dritte, rest: m[2] };
  if (/^[a-zäöüß]/.test(raw) && (EXTRA_FINITE_RE.test(w) || wirktFinit(w))) {
    return { verb: raw, rest: m[2] };
  }
  return { verb: null, rest: s };
}
var ICH_DU_HAND = {
  sehe: "sieht",
  siehst: "sieht",
  gehe: "geht",
  gehst: "geht",
  komme: "kommt",
  kommst: "kommt",
  finde: "findet",
  findest: "findet",
  glaube: "glaubt",
  glaubst: "glaubt",
  lebe: "lebt",
  lebst: "lebt",
  liege: "liegt",
  liegst: "liegt",
  sitze: "sitzt",
  lese: "liest",
  liest: "liest",
  schlafe: "schl\xE4ft",
  schl\u00E4fst: "schl\xE4ft",
  laufe: "l\xE4uft",
  l\u00E4ufst: "l\xE4uft",
  falle: "f\xE4llt",
  f\u00E4llst: "f\xE4llt",
  breche: "bricht",
  brichst: "bricht",
  rufe: "ruft",
  rufst: "ruft",
  weine: "weint",
  weinst: "weint",
  lache: "lacht",
  lachst: "lacht",
  sp\u00FCre: "sp\xFCrt",
  sp\u00FCrst: "sp\xFCrt",
  atme: "atmet",
  atmest: "atmet",
  singe: "singt",
  singst: "singt",
  \u00F6ffne: "\xF6ffnet",
  \u00F6ffnest: "\xF6ffnet",
  erinnere: "erinnert",
  erinnerst: "erinnert",
  erkenne: "erkennt",
  erkennst: "erkennt",
  zerbreche: "zerbricht",
  zerbrichst: "zerbricht",
  stolpere: "stolpert",
  stolperst: "stolpert",
  verharre: "verharrt",
  verharrst: "verharrt",
  wandere: "wandert",
  wanderst: "wandert",
  zittere: "zittert",
  zitterst: "zittert",
  fl\u00FCstere: "fl\xFCstert",
  fl\u00FCsterst: "fl\xFCstert",
  wundere: "wundert",
  wunderst: "wundert",
  z\u00F6gere: "z\xF6gert",
  z\u00F6gerst: "z\xF6gert",
  erwache: "erwacht",
  erwachst: "erwacht",
  verschwinde: "verschwindet",
  verschwindest: "verschwindet",
  begreife: "begreift",
  begreifst: "begreift",
  verstehe: "versteht",
  verstehst: "versteht",
  bleibe: "bleibt",
  bleibst: "bleibt",
  ziehe: "zieht",
  ziehst: "zieht"
};
var ICH_DU_ZU_ER = (() => {
  const m = {};
  for (const [dritte, formen] of Object.entries(VERB_CONJ)) {
    for (const p of ["ich", "du", "wir", "ihr"]) {
      const f = formen[p];
      if (f && !m[f]) m[f] = dritte;
    }
  }
  return { ...m, ...ICH_DU_HAND };
})();
var EXTRA_FINITE_RE = /\b(geschieht|geschehen|geschah|passiert|passieren|passierte|tickt|ticken|atmet|atmen|wächst|wachsen|wuchs|brennt|brennen|brannte|fällt|fallen|fiel|zerfällt|zerfallen|verschwindet|verschwinden|verschwand|erscheint|erscheinen|erschien|endet|enden|endete|beginnt|beginnen|begann|stirbt|sterben|starb|blüht|blühen|klopft|klopfen|flackert|flackern|zerbricht|zerbrechen|zerbrach|dreht|drehen|schweigt|schweigen|schwieg|singt|singen|sang|wandert|wandern|glüht|glühen|tanzt|tanzen|brüllt|brüllen|reagiert|reagieren|zeigt|zeigen|spricht|sprechen|sprach|antwortet|antworten|erinnert|erinnern|verändert|verändern|zittert|zittern|leuchtet|leuchten|schmilzt|schmelzen|regnet|schneit|blitzt|donnert|bebt|läuft|laufen|lief|rinnt|tropft|fließt|fließen|floss|steigt|steigen|stieg|sinkt|sinken|sank|kreist|kreisen|pulsiert|vibriert|summt|brummt|knistert|raschelt|flüstert|flüstern|schreit|schreien|schrie|weint|weinen|lacht|lachen|verglüht|verblasst|zerrinnt|wartet|warten)\b/i;
function looksLikeFullClause(leadVerb, rest) {
  if (leadVerb) return false;
  return VERB_TOKEN_RE.test(rest || "") || EXTRA_FINITE_RE.test(rest || "");
}

// src/generation/coherence.ts
var PRAET_STRONG = /\b(war|waren|warst|hatte|hatten|wurde|wurden|ging|gingen|kam|kamen|sah|sahen|gab|gaben|stand|standen|blieb|blieben|hielt|hielten|ließ|ließen|fand|fanden|nahm|nahmen|sprach|sprachen|schrieb|schrieben|trug|trugen|fuhr|fuhren|lief|liefen|saß|saßen|lag|lagen|hieß|hießen|zog|zogen|schlief|schliefen|rief|riefen|fiel|fielen|sang|sangen|trank|tranken|schwieg|schwiegen|floss|flossen|stieg|stiegen|sank|sanken|bot|boten|schloss|schlossen|verlor|verloren|begann|begannen|geschah|geschahen|konnte|konnten|musste|mussten|wollte|wollten|sollte|sollten|durfte|durften|wusste|wussten|dachte|dachten|brachte|brachten)\b/i;
var PRAET_WEAK = /\b[a-zäöüß]{3,}(te|ten|test)\b/;
var PRAES_MARK = /\b(ist|sind|bin|bist|seid|hat|habe|hast|haben|habt|wird|werden|wirst|kann|kannst|können|muss|musst|müssen|will|willst|wollen|soll|sollen|darf|dürfen|weiß|wissen|geht|gehen|kommt|kommen|sieht|sehen|steht|stehen|bleibt|bleiben|liegt|liegen|gibt|geben|nimmt|nehmen|spricht|sprechen|trägt|tragen|läuft|laufen|fällt|fallen|geschieht|passiert|beginnt|endet|wartet|antwortet|arbeitet|bedeutet|beobachtet|berichtet|schlägt|zeigt|dauert|öffnet|schließt|klingt|riecht|scheint|hört|fühlt|wirkt|führt|dreht|zieht|hält|läuft|fließt|wächst|sinkt|steigt|schweigt|spricht|denkt|kennt|nennt|trägt|findet|verliert|verschwindet)\b/i;
var ADJ_CONTEXT = /(?:\b(?:der|die|das|den|dem|des|ein|eine|einen|einem|einer|eines|kein|keine|mein|meine|dein|deine|sein|seine|ihr|ihre|unser|unsere|jede|jeder|jedes|diese|dieser|dieses|manche|viele|alle)\s+[a-zäöüß]*)?\b[a-zäöüß]{3,}(?:te|ten)\b(?=\s+[A-ZÄÖÜ])/;
var weakLooksVerbal = (t) => {
  const m = t.match(/\b[a-zäöüß]{3,}(te|ten|test|tet)\b/g);
  if (!m) return false;
  return m.some((w) => {
    const re = new RegExp("\\b" + w + "\\b(?=\\s+[A-Z\xC4\xD6\xDC])");
    return !re.test(t);
  });
};
function isPastTense(s) {
  const t = s || "";
  if (PRAES_MARK.test(t)) return false;
  if (PRAET_STRONG.test(t)) return true;
  if (PRAET_WEAK.test(t) && weakLooksVerbal(t) && !ADJ_CONTEXT.test(t)) return true;
  return (t.toLowerCase().match(/[a-zäöüß]+/g) || []).some((w) => !!PAST2PRES[w]);
}
var NAME_STOP = /* @__PURE__ */ new Set(["der", "die", "das", "den", "dem", "des", "ein", "eine", "einen", "einem", "einer", "und", "oder", "aber", "denn", "doch", "dann", "als", "wie", "was", "wer", "wo", "wann", "warum", "ich", "du", "er", "sie", "es", "wir", "ihr", "man", "hier", "dort", "jetzt", "noch", "nur", "auch", "schon", "immer", "nie", "sehr", "so", "zu", "im", "am", "auf", "in", "an", "mit", "von", "f\xFCr", "bei", "nach", "vor", "\xFCber", "unter", "durch", "um", "ohne", "seit", "damals", "sp\xE4ter", "zuerst", "zuletzt", "stille", "nein", "ja", "fast", "vielleicht", "genau", "warte", "gut", "dabei", "dazu", "dann"]);
var DETERMINER = /^(der|die|das|den|dem|des|ein|eine|einen|einem|einer|eines|mein|meine|meinen|meinem|meiner|dein|deine|sein|seine|seinen|seinem|ihr|ihre|ihren|ihrem|unser|unsere|euer|eure|kein|keine|keinen|keinem|jeder|jede|jedes|dieser|diese|dieses|diesem|diesen|jener|jene|manche|viele|alle|beide|im|am|zum|zur|ins|ans|vom|beim|aufs|durchs|übers|unters)$/i;
var PREP = /^(in|an|auf|bei|mit|von|zu|nach|über|unter|vor|hinter|neben|zwischen|durch|für|ohne|um|gegen|seit|trotz|wegen|während|aus)$/i;
function properNames(text) {
  const out = /* @__PURE__ */ new Set();
  for (const sent of splitSentences(text)) {
    const w = sent.trim().split(/\s+/);
    for (let i = 1; i < w.length; i++) {
      const raw = w[i].replace(/[^A-Za-zÄÖÜäöüß-]/g, "");
      if (raw.length < 3 || !/^[A-ZÄÖÜ]/.test(raw)) continue;
      const lowRaw = raw.toLowerCase();
      if (NAME_STOP.has(lowRaw)) continue;
      if (NOUN_GENDER[lowRaw]) continue;
      const prev = (w[i - 1] || "").replace(/[^A-Za-zÄÖÜäöüß]/g, "");
      if (DETERMINER.test(prev) || PREP.test(prev)) continue;
      out.add(raw);
    }
  }
  return [...out];
}
var PAST2PRES = {
  war: "ist",
  waren: "sind",
  warst: "bist",
  hatte: "hat",
  hatten: "haben",
  hattest: "hast",
  wurde: "wird",
  wurden: "werden",
  ging: "geht",
  gingen: "gehen",
  kam: "kommt",
  kamen: "kommen",
  sah: "sieht",
  sahen: "sehen",
  gab: "gibt",
  gaben: "geben",
  stand: "steht",
  standen: "stehen",
  blieb: "bleibt",
  blieben: "bleiben",
  hielt: "h\xE4lt",
  hielten: "halten",
  lie\u00DF: "l\xE4sst",
  lie\u00DFen: "lassen",
  fand: "findet",
  fanden: "finden",
  nahm: "nimmt",
  nahmen: "nehmen",
  sprach: "spricht",
  sprachen: "sprechen",
  schrieb: "schreibt",
  schrieben: "schreiben",
  trug: "tr\xE4gt",
  trugen: "tragen",
  fuhr: "f\xE4hrt",
  fuhren: "fahren",
  lief: "l\xE4uft",
  liefen: "laufen",
  sa\u00DF: "sitzt",
  sa\u00DFen: "sitzen",
  lag: "liegt",
  lagen: "liegen",
  hie\u00DF: "hei\xDFt",
  hie\u00DFen: "hei\xDFen",
  zog: "zieht",
  zogen: "ziehen",
  schlief: "schl\xE4ft",
  schliefen: "schlafen",
  rief: "ruft",
  riefen: "rufen",
  fiel: "f\xE4llt",
  fielen: "fallen",
  sang: "singt",
  sangen: "singen",
  trank: "trinkt",
  tranken: "trinken",
  schwieg: "schweigt",
  schwiegen: "schweigen",
  floss: "flie\xDFt",
  flossen: "flie\xDFen",
  stieg: "steigt",
  stiegen: "steigen",
  sank: "sinkt",
  sanken: "sinken",
  bot: "bietet",
  boten: "bieten",
  schloss: "schlie\xDFt",
  schlossen: "schlie\xDFen",
  verlor: "verliert",
  verloren: "verlieren",
  begann: "beginnt",
  begannen: "beginnen",
  geschah: "geschieht",
  geschahen: "geschehen",
  konnte: "kann",
  konnten: "k\xF6nnen",
  musste: "muss",
  mussten: "m\xFCssen",
  wollte: "will",
  wollten: "wollen",
  sollte: "soll",
  sollten: "sollen",
  durfte: "darf",
  durften: "d\xFCrfen",
  wusste: "wei\xDF",
  wussten: "wissen",
  dachte: "denkt",
  dachten: "denken",
  brachte: "bringt",
  brachten: "bringen",
  kannte: "kennt",
  kannten: "kennen",
  erkannte: "erkennt",
  erkannten: "erkennen",
  brannte: "brennt",
  brannten: "brennen",
  nannte: "nennt",
  nannten: "nennen",
  rannte: "rennt",
  rannten: "rennen",
  wandte: "wendet",
  wandten: "wenden",
  sprang: "springt",
  sprangen: "springen",
  schrie: "schreit",
  schrien: "schreien",
  flog: "fliegt",
  flogen: "fliegen",
  floh: "flieht",
  flohen: "fliehen",
  schoss: "schie\xDFt",
  schossen: "schie\xDFen",
  riss: "rei\xDFt",
  rissen: "rei\xDFen",
  biss: "bei\xDFt",
  bissen: "bei\xDFen",
  griff: "greift",
  griffen: "greifen",
  pfiff: "pfeift",
  pfiffen: "pfeifen",
  schnitt: "schneidet",
  schnitten: "schneiden",
  litt: "leidet",
  litten: "leiden",
  trat: "tritt",
  traten: "treten",
  verga\u00DF: "vergisst",
  verga\u00DFen: "vergessen",
  wuchs: "w\xE4chst",
  wuchsen: "wachsen",
  wich: "weicht",
  wichen: "weichen",
  schien: "scheint",
  schienen: "scheinen",
  zerbrach: "zerbricht",
  zerbrachen: "zerbrechen",
  verschwand: "verschwindet",
  verschwanden: "verschwinden",
  erschien: "erscheint",
  erschienen: "erscheinen",
  starb: "stirbt",
  starben: "sterben",
  brach: "bricht",
  brachen: "brechen",
  sprach2: "spricht",
  schwoll: "schwillt",
  schwollen: "schwellen",
  bog: "biegt",
  bogen: "biegen",
  hob: "hebt",
  hoben: "heben",
  wob: "webt",
  woben: "weben",
  klang: "klingt",
  klangen: "klingen",
  sann: "sinnt",
  sannen: "sinnen",
  rann: "rinnt",
  rannen: "rinnen",
  schwamm: "schwimmt",
  schwammen: "schwimmen",
  verschwieg: "verschweigt",
  zerfiel: "zerf\xE4llt",
  zerfielen: "zerfallen",
  entstand: "entsteht",
  entstanden: "entstehen",
  verstand: "versteht",
  verstanden: "verstehen",
  bestand: "besteht",
  bestanden: "bestehen",
  geriet: "ger\xE4t",
  gerieten: "geraten",
  trieb: "treibt",
  trieben: "treiben",
  schrak: "schrickt",
  wies: "weist",
  wiesen: "weisen",
  hing: "h\xE4ngt",
  hingen: "h\xE4ngen",
  schwand: "schwindet",
  schwanden: "schwinden",
  gewann: "gewinnt",
  gewannen: "gewinnen",
  zerriss: "zerrei\xDFt",
  zerrissen2: "zerrei\xDFen",
  empfand: "empfindet",
  empfanden: "empfinden",
  befahl: "befiehlt",
  befahlen: "befehlen",
  half: "hilft",
  halfen: "helfen",
  warf: "wirft",
  warfen: "werfen",
  starrte2: "starrt",
  las: "liest",
  lasen: "lesen",
  a\u00DF: "isst",
  a\u00DFen: "essen",
  bat: "bittet",
  baten: "bitten"
};

// src/atoms/derive.ts
var SEIN_HABEN_WERDEN = /^(ist|sind|bin|bist|seid|war|waren|warst|hat|habe|hast|haben|habt|hatte|hatten|wird|werden|wirst|werdet|wurde|wurden|kann|kannst|können|könnt|konnte|muss|musst|müssen|müsst|will|willst|wollen|wollt|soll|sollen|darf|dürfen|mag|mögen|weiß|wissen|bleibt|bleiben|blieb|gibt|geben|gab)$/;
var KURZVERB = /^(löst|geht|ruft|tut|gibt|lebt|hebt|legt|sagt|sieht|hält|fällt|zieht|trägt|liegt|kommt|nimmt|läuft|steht|dreht|führt|hört|fühlt|zählt|setzt|passt|weint|lacht|denkt|kennt|nennt|misst|sinkt|steigt|klingt|singt|fehlt|blickt|wirkt|reißt|bricht|spricht|wächst)$/;
var PRAET_FORM = /(?:^|^[a-zäöüß]{2,6})(lag|lagen|stand|standen|ging|gingen|kam|kamen|sah|sahen|nahm|nahmen|hielt|hielten|ließ|ließen|fand|fanden|zog|zogen|trug|trugen|fiel|fielen|rief|riefen|sprach|schrieb|floss|stieg|sank|klang|hing|schien|trieb|brach|schloss|verlor|begann|geschah|roch|rochen|sass|saßen|riss|rissen|sprang|sprangen|schlug|schlugen|traf|trafen|griff|griffen|lief|liefen|wusste|wussten|verschwand|verschwanden|blieb|blieben|hieß|hießen|wuchs|wuchsen|schob|schoben|bog|bogen|schwieg|schwiegen)$/;
var EN_KEIN_VERB = /* @__PURE__ */ new Set([
  "gegen",
  "neben",
  "wegen",
  "zwischen",
  "entgegen",
  "oben",
  "unten",
  "eben",
  "dr\xFCben",
  "drau\xDFen",
  "drinnen",
  "morgen",
  "selten",
  "ansonsten",
  "meisten",
  "wenigsten",
  "offen",
  "eigen",
  "golden",
  "seiden",
  "wollen",
  "einen",
  "keinen",
  "meinen",
  "seinen",
  "ihren",
  "deinen",
  "unseren",
  "euren",
  "deren",
  "dessen",
  "allen",
  "vielen",
  "manchen",
  "welchen",
  "jeden",
  "diesen",
  "jenen",
  "denen",
  "ihnen",
  "sieben",
  "tausenden",
  "hunderten",
  "anderen",
  "einigen",
  "wenigen",
  "beiden",
  "solchen",
  "eigenen",
  "ersten",
  "zweiten",
  "dritten",
  "letzten",
  "n\xE4chsten",
  "besten",
  "ganzen",
  "halben",
  "fernen",
  "nahen",
  "hohen",
  "tiefen",
  "langen",
  "kurzen",
  "alten",
  "neuen",
  "jungen",
  "kleinen",
  "gro\xDFen",
  "roten",
  "gr\xFCnen",
  "blauen",
  "schwarzen",
  "wei\xDFen",
  "kalten",
  "warmen",
  "leeren",
  "vollen",
  "toten",
  "fremden",
  "stillen",
  "dunklen",
  "hellen",
  "innen",
  "au\xDFen",
  "hinten",
  "vorn",
  "mitten",
  "unterdessen",
  "indessen",
  "\xFCbrigen",
  "wegen",
  "trotzdem",
  "zusammen",
  "gegen\xFCber",
  "dr\xFCben"
]);
var DET_ODER_PREP = /* @__PURE__ */ new Set([
  "der",
  "die",
  "das",
  "des",
  "dem",
  "den",
  "ein",
  "eine",
  "einen",
  "einem",
  "einer",
  "eines",
  "kein",
  "keine",
  "keinen",
  "keinem",
  "keiner",
  "mein",
  "meine",
  "meinen",
  "meinem",
  "meiner",
  "dein",
  "deine",
  "deinen",
  "sein",
  "seine",
  "seinen",
  "seinem",
  "seiner",
  "ihr",
  "ihre",
  "ihren",
  "ihrem",
  "ihrer",
  "unser",
  "unsere",
  "unseren",
  "im",
  "am",
  "vom",
  "zum",
  "zur",
  "beim",
  "ins",
  "ans",
  "mit",
  "von",
  "zu",
  "aus",
  "bei",
  "nach",
  "seit",
  "auf",
  "an",
  "in",
  "\xFCber",
  "unter",
  "vor",
  "hinter",
  "neben",
  "zwischen",
  "durch",
  "f\xFCr",
  "ohne",
  "um",
  "gegen",
  "wegen",
  "trotz",
  "w\xE4hrend",
  "dieser",
  "diese",
  "diesen",
  "diesem",
  "dieses",
  "jeder",
  "jede",
  "jeden",
  "jedem",
  "jedes",
  "welcher",
  "welche",
  "welchen",
  "welchem",
  "manche",
  "manchen",
  "solche",
  "solchen",
  "viele",
  "vielen",
  "wenige",
  "wenigen",
  "einige",
  "einigen",
  "beide",
  "beiden",
  "zwei",
  "drei",
  "vier",
  "f\xFCnf",
  "sechs",
  "sieben",
  "acht",
  "neun",
  "zehn",
  "ganz",
  "sehr",
  "zu",
  "so",
  "wie",
  "als",
  "etwas",
  "nichts"
]);
var NOMEN_ENDUNG = /(ung|heit|keit|schaft|tät|ion|nis|tum|chen|lein|ment)$/;
var PREP2 = /^(in|im|an|am|auf|bei|beim|mit|von|vom|zu|zum|zur|nach|über|unter|vor|hinter|neben|zwischen|durch|für|ohne|um|gegen|seit|trotz|wegen|während|aus|entlang|inmitten|jenseits|abseits)\b/i;
var SUBJUNKTION = /^(dass|weil|obwohl|wenn|nachdem|bevor|ob|indem|sobald|solange|falls|sodass)\b/i;
var REL = /^(der|die|das|den|dem|des|welche[rsmn]?)\s+\S+\s/i;
var KONNEKTOR = /^(und|oder|aber|doch|denn|sondern|dann|dabei|also|somit|trotzdem|dennoch|außerdem|zudem)(\s+\w+)?$/i;
var ARTIKEL = /^(ein|eine|einen|einem|einer|eines|der|die|das|den|dem|des|kein|keine|mein|meine|dein|deine|sein|seine|ihr|ihre|dieser|diese|dieses|jener|jene)\b/i;
var PRON_START = /^(er|sie|es|ihm|ihr|ihn|ihnen|dessen|deren|diese[rs]?|jene[rs]?)\b/i;
var silben = (t) => {
  const w = t.toLowerCase().match(/[a-zäöüß]+/g) || [];
  return w.reduce((n, x) => n + Math.max(1, (x.match(/[aeiouäöüy]+/g) || []).length), 0);
};
var woerter = (t) => (t.match(/\S+/g) || []).length;
var tiefe = (t) => (t.match(/,\s*(dass|weil|obwohl|wenn|als|während|nachdem|bevor|damit|ob|indem|der|die|das|den|dem|welche)/gi) || []).length;
function subjektOf(t, typ) {
  if (!["hauptsatz", "nebensatz", "rahmen", "kopf"].includes(typ)) return null;
  const s = " " + t.toLowerCase() + " ";
  if (/\b(ich|mir|mich)\b/.test(s)) return { person: 1, numerus: "sg", genus: null };
  if (/\b(wir|uns)\b/.test(s)) return { person: 1, numerus: "pl", genus: null };
  if (/\b(du|dir|dich)\b/.test(s)) return { person: 2, numerus: "sg", genus: null };
  if (/\b(ihr|euch)\b/.test(s)) return { person: 2, numerus: "pl", genus: null };
  const m = t.match(/\b(?:der|die|das|ein|eine)\s+([A-ZÄÖÜ][a-zäöüß-]+)/);
  const g = m ? guessGender(m[1]) : void 0;
  const genus = g === "m" ? "mask" : g === "f" ? "fem" : g === "n" ? "neut" : null;
  const plural = /\b(sie|die)\s+\w+en\b/.test(t.toLowerCase()) || /\b(sind|waren|haben|werden)\b/.test(t.toLowerCase());
  return { person: 3, numerus: plural ? "pl" : "sg", genus };
}
function hatFinitesVerb(seg) {
  const ws = seg.match(/[A-Za-zÄÖÜäöüß]+/g) || [];
  for (let i = 0; i < ws.length; i++) {
    const w = ws[i];
    if (/^[A-ZÄÖÜ]/.test(w)) continue;
    const l = w.toLowerCase();
    const prev = (ws[i - 1] || "").toLowerCase(), next = ws[i + 1] || "";
    const attributiv = DET_ODER_PREP.has(prev) || /^[A-ZÄÖÜ]/.test(next);
    if ((prev === "ich" || next.toLowerCase() === "ich") && /^[a-zäöüß]{3,}e$/.test(l) && !DET_ODER_PREP.has(l)) return true;
    if (VERB_CONJ[l]) return true;
    if (SEIN_HABEN_WERDEN.test(l)) return true;
    if (PRAET_FORM.test(l)) return true;
    if (KURZVERB.test(l)) return true;
    if (/t$/.test(l) && !attributiv && istVerbform(l)) return true;
    if (/en$/.test(l) && l.length >= 5 && !EN_KEIN_VERB.has(l) && !attributiv && (VERB_CONJ[l.slice(0, -2) + "t"] || VERB_CONJ[l.slice(0, -2) + "et"] || istVerbform(l.slice(0, -2) + "t"))) return true;
    if (/^(?!ge)[a-zäöüß]{4,}(?:t|te|en|ten)$/.test(l) && !NOMEN_ENDUNG.test(l) && !KEIN_VERB.has(l) && !EN_KEIN_VERB.has(l)) return true;
  }
  const first = (seg.match(/^([A-ZÄÖÜ][a-zäöüß]+)/) || [])[1];
  if (first) {
    const l = first.toLowerCase();
    if (VERB_CONJ[l] || SEIN_HABEN_WERDEN.test(l) || PRAET_FORM.test(l)) return true;
  }
  return looksLikeFullClause(null, seg);
}
function deriveAtom(raw) {
  const text = (raw || "").trim();
  const unsicher = [];
  const wcount = woerter(text);
  const end = (text.match(/[.!?:;—]$/) || [""])[0];
  const lead = extractLeadVerb(text);
  const haupt = text.split(",")[0];
  const hatFinit = !!lead.verb || hatFinitesVerb(haupt);
  let typ;
  if (/:$/.test(text)) typ = "kopf";
  else if (text.includes("\u27E8")) typ = "rahmen";
  else if (wcount === 1) typ = "einwort";
  else if (KONNEKTOR.test(text)) typ = "konnektor";
  else if (SUBJUNKTION.test(text) && hatFinit) typ = "nebensatz";
  else if (REL.test(text) && hatFinit && /,/.test(text) === false && /\ben\b|\bt\b/.test("")) typ = "nebensatz";
  else if (hatFinit) typ = "hauptsatz";
  else if (PREP2.test(text)) typ = "praepositionalphrase";
  else if (ARTIKEL.test(text) || /\b[A-ZÄÖÜ][a-zäöüß-]{2,}/.test(text)) typ = "nominalphrase";
  else typ = "fragment";
  if (PREP2.test(text) && hatFinit) unsicher.push("typ (Inversion?)");
  if (typ === "fragment" && wcount >= 6) unsicher.push("typ (langes Fragment?)");
  let kasus = null;
  if (typ === "nominalphrase") {
    const a = (text.match(/^(\S+)/) || [""])[0].toLowerCase();
    const kern = (text.match(/\b([A-ZÄÖÜ][a-zäöüß-]{2,})/) || [])[1];
    const g = kern ? guessGender(kern) : void 0;
    if (/^(einen|den)$/.test(a)) kasus = "akk";
    else if (/^(einem|dem|einer)$/.test(a)) kasus = "dat";
    else if (a === "der") {
      kasus = g === "f" ? "dat" : g === "m" ? "nom" : null;
      if (!kasus) unsicher.push("kasus (der: Nom/Dat)");
    } else if (/^(eines|des)$/.test(a)) kasus = "gen";
    else if (/^(ein|eine|die|das)$/.test(a)) {
      kasus = "nom_akk";
      unsicher.push("kasus (nom/akk mehrdeutig)");
    } else unsicher.push("kasus");
  }
  const kadenz = end === ":" ? "schwebend" : end ? "fallend" : "offen";
  const tempus = typ === "nominalphrase" || typ === "fragment" || typ === "praepositionalphrase" || typ === "einwort" ? "kein" : isPastTense(text) ? "praeteritum" : "praesens";
  const bezug = PRON_START.test(text) ? { pronomen: (text.match(/^\S+/) || [""])[0].toLowerCase(), genus: /^(sie|ihr|ihnen)/i.test(text) ? "fem" : "mask", numerus: "sg" } : null;
  if (bezug) unsicher.push("verlangt_bezug (Genus gesch\xE4tzt)");
  const s = silben(text);
  return {
    text,
    typ,
    bietet: { kasus, kadenz },
    subjekt: subjektOf(text, typ),
    tempus,
    fuehrt_ein: properNames(text),
    verlangt_bezug: bezug,
    oeffnet: typ === "kopf",
    rhythmus: { woerter: wcount, silben: s, tiefe: tiefe(text), endzeichen: end, gewicht: wcount <= 4 ? "kurz" : wcount <= 9 ? "mittel" : "lang" },
    unsicher
  };
}

// src/features/textpreset.ts
var KATEGORIEN = ["motifs", "hooks", "props", "turns", "obstacles", "stakes", "endings"];
var WIDERSTAND = /\b(aber|doch|kein|keine|keinen|nicht|niemand|nichts|nie|niemals|fehlt|fehlen|scheitert|verweigert|bleibt aus|reicht nicht|zu spät|vergebens|umsonst)\b/i;
var WENDE = /^(dann|plötzlich|auf einmal|mit einem mal|seitdem|von da an)\b|\b(kippt|kippen|beginnt|beginnen|bricht|brechen|verwandelt|wendet|ändert|dreht sich|wird zu|wechselt)\b/i;
var SPIEL = /\b(es geht um|auf dem spiel|einsatz|entscheidet|entscheiden|zählt|zählen|gehört|gilt|bedeutet|kostet|verliert|gewinnt)\b/i;
function teilstuecke(text) {
  return (text || "").replace(/\s+/g, " ").split(/(?<=[.!?…])\s+/).flatMap((s) => s.split(/\s*[;—–]\s*/)).map((s) => clean(s).replace(/^[„"«»]+|[.!?…„"«»]+$/g, "").trim()).filter((s) => {
    const w = s.split(/\s+/).filter(Boolean).length;
    return w >= 3 && w <= 22;
  });
}
function kategorieFuer(stueck, istSchluss) {
  const typ = deriveAtom(stueck).typ;
  const wc = stueck.split(/\s+/).filter(Boolean).length;
  if (typ === "nominalphrase") return wc <= 5 ? "props" : "motifs";
  if (typ !== "hauptsatz") return "motifs";
  if (istSchluss) return "endings";
  if (WIDERSTAND.test(stueck)) return "obstacles";
  if (WENDE.test(stueck)) return "turns";
  if (SPIEL.test(stueck)) return "stakes";
  return wc <= 14 ? "hooks" : "motifs";
}
function presetAusText(text) {
  const stuecke = teilstuecke(text);
  const bank2 = { motifs: [], hooks: [], props: [], turns: [], obstacles: [], stakes: [], endings: [] };
  const schlussGrenze = Math.max(0, stuecke.length - 2);
  const gesehen = /* @__PURE__ */ new Set();
  stuecke.forEach((s, i) => {
    const key = s.toLowerCase();
    if (gesehen.has(key)) return;
    gesehen.add(key);
    bank2[kategorieFuer(s, i >= schlussGrenze && deriveAtom(s).typ === "hauptsatz")].push(s);
  });
  for (const k of KATEGORIEN) {
    if (bank2[k].length) continue;
    const vollste = KATEGORIEN.filter((x) => bank2[x].length > 1).sort((a, b) => bank2[b].length - bank2[a].length)[0];
    if (vollste) bank2[k].push(bank2[vollste].pop());
  }
  const woerter2 = (text || "").split(/\s+/).filter(Boolean).length;
  return { bank: bank2, woerter: woerter2, stuecke: gesehen.size };
}
function preset2AusText(text) {
  const p = presetAusText(text);
  const b = p.bank;
  const konflikte = [...b.stakes, ...b.hooks].map((s) => (s.match(/\bes geht um\s+(.{3,60})$/i) || [])[1]).filter((x) => !!x);
  const drama = {
    einstieg: b.hooks.slice(0, 3),
    mitte: b.motifs.slice(0, 4),
    hoehepunkt: b.turns.slice(0, 2),
    schluss: b.endings.slice(0, 3),
    ausloeser: b.props.slice(0, 5),
    veraenderungen: b.turns.slice(0, 4),
    konflikte: konflikte.slice(0, 5),
    zeitanomalien: [],
    regeln: []
  };
  const pools = [.../* @__PURE__ */ new Set([...b.props, ...b.motifs])];
  return { ...p, drama, pools };
}
var VORLAGE_EVOLUTION = `Das Leben probiert alles einmal aus. Ein Kiefer aus fr\xFCheren Zeiten. Die Flosse erinnert sich an den Weg zum Ufer. Ein Auge, das in vier Linien zugleich erfunden wird. Der lange Hals entscheidet \xFCber den Hunger. Eine Feder, die zuerst w\xE4rmt und dann tr\xE4gt. Das Wasser entl\xE4sst seine Kinder an Land. Ein Panzer mit Jahresringen. Die Zuf\xE4lle sammeln sich, bis sie wie ein Plan aussehen. Aber kein Bauplan liegt dem Ganzen bei. Die Kiemen schlie\xDFen sich, und die Lunge \xFCbernimmt. Ein Fossil im Kalk. Kein Merkmal wei\xDF, wof\xFCr es sp\xE4ter gut sein wird. Die Insel formt ihre eigenen Schn\xE4bel. Es geht um den n\xE4chsten Morgen, nicht um den fernen Plan. Pl\xF6tzlich kippt das Klima, und die Gr\xF6\xDFten verschwinden zuerst. Dann beginnt das Kleine, die leeren R\xE4ume zu besetzen. Ein angespitzter Zahn als Werkzeug. Die Landschaft schreibt an den K\xF6rpern mit. Der Wald weicht der Savanne, und der Gang richtet sich auf. Eine Hand mit einem Daumen, der den Fingern begegnet. Das Erbgut vergisst nichts und verr\xE4t nichts. Aber die L\xFCcke zwischen den Funden bleibt. Die H\xE4utung dauert eine Nacht und ein Erdzeitalter. Ein Bernstein mit M\xFCcke. Es geht um das Weiterreichen selbst. Die Arten wandern, wenn der Boden es verlangt. Ein Geweih, das zu schwer f\xFCr seinen Tr\xE4ger wird. Die Anpassung kennt keine Richtung, nur den n\xE4chsten Schritt. Pl\xF6tzlich steht ein Tier am Feuer und gibt ihm einen Namen. Dann wendet sich die Auslese nach innen. Die Schrift \xFCbernimmt, was die Knochen begonnen haben. Am Ende sitzt das Ergebnis am Mikroskop und sucht seinen Anfang. Zur\xFCck bleibt ein Abdruck im Schlamm, \xE4lter als jede Frage.`;

// src/features/erzaehlerbank.ts
var ERZAEHLER_PLAETZE = 10;
var BANK_KEY = "dm_erzaehlerbank_v1";
var QUELLE_KEY = "dm_erzaehler_quelle_v1";
function ladeErzaehlerbank() {
  let roh = [];
  try {
    roh = JSON.parse(localStorage.getItem(BANK_KEY) || "[]");
  } catch {
    roh = [];
  }
  const list = Array.isArray(roh) ? roh : [];
  return Array.from({ length: ERZAEHLER_PLAETZE }, (_, i) => {
    const e = list[i];
    return { titel: String(e?.titel || "").slice(0, 60), text: String(e?.text || "") };
  });
}
function speichereErzaehlerbank(list) {
  try {
    localStorage.setItem(BANK_KEY, JSON.stringify(list.slice(0, ERZAEHLER_PLAETZE)));
  } catch {
  }
}
function ladeQuelle() {
  const q = localStorage.getItem(QUELLE_KEY) || "preset";
  return q === "preset" || q === "wuerfeln" || /^[0-9]$/.test(q) ? q : "preset";
}
function setzeQuelle(q) {
  try {
    localStorage.setItem(QUELLE_KEY, q);
  } catch {
  }
}
function platzBrauchbar(e) {
  return (e.text || "").split(/\s+/).filter(Boolean).length >= 40;
}
function erzaehlerBogen(index) {
  const e = ladeErzaehlerbank()[index];
  if (!e || !platzBrauchbar(e)) return null;
  return preset2AusText(e.text).drama;
}
function bogenFuerErzeugung() {
  const q = ladeQuelle();
  if (q === "preset") return null;
  if (/^[0-9]$/.test(q)) return erzaehlerBogen(parseInt(q, 10));
  const brauchbar = ladeErzaehlerbank().map((e, i) => ({ e, i })).filter((x) => platzBrauchbar(x.e));
  if (!brauchbar.length) return null;
  return erzaehlerBogen(brauchbar[Math.floor(Math.random() * brauchbar.length)].i);
}

// src/features/erzaehlungen.data.ts
var ERZAEHLUNGEN_VORLAGEN = [
  {
    titel: "Steigender Bogen",
    text: "Der F\xE4hrmann z\xE4hlt am Morgen die Ruder. Ein Riemen fehlt. Das Wasser steht still wie ein Gedanke. Die erste Fuhre geht gut, die zweite auch. Ein Passagier l\xE4sst eine M\xFCnze fallen, die niemand aufhebt. Der Wind dreht gegen Mittag. Die Str\xF6mung zieht st\xE4rker als sonst. Es geht um die letzte \xDCberfahrt des Tages. Der F\xE4hrmann sp\xFCrt das Seil in den H\xE4nden arbeiten. Aber das andere Ufer r\xFCckt nicht n\xE4her. Die Glocke am Steg schl\xE4gt von allein. Dann rei\xDFt die Halterung, und die F\xE4hre dreht sich aus der Linie. Pl\xF6tzlich kippt der Nachmittag ins Dunkle. Die Passagiere schweigen in einer Reihe. Der F\xE4hrmann bindet das Seil um den eigenen Arm. Die F\xE4hre erreicht das Ufer schr\xE4g und zu sp\xE4t. Am Ende fehlt eine M\xFCnze, und niemand fehlt. Zur\xFCck bleibt ein Riemen, der am n\xE4chsten Morgen wieder da ist."
  },
  {
    titel: "Kreisschluss",
    text: "Eine Frau kehrt in das Haus ihrer Kindheit zur\xFCck und findet die T\xFCr offen. Ein Flur voller M\xE4ntel, die niemandem geh\xF6ren. Der Geruch von Bohnerwachs und Winter. Sie stellt den Koffer an die Stelle, an der er immer stand. Die Uhr in der K\xFCche geht sieben Minuten vor, wie damals. Ein Fenster, das sich nur von innen \xF6ffnen l\xE4sst. Es geht um das, was bleibt, wenn man geht. Die Nachbarin gr\xFC\xDFt mit dem Namen der Mutter. Aber die Treppe knarrt an einer neuen Stelle. Dann findet sie im Schrank ihren eigenen Kindermantel, frisch geb\xFCrstet. Die Zimmer werden kleiner, je l\xE4nger sie bleibt. Pl\xF6tzlich versteht sie, dass das Haus sie erwartet hat. Sie \xF6ffnet alle Fenster von innen. Am Ende stellt sie den Koffer wieder in den Flur und l\xE4sst die T\xFCr offen. Zur\xFCck bleibt ein Haus, das auf die N\xE4chste wartet."
  },
  {
    titel: "R\xFCckw\xE4rts erz\xE4hlt",
    text: "Am Ende liegt der Brief unge\xF6ffnet im Fluss. Davor steht ein Mann eine Stunde auf der Br\xFCcke. Ein Umschlag mit einem fremden Poststempel. Die H\xE4nde sind ruhiger, als sie sein d\xFCrften. Davor kauft er am Kiosk eine Zeitung, die er nicht liest. Der Kiosk verkauft an diesem Tag nur an ihn. Es geht um eine Nachricht, die alles ordnen w\xFCrde. Davor wartet er drei Tage neben dem Briefkasten. Aber der Briefkasten bleibt drei Tage leer. Dann kommt der Brief am vierten Tag, zu fr\xFCh am Morgen. Ein Absender ohne Namen, eine Schrift wie seine eigene. Pl\xF6tzlich wei\xDF er, was darin steht, ohne zu \xF6ffnen. Davor, ganz am Anfang, schreibt jemand in einer anderen Stadt eine einzige Zeile. Die Zeile lautet: Komm nicht. Zur\xFCck bleibt ein Fluss, der Briefe kennt."
  },
  {
    titel: "Retardation \u2014 die falsche Entwarnung",
    text: "Im Bergwerk riecht es seit Tagen nach kaltem Rauch. Eine Lampe, die zweimal flackert. Der Steiger klopft die W\xE4nde ab und nickt. Die Messung zeigt nichts, die zweite auch nichts. Ein Kanarienvogel singt lauter als sonst. Die Schicht arbeitet weiter, beruhigt und schneller. Es geht um den tiefsten Stollen der Grube. Aber der Geruch kehrt hinter der Entwarnung zur\xFCck. Ein Hut voller Staub vom Firstholz. Die dritte Messung f\xE4llt aus, weil das Ger\xE4t schweigt. Dann knackt das Holz in einer Sprache, die alle kennen. Der Steiger hebt die Hand, und die Lampen gehen aus. Pl\xF6tzlich l\xE4uft die Schicht in vollkommener Ordnung r\xFCckw\xE4rts. Der Berg l\xE4sst sie gehen, einen nach dem anderen. Am Ende z\xE4hlt der Steiger am Tageslicht die Helme. Die Zahl stimmt, und niemand spricht sie aus. Zur\xFCck bleibt ein Vogel, der im Dunkeln weitersingt."
  },
  {
    titel: "Doppelte Wende",
    text: "Die Schachspielerin erkennt die Falle im siebten Zug. Ein Springer am Rand, scheinbar vergessen. Sie lehnt das Opfer ab und steht besser. Der Saal atmet mit den Uhren. Es geht um die Partie ihres Lebens. Der Gegner l\xE4chelt, als h\xE4tte er das erwartet. Dann opfert er die Dame, und das Brett kippt. Pl\xF6tzlich ist ihr Vorteil eine Grube. Aber in der Grube liegt ein zweiter Weg, den keiner sah. Ein Bauer, der seit dem ersten Zug wartet. Sie gibt den Turm und dann den zweiten Turm. Der Saal versteht nichts und wird still. Dann wendet sich die Partie zum zweiten Mal. Der Bauer geht seinen letzten Schritt und wird alles. Am Ende reicht der Gegner die Hand \xFCber ein leeres Brett. Zur\xFCck bleibt ein Springer am Rand, unber\xFChrt bis zuletzt."
  },
  {
    titel: "Stiller Bogen \u2014 nichts passiert, alles \xE4ndert sich",
    text: "Der Leuchtturmw\xE4rter hat seit Wochen kein Schiff gesehen. Eine Kanne Tee f\xFCr einen Menschen. Das Licht dreht sich, ob jemand f\xE4hrt oder nicht. Er streicht das Gel\xE4nder, das niemand anfasst. Eine Liste der St\xFCrme, sauber gef\xFChrt. Das Meer bleibt h\xF6flich und fern. Es geht um das Warten selbst. Aber die Vorr\xE4te rechnen mit einem zweiten Menschen. Der Funk sagt jeden Abend dasselbe Rauschen. Dann bleibt eines Nachts das Rauschen aus. Nichts geschieht, und nichts geschieht sehr laut. Der W\xE4rter deckt den Tisch f\xFCr zwei und lacht nicht. Pl\xF6tzlich versteht er das Licht als Frage. Er beantwortet sie, indem er bleibt. Am Ende f\xE4hrt kein Schiff vorbei, und es gen\xFCgt. Zur\xFCck bleibt eine zweite Tasse, gew\xE4rmt und leer."
  },
  {
    titel: "Eskalation in drei Stufen",
    text: "Am ersten Tag fehlt dem Dorf ein Brunnen. Die Leute holen Wasser vom Bach und lachen dar\xFCber. Ein Eimer mit neuem Seil. Am zweiten Tag fehlt dem Dorf der Bach. Das Bett liegt trocken wie ein Sonntag. Die Leute graben und finden feuchten Sand. Es geht um das Wasser und um mehr als das Wasser. Ein Maulwurf flieht in die falsche Richtung. Aber der Regen zieht am Dorf vorbei, dreimal hintereinander. Am dritten Tag fehlt dem Dorf der Himmel. Ein Grau ohne Wolken, ein Licht ohne Quelle. Dann \xF6ffnet die \xE4lteste Frau den versiegelten Keller. Pl\xF6tzlich steht dort Wasser bis zur dritten Stufe. Das Dorf trinkt und fragt erst danach. Am Ende kehrt der Bach zur\xFCck, als w\xE4re er beleidigt gewesen. Zur\xFCck bleibt ein Keller, den keiner mehr versiegelt."
  },
  {
    titel: "Katastrophe zuerst",
    text: "Das Feuer ist am Morgen schon vorbei. Ein Dachstuhl wie ein schwarzes Geweih. Die Bewohner stehen im Garten und halten Tassen. Niemand fehlt, das ist das Erste. Es geht um das, was nach dem Ende beginnt. Der Kater kehrt ru\xDFig zur\xFCck und wird gefeiert. Aber die Papiere sind Asche, alle Namen darin. Ein Nachbar bringt Brot, ein anderer eine Leiter. Die Versicherung schickt einen Mann mit sauberen Schuhen. Dann findet das Kind im Schutt die eiserne Kassette. Pl\xF6tzlich ist der Schl\xFCssel wichtiger als das Haus. Die Kassette \xF6ffnet sich mit dem zweit\xE4ltesten Schl\xFCssel. Darin liegt kein Geld, sondern eine Liste der Nachbarn von 1911. Die Familie liest die Namen laut in den Garten. Am Ende bauen dieselben Namen das Dach neu. Zur\xFCck bleibt ein Geruch, der nach zwei Wintern geht."
  },
  {
    titel: "Zwei Str\xE4nge, ein Treffpunkt",
    text: "Die Botin nimmt den Weg \xFCber den Pass, weil die Br\xFCcke gesperrt ist. Ein Paket, das nicht klappern darf. Im Tal packt der Uhrmacher seine Werkstatt in vier Kisten. Eine Wand voller stehender Uhren. Die Botin teilt ihr Brot mit einem Hund, der den Weg kennt. Der Uhrmacher verschenkt die Uhren, die niemand abholte. Es geht um eine Lieferung und einen Abschied. Aber der Pass schlie\xDFt hinter der Botin im Schnee. Der Hund geht voraus, als h\xE4tte er den Auftrag. Dann stehen beide zur selben Stunde am selben Tor. Das Paket enth\xE4lt eine einzige Unruh, klein wie ein Same. Pl\xF6tzlich schl\xE4gt die Wand der stehenden Uhren an. Der Uhrmacher packt die Kisten wieder aus. Am Ende bleibt die Werkstatt, und die Botin bleibt den Winter. Zur\xFCck bleibt ein Hund, der zwei Herren dient."
  },
  {
    titel: "Offenes Ende \u2014 die Schwebe",
    text: "Auf dem Bahnsteig steht ein Koffer ohne Besitzer. Die Ansage nennt einen Zug, den der Plan nicht kennt. Eine Frau setzt sich neben den Koffer, als geh\xF6re sie dazu. Der Abend riecht nach Eisen und Regen. Es geht um eine Entscheidung, die noch niemand getroffen hat. Ein Schaffner geht vorbei und gr\xFC\xDFt den Koffer. Aber der angek\xFCndigte Zug f\xE4hrt auf keinem Gleis ein. Die Uhr \xFCber dem Bahnsteig verliert eine Minute. Dann \xF6ffnet die Frau den Koffer einen Fingerbreit. Ein Licht f\xE4llt heraus, das zu keiner Lampe geh\xF6rt. Pl\xF6tzlich stehen mehr Menschen auf dem Bahnsteig, als gekommen sind. Alle sehen auf das Gleis, keiner auf den Koffer. Die Ansage wiederholt sich, freundlicher als zuvor. Am Ende f\xE4hrt etwas ein, das man nicht beschreiben kann. Ob die Frau einsteigt, wei\xDF der Bahnsteig allein."
  }
];

// src/generation/dramaturgie.ts
var DKEY = "dm_dramaturgie_v1";
function setDramaData(d) {
  try {
    if (d) localStorage.setItem(DKEY, JSON.stringify(d));
    else localStorage.removeItem(DKEY);
  } catch {
  }
}
var bogenOverride = null;
function setBogenOverride(d) {
  bogenOverride = d;
}
function loadDramaData() {
  if (bogenOverride) return bogenOverride;
  try {
    const r = localStorage.getItem(DKEY);
    return r ? JSON.parse(r) : null;
  } catch {
    return null;
  }
}
function hasDramaData() {
  const d = loadDramaData();
  return !!(d && (d.einstieg.length || d.mitte.length || d.hoehepunkt.length || d.veraenderungen.length));
}

// test/erzaehler.ts
var dom = new import_jsdom.JSDOM("<!doctype html><html><body></body></html>", { url: "https://x.test/" });
globalThis.localStorage = dom.window.localStorage;
var fails = [];
var geprueft = 0;
var bestanden = 0;
var ist = (name, wert, soll) => {
  geprueft++;
  if (wert === soll) bestanden++;
  else fails.push(`${name}: \u201E${String(wert)}\u201C \u2014 erwartet \u201E${String(soll)}\u201C`);
};
var wahr = (name, b) => ist(name, b, true);
ist("immer zehn Pl\xE4tze", ladeErzaehlerbank().length, ERZAEHLER_PLAETZE);
localStorage.setItem("dm_erzaehlerbank_v1", "kaputt{");
ist("kaputter Speicher \u2192 zehn leere Pl\xE4tze", ladeErzaehlerbank().filter((e) => !e.text).length, ERZAEHLER_PLAETZE);
var bank = ladeErzaehlerbank();
bank[2] = { titel: "Evolution", text: VORLAGE_EVOLUTION };
speichereErzaehlerbank(bank);
ist("gespeichert und gelesen", ladeErzaehlerbank()[2].titel, "Evolution");
wahr("brauchbar ab vierzig W\xF6rtern", platzBrauchbar(bank[2]) && !platzBrauchbar({ titel: "x", text: "zu kurz" }));
var b2 = erzaehlerBogen(2);
wahr("ein voller Platz liefert einen Bogen", !!b2 && b2.einstieg.length >= 1 && b2.schluss.length >= 1);
ist("ein leerer Platz liefert null", erzaehlerBogen(5), null);
setzeQuelle("2");
ist("die Wahl wird gehalten", ladeQuelle(), "2");
wahr("fest gew\xE4hlt \u2192 der Bogen dieses Platzes", JSON.stringify(bogenFuerErzeugung()) === JSON.stringify(b2));
setzeQuelle("preset");
ist("aus Preset \u2192 null (der Preset-Bogen gilt)", bogenFuerErzeugung(), null);
setzeQuelle("wuerfeln");
wahr("w\xFCrfeln \u2192 ein brauchbarer Bogen", !!bogenFuerErzeugung());
setzeQuelle("5");
ist("fest auf leerem Platz \u2192 null, die Maschine erz\xE4hlt wie bisher", bogenFuerErzeugung(), null);
setzeQuelle("unsinn");
ist("Unsinn f\xE4llt auf preset zur\xFCck", ladeQuelle(), "preset");
setDramaData({ einstieg: ["Preset-Einstieg."], mitte: [], hoehepunkt: [], schluss: [], ausloeser: [], veraenderungen: [], konflikte: [], zeitanomalien: [], regeln: [] });
ist("ohne Override: der gespeicherte Bogen", loadDramaData().einstieg[0], "Preset-Einstieg.");
setBogenOverride(b2);
wahr("mit Override: der Erz\xE4hler-Bogen", loadDramaData().einstieg[0] !== "Preset-Einstieg.");
wahr("hasDramaData sieht ihn ebenfalls", hasDramaData());
setBogenOverride(null);
ist("abger\xE4umt: wieder der gespeicherte", loadDramaData().einstieg[0], "Preset-Einstieg.");
setDramaData(null);
var st = (0, import_fs.readFileSync)("src/ui/studio.ts", "utf8");
wahr("das Studio hat den Bogen-Regler neben der Struktur", /lockField\("Struktur", structure\),[\s\S]{0,400}?el\("span", \{\}, "Bogen"\)\), bogenSel\)/.test(st));
wahr("der Bogen ist nicht w\xFCrfelbar", !/ROLL_SELECTS = \[[^\]]*bogenSel/.test(st));
wahr("die Wahl wird beim Wechsel gesichert", /bogenSel\.addEventListener\("change", \(\) => setzeQuelle\(bogenSel\.value\)\)/.test(st));
wahr("vor jeder Erzeugung wird die Weiche gestellt", /setBogenOverride\(bogenFuerErzeugung\(\)\);\s*\n\s*const model = /.test(st));
var ap = (0, import_fs.readFileSync)("src/ui/app.ts", "utf8");
wahr("der Reiter steht neben der Wortbank", /\["Wortbank", mountWordbank\],\s*\n\s*\["Erzählerbank", mountErzaehlerbank\],/.test(ap));
var ev = (0, import_fs.readFileSync)("src/ui/erzaehlerbankView.ts", "utf8");
wahr(
  "jeder Platz hat Titel, Text, Bogen-Vorschau, Einf\xFCgen, Speichern, Leeren",
  /Bogen zeigen/.test(ev) && /Einfügen/.test(ev) && /Platz leeren/.test(ev) && /preset2AusText\(textIn\.value\)\.drama/.test(ev)
);
{
  ist("es sind zehn", ERZAEHLUNGEN_VORLAGEN.length, 10);
  wahr("alle brauchbar (\xFCber der 40-W\xF6rter-Schwelle)", ERZAEHLUNGEN_VORLAGEN.every((e) => platzBrauchbar(e)));
  ist("die Titel sind verschieden", new Set(ERZAEHLUNGEN_VORLAGEN.map((e) => e.titel)).size, 10);
  wahr("jede tr\xE4gt Einstieg, H\xF6hepunkt und Schluss", ERZAEHLUNGEN_VORLAGEN.every((e) => {
    const d = preset2AusText(e.text).drama;
    return d.einstieg.length >= 1 && d.hoehepunkt.length >= 1 && d.schluss.length >= 1;
  }));
  wahr("und die Texte sind verschieden lang gebaut (kein Klon)", new Set(ERZAEHLUNGEN_VORLAGEN.map((e) => e.text.length)).size === 10);
  const q2 = (0, import_fs.readFileSync)("src/ui/erzaehlerbankView.ts", "utf8");
  wahr("der Reiter hat den Vorlagen-Knopf", /"Vorlagen einsetzen \(leere Plätze\)"/.test(q2));
  wahr("er f\xFCllt nur leere Pl\xE4tze", /if \(alle\[i\]!\.text\.trim\(\)\) continue;/.test(q2));
  wahr("belegte Pl\xE4tze melden sich statt zu \xFCberschreiben", /"Kein Platz frei"/.test(q2));
}
console.log(`Pr\xFCfstand Erz\xE4hlerbank \u2014 ${geprueft} Pr\xFCfungen, ${bestanden} bestanden`);
var proc = globalThis;
if (fails.length) {
  console.error(`
\u274C Erz\xE4hlerbank: ${fails.length} Fehler:`);
  fails.forEach((f) => console.error("  - " + f));
  proc.process?.exit(1);
} else {
  console.log(`
\u2705 Erz\xE4hlerbank: alle ${geprueft} Pr\xFCfungen bestanden.`);
}
