"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/text-utils.ts
function keineGrenze(vor, nach) {
  if (ABKUERZUNG.test(vor)) return true;
  if (!ORDNUNGSZAHL.test(vor)) return false;
  return MONATE.test(nach) || /^\d/.test(nach);
}
function splitSentences(txt) {
  const flach = txt.replace(/\s+/g, " ").trim();
  const roh = flach.split(/(?<=[.!?…])\s+/).filter(Boolean);
  const raus = [];
  for (const teil of roh) {
    const vor = raus[raus.length - 1];
    if (vor && keineGrenze(vor, teil)) raus[raus.length - 1] = vor + " " + teil;
    else raus.push(teil);
  }
  return raus;
}
var MONATE, ORDNUNGSZAHL, ABKUERZUNG;
var init_text_utils = __esm({
  "src/text-utils.ts"() {
    "use strict";
    MONATE = /^(?:Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember|Jahrhunderts?|Jh\.|Hälfte|Auflage|Band|Kapitel|Absatz|Teil)\b/u;
    ORDNUNGSZAHL = /\d\.$/;
    ABKUERZUNG = /(?:^|\s)(?:[A-Za-zÄÖÜäöü]|ca|bzw|bspw|evtl|ggf|inkl|Nr|St|Dr|Prof|Abs|Art|Bd|Hrsg|usw|etc)\.$/u;
  }
});

// src/generation/verblex.data.ts
var GRUND, VERB_PRAEFIXE, PAST2PRES, VERB_INFINITIVE;
var init_verblex_data = __esm({
  "src/generation/verblex.data.ts"() {
    "use strict";
    GRUND = `
achten \xE4chzen ahnen \xE4ndern \xE4rgern arbeiten atmen backen baden bangen bauen beben bedeuten beeilen befehlen beginnen begreifen
behalten bei\xDFen bellen bergen bersten beten betteln beugen bewegen biegen bieten bilden binden bitten blasen bleiben blenden blicken
blinken blinzeln blitzen bl\xFChen bluten bohren borgen brauchen brausen brechen bremsen brennen bringen br\xFCllen brummen buchen b\xFCcken
b\xFCgeln b\xFCrsten danken decken dehnen denken deuten dichten dienen d\xF6sen dr\xE4ngen drehen dreschen dringen drohen dr\xF6hnen drucken dr\xFCcken
dulden dunkeln d\xFCrfen duften d\xFCngen d\xFCnken durchqueren ebben ehren eignen eilen einen eitern ekeln enden entbehren entgleiten erben
erl\xF6schen ernten essen f\xE4cheln fahren fallen falten fangen fassen fasten fauchen fechten fegen fehlen feiern feilen feixen fesseln
feuern finden fischen flackern flattern flechten flehen flicken fliegen fliehen flie\xDFen flimmern flirren fl\xF6ten fluchen fluten
fl\xFCstern folgen fordern forschen fragen fressen freuen frieren f\xFCgen f\xFChlen f\xFChren f\xFCllen funkeln f\xFCrchten fu\xDFen g\xE4hnen g\xE4ren gaffen
geben gedeihen gehen gehorchen geh\xF6ren gelingen gelten genesen genie\xDFen geraten geschehen gewinnen gie\xDFen gl\xE4nzen glauben gleichen
gleiten glimmen glitzern gl\xFChen g\xF6nnen graben grasen greifen grinsen grollen gr\xFCbeln gr\xFCnen gr\xFC\xDFen gucken haben hacken haften hageln
haken hallen halten h\xE4mmern handeln h\xE4ngen harren hassen hasten hauchen hauen h\xE4ufen heben heften hegen heilen hei\xDFen heizen helfen
hemmen herrschen hetzen heulen hinken hocken hoffen holen horchen h\xF6ren huldigen h\xFCllen humpeln hungern hupen h\xFCpfen husten h\xFCten
irren jagen jammern jauchzen jubeln k\xE4mmen k\xE4mpfen kauen kaufen kehren keimen kennen kichern kippen kitzeln klagen klappen klappern
kl\xE4ren klatschen kleben kleiden klettern klingeln klingen klirren klopfen knabbern knacken knallen knarren kneifen kneten knicken
knien knirschen knistern kn\xFCpfen kochen kommen k\xF6nnen kosten krachen kr\xE4hen kr\xE4nken kratzen kreisen kreuzen kriechen kriegen
kritzeln kr\xFCmmen k\xFChlen k\xFCmmern k\xFCrzen k\xFCssen lachen laden lagern l\xE4hmen landen langen lassen lasten lauern laufen lauschen lauten
l\xE4uten leben lecken legen lehnen lehren leiden leihen leisten leiten lenken lernen lesen leuchten lieben liefern liegen lindern
loben locken lodern lohnen l\xF6schen l\xF6sen l\xFCgen lutschen machen mahlen mahnen malen mangeln meiden meinen melden melken merken messen
mischen missen m\xF6gen morden m\xFCssen munkeln murmeln nagen n\xE4hen nahen n\xE4hern n\xE4hren naschen necken nehmen neigen nennen nesteln
nicken nieseln nippen nisten n\xF6rgeln nutzen n\xFCtzen \xF6ffnen opfern ordnen packen passen pausieren peitschen pfeifen pflanzen pflegen
pfl\xFCcken picken plagen platzen plaudern pochen poltern pr\xE4gen prallen prangen prasseln predigen preisen pressen probieren pr\xFCfen
pr\xFCgeln pulsieren pumpen putzen qu\xE4len quellen quietschen raffen ragen rasen rasten raten rauben rauchen r\xE4umen rauschen rechnen
reden regen regnen reiben reichen reifen reihen reimen reisen rei\xDFen reiten rennen retten reuen richten riechen ringen rinnen
ritzen rollen rosten r\xFCcken rudern rufen ruhen r\xFChmen r\xFChren r\xFCtteln s\xE4en sagen sammeln s\xE4umen saugen s\xE4useln schaben schaffen
schallen schalten sch\xE4men scharren sch\xE4tzen schauen schaufeln schaukeln scheiden scheinen scheitern schellen schelten schenken
scheren scheuchen scheuen schicken schieben schielen schie\xDFen schildern schimmern schimpfen schinden schlafen schlagen schleichen
schleifen schleppen schleudern schlie\xDFen schlingen schlucken schl\xFCpfen schmecken schmeicheln schmelzen schmerzen schmieden
schmieren schm\xFCcken schmunzeln schnappen schnarchen schneiden schneien schn\xFCren schnuppern schonen sch\xF6pfen schrauben schreiben
schreien schreiten schrumpfen sch\xFCren sch\xFCrfen sch\xFCtteln sch\xFCtten sch\xFCtzen schwanken schw\xE4rmen schwatzen schweben schweifen
schweigen schwellen schwenken schwimmen schwinden schwingen schwitzen schw\xF6ren segeln segnen sehen sehnen seufzen sichern sichten
sickern sieden siegen singen sinken sinnen sitzen sollen sorgen sp\xE4hen spalten spannen sparen spazieren speien speisen spenden
sperren spielen spinnen spotten sprechen sprengen sprie\xDFen springen spritzen spr\xFChen spucken sp\xFClen sp\xFCren stammeln stammen
stampfen stapeln starren stauben staunen stechen stecken stehen stehlen steigen steinigen stellen sterben steuern sticken
stinken st\xF6hnen stolpern stopfen st\xF6ren sto\xDFen strahlen stranden streben strecken streichen streicheln streiten streuen
stricken str\xF6men st\xFCrmen st\xFCrzen stutzen st\xFCtzen suchen summen s\xFCndigen tadeln tagen tanken tanzen tappen tasten tauchen tauen
taugen taumeln tauschen t\xE4uschen teilen tilgen toben t\xF6nen tosen traben trachten tragen trampeln trauen trauern tr\xE4umen treffen
treiben trennen treten triefen trinken trocknen trommeln tropfen tr\xF6sten trotzen tr\xFCben tun t\xFCrmen \xFCben umarmen urteilen
vergessen verlieren verzeihen wachen wachsen wagen w\xE4hlen w\xE4hnen wahren w\xE4hren wandeln wandern wanken w\xE4rmen warnen warten waschen
weben wechseln wecken wehen wehren weichen weiden weigern weihen weilen weinen weisen weiten welken wenden werben werden werfen
werken wetten wickeln widmen wiegen wimmeln wimmern winden winken wirbeln wirken wischen wissen wittern wohnen w\xF6lben wollen
wuchern w\xFChlen wundern w\xFCnschen w\xFCrdigen w\xFCrgen w\xFCrzen zagen zahlen z\xE4hlen z\xE4hmen zaubern zaudern zausen zehren zeichnen zeigen
zerren zeugen ziehen zielen ziemen zieren zischen zittern z\xF6gern zucken zupfen zw\xE4ngen zweifeln zwingen zwinkern zwitschern
adeln \xE4hneln akzeptieren analysieren antworten applaudieren beantworten begegnen begleiten behaupten beobachten berichten
ber\xFChren beschreiben besitzen bestimmen besuchen betrachten betreten beweisen bezahlen br\xFCten datieren definieren diskutieren
d\xE4mmern d\xE4mpfen dampfen detonieren donnern duschen entdecken entscheiden entschuldigen entwickeln erinnern erkennen erkl\xE4ren
erlauben erleben erreichen erschrecken erwarten erz\xE4hlen existieren fabrizieren fasziniert funktionieren garantieren geb\xE4ren
gefallen gen\xFCgen geschehen gestalten gew\xF6hnen glitschen h\xE4mmern handeln heiraten hindern ignorieren informieren interessieren
kapitulieren kentern klettern kombinieren kontrollieren korrigieren kosten kreisen k\xFCrzen leiden lodern markieren marschieren
meistern montieren murren musizieren notieren n\xF6tigen operieren organisieren passieren pilgern planen pl\xFCndern posieren
probieren produzieren protestieren protokollieren rasieren reagieren regieren reparieren respektieren riskieren rotieren
schmei\xDFen schmettern schnattern sortieren spekulieren studieren telefonieren transportieren trainieren trauen tr\xF6deln
\xFCberlegen verabschieden ver\xE4ndern verbergen verbinden verbrennen verdienen verfolgen verhalten verhandeln verkaufen verlangen
verlassen vermeiden vermuten verraten versagen verschieben verschwinden versichern versprechen verstecken verstehen versuchen
verteidigen vertrauen verwalten verwandeln verweigern verwenden verzichten vollenden wackeln wandeln weinen wirbeln zerbrechen
zerst\xF6ren z\xF6gern zurechtkommen zweifeln
stimmen passen setzen dauern l\xF6sen l\xE4cheln k\xFCndigen retten ticken z\xFCnden siegeln entfernen verl\xE4ngern verstummen beschriften
gabeln erledigen bewilligen best\xE4tigen sichern lohnen stauen stocken t\xF6nen tr\xFCben w\xE4hnen zerren fehlen kosten sparen sperren
st\xFCrzen stapeln stehlen schweigen taumeln t\xF6ten trocknen tr\xF6pfeln \xFCbergehen verschlie\xDFen vertreten verwahren verwirren vollziehen
wachsen wandern weichen wirken wurzeln zerfallen zerflie\xDFen zergehen zerrei\xDFen zerschlagen zersplittern zischen
regeln spiegeln speichern beschleunigen senken f\xE4rben formen altern riegeln fiebern schlitzen rutschen beanstanden erg\xE4nzen
bl\xE4ttern sanden schulden bessern bremsen dunkeln d\xFCstern erkennen ernennen f\xE4rben festigen filtern fl\xFCchten fr\xF6nen g\xE4hnen
h\xE4uten heilen hetzen k\xE4mmen klammern klemmen kneten kramen kr\xE4nkeln kr\xE4useln lasten leimen l\xFCften mildern mustern nachten
n\xE4ssen nieten \xF6len pinseln pl\xE4tschern polstern prallen prunken quirlen r\xE4dern reifen richten r\xF6cheln r\xFCtteln s\xE4ubern salzen
s\xE4umen sch\xE4tzen schaudern schl\xE4ngeln schleimen schlummern schmoren schn\xFCffeln schrubben schw\xE4chen schwelen sengen sondern
spalten spiegeln spitzen sprudeln stauben steuern stochern strampeln streifen striegeln stumpfen sudeln tauen tigern tippen
trampeln t\xFCnchen wabern watscheln wetzen wiehern winseln wispern wittern wuchten zerknittern zetern zieren zittern zotteln zuckeln
abh\xE4ngen ankommen anfangen aufstehen ausgehen bedienen befreien behandeln bemerken benennen beschlie\xDFen bestehen betonen bewahren
bezeichnen bilden bluten br\xFCten b\xFC\xDFen d\xE4mmern deuten drehen ehren einigen empfangen empfehlen entfalten enthalten entlassen entstehen
erfahren erfinden ergeben erhalten erheben erholen erl\xF6sen ermahnen ern\xE4hren er\xF6ffnen erregen ersch\xF6pfen ersticken erstarren erw\xE4hnen
erweitern erzeugen fesseln fl\xFCchten fr\xF6steln funken gebieten gedenken gelangen gemahnen geraten gestehen gew\xE4hren graben grenzen
gr\xFCbeln hadern harken hausen heben herrschen hindern huschen j\xE4ten jucken keuchen klaffen kleckern klimpern knallen kraulen kreischen
kringeln kritzeln kr\xF6nen kuscheln l\xE4rmen leuchten lichten lispeln lugen lungern m\xE4\xDFigen mei\xDFeln mieten mindern m\xFChen murksen nachahmen
nagen n\xE4seln n\xF6rgeln nuscheln pachten pflastern pieksen plappern prahlen prangen prellen prosten quaken qualmen r\xE4uspern rauen r\xE4umen
reizen rieseln rodeln r\xF6hren rumpeln s\xE4beln s\xE4ckeln s\xE4gen sausen sch\xE4umen sch\xE4len schaufeln schnalzen schnaufen schnellen schnippen
schwappen schwirren seihen sichten siezen sinnieren spannen spenden spicken spie\xDFen sprenkeln spuken st\xE4nkern stelzen stemmen sticheln
st\xF6bern stopfen strapazieren strotzen st\xFClpen stutzen t\xE4ndeln taxieren tollen torkeln tr\xE4llern trudeln tuscheln umgarnen verharren
wabbeln walzen wedeln weilen wetteifern wimmeln wringen wuseln zappeln zaubern zechen zergehen zerkn\xFCllen zerlegen zerm\xFCrben zerpfl\xFCcken
zerschellen zertr\xFCmmern zeugen zirpen zocken zurren
`;
    VERB_PRAEFIXE = [
      "zusammen",
      "zur\xFCck",
      "wieder",
      "gegen",
      "hinter",
      "durch",
      "unter",
      "\xFCber",
      "voran",
      "vorbei",
      "heraus",
      "herein",
      "hinaus",
      "hinein",
      "herum",
      "hinauf",
      "hinab",
      "herab",
      "empor",
      "fort",
      "los",
      "weg",
      "fest",
      "auseinander",
      "entgegen",
      "entlang",
      "nieder",
      "umher",
      "davon",
      "dazu",
      "hoch",
      "her",
      "hin",
      "ver",
      "ent",
      "emp",
      "miss",
      "zer",
      "be",
      "er",
      "ge",
      "an",
      "ab",
      "auf",
      "aus",
      "ein",
      "mit",
      "nach",
      "vor",
      "zu",
      "um",
      "bei",
      "da",
      "wider",
      "still",
      "frei",
      "leer",
      "tot",
      "voll",
      "wahr",
      "gut",
      "kaputt"
    ];
    PAST2PRES = {
      // Ergänzt 4.338.2 (Blatt „Vier Kinder": „Das Herz schlug mir bis zum Hals" blieb stehen):
      schlug: "schl\xE4gt",
      schlugen: "schlagen",
      roch: "riecht",
      rochen: "riechen",
      traf: "trifft",
      trafen: "treffen",
      schob: "schiebt",
      schoben: "schieben",
      tat: "tut",
      taten: "tun",
      wusch: "w\xE4scht",
      stritt: "streitet",
      glitt: "gleitet",
      stie\u00DF: "st\xF6\xDFt",
      stie\u00DFen: "sto\xDFen",
      goss: "gie\xDFt",
      band: "bindet",
      banden: "binden",
      zwang: "zwingt",
      fing: "f\xE4ngt",
      fingen: "fangen",
      sandte: "sendet",
      mochte: "mag",
      mochten: "m\xF6gen",
      stahl: "stiehlt",
      galt: "gilt",
      galten: "gelten",
      gelang: "gelingt",
      verband: "verbindet",
      erhielt: "erh\xE4lt",
      erhielten: "erhalten",
      behielt: "beh\xE4lt",
      enthielt: "enth\xE4lt",
      verlie\u00DF: "verl\xE4sst",
      verlie\u00DFen: "verlassen",
      genoss: "genie\xDFt",
      schlich: "schleicht",
      strich: "streicht",
      blies: "bl\xE4st",
      lud: "l\xE4dt",
      luden: "laden",
      schuf: "schafft",
      schufen: "schaffen",
      log: "l\xFCgt",
      betrog: "betr\xFCgt",
      flocht: "flicht",
      kroch: "kriecht",
      krochen: "kriechen",
      schmolz: "schmilzt",
      quoll: "quillt",
      quollen: "quellen",
      verging: "vergeht",
      vergingen: "vergehen",
      entging: "entgeht",
      erging: "ergeht",
      erschrak: "erschrickt",
      war: "ist",
      waren: "sind",
      warst: "bist",
      hatte: "hat",
      hatten: "haben",
      hattest: "hast",
      wurde: "wird",
      wurden: "werden",
      ging: "geht",
      gingen: "gehen",
      kam: "kommt",
      kamen: "kommen",
      sah: "sieht",
      sahen: "sehen",
      gab: "gibt",
      gaben: "geben",
      stand: "steht",
      standen: "stehen",
      blieb: "bleibt",
      blieben: "bleiben",
      hielt: "h\xE4lt",
      hielten: "halten",
      lie\u00DF: "l\xE4sst",
      lie\u00DFen: "lassen",
      fand: "findet",
      fanden: "finden",
      nahm: "nimmt",
      nahmen: "nehmen",
      sprach: "spricht",
      sprachen: "sprechen",
      schrieb: "schreibt",
      schrieben: "schreiben",
      trug: "tr\xE4gt",
      trugen: "tragen",
      fuhr: "f\xE4hrt",
      fuhren: "fahren",
      lief: "l\xE4uft",
      liefen: "laufen",
      sa\u00DF: "sitzt",
      sa\u00DFen: "sitzen",
      lag: "liegt",
      lagen: "liegen",
      hie\u00DF: "hei\xDFt",
      hie\u00DFen: "hei\xDFen",
      zog: "zieht",
      zogen: "ziehen",
      schlief: "schl\xE4ft",
      schliefen: "schlafen",
      rief: "ruft",
      riefen: "rufen",
      fiel: "f\xE4llt",
      fielen: "fallen",
      sang: "singt",
      sangen: "singen",
      trank: "trinkt",
      tranken: "trinken",
      schwieg: "schweigt",
      schwiegen: "schweigen",
      floss: "flie\xDFt",
      flossen: "flie\xDFen",
      stieg: "steigt",
      stiegen: "steigen",
      sank: "sinkt",
      sanken: "sinken",
      bot: "bietet",
      boten: "bieten",
      schloss: "schlie\xDFt",
      schlossen: "schlie\xDFen",
      verlor: "verliert",
      verloren: "verlieren",
      begann: "beginnt",
      begannen: "beginnen",
      geschah: "geschieht",
      geschahen: "geschehen",
      konnte: "kann",
      konnten: "k\xF6nnen",
      musste: "muss",
      mussten: "m\xFCssen",
      wollte: "will",
      wollten: "wollen",
      sollte: "soll",
      sollten: "sollen",
      durfte: "darf",
      durften: "d\xFCrfen",
      wusste: "wei\xDF",
      wussten: "wissen",
      dachte: "denkt",
      dachten: "denken",
      brachte: "bringt",
      brachten: "bringen",
      kannte: "kennt",
      kannten: "kennen",
      erkannte: "erkennt",
      erkannten: "erkennen",
      brannte: "brennt",
      brannten: "brennen",
      nannte: "nennt",
      nannten: "nennen",
      rannte: "rennt",
      rannten: "rennen",
      wandte: "wendet",
      wandten: "wenden",
      sprang: "springt",
      sprangen: "springen",
      schrie: "schreit",
      schrien: "schreien",
      flog: "fliegt",
      flogen: "fliegen",
      floh: "flieht",
      flohen: "fliehen",
      schoss: "schie\xDFt",
      schossen: "schie\xDFen",
      riss: "rei\xDFt",
      rissen: "rei\xDFen",
      biss: "bei\xDFt",
      bissen: "bei\xDFen",
      griff: "greift",
      griffen: "greifen",
      pfiff: "pfeift",
      pfiffen: "pfeifen",
      schnitt: "schneidet",
      schnitten: "schneiden",
      litt: "leidet",
      litten: "leiden",
      trat: "tritt",
      traten: "treten",
      verga\u00DF: "vergisst",
      verga\u00DFen: "vergessen",
      wuchs: "w\xE4chst",
      wuchsen: "wachsen",
      wich: "weicht",
      wichen: "weichen",
      schien: "scheint",
      schienen: "scheinen",
      zerbrach: "zerbricht",
      zerbrachen: "zerbrechen",
      verschwand: "verschwindet",
      verschwanden: "verschwinden",
      erschien: "erscheint",
      erschienen: "erscheinen",
      starb: "stirbt",
      starben: "sterben",
      brach: "bricht",
      brachen: "brechen",
      sprach2: "spricht",
      schwoll: "schwillt",
      schwollen: "schwellen",
      bog: "biegt",
      bogen: "biegen",
      hob: "hebt",
      hoben: "heben",
      wob: "webt",
      woben: "weben",
      klang: "klingt",
      klangen: "klingen",
      sann: "sinnt",
      sannen: "sinnen",
      rann: "rinnt",
      rannen: "rinnen",
      schwamm: "schwimmt",
      schwammen: "schwimmen",
      verschwieg: "verschweigt",
      zerfiel: "zerf\xE4llt",
      zerfielen: "zerfallen",
      entstand: "entsteht",
      entstanden: "entstehen",
      verstand: "versteht",
      verstanden: "verstehen",
      bestand: "besteht",
      bestanden: "bestehen",
      geriet: "ger\xE4t",
      gerieten: "geraten",
      trieb: "treibt",
      trieben: "treiben",
      schrak: "schrickt",
      wies: "weist",
      wiesen: "weisen",
      hing: "h\xE4ngt",
      hingen: "h\xE4ngen",
      schwand: "schwindet",
      schwanden: "schwinden",
      gewann: "gewinnt",
      gewannen: "gewinnen",
      zerriss: "zerrei\xDFt",
      zerrissen2: "zerrei\xDFen",
      empfand: "empfindet",
      empfanden: "empfinden",
      befahl: "befiehlt",
      befahlen: "befehlen",
      half: "hilft",
      halfen: "helfen",
      warf: "wirft",
      warfen: "werfen",
      starrte2: "starrt",
      las: "liest",
      lasen: "lesen",
      a\u00DF: "isst",
      a\u00DFen: "essen",
      bat: "bittet",
      baten: "bitten"
    };
    VERB_INFINITIVE = new Set(GRUND.split(/\s+/).map((w) => w.trim()).filter((w) => w.length > 2));
  }
});

// src/generation/verben.ts
function starkMitPraefix(form) {
  if (STARK[form]) return ["", STARK[form]];
  for (const p of PRAEFIXE) {
    if (form.startsWith(p) && form.length > p.length + 2) {
      const rest = form.slice(p.length);
      if (STARK[rest]) return [p, STARK[rest]];
    }
  }
  return null;
}
function kenntInfinitiv(wort) {
  const w = wort.toLowerCase();
  if (VERB_INFINITIVE.has(w)) return true;
  for (const p of VERB_PRAEFIXE) {
    if (w.startsWith(p) && w.length > p.length + 3 && VERB_INFINITIVE.has(w.slice(p.length))) return true;
  }
  return false;
}
function infinitivZuStamm(stamm) {
  const s = stamm.toLowerCase();
  if (!s) return null;
  const kandidaten = [s + "en", s + "n", s + "eln", s + "ern"];
  if (/e[lr]$/.test(s)) kandidaten.unshift(s + "n");
  const st = starkMitPraefix(s + "t");
  if (st) return st[0] + st[1][2];
  for (const k of kandidaten) if (kenntInfinitiv(k)) return k;
  return null;
}
function istLexikonVerb(wort) {
  const w = wort.toLowerCase().replace(/[^a-zäöüß]/g, "");
  if (!w || w.length < 3) return false;
  if (starkMitPraefix(w)) return true;
  if (kenntInfinitiv(w)) return true;
  if (PAST2PRES[w]) return true;
  if (/^(bin|bist|sind|seid|habe|hast|habt|werde|wirst|werdet|wäre|wären|hätte|hätten|würde|würden|sei|seien)$/.test(w)) return true;
  for (const suffix of ["etest", "test", "eten", "ten", "ete", "te", "est", "st", "et", "en", "t", "e", "tet"]) {
    if (!w.endsWith(suffix) || w.length - suffix.length < 2) continue;
    const st = w.slice(0, -suffix.length);
    if (/ier$/.test(st)) return true;
    if (infinitivZuStamm(st)) return true;
  }
  const pz = w.match(/^(?:[a-zäöü]{2,8})?ge(.+?)(?:t|en)$/);
  if (pz && infinitivZuStamm(pz[1])) return true;
  return false;
}
function istVerbform(wort) {
  const w = wort.toLowerCase();
  if (starkMitPraefix(w)) return true;
  if (KEIN_VERB.has(w)) return false;
  if (/^[a-zäöüß]{3,}(t|st|e|en)$/.test(w) && istLexikonVerb(w)) return true;
  if (!/^[a-zäöüß]{3,}t$/.test(w)) return false;
  if (/^ge[a-zäöüß]{2,}t$/.test(w)) return GE_VERBEN.test(w);
  return true;
}
var STARK, PRAEFIXE, KEIN_VERB, GE_VERBEN;
var init_verben = __esm({
  "src/generation/verben.ts"() {
    "use strict";
    init_verblex_data();
    STARK = {
      // sein · haben · werden · wissen · tun · Modalverben
      ist: ["bin", "bist", "sind", "seid"],
      hat: ["habe", "hast", "haben", "habt"],
      wird: ["werde", "wirst", "werden", "werdet"],
      wei\u00DF: ["wei\xDF", "wei\xDFt", "wissen", "wisst"],
      tut: ["tue", "tust", "tun", "tut"],
      kann: ["kann", "kannst", "k\xF6nnen", "k\xF6nnt"],
      muss: ["muss", "musst", "m\xFCssen", "m\xFCsst"],
      will: ["will", "willst", "wollen", "wollt"],
      soll: ["soll", "sollst", "sollen", "sollt"],
      darf: ["darf", "darfst", "d\xFCrfen", "d\xFCrft"],
      mag: ["mag", "magst", "m\xF6gen", "m\xF6gt"],
      // a → ä
      h\u00E4lt: ["halte", "h\xE4ltst", "halten", "haltet"],
      f\u00E4llt: ["falle", "f\xE4llst", "fallen", "fallt"],
      tr\u00E4gt: ["trage", "tr\xE4gst", "tragen", "tragt"],
      l\u00E4uft: ["laufe", "l\xE4ufst", "laufen", "lauft"],
      schl\u00E4ft: ["schlafe", "schl\xE4fst", "schlafen", "schlaft"],
      f\u00E4ngt: ["fange", "f\xE4ngst", "fangen", "fangt"],
      l\u00E4sst: ["lasse", "l\xE4sst", "lassen", "lasst"],
      w\u00E4chst: ["wachse", "w\xE4chst", "wachsen", "wachst"],
      gr\u00E4bt: ["grabe", "gr\xE4bst", "graben", "grabt"],
      schl\u00E4gt: ["schlage", "schl\xE4gst", "schlagen", "schlagt"],
      r\u00E4t: ["rate", "r\xE4tst", "raten", "ratet"],
      bl\u00E4st: ["blase", "bl\xE4st", "blasen", "blast"],
      st\u00F6\u00DFt: ["sto\xDFe", "st\xF6\xDFt", "sto\xDFen", "sto\xDFt"],
      f\u00E4hrt: ["fahre", "f\xE4hrst", "fahren", "fahrt"],
      w\u00E4scht: ["wasche", "w\xE4schst", "waschen", "wascht"],
      l\u00E4dt: ["lade", "l\xE4dst", "laden", "ladet"],
      s\u00E4uft: ["saufe", "s\xE4ufst", "saufen", "sauft"],
      // e → i / ie
      gibt: ["gebe", "gibst", "geben", "gebt"],
      nimmt: ["nehme", "nimmst", "nehmen", "nehmt"],
      spricht: ["spreche", "sprichst", "sprechen", "sprecht"],
      bricht: ["breche", "brichst", "brechen", "brecht"],
      sieht: ["sehe", "siehst", "sehen", "seht"],
      liest: ["lese", "liest", "lesen", "lest"],
      isst: ["esse", "isst", "essen", "esst"],
      frisst: ["fresse", "frisst", "fressen", "fresst"],
      misst: ["messe", "misst", "messen", "messt"],
      vergisst: ["vergesse", "vergisst", "vergessen", "vergesst"],
      hilft: ["helfe", "hilfst", "helfen", "helft"],
      stirbt: ["sterbe", "stirbst", "sterben", "sterbt"],
      wirft: ["werfe", "wirfst", "werfen", "werft"],
      trifft: ["treffe", "triffst", "treffen", "trefft"],
      gilt: ["gelte", "giltst", "gelten", "geltet"],
      tritt: ["trete", "trittst", "treten", "tretet"],
      birgt: ["berge", "birgst", "bergen", "bergt"],
      quillt: ["quelle", "quillst", "quellen", "quellt"],
      schilt: ["schelte", "schiltst", "schelten", "scheltet"],
      ficht: ["fechte", "fichtst", "fechten", "fechtet"],
      flicht: ["flechte", "flichtst", "flechten", "flechtet"],
      verdirbt: ["verderbe", "verdirbst", "verderben", "verderbt"],
      wirbt: ["werbe", "wirbst", "werben", "werbt"],
      erschrickt: ["erschrecke", "erschrickst", "erschrecken", "erschreckt"],
      sticht: ["steche", "stichst", "stechen", "stecht"],
      schmilzt: ["schmelze", "schmilzt", "schmelzen", "schmelzt"],
      befiehlt: ["befehle", "befiehlst", "befehlen", "befehlt"],
      stiehlt: ["stehle", "stiehlst", "stehlen", "stehlt"],
      empfiehlt: ["empfehle", "empfiehlst", "empfehlen", "empfehlt"],
      geschieht: ["geschehe", "geschiehst", "geschehen", "gescheht"],
      gebiert: ["geb\xE4re", "gebierst", "geb\xE4ren", "geb\xE4rt"],
      schwillt: ["schwelle", "schwillst", "schwellen", "schwellt"]
    };
    PRAEFIXE = [
      "zusammen",
      "zur\xFCck",
      "wieder",
      "gegen",
      "hinter",
      "durch",
      "unter",
      "\xFCber",
      "voran",
      "vorbei",
      "heraus",
      "herein",
      "hinaus",
      "hinein",
      "herum",
      "hinauf",
      "hinab",
      "herab",
      "empor",
      "fort",
      "los",
      "weg",
      "fest",
      "her",
      "hin",
      "ver",
      "ent",
      "emp",
      "miss",
      "zer",
      "be",
      "er",
      "ge",
      "an",
      "ab",
      "auf",
      "aus",
      "ein",
      "mit",
      "nach",
      "vor",
      "zu",
      "um",
      "bei",
      "da",
      "wider"
    ];
    KEIN_VERB = /* @__PURE__ */ new Set([
      "alt",
      "kalt",
      "laut",
      "bunt",
      "hart",
      "zart",
      "satt",
      "glatt",
      "weit",
      "breit",
      "rot",
      "tot",
      "gut",
      "sp\xE4t",
      "echt",
      "leicht",
      "dicht",
      "recht",
      "schlecht",
      "nackt",
      "fest",
      "letzt",
      "jetzt",
      "sanft",
      "ernst",
      "wert",
      "seit",
      "statt",
      "samt",
      "nicht",
      "mit",
      "seid",
      "zuletzt",
      "zuerst",
      "oft",
      "fast",
      "erst",
      "sonst",
      "meist",
      "direkt",
      "dort",
      "fort",
      "sofort",
      "selbst",
      "vielleicht",
      "\xFCberhaupt",
      "bereit",
      "gerecht",
      "perfekt",
      "exakt",
      "absolut",
      "gesamt",
      "komplett",
      "verr\xFCckt",
      "bekannt",
      "geschickt",
      "welt",
      "zeit",
      "nacht",
      "stadt",
      "acht",
      "licht",
      "wort",
      "ort",
      "blut",
      "brot",
      "mut",
      "hut",
      "gebet",
      "geist",
      "gott",
      "kraft",
      "luft",
      "haut",
      "haft",
      "gift",
      "schrift",
      "frucht",
      "flucht",
      "sicht",
      "pflicht",
      "angst",
      "kunst",
      "dienst",
      "frost",
      "post",
      "ost",
      "west",
      "rest",
      "test",
      "text",
      "w\xFCst",
      "getrennt",
      "gemischt",
      "gebrannt",
      "verschwunden",
      "gewohnt",
      "gelaunt",
      "ber\xFChmt",
      "geliebt",
      "gelebt",
      "gedacht",
      "gemacht",
      "gebracht",
      "gesagt",
      "gesucht",
      "gehabt",
      "gewusst",
      "gekannt",
      "genannt",
      "benannt",
      "gewollt",
      "verboten",
      "ge\xF6ffnet",
      "ungeahnt",
      "gestern",
      "heut",
      "abrupt",
      "ad\xE4quat",
      "privat",
      "intakt",
      "korrekt",
      "konkret",
      "moderat",
      "elegant",
      "brillant",
      "tolerant",
      "relevant",
      "markant",
      "rasant",
      "galant",
      "latent",
      "dezent",
      "prominent",
      "kompetent",
      "konsequent",
      "permanent",
      "evident",
      "eloquent",
      "intelligent",
      "gespannt",
      "entspannt",
      "gewandt",
      "verwandt",
      "bewusst",
      "unbewusst",
      "robust",
      "abstrakt",
      "kompakt",
      "exakt",
      "defekt",
      "perfekt",
      "insgesamt",
      "total"
    ]);
    GE_VERBEN = /^ge(ht|nügt|hört|horcht|lingt|winnt|langt|schieht|steht|rät|nießt|wöhnt|fährdet|währt|stattet|staltet|denkt|bietet|braucht|hörcht|nest|reicht|dulde?t|fällt|deiht|lobt|leitet|langt|winnt|behrt|bärt|fried[e]?t|fällt|lüstet|mahnt|rinnt|hört)$/;
  }
});

// src/generation/nouns.data.ts
var NOUN_GENDER;
var init_nouns_data = __esm({
  "src/generation/nouns.data.ts"() {
    "use strict";
    NOUN_GENDER = {
      "abdruck": "m",
      "abend": "m",
      "abgrund": "m",
      "absatz": "m",
      "abschalten": "n",
      "abstand": "m",
      "acker": "m",
      "ader": "f",
      "adressbuch": "n",
      "adresse": "f",
      "ahnung": "f",
      "airpod": "m",
      "akku": "m",
      "akte": "f",
      "aktendeckel": "m",
      "aktennotiz": "f",
      "allee": "f",
      "alptraum": "m",
      "altar": "m",
      "alte": "f",
      "alter": "n",
      "amt": "n",
      "amulett": "n",
      "angebot": "n",
      "angst": "f",
      "anker": "m",
      "antenne": "f",
      "antrag": "m",
      "antwort": "f",
      "apfel": "m",
      "applaus": "m",
      "archiv": "n",
      "arm": "m",
      "armband": "n",
      "armbrust": "f",
      "art": "f",
      "arzt": "m",
      "asche": "f",
      "ast": "m",
      "atelier": "n",
      "atem": "m",
      "atmosph\xE4re": "f",
      "aufkleber": "m",
      "aufnahme": "f",
      "auftrag": "m",
      "auge": "n",
      "augenblick": "m",
      "augenlid": "n",
      "ausdehnung": "f",
      "ausgang": "m",
      "ausnahme": "f",
      "ausrede": "f",
      "ausweis": "m",
      "axiom": "n",
      "baby": "n",
      "bach": "m",
      "backup": "n",
      "badeanstalt": "f",
      "bahn": "f",
      "bahnkarte": "f",
      "balkon": "m",
      "ball": "m",
      "ballade": "f",
      "band": "n",
      "bank": "f",
      "banner": "n",
      "basecap": "n",
      "bau": "m",
      "bauch": "m",
      "bauer": "m",
      "baum": "m",
      "becher": "m",
      "befehl": "m",
      "begriff": "m",
      "beil": "n",
      "bein": "n",
      "benachrichtigung": "f",
      "berg": "m",
      "bergfried": "m",
      "bericht": "m",
      "bescheid": "m",
      "beschluss": "m",
      "besen": "m",
      "besitz": "m",
      "bestand": "m",
      "besuch": "m",
      "betonprobe": "f",
      "bett": "n",
      "beutel": "m",
      "beweis": "m",
      "bibel": "f",
      "bibliothek": "f",
      "biene": "f",
      "bild": "n",
      "bildschirm": "m",
      "binde": "f",
      "birne": "f",
      "blatt": "n",
      "blechb\xFCchse": "f",
      "blechdose": "f",
      "blechkanne": "f",
      "blechtrompete": "f",
      "blei": "n",
      "bleistift": "m",
      "blende": "f",
      "blick": "m",
      "blitz": "m",
      "blume": "f",
      "blumenstrau\xDF": "m",
      "bluse": "f",
      "bl\xFCte": "f",
      "boden": "m",
      "bohne": "f",
      "bohrkern": "m",
      "bohrprobe": "f",
      "boje": "f",
      "bonbon": "n",
      "boot": "n",
      "bote": "m",
      "botschaft": "f",
      "braten": "m",
      "braue": "f",
      "brett": "n",
      "brief": "m",
      "briefumschlag": "m",
      "brille": "f",
      "brot": "n",
      "brotdose": "f",
      "brotlaib": "m",
      "bruch": "m",
      "bruder": "m",
      "brunnen": "m",
      "brust": "f",
      "br\xFCcke": "f",
      "br\xFChe": "f",
      "buch": "n",
      "buchstabe": "m",
      "bucht": "f",
      "bug": "m",
      "burg": "f",
      "bus": "m",
      "busch": "m",
      "butter": "f",
      "b\xE4r": "m",
      "b\xFChne": "f",
      "b\xFCndel": "n",
      "b\xFCrde": "f",
      "cache": "m",
      "cadtablet": "n",
      "caf": "n",
      "caf\xE9": "n",
      "chat": "m",
      "clown": "m",
      "computer": "m",
      "container": "m",
      "couch": "f",
      "dach": "n",
      "dachboden": "m",
      "dame": "f",
      "damm": "m",
      "dashboard": "n",
      "datei": "f",
      "dattel": "f",
      "datum": "n",
      "daumen": "m",
      "deck": "n",
      "decke": "f",
      "deckel": "m",
      "denkmalschutz": "m",
      "deo": "n",
      "detail": "n",
      "detektor": "m",
      "detektorkopf": "m",
      "dewar": "m",
      "diagramm": "n",
      "dichter": "m",
      "dieb": "m",
      "dienst": "m",
      "direktor": "m",
      "dnaspirale": "f",
      "dokument": "n",
      "dolch": "m",
      "donner": "m",
      "dorf": "n",
      "dorn": "m",
      "dose": "f",
      "draht": "m",
      "droschke": "f",
      "druck": "m",
      "duell": "n",
      "duft": "m",
      "durchsage": "f",
      "durchschlag": "m",
      "d\xE4mmerung": "f",
      "ebbe": "f",
      "ebene": "f",
      "echo": "n",
      "ecke": "f",
      "ehre": "f",
      "ei": "n",
      "eid": "m",
      "einspruch": "m",
      "eis": "n",
      "eisen": "n",
      "elch": "m",
      "elend": "n",
      "ellbogen": "m",
      "emoji": "n",
      "engel": "m",
      "enkel": "m",
      "ente": "f",
      "entwurf": "m",
      "ephemeride": "f",
      "erbe": "n",
      "erbse": "f",
      "erdbeben": "n",
      "erde": "f",
      "erinnerung": "f",
      "etikett": "n",
      "eule": "f",
      "ewigkeit": "f",
      "fabel": "f",
      "fabrik": "f",
      "fackel": "f",
      "faden": "m",
      "fahne": "f",
      "fahrschein": "m",
      "fahrt": "f",
      "falle": "f",
      "falte": "f",
      "farbe": "f",
      "farbenscheibe": "f",
      "fass": "n",
      "faust": "f",
      "feder": "f",
      "federkiel": "m",
      "fee": "f",
      "fehlercode": "m",
      "feile": "f",
      "feind": "m",
      "feld": "n",
      "feldbesteck": "n",
      "felder": "n",
      "fell": "n",
      "fellhandschuh": "m",
      "fels": "m",
      "felsen": "m",
      "fenster": "n",
      "fensterplatz": "m",
      "ferkel": "n",
      "ferne": "f",
      "fernglas": "n",
      "fernrohr": "n",
      "ferse": "f",
      "fessel": "f",
      "festung": "f",
      "feuer": "n",
      "feuerzeug": "n",
      "fibel": "f",
      "fieber": "n",
      "filter": "m",
      "finger": "m",
      "fingerhut": "m",
      "fisch": "m",
      "fischer": "m",
      "flakon": "m",
      "flasche": "f",
      "flaute": "f",
      "fleisch": "n",
      "fliege": "f",
      "flo\xDF": "n",
      "fluch": "m",
      "flucht": "f",
      "flur": "m",
      "fluss": "m",
      "flut": "f",
      "fl\xE4che": "f",
      "fl\xF6te": "f",
      "fl\xFCstern": "n",
      "formel": "f",
      "formular": "n",
      "fossil": "n",
      "fossilie": "f",
      "foto": "n",
      "fotografie": "f",
      "frachtbrief": "m",
      "frage": "f",
      "frau": "f",
      "freude": "f",
      "freund": "m",
      "frist": "f",
      "frost": "m",
      "frucht": "f",
      "fr\xFChling": "m",
      "fuchs": "m",
      "fuge": "f",
      "fund": "m",
      "fundament": "n",
      "funke": "m",
      "funkger\xE4t": "n",
      "furcht": "f",
      "furt": "f",
      "fu\xDF": "m",
      "f\xE4hrmann": "m",
      "f\xE4hrplan": "m",
      "f\xE4sser": "n",
      "f\xFCrst": "m",
      "gabe": "f",
      "gabel": "f",
      "gabelung": "f",
      "galaxie": "f",
      "gang": "m",
      "gans": "f",
      "garn": "n",
      "garten": "m",
      "gasse": "f",
      "gast": "m",
      "gebet": "n",
      "gebetbuch": "n",
      "gebete": "n",
      "gebetsschale": "f",
      "gebirge": "n",
      "geb\xE4lk": "n",
      "geb\xE4ude": "n",
      "gedanke": "m",
      "gedanken": "m",
      "gedicht": "n",
      "gedichte": "n",
      "geduld": "f",
      "gefahr": "f",
      "gef\xFChl": "n",
      "gef\xFChlen": "n",
      "gegend": "f",
      "gegensatz": "m",
      "gegenstand": "m",
      "gegens\xE4tze": "m",
      "gegenteil": "n",
      "gegenwart": "f",
      "gegners": "m",
      "geheimnis": "n",
      "gehirn": "n",
      "geh\xE4use": "n",
      "geige": "f",
      "geist": "m",
      "geleitbrief": "m",
      "gel\xE4nde": "n",
      "gel\xFCbde": "n",
      "gemach": "n",
      "gem\xE4lde": "n",
      "gem\xFCse": "n",
      "gep\xE4ck": "n",
      "gericht": "n",
      "geruch": "m",
      "ger\xE4t": "n",
      "ger\xE4usch": "n",
      "ger\xE4usche": "n",
      "ger\xF6ll": "n",
      "ger\xFCcht": "n",
      "ger\xFCchte": "n",
      "ger\xFCst": "n",
      "gesangbuch": "n",
      "geschenk": "n",
      "geschichte": "f",
      "geschichten": "f",
      "geschmack": "m",
      "gesetz": "n",
      "gesetze": "n",
      "gesetzen": "n",
      "gesetzes": "n",
      "gesetzestext": "m",
      "gesicht": "n",
      "gesichter": "n",
      "gespr\xE4ch": "n",
      "gestalt": "f",
      "gestalten": "f",
      "geste": "f",
      "gestein": "n",
      "gesteinsschichten": "f",
      "getreide": "n",
      "getreidek\xF6rner": "n",
      "gewand": "n",
      "gewebe": "n",
      "gewehr": "n",
      "gewehre": "n",
      "geweih": "n",
      "gewicht": "n",
      "gewichte": "n",
      "gewissen": "n",
      "gew\xF6lbe": "n",
      "gezeiten": "f",
      "gier": "f",
      "gie\xDFkanne": "f",
      "gift": "n",
      "gipfel": "m",
      "gitter": "n",
      "glas": "n",
      "glasplatte": "f",
      "glaube": "m",
      "gleichung": "f",
      "gletscher": "m",
      "glocke": "f",
      "gl\xFCck": "n",
      "gold": "n",
      "gott": "m",
      "grab": "n",
      "graben": "m",
      "granitblock": "m",
      "grenze": "f",
      "grotte": "f",
      "grund": "m",
      "grundrissplan": "m",
      "gruppe": "f",
      "gruppenchat": "m",
      "gurke": "f",
      "g\xF6tter": "m",
      "g\xF6ttin": "f",
      "g\xFCrtel": "m",
      "haar": "n",
      "haarnadel": "f",
      "hafen": "m",
      "hagel": "m",
      "hahn": "m",
      "hain": "m",
      "haken": "m",
      "halde": "f",
      "hall": "m",
      "halle": "f",
      "hals": "m",
      "halter": "m",
      "hammer": "m",
      "hand": "f",
      "handbuch": "n",
      "handkarren": "m",
      "handschuh": "m",
      "handschuhspitze": "f",
      "handvoll": "f",
      "handy": "n",
      "hang": "m",
      "harfe": "f",
      "harpune": "f",
      "hase": "m",
      "hass": "m",
      "haus": "n",
      "haut": "f",
      "hecke": "f",
      "heft": "n",
      "held": "m",
      "helm": "m",
      "hemd": "n",
      "henne": "f",
      "herbst": "m",
      "herd": "m",
      "herr": "m",
      "herrscherstab": "m",
      "herz": "n",
      "herzschlag": "m",
      "heuer": "f",
      "hexe": "f",
      "hierarchie": "f",
      "himmel": "m",
      "hintergrund": "m",
      "hintert\xFCr": "f",
      "hirn": "n",
      "hirsch": "m",
      "hirtenstab": "m",
      "hof": "m",
      "hoffnung": "f",
      "holz": "n",
      "honig": "m",
      "hoodie": "m",
      "horn": "n",
      "hose": "f",
      "huhn": "n",
      "hund": "m",
      "hut": "m",
      "h\xE4user": "n",
      "h\xF6henmesser": "m",
      "h\xF6hle": "f",
      "h\xFCfte": "f",
      "h\xFCgel": "m",
      "h\xFCtte": "f",
      "igel": "m",
      "index": "m",
      "insekt": "n",
      "insel": "f",
      "instanz": "f",
      "instastory": "f",
      "instrument": "n",
      "interferometer": "n",
      "jacke": "f",
      "jazz": "m",
      "junge": "m",
      "justiergewicht": "n",
      "j\xE4ger": "m",
      "kabel": "n",
      "kaffee": "m",
      "kai": "m",
      "kaiser": "m",
      "kalb": "n",
      "kalender": "m",
      "kamin": "m",
      "kaminfeuer": "n",
      "kammer": "f",
      "kampf": "m",
      "kanal": "m",
      "kaninchen": "n",
      "kanister": "m",
      "kanne": "f",
      "kanten": "m",
      "kapelle": "f",
      "kapit\xE4n": "m",
      "karawane": "f",
      "karotte": "f",
      "karte": "f",
      "karteikarte": "f",
      "kartoffel": "f",
      "kassenbuch": "n",
      "kathedrale": "f",
      "katze": "f",
      "kaugummi": "m",
      "kehle": "f",
      "kelch": "m",
      "kelle": "f",
      "keller": "m",
      "kerze": "f",
      "kessel": "m",
      "kette": "f",
      "kettenhemd": "n",
      "kiefer": "m",
      "kiel": "m",
      "kies": "m",
      "kilometer": "m",
      "kind": "n",
      "kinder": "n",
      "kinderspielzeug": "n",
      "kinn": "n",
      "kirche": "f",
      "kirsche": "f",
      "kissen": "n",
      "kiste": "f",
      "klammer": "f",
      "klang": "m",
      "klaue": "f",
      "klavier": "n",
      "kleid": "n",
      "kleidersack": "m",
      "kleingeldfach": "n",
      "kleinod": "n",
      "klinge": "f",
      "klingel": "f",
      "klippe": "f",
      "klopfen": "n",
      "knabe": "m",
      "knie": "n",
      "knochen": "m",
      "knopf": "m",
      "knospe": "f",
      "knoten": "m",
      "kn\xE4uel": "n",
      "kn\xF6chel": "m",
      "koffer": "m",
      "kohleneimer": "m",
      "kohleschale": "f",
      "kollege": "m",
      "kollegheft": "n",
      "kollektiv": "n",
      "kolonie": "f",
      "komet": "m",
      "kommentar": "m",
      "kommissar": "m",
      "kompass": "m",
      "kompressor": "m",
      "konstante": "f",
      "konto": "n",
      "kontobuch": "n",
      "kontor": "n",
      "kontorbuch": "n",
      "kontostand": "m",
      "kopf": "m",
      "kopfh\xF6rer": "m",
      "kopie": "f",
      "korb": "m",
      "korken": "m",
      "korn": "n",
      "kraft": "f",
      "kran": "m",
      "krater": "m",
      "kreide": "f",
      "kreis": "m",
      "kreuz": "n",
      "kreuzung": "f",
      "kribbeln": "n",
      "krieg": "m",
      "krieger": "m",
      "kristall": "m",
      "krone": "f",
      "krug": "m",
      "kr\xE4he": "f",
      "kuchen": "m",
      "kuh": "f",
      "kupfer": "n",
      "kuppel": "f",
      "kurbel": "f",
      "kurve": "f",
      "kuss": "m",
      "kutsche": "f",
      "kuvert": "n",
      "k\xE4fer": "m",
      "k\xE4lte": "f",
      "k\xE4se": "m",
      "k\xF6nig": "m",
      "k\xF6nigin": "f",
      "k\xF6rper": "m",
      "k\xFCche": "f",
      "k\xFChlbox": "f",
      "k\xFChlfalle": "f",
      "k\xFCken": "n",
      "k\xFCste": "f",
      "labyrinth": "n",
      "ladebalken": "m",
      "ladekabel": "n",
      "ladeliste": "f",
      "lager": "n",
      "lagune": "f",
      "laib": "m",
      "lamm": "n",
      "lampe": "f",
      "land": "n",
      "lanze": "f",
      "laterne": "f",
      "laub": "n",
      "laufzettel": "m",
      "laute": "f",
      "lawine": "f",
      "leder": "n",
      "lederbeutel": "m",
      "legende": "f",
      "lehen": "n",
      "lehrer": "m",
      "leid": "n",
      "leine": "f",
      "leitdetail": "n",
      "leitung": "f",
      "leuchten": "n",
      "leuchtturm": "m",
      "licht": "n",
      "lichtstreifen": "m",
      "lider": "n",
      "liebe": "f",
      "lied": "n",
      "lilie": "f",
      "lineal": "n",
      "linie": "f",
      "lippe": "f",
      "liste": "f",
      "loch": "n",
      "locke": "f",
      "log": "n",
      "logbuch": "n",
      "logfile": "n",
      "los": "n",
      "lot": "n",
      "luft": "f",
      "lupe": "f",
      "lust": "f",
      "l\xE4cheln": "n",
      "l\xE4nder": "n",
      "l\xE4rm": "m",
      "l\xF6cher": "n",
      "l\xF6ffel": "m",
      "l\xF6we": "m",
      "l\xFCcke": "f",
      "l\xFCge": "f",
      "macht": "f",
      "magen": "m",
      "mala": "f",
      "maler": "m",
      "manege": "f",
      "manifest": "n",
      "mann": "m",
      "mantel": "m",
      "manuskript": "n",
      "mappe": "f",
      "marmelade": "f",
      "masche": "f",
      "maschine": "f",
      "maske": "f",
      "mast": "m",
      "matte": "f",
      "mauer": "f",
      "maus": "f",
      "ma\xDF": "n",
      "ma\xDFband": "n",
      "ma\xDFstab": "m",
      "medaillon": "n",
      "meer": "n",
      "mehl": "n",
      "mei\xDFel": "m",
      "melodie": "f",
      "meme": "n",
      "menge": "f",
      "merkblatt": "n",
      "messer": "n",
      "messprotokoll": "n",
      "messreihe": "f",
      "messung": "f",
      "metall": "n",
      "meter": "m",
      "metronom": "n",
      "miene": "f",
      "mikrofon": "n",
      "mikroskop": "n",
      "milch": "f",
      "millimeter": "m",
      "minute": "f",
      "mitleid": "n",
      "mittag": "m",
      "mittel": "n",
      "mitternacht": "f",
      "modell": "n",
      "modellplaneten": "m",
      "moment": "m",
      "monat": "m",
      "mond": "m",
      "moor": "n",
      "morgen": "m",
      "moschee": "f",
      "motor": "m",
      "mus": "n",
      "muschel": "f",
      "muskel": "m",
      "muster": "n",
      "mut": "m",
      "mutter": "f",
      "m\xE4dchen": "n",
      "m\xE4hne": "f",
      "m\xF6hre": "f",
      "m\xF6nch": "m",
      "m\xF6rder": "m",
      "m\xF6we": "f",
      "m\xFCcke": "f",
      "m\xFChle": "f",
      "m\xFCller": "m",
      "m\xFCnze": "f",
      "m\xFCtze": "f",
      "nachbar": "m",
      "nachbarort": "m",
      "nachlass": "m",
      "nachmittag": "m",
      "nachricht": "f",
      "nacht": "f",
      "nachtigall": "f",
      "nacken": "m",
      "nadel": "f",
      "nadelkissen": "n",
      "nagel": "m",
      "naht": "f",
      "name": "m",
      "napf": "m",
      "narbe": "f",
      "nase": "f",
      "nebel": "m",
      "neffe": "m",
      "neid": "m",
      "neigung": "f",
      "neigungsmesser": "m",
      "nelke": "f",
      "nest": "n",
      "nester": "n",
      "netz": "n",
      "nische": "f",
      "nonne": "f",
      "note": "f",
      "notenblatt": "n",
      "notiz": "f",
      "notizblock": "m",
      "notizbuch": "n",
      "nummer": "f",
      "nuss": "f",
      "nymphe": "f",
      "n\xE4he": "f",
      "obst": "n",
      "ofen": "m",
      "ohr": "n",
      "oma": "f",
      "omen": "n",
      "onkel": "m",
      "opfer": "n",
      "opferschale": "f",
      "opiumdose": "f",
      "orakel": "n",
      "orange": "f",
      "organ": "n",
      "orgel": "f",
      "ort": "m",
      "ozean": "m",
      "paar": "n",
      "paket": "n",
      "pakt": "m",
      "papier": "n",
      "paradoxon": "n",
      "paragraph": "m",
      "parameter": "m",
      "park": "m",
      "passagier": "m",
      "passierschein": "m",
      "pegelstab": "m",
      "peilstock": "m",
      "peitsche": "f",
      "pendel": "n",
      "pergamentrolle": "f",
      "perle": "f",
      "perlmuttknopf": "m",
      "person": "f",
      "petrischale": "f",
      "petroleumlampe": "f",
      "pfad": "m",
      "pfand": "n",
      "pfandschein": "m",
      "pfeffer": "m",
      "pfeife": "f",
      "pferd": "n",
      "pfirsich": "m",
      "pflaster": "n",
      "pflaume": "f",
      "pflug": "m",
      "pf\xFCtze": "f",
      "phiole": "f",
      "photoplatte": "f",
      "pickel": "m",
      "pilz": "m",
      "ping": "m",
      "pinzette": "f",
      "pipette": "f",
      "plakat": "n",
      "plan": "m",
      "plane": "f",
      "planet": "m",
      "planke": "f",
      "platte": "f",
      "platz": "m",
      "platzhalter": "m",
      "poller": "m",
      "port": "m",
      "portal": "n",
      "postkarte": "f",
      "powerbank": "f",
      "priester": "m",
      "prisma": "n",
      "probe": "f",
      "programm": "n",
      "protokoll": "n",
      "prozess": "m",
      "puls": "m",
      "pulver": "n",
      "punkt": "m",
      "puppe": "f",
      "qualle": "f",
      "quelle": "f",
      "quittung": "f",
      "rad": "n",
      "rampe": "f",
      "rand": "m",
      "randnotiz": "f",
      "ranke": "f",
      "ranzen": "m",
      "ratte": "f",
      "rauch": "m",
      "raumkapsel": "f",
      "rausch": "m",
      "rauschen": "n",
      "rechentafel": "f",
      "recht": "n",
      "regal": "n",
      "regel": "f",
      "regen": "m",
      "regenmesser": "m",
      "register": "n",
      "reh": "n",
      "reich": "n",
      "reif": "m",
      "reigen": "m",
      "reihe": "f",
      "reinraumhaube": "f",
      "reise": "f",
      "reisemantel": "m",
      "rei\xDFverschluss": "m",
      "reklame": "f",
      "rest": "m",
      "rettung": "f",
      "rezept": "n",
      "richter": "m",
      "riegel": "m",
      "riff": "n",
      "rinde": "f",
      "ring": "m",
      "rippe": "f",
      "riss": "m",
      "ritter": "m",
      "ritterhelm": "m",
      "rohr": "n",
      "roman": "m",
      "rose": "f",
      "ruder": "n",
      "ruf": "m",
      "ruine": "f",
      "rumpf": "m",
      "r\xE4tsel": "n",
      "r\xFCcken": "m",
      "saal": "m",
      "sachbearbeiter": "m",
      "sack": "m",
      "saft": "m",
      "sage": "f",
      "sahne": "f",
      "saite": "f",
      "salat": "m",
      "salz": "n",
      "samen": "m",
      "sammlung": "f",
      "sand": "m",
      "sandsack": "m",
      "sanduhr": "f",
      "sarg": "m",
      "satellit": "m",
      "sattel": "m",
      "sattelgurt": "m",
      "satz": "m",
      "saum": "m",
      "savanne": "f",
      "schacht": "m",
      "schaf": "n",
      "schale": "f",
      "schalter": "m",
      "scham": "f",
      "schatten": "m",
      "schatulle": "f",
      "schaufel": "f",
      "schere": "f",
      "schicht": "f",
      "schicksal": "n",
      "schiff": "n",
      "schiffssextanten": "m",
      "schiffszwieback": "m",
      "schild": "n",
      "schirm": "m",
      "schlaf": "m",
      "schlag": "m",
      "schlamm": "m",
      "schlange": "f",
      "schleife": "f",
      "schloss": "n",
      "schlucht": "f",
      "schl\xFCssel": "m",
      "schl\xFCsselbund": "m",
      "schmerz": "m",
      "schmied": "m",
      "schmiede": "f",
      "schminkkasten": "m",
      "schnecke": "f",
      "schnee": "m",
      "schneiderpuppe": "f",
      "schnitt": "m",
      "schnittbogen": "m",
      "schnittstelle": "f",
      "schnur": "f",
      "schokolade": "f",
      "schrank": "m",
      "schrei": "m",
      "schreiber": "m",
      "schrein": "m",
      "schrift": "f",
      "schritt": "m",
      "schuh": "m",
      "schuld": "f",
      "schuldschein": "m",
      "schule": "f",
      "schulter": "f",
      "schuppen": "m",
      "schuss": "m",
      "schwamm": "m",
      "schwein": "n",
      "schwelle": "f",
      "schwert": "n",
      "schwertgriff": "m",
      "schwertgurt": "m",
      "schwester": "f",
      "schw\xE4che": "f",
      "sch\xE4del": "m",
      "sch\xE4rpe": "f",
      "sch\xFCrze": "f",
      "sch\xFCssel": "f",
      "screenshot": "m",
      "see": "m",
      "seekarte": "f",
      "seele": "f",
      "seesack": "m",
      "segel": "n",
      "segeltuch": "n",
      "segen": "m",
      "sehne": "f",
      "sehnsucht": "f",
      "seidenfaden": "m",
      "seil": "n",
      "seismograph": "m",
      "seismographen": "m",
      "seite": "f",
      "sekunde": "f",
      "senf": "m",
      "sensor": "m",
      "sessel": "m",
      "sieb": "n",
      "siegel": "n",
      "siegelring": "m",
      "signal": "n",
      "signalflagge": "f",
      "silbe": "f",
      "silber": "n",
      "sinn": "m",
      "sirene": "f",
      "skala": "f",
      "skalpell": "n",
      "skelett": "n",
      "skizze": "f",
      "smartphone": "n",
      "socke": "f",
      "sofa": "n",
      "sohn": "m",
      "soldat": "m",
      "sommer": "m",
      "sonne": "f",
      "sonnenbrille": "f",
      "so\xDFe": "f",
      "spalt": "m",
      "speicher": "m",
      "spektrogramm": "n",
      "spektrometer": "n",
      "sperre": "f",
      "spiegel": "m",
      "spiegelscherben": "m",
      "spiel": "n",
      "spinne": "f",
      "sporn": "m",
      "sprache": "f",
      "sprung": "m",
      "spule": "f",
      "spur": "f",
      "stab": "m",
      "stadt": "f",
      "stahlstrebe": "f",
      "stamm": "m",
      "standarte": "f",
      "stapel": "m",
      "statue": "f",
      "staub": "m",
      "stecknadel": "f",
      "steg": "m",
      "steig": "m",
      "steigb\xFCgel": "m",
      "steigeisen": "n",
      "stein": "m",
      "stelle": "f",
      "stempel": "m",
      "stempelger\xE4usch": "n",
      "stempelhalter": "m",
      "steppe": "f",
      "stern": "m",
      "sternbilder": "n",
      "sternwarte": "f",
      "stethoskop": "n",
      "stiefel": "m",
      "stier": "m",
      "stille": "f",
      "stimme": "f",
      "stirn": "f",
      "stock": "m",
      "stoff": "m",
      "stollen": "m",
      "stolz": "m",
      "story": "f",
      "strand": "m",
      "strauch": "m",
      "stra\xDFe": "f",
      "streichholzschachtel": "f",
      "streit": "m",
      "strich": "m",
      "strom": "m",
      "strophe": "f",
      "str\xF6mung": "f",
      "stube": "f",
      "stufe": "f",
      "stuhl": "m",
      "stunde": "f",
      "stundenplan": "m",
      "sturm": "m",
      "sturmlaterne": "f",
      "st\xE4rke": "f",
      "st\xFCck": "n",
      "sumpf": "m",
      "suppe": "f",
      "suppenkelle": "f",
      "symbol": "n",
      "symptom": "n",
      "system": "n",
      "s\xE4ge": "f",
      "s\xE4ule": "f",
      "tabelle": "f",
      "tafel": "f",
      "tafelrunde": "f",
      "tag": "m",
      "takt": "m",
      "tal": "n",
      "talar": "m",
      "tante": "f",
      "tanz": "m",
      "tasche": "f",
      "taschenradio": "n",
      "tasse": "f",
      "tau": "n",
      "taube": "f",
      "tee": "m",
      "teer": "m",
      "teeschale": "f",
      "teich": "m",
      "teil": "m",
      "telefon": "n",
      "teleskop": "n",
      "teller": "m",
      "teppich": "m",
      "termin": "m",
      "terminal": "n",
      "terminzettel": "m",
      "teufel": "m",
      "thermometer": "n",
      "thermoskanne": "f",
      "thron": "m",
      "ticket": "n",
      "tier": "n",
      "tiger": "m",
      "tiktoksound": "m",
      "tintenfass": "n",
      "tisch": "m",
      "tochter": "f",
      "tod": "m",
      "tomate": "f",
      "ton": "m",
      "tonband": "n",
      "tonschale": "f",
      "tontafel": "f",
      "topf": "m",
      "tor": "n",
      "torte": "f",
      "trapezhaken": "m",
      "traube": "f",
      "trauer": "f",
      "traum": "m",
      "trend": "m",
      "treppe": "f",
      "treue": "f",
      "trillerpfeife": "f",
      "trinkhorn": "n",
      "trommel": "f",
      "truhe": "f",
      "tr\xE4ne": "f",
      "tuch": "n",
      "tulpe": "f",
      "tunnel": "m",
      "turm": "m",
      "turnbeutel": "m",
      "turnier": "n",
      "turnierplatz": "m",
      "turnierstab": "m",
      "t\xFCr": "f",
      "t\xFCte": "f",
      "ufer": "n",
      "uhr": "f",
      "umriss": "m",
      "umschlag": "m",
      "ungl\xFCck": "n",
      "untergrund": "m",
      "unterschrift": "f",
      "untersuchungsliege": "f",
      "update": "n",
      "urne": "f",
      "urteil": "n",
      "vater": "m",
      "verdacht": "m",
      "verfahren": "n",
      "vergangenheit": "f",
      "vermerk": "m",
      "vers": "m",
      "verstand": "m",
      "vertrag": "m",
      "vertrauen": "n",
      "video": "n",
      "virus": "n",
      "visier": "n",
      "vogel": "m",
      "vollmacht": "f",
      "vordruck": "m",
      "vorhang": "m",
      "vormund": "m",
      "vorrat": "m",
      "vorratsgl\xE4ser": "n",
      "vulkan": "m",
      "wachs": "n",
      "wachstuch": "n",
      "wagen": "m",
      "wahrheit": "f",
      "waisenjunge": "m",
      "wal": "m",
      "wald": "m",
      "waldhorn": "n",
      "wand": "f",
      "wanderstab": "m",
      "wanderstock": "m",
      "wanderung": "f",
      "wange": "f",
      "wappen": "n",
      "wappenschild": "n",
      "warnung": "f",
      "warnweste": "f",
      "wartemarke": "f",
      "warze": "f",
      "wasser": "n",
      "wasserflasche": "f",
      "wasserhahn": "m",
      "weg": "m",
      "wegmarke": "f",
      "weide": "f",
      "wein": "m",
      "weite": "f",
      "wei\xDF": "n",
      "welle": "f",
      "werk": "n",
      "werkstatt": "f",
      "werkzeug": "n",
      "wert": "m",
      "wespe": "f",
      "wetter": "n",
      "wetterfahne": "f",
      "widerstand": "m",
      "wiese": "f",
      "wille": "m",
      "wimper": "f",
      "wind": "m",
      "windhauch": "m",
      "windsto\xDF": "m",
      "winter": "m",
      "witz": "m",
      "woche": "f",
      "wolf": "m",
      "wolke": "f",
      "wollschal": "m",
      "wort": "n",
      "wrack": "n",
      "wunde": "f",
      "wunder": "n",
      "wunsch": "m",
      "wurm": "m",
      "wurzel": "f",
      "wut": "f",
      "w\xE4chter": "m",
      "w\xE4lder": "m",
      "w\xE4rme": "f",
      "w\xE4rmestein": "m",
      "w\xE4schekorb": "m",
      "w\xF6rter": "n",
      "w\xFCrfel": "m",
      "w\xFCste": "f",
      "zahl": "f",
      "zahn": "m",
      "zange": "f",
      "zauberbesen": "m",
      "zaun": "m",
      "zeh": "m",
      "zeichen": "n",
      "zeile": "f",
      "zeit": "f",
      "zeitgeber": "m",
      "zeitmarke": "f",
      "zelle": "f",
      "zelt": "n",
      "zentimeter": "m",
      "zepter": "n",
      "zettel": "m",
      "zeuge": "m",
      "ziffer": "f",
      "zigarettenstummel": "m",
      "zigarre": "f",
      "zimmer": "n",
      "zirkel": "m",
      "zitrone": "f",
      "zittern": "n",
      "zorn": "m",
      "zucker": "m",
      "zug": "m",
      "zukunft": "f",
      "zunderbeutel": "m",
      "zunge": "f",
      "zweifel": "m",
      "zweig": "m",
      "zweitschl\xFCssel": "m",
      "zwieback": "m",
      "zwiebel": "f",
      "z\xE4hlrahmen": "m",
      "z\xF6gern": "n",
      "\xE4rmel": "m",
      "\xE4rztin": "f",
      "\xF6l": "n",
      "\xF6llampe": "f",
      "\xF6llaterne": "f",
      "\xF6lschl\xFCssel": "m"
    };
  }
});

// src/generation/nouns2.data.ts
var NOUN_GENDER_2;
var init_nouns2_data = __esm({
  "src/generation/nouns2.data.ts"() {
    "use strict";
    NOUN_GENDER_2 = {
      // Nachtrag 4.357.1 (Blatt „Ost-Berlin": „Ein rotes Ballon")
      ballon: "m",
      luftballon: "m",
      stoff: "m",
      geschmack: "m",
      sperrstunde: "f",
      zugang: "m",
      kopie: "f",
      l\u00F6schung: "f",
      // ── Häufigste ──
      ende: "n",
      jahr: "n",
      mal: "n",
      anfang: "m",
      leben: "n",
      auskunft: "f",
      welt: "f",
      fr\u00FChjahr: "n",
      fall: "m",
      arbeit: "f",
      sache: "f",
      zufall: "m",
      form: "f",
      ziel: "n",
      kontrolle: "f",
      reihenfolge: "f",
      wissen: "n",
      post: "f",
      ernte: "f",
      geld: "n",
      mund: "m",
      schweigen: "n",
      wette: "f",
      schminke: "f",
      kurs: "m",
      original: "n",
      text: "m",
      gras: "n",
      warten: "n",
      ruhe: "f",
      mitte: "f",
      seide: "f",
      familie: "f",
      tiefe: "f",
      norden: "m",
      s\u00FCden: "m",
      osten: "m",
      westen: "m",
      blut: "n",
      horizont: "m",
      ursache: "f",
      absicht: "f",
      wirt: "m",
      jagd: "f",
      herkunft: "f",
      essen: "n",
      r\u00FCckkehr: "f",
      rahmen: "m",
      w\u00FCrde: "f",
      w\u00E4sche: "f",
      miete: "f",
      verlangen: "n",
      marke: "f",
      griff: "m",
      wache: "f",
      vernunft: "f",
      markt: "m",
      pegel: "m",
      halbdunkel: "n",
      rolle: "f",
      grad: "m",
      streben: "n",
      fach: "n",
      weise: "f",
      wipfel: "m",
      kohle: "f",
      lehne: "f",
      tide: "f",
      ru\u00DF: "m",
      idee: "f",
      gemeinde: "f",
      jahrhundert: "n",
      ernst: "m",
      betrag: "m",
      unterschied: "m",
      material: "n",
      annahme: "f",
      merkmal: "n",
      radio: "n",
      hitze: "f",
      herold: "m",
      grat: "m",
      kasse: "f",
      zoll: "m",
      heimweh: "n",
      laden: "m",
      f\u00E4hre: "f",
      herzog: "m",
      inhalt: "m",
      titel: "m",
      problem: "n",
      sicht: "f",
      beh\u00F6rde: "f",
      winkel: "m",
      hilfe: "f",
      pass: "m",
      viertel: "n",
      jahrzehnt: "n",
      anrede: "f",
      rost: "m",
      ekel: "m",
      tat: "f",
      methode: "f",
      zwang: "m",
      heimkehr: "f",
      umkehr: "f",
      norm: "f",
      leere: "f",
      umlauf: "m",
      flamme: "f",
      einsicht: "f",
      messing: "n",
      personal: "n",
      widerspruch: "m",
      schluss: "m",
      stroh: "n",
      rang: "m",
      vieh: "n",
      garderobe: "f",
      g\u00FCte: "f",
      anlass: "m",
      anwalt: "m",
      rat: "m",
      code: "m",
      bad: "n",
      handgelenk: "n",
      scheibe: "f",
      zustand: "m",
      eile: "f",
      saatgut: "n",
      fracht: "f",
      automat: "m",
      lehre: "f",
      ding: "n",
      verzicht: "m",
      zweck: "m",
      waffe: "f",
      blech: "n",
      trost: "m",
      versuch: "m",
      ironie: "f",
      d\u00FCrre: "f",
      fest: "n",
      aufsicht: "f",
      kapitel: "n",
      aussicht: "f",
      absinth: "m",
      parf\u00FCm: "n",
      schmutz: "m",
      knick: "m",
      andacht: "f",
      spitze: "f",
      szene: "f",
      erfolg: "m",
      ausguck: "m",
      bord: "m",
      sieg: "m",
      klausel: "f",
      haupttext: "m",
      sachverhalt: "m",
      tinte: "f",
      stand: "m",
      wortlaut: "m",
      klinke: "f",
      kanzel: "f",
      verrat: "m",
      mulde: "f",
      februar: "m",
      parasit: "m",
      pr\u00E4parat: "n",
      wesen: "n",
      lava: "f",
      schwefel: "m",
      lauf: "m",
      spa\u00DF: "m",
      m\u00F6bel: "n",
      b\u00FCro: "n",
      hauptsache: "f",
      saat: "f",
      fehde: "f",
      portr\u00E4t: "n",
      reue: "f",
      konfetti: "n",
      trapez: "n",
      narr: "m",
      truppe: "f",
      pudel: "m",
      jugend: "f",
      abschied: "m",
      bronze: "f",
      tempel: "m",
      geschlecht: "n",
      stra\u00DFenanfang: "m",
      brauch: "m",
      wiederkehr: "f",
      h\u00E4lfte: "f",
      pappe: "f",
      kante: "f",
      eintrag: "m",
      format: "n",
      giebel: "m",
      heimat: "f",
      armenkasse: "f",
      materie: "f",
      mensch: "m",
      glied: "n",
      betrieb: "m",
      m\u00FCll: "m",
      kleingeld: "n",
      ruhm: "m",
      ritt: "m",
      sch\u00E4rfe: "f",
      ankunft: "f",
      symmetrie: "f",
      adressat: "m",
      kreislauf: "m",
      aufstieg: "m",
      f\u00FClle: "f",
      bitte: "f",
      brand: "m",
      waise: "f",
      gesang: "m",
      subjekt: "n",
      objekt: "n",
      moral: "f",
      schilf: "n",
      diagnose: "f",
      gr\u00F6\u00DFe: "f",
      wahl: "f",
      sturz: "m",
      gischt: "f",
      ekstase: "f",
      becken: "n",
      putz: "m",
      minze: "f",
      samt: "m",
      pause: "f",
      knauf: "m",
      apotheke: "f",
      kost\u00FCm: "n",
      versto\u00DF: "m",
      satzanfang: "m",
      sprint: "m",
      beule: "f",
      banane: "f",
      tapete: "f",
      galerie: "f",
      kl\u00F6ppel: "m",
      predigt: "f",
      zierrat: "m",
      wachwechsel: "m",
      wimpel: "m",
      rah: "f",
      streitfall: "m",
      docht: "m",
      wundmal: "n",
      pforte: "f",
      gebot: "n",
      fl\u00FCgel: "m",
      l\u00E4nge: "f",
      kamel: "n",
      achse: "f",
      schlegel: "m",
      affe: "m",
      nirwana: "n",
      alkohol: "m",
      instinkt: "m",
      balance: "f",
      aushub: "m",
      kalk: "m",
      r\u00F6hre: "f",
      basalt: "m",
      salzs\u00E4ure: "f",
      erdkruste: "f",
      schichtfolge: "f",
      sohle: "f",
      profil: "n",
      schneeschmelze: "f",
      orbit: "m",
      funkspruch: "m",
      meteorit: "m",
      stromausfall: "m",
      theorie: "f",
      nervengeflecht: "n",
      bodenprofil: "n",
      senke: "f",
      gebiet: "n",
      phase: "f",
      honorar: "n",
      kordel: "f",
      spind: "m",
      tonfall: "m",
      tempo: "n",
      schattenkante: "f",
      stahl: "m",
      graupappe: "f",
      st\u00FCtze: "f",
      perspektive: "f",
      tank: "m",
      stillstand: "m",
      pumpe: "f",
      debatte: "f",
      bahre: "f",
      fackelru\u00DF: "m",
      kerbe: "f",
      t\u00FCrsturz: "m",
      groll: "m",
      seuche: "f",
      lunge: "f",
      pferdegeschirr: "n",
      zeltgest\u00E4nge: "n",
      marsch: "m",
      schaumgummi: "m",
      knall: "m",
      zeltmitte: "f",
      trick: "m",
      wurf: "m",
      pult: "n",
      pentagramm: "n",
      handel: "m",
      r\u00FCcktritt: "m",
      zimt: "m",
      akt: "m",
      schatz: "m",
      betrug: "m",
      kopfende: "n",
      parkett: "n",
      lack: "m",
      leib: "m",
      efeu: "m",
      anstand: "m",
      schafwolle: "f",
      milde: "f",
      wiege: "f",
      schar: "f",
      gunst: "f",
      volk: "n",
      staat: "m",
      antlitz: "n",
      fleck: "m",
      alibi: "n",
      kamera: "f",
      vorfall: "m",
      quelltext: "m",
      ritual: "n",
      schl\u00E4fe: "f",
      wetterwechsel: "m",
      anzeige: "f",
      jahresende: "n",
      weile: "f",
      t\u00FCll: "m",
      schleppe: "f",
      b\u00FCgel: "m",
      dampf: "m",
      kragen: "m",
      kerzenstummel: "m",
      klasse: "f",
      monatsende: "n",
      tausendstel: "n",
      durchlauf: "m",
      jahrtausend: "n",
      scheu: "f",
      taxi: "n",
      mittwoch: "m",
      erz: "n",
      diebstahl: "m",
      nachtwache: "f",
      schleuse: "f",
      \u00FCbernahme: "f",
      luke: "f",
      sp\u00FCle: "f",
      ampel: "f",
      sperrm\u00FCll: "m",
      speiche: "f",
      henkel: "m",
      routine: "f",
      mai: "m",
      wolle: "f",
      schluck: "m",
      biologie: "f",
      geologie: "f",
      astrologie: "f",
      philosophie: "f",
      krise: "f",
      trag\u00F6die: "f",
      urknall: "m",
      stift: "m",
      mine: "f",
      abwehr: "f",
      mole: "f",
      zerfall: "m",
      masse: "f",
      handbreit: "f",
      verfall: "m",
      tischkante: "f",
      beute: "f",
      rache: "f",
      font\u00E4ne: "f",
      zuversicht: "f",
      unruhe: "f",
      energie: "f",
      enge: "f",
      april: "m",
      rekord: "m",
      normalzustand: "m",
      h\u00F6he: "f",
      abstieg: "m",
      requisit: "n",
      schwindel: "m",
      orakelspruch: "m",
      erlass: "m",
      aufstand: "m",
      gehorsam: "m",
      blackbox: "f",
      silhouette: "f",
      mode: "f",
      not: "f",
      urform: "f",
      ruhestand: "m",
      schaden: "m",
      anlauf: "m",
      dienstjahr: "n",
      witwe: "f",
      ensemble: "n",
      kommune: "f",
      sekte: "f",
      rettungstrupp: "m",
      exil: "n",
      zentrale: "f",
      zensurbeh\u00F6rde: "f",
      doktortitel: "m",
      naturschutzgebiet: "n",
      boulevard: "m",
      hotel: "n",
      kino: "n",
      verkehr: "m",
      kellerclub: "m",
      kabine: "f",
      auto: "n",
      kaserne: "f",
      internat: "n",
      wahlkabine: "f",
      anstalt: "f",
      mittagspause: "f",
      choleraepidemie: "f",
      monarchie: "f",
      hungersnot: "f",
      null: "f",
      route: "f",
      kampagne: "f",
      karriere: "f",
      neuanfang: "m",
      sorte: "f",
      verhandlungssache: "f",
      folge: "f",
      ablauf: "m",
      strategie: "f",
      apparat: "m",
      psychopath: "m",
      variable: "f",
      empathie: "f",
      amsel: "f",
      schneefall: "m",
      abendrot: "n",
      wechsel: "m",
      // ── Nachschlag: Alltag, Körper, Haus, Natur, Amt ──
      auge: "n",
      name: "m",
      glaube: "m",
      wille: "m",
      gedanke: "m",
      friede: "m",
      funke: "m",
      k\u00E4se: "m",
      junge: "m",
      kunde: "m",
      l\u00F6we: "m",
      hase: "m",
      bote: "m",
      zeuge: "m",
      riese: "m",
      rabe: "m",
      falke: "m",
      ochse: "m",
      bursche: "m",
      knabe: "m",
      neffe: "m",
      erbe: "m",
      buchstabe: "m",
      same: "m",
      schatten: "m",
      wagen: "m",
      boden: "m",
      garten: "m",
      ofen: "m",
      regen: "m",
      faden: "m",
      haken: "m",
      hafen: "m",
      morgen: "m",
      tropfen: "m",
      kissen: "n",
      zeichen: "n",
      kuchen: "m",
      knochen: "m",
      r\u00FCcken: "m",
      segen: "m",
      bogen: "m",
      balken: "m",
      riegel: "m",
      ballen: "m",
      fels: "m",
      haus: "n",
      glas: "n",
      bus: "m",
      fluss: "m",
      kuss: "m",
      guss: "m",
      gru\u00DF: "m",
      fu\u00DF: "m",
      hass: "m",
      kompass: "m",
      atlas: "m",
      kreis: "m",
      preis: "m",
      eis: "n",
      reis: "m",
      gleis: "n",
      flei\u00DF: "m",
      geheimnis: "n",
      ergebnis: "n",
      zeugnis: "n",
      bed\u00FCrfnis: "n",
      verh\u00E4ltnis: "n",
      ereignis: "n",
      erlebnis: "n",
      b\u00FCndnis: "n",
      hindernis: "n",
      gef\u00E4ngnis: "n",
      wildnis: "f",
      finsternis: "f",
      fenster: "n",
      zimmer: "n",
      wasser: "n",
      messer: "n",
      feuer: "n",
      kupfer: "n",
      silber: "n",
      pulver: "n",
      wetter: "n",
      alter: "n",
      ufer: "n",
      lager: "n",
      opfer: "n",
      muster: "n",
      kloster: "n",
      register: "n",
      theater: "n",
      fieber: "n",
      leder: "n",
      futter: "n",
      gitter: "n",
      ruder: "n",
      wunder: "n",
      orchester: "n",
      zepter: "n",
      semester: "n",
      polster: "n",
      pflaster: "n",
      laster: "n",
      meter: "m",
      liter: "m",
      zentrum: "n",
      datum: "n",
      museum: "n",
      t\u00FCr: "f",
      hand: "f",
      stern: "m",
      schritt: "m",
      brief: "m",
      weg: "m",
      stimme: "f",
      spur: "f",
      lippe: "f",
      frage: "f",
      perle: "f",
      glocke: "f",
      uhr: "f",
      herz: "n",
      dach: "n",
      stra\u00DFe: "f",
      regel: "f",
      vorrat: "m",
      schicht: "f",
      schaf: "n",
      nummer: "f",
      schuh: "m",
      grenze: "f",
      gutachten: "n",
      satz: "m",
      wort: "n",
      seele: "f",
      teil: "m",
      blume: "f",
      richtung: "f",
      monat: "m",
      zahn: "m",
      ort: "m",
      wand: "f",
      vorhang: "m",
      umstand: "m",
      sandsack: "m",
      kraft: "f",
      bein: "n",
      kanal: "m",
      sinn: "m",
      netz: "n",
      pflasterstein: "m",
      handschuh: "m",
      protokoll: "n",
      system: "n",
      kreidestrich: "m",
      bruchteil: "m",
      tor: "n",
      kran: "m",
      beweis: "m",
      nacht: "f",
      stadt: "f",
      grund: "m",
      zug: "m",
      riff: "n",
      plakat: "n",
      baum: "m",
      erbgang: "m",
      exemplar: "n",
      symptom: "n",
      plan: "m",
      umriss: "m",
      riss: "m",
      bahngleis: "n",
      regal: "n",
      blick: "m",
      bergpass: "m",
      faust: "f",
      stuhl: "m",
      freund: "m",
      stamm: "m",
      tanzschuh: "m",
      dienst: "m",
      ma\u00DF: "n",
      arm: "m",
      kinderhand: "f",
      tisch: "m",
      seil: "n",
      frachtbrief: "m",
      termin: "m",
      formular: "n",
      messwert: "m",
      gegenstand: "m",
      vogel: "m",
      exponat: "n",
      fahrgast: "m",
      meer: "n",
      anruf: "m",
      vorschlag: "m",
      punkt: "m",
      boot: "n",
      paar: "n",
      gast: "m",
      stein: "m",
      stunde: "f",
      minute: "f",
      tag: "m",
      woche: "f",
      seite: "f",
      farbe: "f",
      papier: "n",
      nachbar: "m",
      wolke: "f",
      zeug: "n",
      kind: "n",
      mann: "m",
      frau: "f",
      vater: "m",
      mutter: "f",
      bruder: "m",
      schwester: "f",
      sohn: "m",
      tochter: "f",
      herr: "m",
      dame: "f",
      lehrer: "m",
      arzt: "m",
      pfarrer: "m",
      priester: "m",
      k\u00F6nig: "m",
      k\u00F6nigin: "f",
      kaiser: "m",
      soldat: "m",
      bauer: "m",
      fischer: "m",
      b\u00E4cker: "m",
      schneider: "m",
      schmied: "m",
      m\u00FCller: "m",
      j\u00E4ger: "m",
      hirte: "m",
      knecht: "m",
      magd: "f",
      w\u00E4chter: "m",
      richter: "m",
      h\u00E4ndler: "m",
      fremde: "m",
      kurier: "m",
      agent: "m",
      spion: "m",
      dieb: "m",
      r\u00E4uber: "m",
      m\u00F6rder: "m",
      opferlamm: "n",
      engel: "m",
      teufel: "m",
      geist: "m",
      gott: "m",
      g\u00F6ttin: "f",
      heiliger: "m",
      m\u00F6nch: "m",
      nonne: "f",
      abt: "m",
      bischof: "m",
      papst: "m",
      ritter: "m",
      knappe: "m",
      graf: "m",
      gr\u00E4fin: "f",
      f\u00FCrst: "m",
      prinz: "m",
      prinzessin: "f",
      zauberer: "m",
      hexe: "f",
      drache: "m",
      zwerg: "m",
      elf: "m",
      troll: "m",
      wolf: "m",
      b\u00E4r: "m",
      fuchs: "m",
      hirsch: "m",
      reh: "n",
      pferd: "n",
      hund: "m",
      katze: "f",
      maus: "f",
      ratte: "f",
      schlange: "f",
      fisch: "m",
      m\u00F6we: "f",
      taube: "f",
      kr\u00E4he: "f",
      eule: "f",
      biene: "f",
      fliege: "f",
      spinne: "f",
      k\u00E4fer: "m",
      schmetterling: "m",
      wurm: "m",
      ameise: "f",
      frosch: "m",
      kr\u00F6te: "f",
      eidechse: "f",
      schwan: "m",
      ente: "f",
      gans: "f",
      huhn: "n",
      hahn: "m",
      kuh: "f",
      stier: "m",
      ziege: "f",
      esel: "m",
      schwein: "n",
      lamm: "n",
      // Schwache Maskulina auf -e, die die -e→f-Regel sonst fälschlich fängt
      kollege: "m",
      experte: "m",
      matrose: "m",
      pate: "m",
      sklave: "m",
      laie: "m",
      insasse: "m",
      gatte: "m",
      bulle: "m",
      schurke: "m",
      geselle: "m",
      gef\u00E4hrte: "m",
      genosse: "m",
      komplize: "m",
      jude: "m",
      zar: "m",
      franzose: "m",
      chinese: "m",
      russe: "m",
      grieche: "m",
      t\u00FCrke: "m",
      ire: "m",
      schwede: "m",
      d\u00E4ne: "m",
      psychologe: "m",
      biologe: "m",
      geologe: "m",
      soziologe: "m",
      arch\u00E4ologe: "m",
      philosoph: "m",
      // Neutra auf -e
      interesse: "n",
      geb\u00E4ude: "n",
      gem\u00E4lde: "n",
      gebirge: "n",
      getreide: "n",
      gefolge: "n",
      gel\u00E4nde: "n",
      gewebe: "n",
      gew\u00F6lbe: "n",
      getriebe: "n",
      gef\u00FCge: "n",
      gelage: "n",
      gerede: "n",
      gehege: "n",
      gewerbe: "n"
    };
  }
});

// src/generation/declension.ts
function istSubstantivierterInfinitiv(w) {
  if (!/^[a-zäöüß]{4,}en$/.test(w)) return false;
  const stamm = w.slice(0, -2);
  return istVerbform(stamm + "t") || istVerbform(stamm + "et");
}
function guessGender(noun) {
  const w = (noun || "").toLowerCase().replace(/[^a-zäöüß]/g, "");
  const known = NOUN_GENDER2[w];
  if (known === "m" || known === "f" || known === "n") return known;
  let best = "";
  for (const k in NOUN_GENDER2) {
    if (k.length >= 3 && w.length >= k.length + 2 && w.endsWith(k) && k.length > best.length) best = k;
  }
  if (best) return NOUN_GENDER2[best];
  if (/(ung|heit|keit|schaft|tät|ion|ik|enz|anz|ei|ade|age|üre|itis|ur)$/.test(w)) return "f";
  if (/(chen|lein|ment|tum|um|nis|ma)$/.test(w)) return "n";
  if (/(ling|ismus|ant|ent|ist|eur|or|ich|ig|ast)$/.test(w)) return "m";
  if (istSubstantivierterInfinitiv(w)) return "n";
  if (/^ge[a-zäöüß]{3,}e$/.test(w)) return "n";
  if (/e$/.test(w) && w.length >= 4 && !E_AUSNAHME.test(w)) return "f";
  if (/er$/.test(w)) return "m";
  return void 0;
}
var NOUN_GENDER2, E_AUSNAHME;
var init_declension = __esm({
  "src/generation/declension.ts"() {
    "use strict";
    init_text_utils();
    init_verben();
    init_nouns_data();
    init_nouns2_data();
    NOUN_GENDER2 = { ...NOUN_GENDER_2, ...NOUN_GENDER };
    E_AUSNAHME = /^(ge[a-zäöüß]+e|.*(auge|ende|käse|junge|erbe|interesse))$/;
  }
});

// src/features/faden.ts
var faden_exports = {};
__export(faden_exports, {
  BAUFORM_JE_SCHLAG: () => BAUFORM_JE_SCHLAG,
  SCHLAG_NAME: () => SCHLAG_NAME,
  SERIEN_LAENGE: () => SERIEN_LAENGE,
  SERIEN_SCHLAEGE: () => SERIEN_SCHLAEGE,
  dingAus: () => dingAus,
  dingSatz: () => dingSatz,
  fadenAus: () => fadenAus,
  fadenBeschreibung: () => fadenBeschreibung,
  fadenstaerke: () => fadenstaerke,
  frageAus: () => frageAus,
  ladeFaden: () => ladeFaden,
  schlagDerFolge: () => schlagDerFolge,
  speichereFaden: () => speichereFaden
});
function ladeFaden() {
  try {
    const v = JSON.parse(localStorage.getItem(KEY) || "null");
    if (!v || !v.aktiv) return null;
    return {
      aktiv: true,
      serie: String(v.serie || ""),
      figur: String(v.figur || ""),
      ding: String(v.ding || ""),
      frage: String(v.frage || ""),
      letzterSatz: String(v.letzterSatz || ""),
      folge: Math.max(2, Number(v.folge) || 2),
      laenge: Math.max(2, Number(v.laenge) || SERIEN_LAENGE),
      bauform: String(v.bauform || "standard")
    };
  } catch {
    return null;
  }
}
function speichereFaden(f) {
  try {
    if (f) localStorage.setItem(KEY, JSON.stringify(f));
    else localStorage.removeItem(KEY);
  } catch {
  }
}
function schlagDerFolge(folge, laenge = SERIEN_LAENGE) {
  const n = Math.max(2, laenge);
  const i = Math.round((Math.max(1, Math.min(n, folge)) - 1) / (n - 1) * (SERIEN_SCHLAEGE.length - 1));
  return SERIEN_SCHLAEGE[i];
}
function dingAus(text2, ausser = "") {
  const kandidaten = /* @__PURE__ */ new Map();
  const re = /\b([Ee]in|[Ee]ine|[Ee]inen|[Ee]inem|[Ee]iner|[Dd]er|[Dd]ie|[Dd]as|[Dd]en|[Dd]em)\s+(?:([a-zäöüß]{3,}(?:e|en|er|es|em))\s+)?([A-ZÄÖÜ][a-zäöüß]{3,})\b/g;
  let m;
  while (m = re.exec(text2)) {
    const art = m[1].toLowerCase(), adj = m[2] || "", nomen = m[3];
    const ausserNomen = (ausser.match(/[A-ZÄÖÜ][a-zäöüß]+$/) || [ausser])[0].toLowerCase();
    if (FUNKTION.has(nomen.toLowerCase()) || nomen.toLowerCase() === ausserNomen) continue;
    const g = guessGender(nomen);
    if (!g) continue;
    const nomArt = art.startsWith("ein") ? g === "f" ? "eine" : "ein" : g === "m" ? "der" : g === "f" ? "die" : "das";
    let nomAdj = adj;
    if (adj) {
      const st = adj.replace(/(e|en|er|es|em)$/, "");
      nomAdj = st + (nomArt.startsWith("ein") ? g === "m" ? "er" : g === "f" ? "e" : "es" : "e");
    }
    const np = `${nomArt} ${nomAdj ? nomAdj + " " : ""}${nomen}`;
    const k = nomen.toLowerCase();
    const e = kandidaten.get(k);
    if (e) {
      e.n++;
      if (art.startsWith("ein")) e.unbestimmt = true;
    } else kandidaten.set(k, { np, n: 1, unbestimmt: art.startsWith("ein") });
  }
  const liste = [...kandidaten.values()].sort((a, b) => b.n - a.n || Number(b.unbestimmt) - Number(a.unbestimmt));
  return liste[0]?.np || "";
}
function frageAus(text2, ding) {
  const s = splitSentences(text2.replace(/\n+/g, " "));
  const fragen = s.filter((x) => /\?$/.test(x.trim()));
  if (fragen.length) return fragen[fragen.length - 1].trim();
  const einsatz = [...s].reverse().find((x) => /^(Es geht um|Der Einsatz ist|Auf dem Spiel steht|Alles dreht sich um|Was zählt, ist)\b/i.test(x));
  if (einsatz) {
    const kern2 = einsatz.replace(/^(Es geht um|Der Einsatz ist|Auf dem Spiel steht|Alles dreht sich um|Was zählt, ist)\s*/i, "").replace(/[.!…]+$/, "").replace(/^(eines|eins):\s*/i, "");
    if (kern2) return `Was wird aus ${kern2}?`;
  }
  if (ding) return `Wer hat ${ding.replace(/^(der|ein)\s/, "den ").replace(/^die\s/, "die ").replace(/^das\s/, "das ").replace(/^eine\s/, "eine ")} zur\xFCckgelassen?`;
  return "Was bleibt?";
}
function fadenAus(text2, figur, titel, bisher) {
  const s = splitSentences(text2.replace(/\n+/g, " "));
  const letzter = (s[s.length - 1] || "").trim();
  const ding = bisher?.ding || dingAus(text2, figur);
  return {
    aktiv: true,
    serie: bisher?.serie || titel || (s[0] || "Serie").slice(0, 40),
    figur: bisher?.figur || figur,
    ding,
    frage: frageAus(text2, ding),
    letzterSatz: letzter,
    folge: (bisher?.folge || 1) + 1,
    laenge: bisher?.laenge || SERIEN_LAENGE,
    bauform: bisher?.bauform || "standard"
  };
}
function dingSatz(ding, rnd = Math.random) {
  const d = ding.charAt(0).toUpperCase() + ding.slice(1);
  const formen = [
    `${d} liegt hier, als w\xE4re es nie fort gewesen.`,
    `${d} ist mitgekommen, ohne dass jemand es getragen h\xE4tte.`,
    `Auf dem Tisch: ${ding}, k\xE4lter als gestern.`,
    `${d} \u2014 noch immer, an einem Ort, der es nicht kennt.`
  ];
  return formen[Math.floor(rnd() * formen.length)];
}
function fadenstaerke(vorher, nachher, f, dingHingelegt = false) {
  const nach = nachher.replace(/\n+/g, " ");
  const nachLow = nach.toLowerCase();
  const dingStamm = (f.ding.match(/[A-ZÄÖÜ][a-zäöüß]{3,}/) || [""])[0].toLowerCase().slice(0, 5);
  const dingDa = !!dingStamm && nachLow.includes(dingStamm);
  const ding = !dingDa ? "fehlt" : dingHingelegt ? "hingelegt" : "natuerlich";
  const figurWort = (f.figur.match(/[A-ZÄÖÜ][a-zäöüß]{2,}$/) || [f.figur.split(/\s+/).pop() || ""])[0].toLowerCase();
  const figur = !!figurWort && figurWort.length >= 3 && nachLow.includes(figurWort);
  const frageWoerter = (f.frage.toLowerCase().match(/[a-zäöüß]{5,}/g) || []).filter((w) => !FRAGEWORT.has(w)).map((w) => w.slice(0, 5));
  const frage = frageWoerter.some((w) => nachLow.includes(w));
  const saetze = splitSentences(nach);
  const erstesDrittel = saetze.slice(0, Math.max(1, Math.ceil(saetze.length / 3))).join(" ");
  const echo = [...kern(f.letzterSatz)].some((k) => erstesDrittel.toLowerCase().includes(k));
  const vorherSaetze = new Set(splitSentences(vorher.replace(/\n+/g, " ")).map((x) => x.toLowerCase().replace(/[^a-zäöüß ]/g, "").trim()));
  const neu = saetze.filter((x) => !vorherSaetze.has(x.toLowerCase().replace(/[^a-zäöüß ]/g, "").trim()));
  const neuheit = saetze.length ? neu.length / saetze.length : 1;
  const punkte = (ding !== "fehlt" ? 1 : 0) + (figur ? 1 : 0) + (frage ? 1 : 0) + (echo ? 1 : 0);
  const zusammenhang = Math.min(2, punkte) + (punkte >= 3 ? 0.5 : 0) + (ding === "natuerlich" ? 0.5 : 0);
  const wert = zusammenhang + 2 * neuheit;
  return { ding, figur, frage, echo, neuheit, punkte, wert };
}
function fadenBeschreibung(s) {
  const kugeln = "\u25CF".repeat(s.punkte) + "\u25CB".repeat(4 - s.punkte);
  const teile = [
    s.ding === "natuerlich" ? "Ding im Text" : s.ding === "hingelegt" ? "Ding hingelegt" : "Ding fehlt",
    s.figur ? "Figur handelt" : "Figur fehlt",
    s.frage ? "Frage aufgenommen" : "Frage nicht aufgenommen",
    s.echo ? "Echo \xFCber die Naht" : "kein Echo \xFCber die Naht"
  ];
  return `Faden: ${kugeln} \u2014 ${teile.join(", ")} \xB7 Neuheit ${Math.round(s.neuheit * 100)} %`;
}
var KEY, SERIEN_LAENGE, SERIEN_SCHLAEGE, BAUFORM_JE_SCHLAG, SCHLAG_NAME, FUNKTION, st5, kern, FRAGEWORT;
var init_faden = __esm({
  "src/features/faden.ts"() {
    "use strict";
    init_text_utils();
    init_declension();
    KEY = "dm_faden_v1";
    SERIEN_LAENGE = 5;
    SERIEN_SCHLAEGE = ["einstieg", "konflikt", "wende", "hoehepunkt", "schluss"];
    BAUFORM_JE_SCHLAG = { einstieg: "standard", konflikt: "retardation", wende: "doppelt", hoehepunkt: "katastrophe", schluss: "kreis" };
    SCHLAG_NAME = { einstieg: "Einstieg", konflikt: "Konflikt", wende: "Wende", hoehepunkt: "H\xF6hepunkt", schluss: "Schluss" };
    FUNKTION = /* @__PURE__ */ new Set(["der", "die", "das", "ein", "eine", "einen", "einem", "einer", "dem", "den", "des", "und", "oder", "aber", "nicht", "kein", "keine", "sich", "ihm", "ihr", "ihn"]);
    st5 = (t) => new Set((t.toLowerCase().match(/[a-zäöüß]{5,}/g) || []).map((x) => x.slice(0, 5)));
    kern = (t) => new Set((t.match(/[A-ZÄÖÜ][a-zäöüß]{4,}/g) || []).map((x) => x.toLowerCase().slice(0, 5)));
    FRAGEWORT = /* @__PURE__ */ new Set(["was", "wer", "wird", "hat", "bleibt", "kommt", "geht", "aus", "den", "die", "der", "das", "dem", "ein", "eine", "einen", "und", "oder", "nicht", "niemand", "noch", "zur\xFCck", "gelassen", "zur\xFCckgelassen"]);
  }
});

// test/faden.ts
var import_jsdom = require("jsdom");
var import_fs = require("fs");
init_faden();
var dom = new import_jsdom.JSDOM("<!doctype html><html><body></body></html>", { url: "https://x.test/" });
globalThis.localStorage = dom.window.localStorage;
var fails = [];
var geprueft = 0;
var bestanden = 0;
var ist = (name, wert, soll) => {
  geprueft++;
  if (wert === soll) bestanden++;
  else fails.push(`${name}: \u201E${String(wert)}\u201C \u2014 erwartet \u201E${String(soll)}\u201C`);
};
var wahr = (name, b, zusatz = "") => ist(name + (zusatz ? ` (${zusatz})` : ""), b, true);
var text = "Der Bote h\xF6rt die Glocke im Hafen. Ein Schl\xFCssel liegt auf dem Tisch, und niemand nimmt ihn. Die Glocke schweigt. Es geht um den Schl\xFCssel, den niemand nimmt. Der Bote wartet, wie man an einem Ort wartet, der einen vergessen hat.";
ist("das Ding: die Nominalphrase, die mehrfach tr\xE4gt (Nominativ)", dingAus(text, "Bote"), "ein Schl\xFCssel");
ist("die Frage aus dem Einsatz", frageAus(text, "ein Schl\xFCssel"), "Was wird aus den Schl\xFCssel, den niemand nimmt?".replace("den Schl\xFCssel", "den Schl\xFCssel"));
ist("ein Fragesatz im Text hat Vorrang", frageAus("Alles still. Wer hat den Zug bestellt? Danach nichts.", ""), "Wer hat den Zug bestellt?");
wahr("ohne Einsatz: eine Frage aus dem Ding", /^Wer hat .* zurückgelassen\?$/.test(frageAus("Alles still. Danach nichts.", "ein Schl\xFCssel")));
speichereFaden(null);
ist("ohne Faden: null", ladeFaden(), null);
var f1 = fadenAus(text, "Der Bote", "Die Glocke im Hafen", null);
ist("Folge 2 ist die n\xE4chste", f1.folge, 2);
ist("die Figur bleibt", f1.figur, "Der Bote");
ist("der letzte Satz wird zum Bisher", f1.letzterSatz, "Der Bote wartet, wie man an einem Ort wartet, der einen vergessen hat.");
speichereFaden(f1);
var f2 = fadenAus("Ein anderer Ort. Der Bote findet nichts. Und du?", "Egal", "Egal", ladeFaden());
ist("weitergesponnen: Folge 3, Figur und Ding bleiben, Serie bleibt", `${f2.folge}|${f2.figur}|${f2.ding}|${f2.serie}`, "3|Der Bote|ein Schl\xFCssel|Die Glocke im Hafen");
ist("\u2026 die Frage ist die neue", f2.frage, "Und du?");
ist("Folge 1 = Einstieg", schlagDerFolge(1), "einstieg");
ist("Folge 3 von 5 = Wende", schlagDerFolge(3), "wende");
ist("Folge 5 = Schluss", schlagDerFolge(5), "schluss");
ist("Folge 2 von 3 = Wende (Mitte)", schlagDerFolge(2, 3), "wende");
ist("jede Bauform ist gesetzt", Object.keys(BAUFORM_JE_SCHLAG).length, 5);
wahr("der Ding-Satz tr\xE4gt das Ding", /Schlüssel/.test(dingSatz("ein Schl\xFCssel", () => 0.1)));
ist("Serienl\xE4nge f\xFCnf", SERIEN_LAENGE, 5);
{
  const q = (0, import_fs.readFileSync)("src/ui/studio.ts", "utf8");
  wahr("Knopf \u201EFortsetzung\u201C neben Behalten", /" Fortsetzung"\)/.test(q) && /keepBtn, fadenBtn, fadenLoesen,/.test(q));
  wahr("er legt die vorige Folge in die Schatzkammer (Serie, Folge)", /serie: f\.serie, folge: String\(f\.folge - 1\)/.test(q));
  wahr("w\xFCrfelt alles au\xDFer der Figur, setzt Wer und Was aus dem Faden", /who\.value = f\.figur;\s*\n\s*what\.value = f\.frage;/.test(q) && /rollPresets\(\);\s*\n\s*rolling = false;\s*\n\s*who\.value = f\.figur/.test(q));
  wahr("die Bauform folgt dem Schlag der Folge \u2014 als Merker, den generate() nach der Weiche anwendet", /folgeBauform = SCHLAGFOLGEN\[BAUFORM_JE_SCHLAG\[schlag\]\]!\.folge;/.test(q) && /if \(folgeBauform\) \{ const basisF = loadDramaData\(\); if \(basisF\) setBogenOverride\(\{ \.\.\.basisF, folge: folgeBauform/.test(q));
  wahr("Titel \u201EFolge n \xB7 Schlag\u201C und Bisher-Zeile", /fadenKopf = `Folge \$\{f\.folge\} · \$\{SCHLAG_NAME\[schlag\]\}`/.test(q) && /bisherEl\.textContent = `Bisher: \$\{f\.letzterSatz\}`/.test(q));
  wahr("das Ding kommt in die Folge, wenn der Text es nicht tr\xE4gt", /s\.splice\(at, 0, dingSatz\(f\.ding\)\)/.test(q));
  wahr("\u201EFaden l\xF6sen\u201C beendet die Serie", /speichereFaden\(null\); fadenKopf = ""/.test(q));
}
{
  const { fadenstaerke: fadenstaerke2, fadenBeschreibung: fadenBeschreibung2 } = (init_faden(), __toCommonJS(faden_exports));
  const f = { figur: "Der Bote", ding: "ein Schl\xFCssel", frage: "Was wird aus dem Schl\xFCssel, den niemand nimmt?", letzterSatz: "Der Bote wartet an der Glocke." };
  const vor = "Der Bote h\xF6rt die Glocke. Ein Schl\xFCssel liegt auf dem Tisch. Der Bote wartet an der Glocke.";
  const gut = "Die Glocke schl\xE4gt in Ost-Berlin. Der Bote findet den Schl\xFCssel im Fluss, und niemand nimmt ihn. Ein Zug f\xE4hrt ein. Der Bahnsteig atmet Beton.";
  const s1 = fadenstaerke2(vor, gut, f);
  ist("gutes Glied: Ding im Text, Figur, Frage, Echo", `${s1.ding}|${s1.figur}|${s1.frage}|${s1.echo}`, "natuerlich|true|true|true");
  wahr("volle Neuheit", s1.neuheit === 1);
  const schwach = "Ein Regen f\xE4llt. Niemand kommt. Die Stadt schl\xE4ft. Ein Fenster ohne Glas.";
  const s2 = fadenstaerke2(vor, schwach, f);
  ist("schwaches Glied: nichts tr\xE4gt", s2.punkte, 0);
  wahr("der gute Kandidat gewinnt die Auslese", s1.wert > s2.wert);
  const kopie = "Der Bote h\xF6rt die Glocke. Ein Schl\xFCssel liegt auf dem Tisch. Der Bote wartet an der Glocke.";
  const s3 = fadenstaerke2(vor, kopie, f);
  wahr("eine Kopie der vorigen Folge hat Zusammenhang, aber keine Neuheit \u2014 und verliert gegen das gute Glied", s3.neuheit === 0 && s3.wert < s1.wert);
  const hingelegt = fadenstaerke2(vor, gut, f, true);
  wahr("ein hingelegtes Ding z\xE4hlt weniger als ein nat\xFCrliches", hingelegt.wert < s1.wert && hingelegt.ding === "hingelegt");
  wahr("die Schwelle: vier Punkte bringen nicht mehr als drei (ohne Ding-Bonus)", (() => {
    const drei = { ...s1, punkte: 3 };
    return s1.wert - 2 * s1.neuheit <= 3;
  })());
  wahr("die Beschreibung tr\xE4gt Kugeln und Gr\xFCnde", /^Faden: ●●●● — Ding im Text, Figur handelt, Frage aufgenommen, Echo über die Naht · Neuheit 100 %$/.test(fadenBeschreibung2(s1)));
  const q = (0, import_fs.readFileSync)("src/ui/studio.ts", "utf8");
  wahr("die Fortsetzung erzeugt drei Kandidaten und nimmt den mit der gr\xF6\xDFten Fadenst\xE4rke", /for \(let k = 0; k < 3; k\+\+\) \{\s*\n\s*generate\(\);/.test(q) && /if \(!bester \|\| st\.wert > bester\.st\.wert\) bester = \{ text: mitDing, st \};/.test(q));
  wahr("die Fadenzeile steht unter dem Titel", /fadenZeile\.textContent = letzteFadenstaerke \? fadenBeschreibung\(letzteFadenstaerke\) : ""/.test(q));
  wahr("\u201EBehalten\u201C merkt die letzte Folge mit ihrer eigenen Nummer (f.folge, nicht f.folge \u2212 1)", /const serienSet = f && fadenKopf \? \{ serie: f\.serie, folge: String\(f\.folge\)/.test(q) && /set: \{ \.\.\.einstellungen\(\), \.\.\.serienSet \}/.test(q));
  wahr("\u201EFortsetzung\u201C legt die vorige Folge mit f.folge \u2212 1 ab \u2014 der Faden z\xE4hlt die Folge im Fenster", /serie: f\.serie, folge: String\(f\.folge - 1\)/.test(q));
  const qt = (0, import_fs.readFileSync)("src/ui/treasuryView.ts", "utf8");
  wahr("die Schatzkammer zeigt Serie, Folge und Fadenst\xE4rke", /Serie „\$\{it\.set\.serie\}“ · Folge/.test(qt));
}
console.log(`Pr\xFCfstand Faden \u2014 ${geprueft} Pr\xFCfungen, ${bestanden} bestanden`);
var proc = globalThis;
if (fails.length) {
  console.error(`
\u274C Faden: ${fails.length} Fehler:`);
  fails.forEach((f) => console.error("  - " + f));
  proc.process?.exit(1);
} else console.log(`
\u2705 Faden: alle ${geprueft} Pr\xFCfungen bestanden.`);
