"use strict";

// test/selbstreinigung.ts
var import_jsdom = require("jsdom");
var import_fs = require("fs");

// src/constants.ts
var STORAGE_CORPUS = "divergenz_persistent_corpus_v1";
var CORPUS_MAX = 16e4;

// src/text-utils.ts
function clean(s) {
  return (s ?? "").toString().trim().replace(/\s+/g, " ");
}

// src/features/storage-status.ts
function isQuotaError(e) {
  if (!(e instanceof DOMException)) return false;
  return e.name === "QuotaExceededError" || e.name === "NS_ERROR_DOM_QUOTA_REACHED" || e.code === 22 || e.code === 1014;
}
var banner = null;
function notifyStorageFull(where) {
  try {
    if (!banner) {
      banner = document.createElement("div");
      banner.setAttribute("role", "alert");
      banner.style.cssText = "position:fixed;left:0;right:0;top:0;z-index:9999;padding:10px 14px;background:#7f1d1d;color:#fff;font:14px/1.4 system-ui,sans-serif;display:flex;gap:12px;align-items:center;justify-content:center;box-shadow:0 2px 8px rgba(0,0,0,.4)";
      const x = document.createElement("button");
      x.textContent = "\u2715";
      x.style.cssText = "background:transparent;border:0;color:#fff;font-size:16px;cursor:pointer";
      x.addEventListener("click", () => {
        banner?.remove();
        banner = null;
      });
      const span = document.createElement("span");
      span.id = "storage-msg";
      banner.append(span, x);
      document.body.appendChild(banner);
    }
    const msg = banner.querySelector("#storage-msg");
    if (msg) msg.textContent = `Speicher voll \u2014 \u201E${where}" konnte nicht gesichert werden. Bitte Korpus k\xFCrzen, Schatzkammer aufr\xE4umen oder ein Projekt exportieren und Daten l\xF6schen.`;
  } catch {
  }
}
function safeSet(key, value, where) {
  try {
    localStorage.setItem(key, value);
    return true;
  } catch (e) {
    if (isQuotaError(e)) notifyStorageFull(where);
    return false;
  }
}

// src/generation/verblex.data.ts
var GRUND = `
achten \xE4chzen ahnen \xE4ndern \xE4rgern arbeiten atmen backen baden bangen bauen beben bedeuten beeilen befehlen beginnen begreifen
behalten bei\xDFen bellen bergen bersten beten betteln beugen bewegen biegen bieten bilden binden bitten blasen bleiben blenden blicken
blinken blinzeln blitzen bl\xFChen bluten bohren borgen brauchen brausen brechen bremsen brennen bringen br\xFCllen brummen buchen b\xFCcken
b\xFCgeln b\xFCrsten danken decken dehnen denken deuten dichten dienen d\xF6sen dr\xE4ngen drehen dreschen dringen drohen dr\xF6hnen drucken dr\xFCcken
dulden dunkeln d\xFCrfen duften d\xFCngen d\xFCnken durchqueren ebben ehren eignen eilen einen eitern ekeln enden entbehren entgleiten erben
erl\xF6schen ernten essen f\xE4cheln fahren fallen falten fangen fassen fasten fauchen fechten fegen fehlen feiern feilen feixen fesseln
feuern finden fischen flackern flattern flechten flehen flicken fliegen fliehen flie\xDFen flimmern flirren fl\xF6ten fluchen fluten
fl\xFCstern folgen fordern forschen fragen fressen freuen frieren f\xFCgen f\xFChlen f\xFChren f\xFCllen funkeln f\xFCrchten fu\xDFen g\xE4hnen g\xE4ren gaffen
geben gedeihen gehen gehorchen geh\xF6ren gelingen gelten genesen genie\xDFen geraten geschehen gewinnen gie\xDFen gl\xE4nzen glauben gleichen
gleiten glimmen glitzern gl\xFChen g\xF6nnen graben grasen greifen grinsen grollen gr\xFCbeln gr\xFCnen gr\xFC\xDFen gucken haben hacken haften hageln
haken hallen halten h\xE4mmern handeln h\xE4ngen harren hassen hasten hauchen hauen h\xE4ufen heben heften hegen heilen hei\xDFen heizen helfen
hemmen herrschen hetzen heulen hinken hocken hoffen holen horchen h\xF6ren huldigen h\xFCllen humpeln hungern hupen h\xFCpfen husten h\xFCten
irren jagen jammern jauchzen jubeln k\xE4mmen k\xE4mpfen kauen kaufen kehren keimen kennen kichern kippen kitzeln klagen klappen klappern
kl\xE4ren klatschen kleben kleiden klettern klingeln klingen klirren klopfen knabbern knacken knallen knarren kneifen kneten knicken
knien knirschen knistern kn\xFCpfen kochen kommen k\xF6nnen kosten krachen kr\xE4hen kr\xE4nken kratzen kreisen kreuzen kriechen kriegen
kritzeln kr\xFCmmen k\xFChlen k\xFCmmern k\xFCrzen k\xFCssen lachen laden lagern l\xE4hmen landen langen lassen lasten lauern laufen lauschen lauten
l\xE4uten leben lecken legen lehnen lehren leiden leihen leisten leiten lenken lernen lesen leuchten lieben liefern liegen lindern
loben locken lodern lohnen l\xF6schen l\xF6sen l\xFCgen lutschen machen mahlen mahnen malen mangeln meiden meinen melden melken merken messen
mischen missen m\xF6gen morden m\xFCssen munkeln murmeln nagen n\xE4hen nahen n\xE4hern n\xE4hren naschen necken nehmen neigen nennen nesteln
nicken nieseln nippen nisten n\xF6rgeln nutzen n\xFCtzen \xF6ffnen opfern ordnen packen passen pausieren peitschen pfeifen pflanzen pflegen
pfl\xFCcken picken plagen platzen plaudern pochen poltern pr\xE4gen prallen prangen prasseln predigen preisen pressen probieren pr\xFCfen
pr\xFCgeln pulsieren pumpen putzen qu\xE4len quellen quietschen raffen ragen rasen rasten raten rauben rauchen r\xE4umen rauschen rechnen
reden regen regnen reiben reichen reifen reihen reimen reisen rei\xDFen reiten rennen retten reuen richten riechen ringen rinnen
ritzen rollen rosten r\xFCcken rudern rufen ruhen r\xFChmen r\xFChren r\xFCtteln s\xE4en sagen sammeln s\xE4umen saugen s\xE4useln schaben schaffen
schallen schalten sch\xE4men scharren sch\xE4tzen schauen schaufeln schaukeln scheiden scheinen scheitern schellen schelten schenken
scheren scheuchen scheuen schicken schieben schielen schie\xDFen schildern schimmern schimpfen schinden schlafen schlagen schleichen
schleifen schleppen schleudern schlie\xDFen schlingen schlucken schl\xFCpfen schmecken schmeicheln schmelzen schmerzen schmieden
schmieren schm\xFCcken schmunzeln schnappen schnarchen schneiden schneien schn\xFCren schnuppern schonen sch\xF6pfen schrauben schreiben
schreien schreiten schrumpfen sch\xFCren sch\xFCrfen sch\xFCtteln sch\xFCtten sch\xFCtzen schwanken schw\xE4rmen schwatzen schweben schweifen
schweigen schwellen schwenken schwimmen schwinden schwingen schwitzen schw\xF6ren segeln segnen sehen sehnen seufzen sichern sichten
sickern sieden siegen singen sinken sinnen sitzen sollen sorgen sp\xE4hen spalten spannen sparen spazieren speien speisen spenden
sperren spielen spinnen spotten sprechen sprengen sprie\xDFen springen spritzen spr\xFChen spucken sp\xFClen sp\xFCren stammeln stammen
stampfen stapeln starren stauben staunen stechen stecken stehen stehlen steigen steinigen stellen sterben steuern sticken
stinken st\xF6hnen stolpern stopfen st\xF6ren sto\xDFen strahlen stranden streben strecken streichen streicheln streiten streuen
stricken str\xF6men st\xFCrmen st\xFCrzen stutzen st\xFCtzen suchen summen s\xFCndigen tadeln tagen tanken tanzen tappen tasten tauchen tauen
taugen taumeln tauschen t\xE4uschen teilen tilgen toben t\xF6nen tosen traben trachten tragen trampeln trauen trauern tr\xE4umen treffen
treiben trennen treten triefen trinken trocknen trommeln tropfen tr\xF6sten trotzen tr\xFCben tun t\xFCrmen \xFCben umarmen urteilen
vergessen verlieren verzeihen wachen wachsen wagen w\xE4hlen w\xE4hnen wahren w\xE4hren wandeln wandern wanken w\xE4rmen warnen warten waschen
weben wechseln wecken wehen wehren weichen weiden weigern weihen weilen weinen weisen weiten welken wenden werben werden werfen
werken wetten wickeln widmen wiegen wimmeln wimmern winden winken wirbeln wirken wischen wissen wittern wohnen w\xF6lben wollen
wuchern w\xFChlen wundern w\xFCnschen w\xFCrdigen w\xFCrgen w\xFCrzen zagen zahlen z\xE4hlen z\xE4hmen zaubern zaudern zausen zehren zeichnen zeigen
zerren zeugen ziehen zielen ziemen zieren zischen zittern z\xF6gern zucken zupfen zw\xE4ngen zweifeln zwingen zwinkern zwitschern
adeln \xE4hneln akzeptieren analysieren antworten applaudieren beantworten begegnen begleiten behaupten beobachten berichten
ber\xFChren beschreiben besitzen bestimmen besuchen betrachten betreten beweisen bezahlen br\xFCten datieren definieren diskutieren
d\xE4mmern d\xE4mpfen dampfen detonieren donnern duschen entdecken entscheiden entschuldigen entwickeln erinnern erkennen erkl\xE4ren
erlauben erleben erreichen erschrecken erwarten erz\xE4hlen existieren fabrizieren fasziniert funktionieren garantieren geb\xE4ren
gefallen gen\xFCgen geschehen gestalten gew\xF6hnen glitschen h\xE4mmern handeln heiraten hindern ignorieren informieren interessieren
kapitulieren kentern klettern kombinieren kontrollieren korrigieren kosten kreisen k\xFCrzen leiden lodern markieren marschieren
meistern montieren murren musizieren notieren n\xF6tigen operieren organisieren passieren pilgern planen pl\xFCndern posieren
probieren produzieren protestieren protokollieren rasieren reagieren regieren reparieren respektieren riskieren rotieren
schmei\xDFen schmettern schnattern sortieren spekulieren studieren telefonieren transportieren trainieren trauen tr\xF6deln
\xFCberlegen verabschieden ver\xE4ndern verbergen verbinden verbrennen verdienen verfolgen verhalten verhandeln verkaufen verlangen
verlassen vermeiden vermuten verraten versagen verschieben verschwinden versichern versprechen verstecken verstehen versuchen
verteidigen vertrauen verwalten verwandeln verweigern verwenden verzichten vollenden wackeln wandeln weinen wirbeln zerbrechen
zerst\xF6ren z\xF6gern zurechtkommen zweifeln
stimmen passen setzen dauern l\xF6sen l\xE4cheln k\xFCndigen retten ticken z\xFCnden siegeln entfernen verl\xE4ngern verstummen beschriften
gabeln erledigen bewilligen best\xE4tigen sichern lohnen stauen stocken t\xF6nen tr\xFCben w\xE4hnen zerren fehlen kosten sparen sperren
st\xFCrzen stapeln stehlen schweigen taumeln t\xF6ten trocknen tr\xF6pfeln \xFCbergehen verschlie\xDFen vertreten verwahren verwirren vollziehen
wachsen wandern weichen wirken wurzeln zerfallen zerflie\xDFen zergehen zerrei\xDFen zerschlagen zersplittern zischen
regeln spiegeln speichern beschleunigen senken f\xE4rben formen altern riegeln fiebern schlitzen rutschen beanstanden erg\xE4nzen
bl\xE4ttern sanden schulden bessern bremsen dunkeln d\xFCstern erkennen ernennen f\xE4rben festigen filtern fl\xFCchten fr\xF6nen g\xE4hnen
h\xE4uten heilen hetzen k\xE4mmen klammern klemmen kneten kramen kr\xE4nkeln kr\xE4useln lasten leimen l\xFCften mildern mustern nachten
n\xE4ssen nieten \xF6len pinseln pl\xE4tschern polstern prallen prunken quirlen r\xE4dern reifen richten r\xF6cheln r\xFCtteln s\xE4ubern salzen
s\xE4umen sch\xE4tzen schaudern schl\xE4ngeln schleimen schlummern schmoren schn\xFCffeln schrubben schw\xE4chen schwelen sengen sondern
spalten spiegeln spitzen sprudeln stauben steuern stochern strampeln streifen striegeln stumpfen sudeln tauen tigern tippen
trampeln t\xFCnchen wabern watscheln wetzen wiehern winseln wispern wittern wuchten zerknittern zetern zieren zittern zotteln zuckeln
abh\xE4ngen ankommen anfangen aufstehen ausgehen bedienen befreien behandeln bemerken benennen beschlie\xDFen bestehen betonen bewahren
bezeichnen bilden bluten br\xFCten b\xFC\xDFen d\xE4mmern deuten drehen ehren einigen empfangen empfehlen entfalten enthalten entlassen entstehen
erfahren erfinden ergeben erhalten erheben erholen erl\xF6sen ermahnen ern\xE4hren er\xF6ffnen erregen ersch\xF6pfen ersticken erstarren erw\xE4hnen
erweitern erzeugen fesseln fl\xFCchten fr\xF6steln funken gebieten gedenken gelangen gemahnen geraten gestehen gew\xE4hren graben grenzen
gr\xFCbeln hadern harken hausen heben herrschen hindern huschen j\xE4ten jucken keuchen klaffen kleckern klimpern knallen kraulen kreischen
kringeln kritzeln kr\xF6nen kuscheln l\xE4rmen leuchten lichten lispeln lugen lungern m\xE4\xDFigen mei\xDFeln mieten mindern m\xFChen murksen nachahmen
nagen n\xE4seln n\xF6rgeln nuscheln pachten pflastern pieksen plappern prahlen prangen prellen prosten quaken qualmen r\xE4uspern rauen r\xE4umen
reizen rieseln rodeln r\xF6hren rumpeln s\xE4beln s\xE4ckeln s\xE4gen sausen sch\xE4umen sch\xE4len schaufeln schnalzen schnaufen schnellen schnippen
schwappen schwirren seihen sichten siezen sinnieren spannen spenden spicken spie\xDFen sprenkeln spuken st\xE4nkern stelzen stemmen sticheln
st\xF6bern stopfen strapazieren strotzen st\xFClpen stutzen t\xE4ndeln taxieren tollen torkeln tr\xE4llern trudeln tuscheln umgarnen verharren
wabbeln walzen wedeln weilen wetteifern wimmeln wringen wuseln zappeln zaubern zechen zergehen zerkn\xFCllen zerlegen zerm\xFCrben zerpfl\xFCcken
zerschellen zertr\xFCmmern zeugen zirpen zocken zurren
`;
var VERB_INFINITIVE = new Set(GRUND.split(/\s+/).map((w) => w.trim()).filter((w) => w.length > 2));

// src/generation/nouns.data.ts
var NOUN_GENDER = {
  "abdruck": "m",
  "abend": "m",
  "abgrund": "m",
  "absatz": "m",
  "abschalten": "n",
  "abstand": "m",
  "acker": "m",
  "ader": "f",
  "adressbuch": "n",
  "adresse": "f",
  "ahnung": "f",
  "airpod": "m",
  "akku": "m",
  "akte": "f",
  "aktendeckel": "m",
  "aktennotiz": "f",
  "allee": "f",
  "alptraum": "m",
  "altar": "m",
  "alte": "f",
  "alter": "n",
  "amt": "n",
  "amulett": "n",
  "angebot": "n",
  "angst": "f",
  "anker": "m",
  "antenne": "f",
  "antrag": "m",
  "antwort": "f",
  "apfel": "m",
  "applaus": "m",
  "archiv": "n",
  "arm": "m",
  "armband": "n",
  "armbrust": "f",
  "art": "f",
  "arzt": "m",
  "asche": "f",
  "ast": "m",
  "atelier": "n",
  "atem": "m",
  "atmosph\xE4re": "f",
  "aufkleber": "m",
  "aufnahme": "f",
  "auftrag": "m",
  "auge": "n",
  "augenblick": "m",
  "augenlid": "n",
  "ausdehnung": "f",
  "ausgang": "m",
  "ausnahme": "f",
  "ausrede": "f",
  "ausweis": "m",
  "axiom": "n",
  "baby": "n",
  "bach": "m",
  "backup": "n",
  "badeanstalt": "f",
  "bahn": "f",
  "bahnkarte": "f",
  "balkon": "m",
  "ball": "m",
  "ballade": "f",
  "band": "n",
  "bank": "f",
  "banner": "n",
  "basecap": "n",
  "bau": "m",
  "bauch": "m",
  "bauer": "m",
  "baum": "m",
  "becher": "m",
  "befehl": "m",
  "begriff": "m",
  "beil": "n",
  "bein": "n",
  "benachrichtigung": "f",
  "berg": "m",
  "bergfried": "m",
  "bericht": "m",
  "bescheid": "m",
  "beschluss": "m",
  "besen": "m",
  "besitz": "m",
  "bestand": "m",
  "besuch": "m",
  "betonprobe": "f",
  "bett": "n",
  "beutel": "m",
  "beweis": "m",
  "bibel": "f",
  "bibliothek": "f",
  "biene": "f",
  "bild": "n",
  "bildschirm": "m",
  "binde": "f",
  "birne": "f",
  "blatt": "n",
  "blechb\xFCchse": "f",
  "blechdose": "f",
  "blechkanne": "f",
  "blechtrompete": "f",
  "blei": "n",
  "bleistift": "m",
  "blende": "f",
  "blick": "m",
  "blitz": "m",
  "blume": "f",
  "blumenstrau\xDF": "m",
  "bluse": "f",
  "bl\xFCte": "f",
  "boden": "m",
  "bohne": "f",
  "bohrkern": "m",
  "bohrprobe": "f",
  "boje": "f",
  "bonbon": "n",
  "boot": "n",
  "bote": "m",
  "botschaft": "f",
  "braten": "m",
  "braue": "f",
  "brett": "n",
  "brief": "m",
  "briefumschlag": "m",
  "brille": "f",
  "brot": "n",
  "brotdose": "f",
  "brotlaib": "m",
  "bruch": "m",
  "bruder": "m",
  "brunnen": "m",
  "brust": "f",
  "br\xFCcke": "f",
  "br\xFChe": "f",
  "buch": "n",
  "buchstabe": "m",
  "bucht": "f",
  "bug": "m",
  "burg": "f",
  "bus": "m",
  "busch": "m",
  "butter": "f",
  "b\xE4r": "m",
  "b\xFChne": "f",
  "b\xFCndel": "n",
  "b\xFCrde": "f",
  "cache": "m",
  "cadtablet": "n",
  "caf": "n",
  "caf\xE9": "n",
  "chat": "m",
  "clown": "m",
  "computer": "m",
  "container": "m",
  "couch": "f",
  "dach": "n",
  "dachboden": "m",
  "dame": "f",
  "damm": "m",
  "dashboard": "n",
  "datei": "f",
  "dattel": "f",
  "datum": "n",
  "daumen": "m",
  "deck": "n",
  "decke": "f",
  "deckel": "m",
  "denkmalschutz": "m",
  "deo": "n",
  "detail": "n",
  "detektor": "m",
  "detektorkopf": "m",
  "dewar": "m",
  "diagramm": "n",
  "dichter": "m",
  "dieb": "m",
  "dienst": "m",
  "direktor": "m",
  "dnaspirale": "f",
  "dokument": "n",
  "dolch": "m",
  "donner": "m",
  "dorf": "n",
  "dorn": "m",
  "dose": "f",
  "draht": "m",
  "droschke": "f",
  "druck": "m",
  "duell": "n",
  "duft": "m",
  "durchsage": "f",
  "durchschlag": "m",
  "d\xE4mmerung": "f",
  "ebbe": "f",
  "ebene": "f",
  "echo": "n",
  "ecke": "f",
  "ehre": "f",
  "ei": "n",
  "eid": "m",
  "einspruch": "m",
  "eis": "n",
  "eisen": "n",
  "elch": "m",
  "elend": "n",
  "ellbogen": "m",
  "emoji": "n",
  "engel": "m",
  "enkel": "m",
  "ente": "f",
  "entwurf": "m",
  "ephemeride": "f",
  "erbe": "n",
  "erbse": "f",
  "erdbeben": "n",
  "erde": "f",
  "erinnerung": "f",
  "etikett": "n",
  "eule": "f",
  "ewigkeit": "f",
  "fabel": "f",
  "fabrik": "f",
  "fackel": "f",
  "faden": "m",
  "fahne": "f",
  "fahrschein": "m",
  "fahrt": "f",
  "falle": "f",
  "falte": "f",
  "farbe": "f",
  "farbenscheibe": "f",
  "fass": "n",
  "faust": "f",
  "feder": "f",
  "federkiel": "m",
  "fee": "f",
  "fehlercode": "m",
  "feile": "f",
  "feind": "m",
  "feld": "n",
  "feldbesteck": "n",
  "felder": "n",
  "fell": "n",
  "fellhandschuh": "m",
  "fels": "m",
  "felsen": "m",
  "fenster": "n",
  "fensterplatz": "m",
  "ferkel": "n",
  "ferne": "f",
  "fernglas": "n",
  "fernrohr": "n",
  "ferse": "f",
  "fessel": "f",
  "festung": "f",
  "feuer": "n",
  "feuerzeug": "n",
  "fibel": "f",
  "fieber": "n",
  "filter": "m",
  "finger": "m",
  "fingerhut": "m",
  "fisch": "m",
  "fischer": "m",
  "flakon": "m",
  "flasche": "f",
  "flaute": "f",
  "fleisch": "n",
  "fliege": "f",
  "flo\xDF": "n",
  "fluch": "m",
  "flucht": "f",
  "flur": "m",
  "fluss": "m",
  "flut": "f",
  "fl\xE4che": "f",
  "fl\xF6te": "f",
  "fl\xFCstern": "n",
  "formel": "f",
  "formular": "n",
  "fossil": "n",
  "fossilie": "f",
  "foto": "n",
  "fotografie": "f",
  "frachtbrief": "m",
  "frage": "f",
  "frau": "f",
  "freude": "f",
  "freund": "m",
  "frist": "f",
  "frost": "m",
  "frucht": "f",
  "fr\xFChling": "m",
  "fuchs": "m",
  "fuge": "f",
  "fund": "m",
  "fundament": "n",
  "funke": "m",
  "funkger\xE4t": "n",
  "furcht": "f",
  "furt": "f",
  "fu\xDF": "m",
  "f\xE4hrmann": "m",
  "f\xE4hrplan": "m",
  "f\xE4sser": "n",
  "f\xFCrst": "m",
  "gabe": "f",
  "gabel": "f",
  "gabelung": "f",
  "galaxie": "f",
  "gang": "m",
  "gans": "f",
  "garn": "n",
  "garten": "m",
  "gasse": "f",
  "gast": "m",
  "gebet": "n",
  "gebetbuch": "n",
  "gebete": "n",
  "gebetsschale": "f",
  "gebirge": "n",
  "geb\xE4lk": "n",
  "geb\xE4ude": "n",
  "gedanke": "m",
  "gedanken": "m",
  "gedicht": "n",
  "gedichte": "n",
  "geduld": "f",
  "gefahr": "f",
  "gef\xFChl": "n",
  "gef\xFChlen": "n",
  "gegend": "f",
  "gegensatz": "m",
  "gegenstand": "m",
  "gegens\xE4tze": "m",
  "gegenteil": "n",
  "gegenwart": "f",
  "gegners": "m",
  "geheimnis": "n",
  "gehirn": "n",
  "geh\xE4use": "n",
  "geige": "f",
  "geist": "m",
  "geleitbrief": "m",
  "gel\xE4nde": "n",
  "gel\xFCbde": "n",
  "gemach": "n",
  "gem\xE4lde": "n",
  "gem\xFCse": "n",
  "gep\xE4ck": "n",
  "gericht": "n",
  "geruch": "m",
  "ger\xE4t": "n",
  "ger\xE4usch": "n",
  "ger\xE4usche": "n",
  "ger\xF6ll": "n",
  "ger\xFCcht": "n",
  "ger\xFCchte": "n",
  "ger\xFCst": "n",
  "gesangbuch": "n",
  "geschenk": "n",
  "geschichte": "f",
  "geschichten": "f",
  "geschmack": "m",
  "gesetz": "n",
  "gesetze": "n",
  "gesetzen": "n",
  "gesetzes": "n",
  "gesetzestext": "m",
  "gesicht": "n",
  "gesichter": "n",
  "gespr\xE4ch": "n",
  "gestalt": "f",
  "gestalten": "f",
  "geste": "f",
  "gestein": "n",
  "gesteinsschichten": "f",
  "getreide": "n",
  "getreidek\xF6rner": "n",
  "gewand": "n",
  "gewebe": "n",
  "gewehr": "n",
  "gewehre": "n",
  "geweih": "n",
  "gewicht": "n",
  "gewichte": "n",
  "gewissen": "n",
  "gew\xF6lbe": "n",
  "gezeiten": "f",
  "gier": "f",
  "gie\xDFkanne": "f",
  "gift": "n",
  "gipfel": "m",
  "gitter": "n",
  "glas": "n",
  "glasplatte": "f",
  "glaube": "m",
  "gleichung": "f",
  "gletscher": "m",
  "glocke": "f",
  "gl\xFCck": "n",
  "gold": "n",
  "gott": "m",
  "grab": "n",
  "graben": "m",
  "granitblock": "m",
  "grenze": "f",
  "grotte": "f",
  "grund": "m",
  "grundrissplan": "m",
  "gruppe": "f",
  "gruppenchat": "m",
  "gurke": "f",
  "g\xF6tter": "m",
  "g\xF6ttin": "f",
  "g\xFCrtel": "m",
  "haar": "n",
  "haarnadel": "f",
  "hafen": "m",
  "hagel": "m",
  "hahn": "m",
  "hain": "m",
  "haken": "m",
  "halde": "f",
  "hall": "m",
  "halle": "f",
  "hals": "m",
  "halter": "m",
  "hammer": "m",
  "hand": "f",
  "handbuch": "n",
  "handkarren": "m",
  "handschuh": "m",
  "handschuhspitze": "f",
  "handvoll": "f",
  "handy": "n",
  "hang": "m",
  "harfe": "f",
  "harpune": "f",
  "hase": "m",
  "hass": "m",
  "haus": "n",
  "haut": "f",
  "hecke": "f",
  "heft": "n",
  "held": "m",
  "helm": "m",
  "hemd": "n",
  "henne": "f",
  "herbst": "m",
  "herd": "m",
  "herr": "m",
  "herrscherstab": "m",
  "herz": "n",
  "herzschlag": "m",
  "heuer": "f",
  "hexe": "f",
  "hierarchie": "f",
  "himmel": "m",
  "hintergrund": "m",
  "hintert\xFCr": "f",
  "hirn": "n",
  "hirsch": "m",
  "hirtenstab": "m",
  "hof": "m",
  "hoffnung": "f",
  "holz": "n",
  "honig": "m",
  "hoodie": "m",
  "horn": "n",
  "hose": "f",
  "huhn": "n",
  "hund": "m",
  "hut": "m",
  "h\xE4user": "n",
  "h\xF6henmesser": "m",
  "h\xF6hle": "f",
  "h\xFCfte": "f",
  "h\xFCgel": "m",
  "h\xFCtte": "f",
  "igel": "m",
  "index": "m",
  "insekt": "n",
  "insel": "f",
  "instanz": "f",
  "instastory": "f",
  "instrument": "n",
  "interferometer": "n",
  "jacke": "f",
  "jazz": "m",
  "junge": "m",
  "justiergewicht": "n",
  "j\xE4ger": "m",
  "kabel": "n",
  "kaffee": "m",
  "kai": "m",
  "kaiser": "m",
  "kalb": "n",
  "kalender": "m",
  "kamin": "m",
  "kaminfeuer": "n",
  "kammer": "f",
  "kampf": "m",
  "kanal": "m",
  "kaninchen": "n",
  "kanister": "m",
  "kanne": "f",
  "kanten": "m",
  "kapelle": "f",
  "kapit\xE4n": "m",
  "karawane": "f",
  "karotte": "f",
  "karte": "f",
  "karteikarte": "f",
  "kartoffel": "f",
  "kassenbuch": "n",
  "kathedrale": "f",
  "katze": "f",
  "kaugummi": "m",
  "kehle": "f",
  "kelch": "m",
  "kelle": "f",
  "keller": "m",
  "kerze": "f",
  "kessel": "m",
  "kette": "f",
  "kettenhemd": "n",
  "kiefer": "m",
  "kiel": "m",
  "kies": "m",
  "kilometer": "m",
  "kind": "n",
  "kinder": "n",
  "kinderspielzeug": "n",
  "kinn": "n",
  "kirche": "f",
  "kirsche": "f",
  "kissen": "n",
  "kiste": "f",
  "klammer": "f",
  "klang": "m",
  "klaue": "f",
  "klavier": "n",
  "kleid": "n",
  "kleidersack": "m",
  "kleingeldfach": "n",
  "kleinod": "n",
  "klinge": "f",
  "klingel": "f",
  "klippe": "f",
  "klopfen": "n",
  "knabe": "m",
  "knie": "n",
  "knochen": "m",
  "knopf": "m",
  "knospe": "f",
  "knoten": "m",
  "kn\xE4uel": "n",
  "kn\xF6chel": "m",
  "koffer": "m",
  "kohleneimer": "m",
  "kohleschale": "f",
  "kollege": "m",
  "kollegheft": "n",
  "kollektiv": "n",
  "kolonie": "f",
  "komet": "m",
  "kommentar": "m",
  "kommissar": "m",
  "kompass": "m",
  "kompressor": "m",
  "konstante": "f",
  "konto": "n",
  "kontobuch": "n",
  "kontor": "n",
  "kontorbuch": "n",
  "kontostand": "m",
  "kopf": "m",
  "kopfh\xF6rer": "m",
  "kopie": "f",
  "korb": "m",
  "korken": "m",
  "korn": "n",
  "kraft": "f",
  "kran": "m",
  "krater": "m",
  "kreide": "f",
  "kreis": "m",
  "kreuz": "n",
  "kreuzung": "f",
  "kribbeln": "n",
  "krieg": "m",
  "krieger": "m",
  "kristall": "m",
  "krone": "f",
  "krug": "m",
  "kr\xE4he": "f",
  "kuchen": "m",
  "kuh": "f",
  "kupfer": "n",
  "kuppel": "f",
  "kurbel": "f",
  "kurve": "f",
  "kuss": "m",
  "kutsche": "f",
  "kuvert": "n",
  "k\xE4fer": "m",
  "k\xE4lte": "f",
  "k\xE4se": "m",
  "k\xF6nig": "m",
  "k\xF6nigin": "f",
  "k\xF6rper": "m",
  "k\xFCche": "f",
  "k\xFChlbox": "f",
  "k\xFChlfalle": "f",
  "k\xFCken": "n",
  "k\xFCste": "f",
  "labyrinth": "n",
  "ladebalken": "m",
  "ladekabel": "n",
  "ladeliste": "f",
  "lager": "n",
  "lagune": "f",
  "laib": "m",
  "lamm": "n",
  "lampe": "f",
  "land": "n",
  "lanze": "f",
  "laterne": "f",
  "laub": "n",
  "laufzettel": "m",
  "laute": "f",
  "lawine": "f",
  "leder": "n",
  "lederbeutel": "m",
  "legende": "f",
  "lehen": "n",
  "lehrer": "m",
  "leid": "n",
  "leine": "f",
  "leitdetail": "n",
  "leitung": "f",
  "leuchten": "n",
  "leuchtturm": "m",
  "licht": "n",
  "lichtstreifen": "m",
  "lider": "n",
  "liebe": "f",
  "lied": "n",
  "lilie": "f",
  "lineal": "n",
  "linie": "f",
  "lippe": "f",
  "liste": "f",
  "loch": "n",
  "locke": "f",
  "log": "n",
  "logbuch": "n",
  "logfile": "n",
  "los": "n",
  "lot": "n",
  "luft": "f",
  "lupe": "f",
  "lust": "f",
  "l\xE4cheln": "n",
  "l\xE4nder": "n",
  "l\xE4rm": "m",
  "l\xF6cher": "n",
  "l\xF6ffel": "m",
  "l\xF6we": "m",
  "l\xFCcke": "f",
  "l\xFCge": "f",
  "macht": "f",
  "magen": "m",
  "mala": "f",
  "maler": "m",
  "manege": "f",
  "manifest": "n",
  "mann": "m",
  "mantel": "m",
  "manuskript": "n",
  "mappe": "f",
  "marmelade": "f",
  "masche": "f",
  "maschine": "f",
  "maske": "f",
  "mast": "m",
  "matte": "f",
  "mauer": "f",
  "maus": "f",
  "ma\xDF": "n",
  "ma\xDFband": "n",
  "ma\xDFstab": "m",
  "medaillon": "n",
  "meer": "n",
  "mehl": "n",
  "mei\xDFel": "m",
  "melodie": "f",
  "meme": "n",
  "menge": "f",
  "merkblatt": "n",
  "messer": "n",
  "messprotokoll": "n",
  "messreihe": "f",
  "messung": "f",
  "metall": "n",
  "meter": "m",
  "metronom": "n",
  "miene": "f",
  "mikrofon": "n",
  "mikroskop": "n",
  "milch": "f",
  "millimeter": "m",
  "minute": "f",
  "mitleid": "n",
  "mittag": "m",
  "mittel": "n",
  "mitternacht": "f",
  "modell": "n",
  "modellplaneten": "m",
  "moment": "m",
  "monat": "m",
  "mond": "m",
  "moor": "n",
  "morgen": "m",
  "moschee": "f",
  "motor": "m",
  "mus": "n",
  "muschel": "f",
  "muskel": "m",
  "muster": "n",
  "mut": "m",
  "mutter": "f",
  "m\xE4dchen": "n",
  "m\xE4hne": "f",
  "m\xF6hre": "f",
  "m\xF6nch": "m",
  "m\xF6rder": "m",
  "m\xF6we": "f",
  "m\xFCcke": "f",
  "m\xFChle": "f",
  "m\xFCller": "m",
  "m\xFCnze": "f",
  "m\xFCtze": "f",
  "nachbar": "m",
  "nachbarort": "m",
  "nachlass": "m",
  "nachmittag": "m",
  "nachricht": "f",
  "nacht": "f",
  "nachtigall": "f",
  "nacken": "m",
  "nadel": "f",
  "nadelkissen": "n",
  "nagel": "m",
  "naht": "f",
  "name": "m",
  "napf": "m",
  "narbe": "f",
  "nase": "f",
  "nebel": "m",
  "neffe": "m",
  "neid": "m",
  "neigung": "f",
  "neigungsmesser": "m",
  "nelke": "f",
  "nest": "n",
  "nester": "n",
  "netz": "n",
  "nische": "f",
  "nonne": "f",
  "note": "f",
  "notenblatt": "n",
  "notiz": "f",
  "notizblock": "m",
  "notizbuch": "n",
  "nummer": "f",
  "nuss": "f",
  "nymphe": "f",
  "n\xE4he": "f",
  "obst": "n",
  "ofen": "m",
  "ohr": "n",
  "oma": "f",
  "omen": "n",
  "onkel": "m",
  "opfer": "n",
  "opferschale": "f",
  "opiumdose": "f",
  "orakel": "n",
  "orange": "f",
  "organ": "n",
  "orgel": "f",
  "ort": "m",
  "ozean": "m",
  "paar": "n",
  "paket": "n",
  "pakt": "m",
  "papier": "n",
  "paradoxon": "n",
  "paragraph": "m",
  "parameter": "m",
  "park": "m",
  "passagier": "m",
  "passierschein": "m",
  "pegelstab": "m",
  "peilstock": "m",
  "peitsche": "f",
  "pendel": "n",
  "pergamentrolle": "f",
  "perle": "f",
  "perlmuttknopf": "m",
  "person": "f",
  "petrischale": "f",
  "petroleumlampe": "f",
  "pfad": "m",
  "pfand": "n",
  "pfandschein": "m",
  "pfeffer": "m",
  "pfeife": "f",
  "pferd": "n",
  "pfirsich": "m",
  "pflaster": "n",
  "pflaume": "f",
  "pflug": "m",
  "pf\xFCtze": "f",
  "phiole": "f",
  "photoplatte": "f",
  "pickel": "m",
  "pilz": "m",
  "ping": "m",
  "pinzette": "f",
  "pipette": "f",
  "plakat": "n",
  "plan": "m",
  "plane": "f",
  "planet": "m",
  "planke": "f",
  "platte": "f",
  "platz": "m",
  "platzhalter": "m",
  "poller": "m",
  "port": "m",
  "portal": "n",
  "postkarte": "f",
  "powerbank": "f",
  "priester": "m",
  "prisma": "n",
  "probe": "f",
  "programm": "n",
  "protokoll": "n",
  "prozess": "m",
  "puls": "m",
  "pulver": "n",
  "punkt": "m",
  "puppe": "f",
  "qualle": "f",
  "quelle": "f",
  "quittung": "f",
  "rad": "n",
  "rampe": "f",
  "rand": "m",
  "randnotiz": "f",
  "ranke": "f",
  "ranzen": "m",
  "ratte": "f",
  "rauch": "m",
  "raumkapsel": "f",
  "rausch": "m",
  "rauschen": "n",
  "rechentafel": "f",
  "recht": "n",
  "regal": "n",
  "regel": "f",
  "regen": "m",
  "regenmesser": "m",
  "register": "n",
  "reh": "n",
  "reich": "n",
  "reif": "m",
  "reigen": "m",
  "reihe": "f",
  "reinraumhaube": "f",
  "reise": "f",
  "reisemantel": "m",
  "rei\xDFverschluss": "m",
  "reklame": "f",
  "rest": "m",
  "rettung": "f",
  "rezept": "n",
  "richter": "m",
  "riegel": "m",
  "riff": "n",
  "rinde": "f",
  "ring": "m",
  "rippe": "f",
  "riss": "m",
  "ritter": "m",
  "ritterhelm": "m",
  "rohr": "n",
  "roman": "m",
  "rose": "f",
  "ruder": "n",
  "ruf": "m",
  "ruine": "f",
  "rumpf": "m",
  "r\xE4tsel": "n",
  "r\xFCcken": "m",
  "saal": "m",
  "sachbearbeiter": "m",
  "sack": "m",
  "saft": "m",
  "sage": "f",
  "sahne": "f",
  "saite": "f",
  "salat": "m",
  "salz": "n",
  "samen": "m",
  "sammlung": "f",
  "sand": "m",
  "sandsack": "m",
  "sanduhr": "f",
  "sarg": "m",
  "satellit": "m",
  "sattel": "m",
  "sattelgurt": "m",
  "satz": "m",
  "saum": "m",
  "savanne": "f",
  "schacht": "m",
  "schaf": "n",
  "schale": "f",
  "schalter": "m",
  "scham": "f",
  "schatten": "m",
  "schatulle": "f",
  "schaufel": "f",
  "schere": "f",
  "schicht": "f",
  "schicksal": "n",
  "schiff": "n",
  "schiffssextanten": "m",
  "schiffszwieback": "m",
  "schild": "n",
  "schirm": "m",
  "schlaf": "m",
  "schlag": "m",
  "schlamm": "m",
  "schlange": "f",
  "schleife": "f",
  "schloss": "n",
  "schlucht": "f",
  "schl\xFCssel": "m",
  "schl\xFCsselbund": "m",
  "schmerz": "m",
  "schmied": "m",
  "schmiede": "f",
  "schminkkasten": "m",
  "schnecke": "f",
  "schnee": "m",
  "schneiderpuppe": "f",
  "schnitt": "m",
  "schnittbogen": "m",
  "schnittstelle": "f",
  "schnur": "f",
  "schokolade": "f",
  "schrank": "m",
  "schrei": "m",
  "schreiber": "m",
  "schrein": "m",
  "schrift": "f",
  "schritt": "m",
  "schuh": "m",
  "schuld": "f",
  "schuldschein": "m",
  "schule": "f",
  "schulter": "f",
  "schuppen": "m",
  "schuss": "m",
  "schwamm": "m",
  "schwein": "n",
  "schwelle": "f",
  "schwert": "n",
  "schwertgriff": "m",
  "schwertgurt": "m",
  "schwester": "f",
  "schw\xE4che": "f",
  "sch\xE4del": "m",
  "sch\xE4rpe": "f",
  "sch\xFCrze": "f",
  "sch\xFCssel": "f",
  "screenshot": "m",
  "see": "m",
  "seekarte": "f",
  "seele": "f",
  "seesack": "m",
  "segel": "n",
  "segeltuch": "n",
  "segen": "m",
  "sehne": "f",
  "sehnsucht": "f",
  "seidenfaden": "m",
  "seil": "n",
  "seismograph": "m",
  "seismographen": "m",
  "seite": "f",
  "sekunde": "f",
  "senf": "m",
  "sensor": "m",
  "sessel": "m",
  "sieb": "n",
  "siegel": "n",
  "siegelring": "m",
  "signal": "n",
  "signalflagge": "f",
  "silbe": "f",
  "silber": "n",
  "sinn": "m",
  "sirene": "f",
  "skala": "f",
  "skalpell": "n",
  "skelett": "n",
  "skizze": "f",
  "smartphone": "n",
  "socke": "f",
  "sofa": "n",
  "sohn": "m",
  "soldat": "m",
  "sommer": "m",
  "sonne": "f",
  "sonnenbrille": "f",
  "so\xDFe": "f",
  "spalt": "m",
  "speicher": "m",
  "spektrogramm": "n",
  "spektrometer": "n",
  "sperre": "f",
  "spiegel": "m",
  "spiegelscherben": "m",
  "spiel": "n",
  "spinne": "f",
  "sporn": "m",
  "sprache": "f",
  "sprung": "m",
  "spule": "f",
  "spur": "f",
  "stab": "m",
  "stadt": "f",
  "stahlstrebe": "f",
  "stamm": "m",
  "standarte": "f",
  "stapel": "m",
  "statue": "f",
  "staub": "m",
  "stecknadel": "f",
  "steg": "m",
  "steig": "m",
  "steigb\xFCgel": "m",
  "steigeisen": "n",
  "stein": "m",
  "stelle": "f",
  "stempel": "m",
  "stempelger\xE4usch": "n",
  "stempelhalter": "m",
  "steppe": "f",
  "stern": "m",
  "sternbilder": "n",
  "sternwarte": "f",
  "stethoskop": "n",
  "stiefel": "m",
  "stier": "m",
  "stille": "f",
  "stimme": "f",
  "stirn": "f",
  "stock": "m",
  "stoff": "m",
  "stollen": "m",
  "stolz": "m",
  "story": "f",
  "strand": "m",
  "strauch": "m",
  "stra\xDFe": "f",
  "streichholzschachtel": "f",
  "streit": "m",
  "strich": "m",
  "strom": "m",
  "strophe": "f",
  "str\xF6mung": "f",
  "stube": "f",
  "stufe": "f",
  "stuhl": "m",
  "stunde": "f",
  "stundenplan": "m",
  "sturm": "m",
  "sturmlaterne": "f",
  "st\xE4rke": "f",
  "st\xFCck": "n",
  "sumpf": "m",
  "suppe": "f",
  "suppenkelle": "f",
  "symbol": "n",
  "symptom": "n",
  "system": "n",
  "s\xE4ge": "f",
  "s\xE4ule": "f",
  "tabelle": "f",
  "tafel": "f",
  "tafelrunde": "f",
  "tag": "m",
  "takt": "m",
  "tal": "n",
  "talar": "m",
  "tante": "f",
  "tanz": "m",
  "tasche": "f",
  "taschenradio": "n",
  "tasse": "f",
  "tau": "n",
  "taube": "f",
  "tee": "m",
  "teer": "m",
  "teeschale": "f",
  "teich": "m",
  "teil": "m",
  "telefon": "n",
  "teleskop": "n",
  "teller": "m",
  "teppich": "m",
  "termin": "m",
  "terminal": "n",
  "terminzettel": "m",
  "teufel": "m",
  "thermometer": "n",
  "thermoskanne": "f",
  "thron": "m",
  "ticket": "n",
  "tier": "n",
  "tiger": "m",
  "tiktoksound": "m",
  "tintenfass": "n",
  "tisch": "m",
  "tochter": "f",
  "tod": "m",
  "tomate": "f",
  "ton": "m",
  "tonband": "n",
  "tonschale": "f",
  "tontafel": "f",
  "topf": "m",
  "tor": "n",
  "torte": "f",
  "trapezhaken": "m",
  "traube": "f",
  "trauer": "f",
  "traum": "m",
  "trend": "m",
  "treppe": "f",
  "treue": "f",
  "trillerpfeife": "f",
  "trinkhorn": "n",
  "trommel": "f",
  "truhe": "f",
  "tr\xE4ne": "f",
  "tuch": "n",
  "tulpe": "f",
  "tunnel": "m",
  "turm": "m",
  "turnbeutel": "m",
  "turnier": "n",
  "turnierplatz": "m",
  "turnierstab": "m",
  "t\xFCr": "f",
  "t\xFCte": "f",
  "ufer": "n",
  "uhr": "f",
  "umriss": "m",
  "umschlag": "m",
  "ungl\xFCck": "n",
  "untergrund": "m",
  "unterschrift": "f",
  "untersuchungsliege": "f",
  "update": "n",
  "urne": "f",
  "urteil": "n",
  "vater": "m",
  "verdacht": "m",
  "verfahren": "n",
  "vergangenheit": "f",
  "vermerk": "m",
  "vers": "m",
  "verstand": "m",
  "vertrag": "m",
  "vertrauen": "n",
  "video": "n",
  "virus": "n",
  "visier": "n",
  "vogel": "m",
  "vollmacht": "f",
  "vordruck": "m",
  "vorhang": "m",
  "vormund": "m",
  "vorrat": "m",
  "vorratsgl\xE4ser": "n",
  "vulkan": "m",
  "wachs": "n",
  "wachstuch": "n",
  "wagen": "m",
  "wahrheit": "f",
  "waisenjunge": "m",
  "wal": "m",
  "wald": "m",
  "waldhorn": "n",
  "wand": "f",
  "wanderstab": "m",
  "wanderstock": "m",
  "wanderung": "f",
  "wange": "f",
  "wappen": "n",
  "wappenschild": "n",
  "warnung": "f",
  "warnweste": "f",
  "wartemarke": "f",
  "warze": "f",
  "wasser": "n",
  "wasserflasche": "f",
  "wasserhahn": "m",
  "weg": "m",
  "wegmarke": "f",
  "weide": "f",
  "wein": "m",
  "weite": "f",
  "wei\xDF": "n",
  "welle": "f",
  "werk": "n",
  "werkstatt": "f",
  "werkzeug": "n",
  "wert": "m",
  "wespe": "f",
  "wetter": "n",
  "wetterfahne": "f",
  "widerstand": "m",
  "wiese": "f",
  "wille": "m",
  "wimper": "f",
  "wind": "m",
  "windhauch": "m",
  "windsto\xDF": "m",
  "winter": "m",
  "witz": "m",
  "woche": "f",
  "wolf": "m",
  "wolke": "f",
  "wollschal": "m",
  "wort": "n",
  "wrack": "n",
  "wunde": "f",
  "wunder": "n",
  "wunsch": "m",
  "wurm": "m",
  "wurzel": "f",
  "wut": "f",
  "w\xE4chter": "m",
  "w\xE4lder": "m",
  "w\xE4rme": "f",
  "w\xE4rmestein": "m",
  "w\xE4schekorb": "m",
  "w\xF6rter": "n",
  "w\xFCrfel": "m",
  "w\xFCste": "f",
  "zahl": "f",
  "zahn": "m",
  "zange": "f",
  "zauberbesen": "m",
  "zaun": "m",
  "zeh": "m",
  "zeichen": "n",
  "zeile": "f",
  "zeit": "f",
  "zeitgeber": "m",
  "zeitmarke": "f",
  "zelle": "f",
  "zelt": "n",
  "zentimeter": "m",
  "zepter": "n",
  "zettel": "m",
  "zeuge": "m",
  "ziffer": "f",
  "zigarettenstummel": "m",
  "zigarre": "f",
  "zimmer": "n",
  "zirkel": "m",
  "zitrone": "f",
  "zittern": "n",
  "zorn": "m",
  "zucker": "m",
  "zug": "m",
  "zukunft": "f",
  "zunderbeutel": "m",
  "zunge": "f",
  "zweifel": "m",
  "zweig": "m",
  "zweitschl\xFCssel": "m",
  "zwieback": "m",
  "zwiebel": "f",
  "z\xE4hlrahmen": "m",
  "z\xF6gern": "n",
  "\xE4rmel": "m",
  "\xE4rztin": "f",
  "\xF6l": "n",
  "\xF6llampe": "f",
  "\xF6llaterne": "f",
  "\xF6lschl\xFCssel": "m"
};

// src/generation/nouns2.data.ts
var NOUN_GENDER_2 = {
  // ── Häufigste ──
  ende: "n",
  jahr: "n",
  mal: "n",
  anfang: "m",
  leben: "n",
  auskunft: "f",
  welt: "f",
  fr\u00FChjahr: "n",
  fall: "m",
  arbeit: "f",
  sache: "f",
  zufall: "m",
  form: "f",
  ziel: "n",
  kontrolle: "f",
  reihenfolge: "f",
  wissen: "n",
  post: "f",
  ernte: "f",
  geld: "n",
  mund: "m",
  schweigen: "n",
  wette: "f",
  schminke: "f",
  kurs: "m",
  original: "n",
  text: "m",
  gras: "n",
  warten: "n",
  ruhe: "f",
  mitte: "f",
  seide: "f",
  familie: "f",
  tiefe: "f",
  norden: "m",
  s\u00FCden: "m",
  osten: "m",
  westen: "m",
  blut: "n",
  horizont: "m",
  ursache: "f",
  absicht: "f",
  wirt: "m",
  jagd: "f",
  herkunft: "f",
  essen: "n",
  r\u00FCckkehr: "f",
  rahmen: "m",
  w\u00FCrde: "f",
  w\u00E4sche: "f",
  miete: "f",
  verlangen: "n",
  marke: "f",
  griff: "m",
  wache: "f",
  vernunft: "f",
  markt: "m",
  pegel: "m",
  halbdunkel: "n",
  rolle: "f",
  grad: "m",
  streben: "n",
  fach: "n",
  weise: "f",
  wipfel: "m",
  kohle: "f",
  lehne: "f",
  tide: "f",
  ru\u00DF: "m",
  idee: "f",
  gemeinde: "f",
  jahrhundert: "n",
  ernst: "m",
  betrag: "m",
  unterschied: "m",
  material: "n",
  annahme: "f",
  merkmal: "n",
  radio: "n",
  hitze: "f",
  herold: "m",
  grat: "m",
  kasse: "f",
  zoll: "m",
  heimweh: "n",
  laden: "m",
  f\u00E4hre: "f",
  herzog: "m",
  inhalt: "m",
  titel: "m",
  problem: "n",
  sicht: "f",
  beh\u00F6rde: "f",
  winkel: "m",
  hilfe: "f",
  pass: "m",
  viertel: "n",
  jahrzehnt: "n",
  anrede: "f",
  rost: "m",
  ekel: "m",
  tat: "f",
  methode: "f",
  zwang: "m",
  heimkehr: "f",
  umkehr: "f",
  norm: "f",
  leere: "f",
  umlauf: "m",
  flamme: "f",
  einsicht: "f",
  messing: "n",
  personal: "n",
  widerspruch: "m",
  schluss: "m",
  stroh: "n",
  rang: "m",
  vieh: "n",
  garderobe: "f",
  g\u00FCte: "f",
  anlass: "m",
  anwalt: "m",
  rat: "m",
  code: "m",
  bad: "n",
  handgelenk: "n",
  scheibe: "f",
  zustand: "m",
  eile: "f",
  saatgut: "n",
  fracht: "f",
  automat: "m",
  lehre: "f",
  ding: "n",
  verzicht: "m",
  zweck: "m",
  waffe: "f",
  blech: "n",
  trost: "m",
  versuch: "m",
  ironie: "f",
  d\u00FCrre: "f",
  fest: "n",
  aufsicht: "f",
  kapitel: "n",
  aussicht: "f",
  absinth: "m",
  parf\u00FCm: "n",
  schmutz: "m",
  knick: "m",
  andacht: "f",
  spitze: "f",
  szene: "f",
  erfolg: "m",
  ausguck: "m",
  bord: "m",
  sieg: "m",
  klausel: "f",
  haupttext: "m",
  sachverhalt: "m",
  tinte: "f",
  stand: "m",
  wortlaut: "m",
  klinke: "f",
  kanzel: "f",
  verrat: "m",
  mulde: "f",
  februar: "m",
  parasit: "m",
  pr\u00E4parat: "n",
  wesen: "n",
  lava: "f",
  schwefel: "m",
  lauf: "m",
  spa\u00DF: "m",
  m\u00F6bel: "n",
  b\u00FCro: "n",
  hauptsache: "f",
  saat: "f",
  fehde: "f",
  portr\u00E4t: "n",
  reue: "f",
  konfetti: "n",
  trapez: "n",
  narr: "m",
  truppe: "f",
  pudel: "m",
  jugend: "f",
  abschied: "m",
  bronze: "f",
  tempel: "m",
  geschlecht: "n",
  stra\u00DFenanfang: "m",
  brauch: "m",
  wiederkehr: "f",
  h\u00E4lfte: "f",
  pappe: "f",
  kante: "f",
  eintrag: "m",
  format: "n",
  giebel: "m",
  heimat: "f",
  armenkasse: "f",
  materie: "f",
  mensch: "m",
  glied: "n",
  betrieb: "m",
  m\u00FCll: "m",
  kleingeld: "n",
  ruhm: "m",
  ritt: "m",
  sch\u00E4rfe: "f",
  ankunft: "f",
  symmetrie: "f",
  adressat: "m",
  kreislauf: "m",
  aufstieg: "m",
  f\u00FClle: "f",
  bitte: "f",
  brand: "m",
  waise: "f",
  gesang: "m",
  subjekt: "n",
  objekt: "n",
  moral: "f",
  schilf: "n",
  diagnose: "f",
  gr\u00F6\u00DFe: "f",
  wahl: "f",
  sturz: "m",
  gischt: "f",
  ekstase: "f",
  becken: "n",
  putz: "m",
  minze: "f",
  samt: "m",
  pause: "f",
  knauf: "m",
  apotheke: "f",
  kost\u00FCm: "n",
  versto\u00DF: "m",
  satzanfang: "m",
  sprint: "m",
  beule: "f",
  banane: "f",
  tapete: "f",
  galerie: "f",
  kl\u00F6ppel: "m",
  predigt: "f",
  zierrat: "m",
  wachwechsel: "m",
  wimpel: "m",
  rah: "f",
  streitfall: "m",
  docht: "m",
  wundmal: "n",
  pforte: "f",
  gebot: "n",
  fl\u00FCgel: "m",
  l\u00E4nge: "f",
  kamel: "n",
  achse: "f",
  schlegel: "m",
  affe: "m",
  nirwana: "n",
  alkohol: "m",
  instinkt: "m",
  balance: "f",
  aushub: "m",
  kalk: "m",
  r\u00F6hre: "f",
  basalt: "m",
  salzs\u00E4ure: "f",
  erdkruste: "f",
  schichtfolge: "f",
  sohle: "f",
  profil: "n",
  schneeschmelze: "f",
  orbit: "m",
  funkspruch: "m",
  meteorit: "m",
  stromausfall: "m",
  theorie: "f",
  nervengeflecht: "n",
  bodenprofil: "n",
  senke: "f",
  gebiet: "n",
  phase: "f",
  honorar: "n",
  kordel: "f",
  spind: "m",
  tonfall: "m",
  tempo: "n",
  schattenkante: "f",
  stahl: "m",
  graupappe: "f",
  st\u00FCtze: "f",
  perspektive: "f",
  tank: "m",
  stillstand: "m",
  pumpe: "f",
  debatte: "f",
  bahre: "f",
  fackelru\u00DF: "m",
  kerbe: "f",
  t\u00FCrsturz: "m",
  groll: "m",
  seuche: "f",
  lunge: "f",
  pferdegeschirr: "n",
  zeltgest\u00E4nge: "n",
  marsch: "m",
  schaumgummi: "m",
  knall: "m",
  zeltmitte: "f",
  trick: "m",
  wurf: "m",
  pult: "n",
  pentagramm: "n",
  handel: "m",
  r\u00FCcktritt: "m",
  zimt: "m",
  akt: "m",
  schatz: "m",
  betrug: "m",
  kopfende: "n",
  parkett: "n",
  lack: "m",
  leib: "m",
  efeu: "m",
  anstand: "m",
  schafwolle: "f",
  milde: "f",
  wiege: "f",
  schar: "f",
  gunst: "f",
  volk: "n",
  staat: "m",
  antlitz: "n",
  fleck: "m",
  alibi: "n",
  kamera: "f",
  vorfall: "m",
  quelltext: "m",
  ritual: "n",
  schl\u00E4fe: "f",
  wetterwechsel: "m",
  anzeige: "f",
  jahresende: "n",
  weile: "f",
  t\u00FCll: "m",
  schleppe: "f",
  b\u00FCgel: "m",
  dampf: "m",
  kragen: "m",
  kerzenstummel: "m",
  klasse: "f",
  monatsende: "n",
  tausendstel: "n",
  durchlauf: "m",
  jahrtausend: "n",
  scheu: "f",
  taxi: "n",
  mittwoch: "m",
  erz: "n",
  diebstahl: "m",
  nachtwache: "f",
  schleuse: "f",
  \u00FCbernahme: "f",
  luke: "f",
  sp\u00FCle: "f",
  ampel: "f",
  sperrm\u00FCll: "m",
  speiche: "f",
  henkel: "m",
  routine: "f",
  mai: "m",
  wolle: "f",
  schluck: "m",
  biologie: "f",
  geologie: "f",
  astrologie: "f",
  philosophie: "f",
  krise: "f",
  trag\u00F6die: "f",
  urknall: "m",
  stift: "m",
  mine: "f",
  abwehr: "f",
  mole: "f",
  zerfall: "m",
  masse: "f",
  handbreit: "f",
  verfall: "m",
  tischkante: "f",
  beute: "f",
  rache: "f",
  font\u00E4ne: "f",
  zuversicht: "f",
  unruhe: "f",
  energie: "f",
  enge: "f",
  april: "m",
  rekord: "m",
  normalzustand: "m",
  h\u00F6he: "f",
  abstieg: "m",
  requisit: "n",
  schwindel: "m",
  orakelspruch: "m",
  erlass: "m",
  aufstand: "m",
  gehorsam: "m",
  blackbox: "f",
  silhouette: "f",
  mode: "f",
  not: "f",
  urform: "f",
  ruhestand: "m",
  schaden: "m",
  anlauf: "m",
  dienstjahr: "n",
  witwe: "f",
  ensemble: "n",
  kommune: "f",
  sekte: "f",
  rettungstrupp: "m",
  exil: "n",
  zentrale: "f",
  zensurbeh\u00F6rde: "f",
  doktortitel: "m",
  naturschutzgebiet: "n",
  boulevard: "m",
  hotel: "n",
  kino: "n",
  verkehr: "m",
  kellerclub: "m",
  kabine: "f",
  auto: "n",
  kaserne: "f",
  internat: "n",
  wahlkabine: "f",
  anstalt: "f",
  mittagspause: "f",
  choleraepidemie: "f",
  monarchie: "f",
  hungersnot: "f",
  null: "f",
  route: "f",
  kampagne: "f",
  karriere: "f",
  neuanfang: "m",
  sorte: "f",
  verhandlungssache: "f",
  folge: "f",
  ablauf: "m",
  strategie: "f",
  apparat: "m",
  psychopath: "m",
  variable: "f",
  empathie: "f",
  amsel: "f",
  schneefall: "m",
  abendrot: "n",
  wechsel: "m",
  // ── Nachschlag: Alltag, Körper, Haus, Natur, Amt ──
  auge: "n",
  name: "m",
  glaube: "m",
  wille: "m",
  gedanke: "m",
  friede: "m",
  funke: "m",
  k\u00E4se: "m",
  junge: "m",
  kunde: "m",
  l\u00F6we: "m",
  hase: "m",
  bote: "m",
  zeuge: "m",
  riese: "m",
  rabe: "m",
  falke: "m",
  ochse: "m",
  bursche: "m",
  knabe: "m",
  neffe: "m",
  erbe: "m",
  buchstabe: "m",
  same: "m",
  schatten: "m",
  wagen: "m",
  boden: "m",
  garten: "m",
  ofen: "m",
  regen: "m",
  faden: "m",
  haken: "m",
  hafen: "m",
  morgen: "m",
  tropfen: "m",
  kissen: "n",
  zeichen: "n",
  kuchen: "m",
  knochen: "m",
  r\u00FCcken: "m",
  segen: "m",
  bogen: "m",
  balken: "m",
  riegel: "m",
  ballen: "m",
  fels: "m",
  haus: "n",
  glas: "n",
  bus: "m",
  fluss: "m",
  kuss: "m",
  guss: "m",
  gru\u00DF: "m",
  fu\u00DF: "m",
  hass: "m",
  kompass: "m",
  atlas: "m",
  kreis: "m",
  preis: "m",
  eis: "n",
  reis: "m",
  gleis: "n",
  flei\u00DF: "m",
  geheimnis: "n",
  ergebnis: "n",
  zeugnis: "n",
  bed\u00FCrfnis: "n",
  verh\u00E4ltnis: "n",
  ereignis: "n",
  erlebnis: "n",
  b\u00FCndnis: "n",
  hindernis: "n",
  gef\u00E4ngnis: "n",
  wildnis: "f",
  finsternis: "f",
  fenster: "n",
  zimmer: "n",
  wasser: "n",
  messer: "n",
  feuer: "n",
  kupfer: "n",
  silber: "n",
  pulver: "n",
  wetter: "n",
  alter: "n",
  ufer: "n",
  lager: "n",
  opfer: "n",
  muster: "n",
  kloster: "n",
  register: "n",
  theater: "n",
  fieber: "n",
  leder: "n",
  futter: "n",
  gitter: "n",
  ruder: "n",
  wunder: "n",
  orchester: "n",
  zepter: "n",
  semester: "n",
  polster: "n",
  pflaster: "n",
  laster: "n",
  meter: "m",
  liter: "m",
  zentrum: "n",
  datum: "n",
  museum: "n",
  t\u00FCr: "f",
  hand: "f",
  stern: "m",
  schritt: "m",
  brief: "m",
  weg: "m",
  stimme: "f",
  spur: "f",
  lippe: "f",
  frage: "f",
  perle: "f",
  glocke: "f",
  uhr: "f",
  herz: "n",
  dach: "n",
  stra\u00DFe: "f",
  regel: "f",
  vorrat: "m",
  schicht: "f",
  schaf: "n",
  nummer: "f",
  schuh: "m",
  grenze: "f",
  gutachten: "n",
  satz: "m",
  wort: "n",
  seele: "f",
  teil: "m",
  blume: "f",
  richtung: "f",
  monat: "m",
  zahn: "m",
  ort: "m",
  wand: "f",
  vorhang: "m",
  umstand: "m",
  sandsack: "m",
  kraft: "f",
  bein: "n",
  kanal: "m",
  sinn: "m",
  netz: "n",
  pflasterstein: "m",
  handschuh: "m",
  protokoll: "n",
  system: "n",
  kreidestrich: "m",
  bruchteil: "m",
  tor: "n",
  kran: "m",
  beweis: "m",
  nacht: "f",
  stadt: "f",
  grund: "m",
  zug: "m",
  riff: "n",
  plakat: "n",
  baum: "m",
  erbgang: "m",
  exemplar: "n",
  symptom: "n",
  plan: "m",
  umriss: "m",
  riss: "m",
  bahngleis: "n",
  regal: "n",
  blick: "m",
  bergpass: "m",
  faust: "f",
  stuhl: "m",
  freund: "m",
  stamm: "m",
  tanzschuh: "m",
  dienst: "m",
  ma\u00DF: "n",
  arm: "m",
  kinderhand: "f",
  tisch: "m",
  seil: "n",
  frachtbrief: "m",
  termin: "m",
  formular: "n",
  messwert: "m",
  gegenstand: "m",
  vogel: "m",
  exponat: "n",
  fahrgast: "m",
  meer: "n",
  anruf: "m",
  vorschlag: "m",
  punkt: "m",
  boot: "n",
  paar: "n",
  gast: "m",
  stein: "m",
  stunde: "f",
  minute: "f",
  tag: "m",
  woche: "f",
  seite: "f",
  farbe: "f",
  papier: "n",
  nachbar: "m",
  wolke: "f",
  zeug: "n",
  kind: "n",
  mann: "m",
  frau: "f",
  vater: "m",
  mutter: "f",
  bruder: "m",
  schwester: "f",
  sohn: "m",
  tochter: "f",
  herr: "m",
  dame: "f",
  lehrer: "m",
  arzt: "m",
  pfarrer: "m",
  priester: "m",
  k\u00F6nig: "m",
  k\u00F6nigin: "f",
  kaiser: "m",
  soldat: "m",
  bauer: "m",
  fischer: "m",
  b\u00E4cker: "m",
  schneider: "m",
  schmied: "m",
  m\u00FCller: "m",
  j\u00E4ger: "m",
  hirte: "m",
  knecht: "m",
  magd: "f",
  w\u00E4chter: "m",
  richter: "m",
  h\u00E4ndler: "m",
  fremde: "m",
  kurier: "m",
  agent: "m",
  spion: "m",
  dieb: "m",
  r\u00E4uber: "m",
  m\u00F6rder: "m",
  opferlamm: "n",
  engel: "m",
  teufel: "m",
  geist: "m",
  gott: "m",
  g\u00F6ttin: "f",
  heiliger: "m",
  m\u00F6nch: "m",
  nonne: "f",
  abt: "m",
  bischof: "m",
  papst: "m",
  ritter: "m",
  knappe: "m",
  graf: "m",
  gr\u00E4fin: "f",
  f\u00FCrst: "m",
  prinz: "m",
  prinzessin: "f",
  zauberer: "m",
  hexe: "f",
  drache: "m",
  zwerg: "m",
  elf: "m",
  troll: "m",
  wolf: "m",
  b\u00E4r: "m",
  fuchs: "m",
  hirsch: "m",
  reh: "n",
  pferd: "n",
  hund: "m",
  katze: "f",
  maus: "f",
  ratte: "f",
  schlange: "f",
  fisch: "m",
  m\u00F6we: "f",
  taube: "f",
  kr\u00E4he: "f",
  eule: "f",
  biene: "f",
  fliege: "f",
  spinne: "f",
  k\u00E4fer: "m",
  schmetterling: "m",
  wurm: "m",
  ameise: "f",
  frosch: "m",
  kr\u00F6te: "f",
  eidechse: "f",
  schwan: "m",
  ente: "f",
  gans: "f",
  huhn: "n",
  hahn: "m",
  kuh: "f",
  stier: "m",
  ziege: "f",
  esel: "m",
  schwein: "n",
  lamm: "n",
  // Schwache Maskulina auf -e, die die -e→f-Regel sonst fälschlich fängt
  kollege: "m",
  experte: "m",
  matrose: "m",
  pate: "m",
  sklave: "m",
  laie: "m",
  insasse: "m",
  gatte: "m",
  bulle: "m",
  schurke: "m",
  geselle: "m",
  gef\u00E4hrte: "m",
  genosse: "m",
  komplize: "m",
  jude: "m",
  zar: "m",
  franzose: "m",
  chinese: "m",
  russe: "m",
  grieche: "m",
  t\u00FCrke: "m",
  ire: "m",
  schwede: "m",
  d\u00E4ne: "m",
  psychologe: "m",
  biologe: "m",
  geologe: "m",
  soziologe: "m",
  arch\u00E4ologe: "m",
  philosoph: "m",
  // Neutra auf -e
  interesse: "n",
  geb\u00E4ude: "n",
  gem\u00E4lde: "n",
  gebirge: "n",
  getreide: "n",
  gefolge: "n",
  gel\u00E4nde: "n",
  gewebe: "n",
  gew\u00F6lbe: "n",
  getriebe: "n",
  gef\u00FCge: "n",
  gelage: "n",
  gerede: "n",
  gehege: "n",
  gewerbe: "n"
};

// src/generation/declension.ts
var NOUN_GENDER2 = { ...NOUN_GENDER_2, ...NOUN_GENDER };

// src/generation/verbconj.data.ts
var VERB_CONJ = {
  "bemerkt": {
    "ich": "bemerke",
    "du": "bemerkst",
    "wir": "bemerken",
    "ihr": "bemerkt"
  },
  "nimmt": {
    "ich": "nehme",
    "du": "nimmst",
    "wir": "nehmen",
    "ihr": "nehmt"
  },
  "steht": {
    "ich": "stehe",
    "du": "stehst",
    "wir": "stehen",
    "ihr": "steht"
  },
  "h\xE4lt": {
    "ich": "halte",
    "du": "h\xE4ltst",
    "wir": "halten",
    "ihr": "haltet"
  },
  "sucht": {
    "ich": "suche",
    "du": "suchst",
    "wir": "suchen",
    "ihr": "sucht"
  },
  "versucht": {
    "ich": "versuche",
    "du": "versuchst",
    "wir": "versuchen",
    "ihr": "versucht"
  },
  "will": {
    "ich": "will",
    "du": "willst",
    "wir": "wollen",
    "ihr": "wollt"
  },
  "kann": {
    "ich": "kann",
    "du": "kannst",
    "wir": "k\xF6nnen",
    "ihr": "k\xF6nnt"
  },
  "muss": {
    "ich": "muss",
    "du": "musst",
    "wir": "m\xFCssen",
    "ihr": "m\xFCsst"
  },
  "darf": {
    "ich": "darf",
    "du": "darfst",
    "wir": "d\xFCrfen",
    "ihr": "d\xFCrft"
  },
  "mag": {
    "ich": "mag",
    "du": "magst",
    "wir": "m\xF6gen",
    "ihr": "m\xF6gt"
  },
  "soll": {
    "ich": "soll",
    "du": "sollst",
    "wir": "sollen",
    "ihr": "sollt"
  },
  "m\xF6chte": {
    "ich": "m\xF6chte",
    "du": "m\xF6chtest",
    "wir": "m\xF6chten",
    "ihr": "m\xF6chtet"
  },
  "ist": {
    "ich": "bin",
    "du": "bist",
    "wir": "sind",
    "ihr": "seid"
  },
  "wird": {
    "ich": "werde",
    "du": "wirst",
    "wir": "werden",
    "ihr": "werdet"
  },
  "geht": {
    "ich": "gehe",
    "du": "gehst",
    "wir": "gehen",
    "ihr": "geht"
  },
  "kommt": {
    "ich": "komme",
    "du": "kommst",
    "wir": "kommen",
    "ihr": "kommt"
  },
  "bleibt": {
    "ich": "bleibe",
    "du": "bleibst",
    "wir": "bleiben",
    "ihr": "bleibt"
  },
  "\xF6ffnet": {
    "ich": "\xF6ffne",
    "du": "\xF6ffnest",
    "wir": "\xF6ffnen",
    "ihr": "\xF6ffnet"
  },
  "schlie\xDFt": {
    "ich": "schlie\xDFe",
    "du": "schlie\xDFt",
    "wir": "schlie\xDFen",
    "ihr": "schlie\xDFt"
  },
  "fragt": {
    "ich": "frage",
    "du": "fragst",
    "wir": "fragen",
    "ihr": "fragt"
  },
  "f\xFChrt": {
    "ich": "f\xFChre",
    "du": "f\xFChrst",
    "wir": "f\xFChren",
    "ihr": "f\xFChrt"
  },
  "begreift": {
    "ich": "begreife",
    "du": "begreifst",
    "wir": "begreifen",
    "ihr": "begreift"
  },
  "bricht": {
    "ich": "breche",
    "du": "brichst",
    "wir": "brechen",
    "ihr": "brecht"
  },
  "kippt": {
    "ich": "kippe",
    "du": "kippst",
    "wir": "kippen",
    "ihr": "kippt"
  },
  "l\xF6scht": {
    "ich": "l\xF6sche",
    "du": "l\xF6schst",
    "wir": "l\xF6schen",
    "ihr": "l\xF6scht"
  },
  "tut": {
    "ich": "tue",
    "du": "tust",
    "wir": "tun",
    "ihr": "tut"
  },
  "macht": {
    "ich": "mache",
    "du": "machst",
    "wir": "machen",
    "ihr": "macht"
  },
  "sieht": {
    "ich": "sehe",
    "du": "siehst",
    "wir": "sehen",
    "ihr": "seht"
  },
  "gibt": {
    "ich": "gebe",
    "du": "gibst",
    "wir": "geben",
    "ihr": "gebt"
  },
  "tr\xE4gt": {
    "ich": "trage",
    "du": "tr\xE4gst",
    "wir": "tragen",
    "ihr": "tragt"
  },
  "h\xF6rt": {
    "ich": "h\xF6re",
    "du": "h\xF6rst",
    "wir": "h\xF6ren",
    "ihr": "h\xF6rt"
  },
  "findet": {
    "ich": "finde",
    "du": "findest",
    "wir": "finden",
    "ihr": "findet"
  },
  "ber\xFChrt": {
    "ich": "ber\xFChre",
    "du": "ber\xFChrst",
    "wir": "ber\xFChren",
    "ihr": "ber\xFChrt"
  },
  "beobachtet": {
    "ich": "beobachte",
    "du": "beobachtest",
    "wir": "beobachten",
    "ihr": "beobachtet"
  },
  "kennt": {
    "ich": "kenne",
    "du": "kennst",
    "wir": "kennen",
    "ihr": "kennt"
  },
  "nennt": {
    "ich": "nenne",
    "du": "nennst",
    "wir": "nennen",
    "ihr": "nennt"
  },
  "sp\xFCrt": {
    "ich": "sp\xFCre",
    "du": "sp\xFCrst",
    "wir": "sp\xFCren",
    "ihr": "sp\xFCrt"
  },
  "wei\xDF": {
    "ich": "wei\xDF",
    "du": "wei\xDFt",
    "wir": "wissen",
    "ihr": "wisst"
  },
  "braucht": {
    "ich": "brauche",
    "du": "brauchst",
    "wir": "brauchen",
    "ihr": "braucht"
  },
  "w\xFCnscht": {
    "ich": "w\xFCnsche",
    "du": "w\xFCnschst",
    "wir": "w\xFCnschen",
    "ihr": "w\xFCnscht"
  },
  "hofft": {
    "ich": "hoffe",
    "du": "hoffst",
    "wir": "hoffen",
    "ihr": "hofft"
  },
  "tr\xE4umt": {
    "ich": "tr\xE4ume",
    "du": "tr\xE4umst",
    "wir": "tr\xE4umen",
    "ihr": "tr\xE4umt"
  },
  "plant": {
    "ich": "plane",
    "du": "planst",
    "wir": "planen",
    "ihr": "plant"
  },
  "f\xFCrchtet": {
    "ich": "f\xFCrchte",
    "du": "f\xFCrchtest",
    "wir": "f\xFCrchten",
    "ihr": "f\xFCrchtet"
  },
  "wartet": {
    "ich": "warte",
    "du": "wartest",
    "wir": "warten",
    "ihr": "wartet"
  },
  "glaubt": {
    "ich": "glaube",
    "du": "glaubst",
    "wir": "glauben",
    "ihr": "glaubt"
  },
  "denkt": {
    "ich": "denke",
    "du": "denkst",
    "wir": "denken",
    "ihr": "denkt"
  },
  "f\xFChlt": {
    "ich": "f\xFChle",
    "du": "f\xFChlst",
    "wir": "f\xFChlen",
    "ihr": "f\xFChlt"
  },
  "verlangt": {
    "ich": "verlange",
    "du": "verlangst",
    "wir": "verlangen",
    "ihr": "verlangt"
  },
  "erwartet": {
    "ich": "erwarte",
    "du": "erwartest",
    "wir": "erwarten",
    "ihr": "erwartet"
  },
  "riskiert": {
    "ich": "riskiere",
    "du": "riskierst",
    "wir": "riskieren",
    "ihr": "riskiert"
  },
  "wagt": {
    "ich": "wage",
    "du": "wagst",
    "wir": "wagen",
    "ihr": "wagt"
  },
  "flieht": {
    "ich": "fliehe",
    "du": "fliehst",
    "wir": "fliehen",
    "ihr": "flieht"
  },
  "jagt": {
    "ich": "jage",
    "du": "jagst",
    "wir": "jagen",
    "ihr": "jagt"
  },
  "folgt": {
    "ich": "folge",
    "du": "folgst",
    "wir": "folgen",
    "ihr": "folgt"
  },
  "verfolgt": {
    "ich": "verfolge",
    "du": "verfolgst",
    "wir": "verfolgen",
    "ihr": "verfolgt"
  },
  "rettet": {
    "ich": "rette",
    "du": "rettest",
    "wir": "retten",
    "ihr": "rettet"
  },
  "verr\xE4t": {
    "ich": "verrate",
    "du": "verr\xE4tst",
    "wir": "verraten",
    "ihr": "verratet"
  },
  "vergisst": {
    "ich": "vergesse",
    "du": "vergisst",
    "wir": "vergessen",
    "ihr": "vergesst"
  },
  "hatte": {
    "ich": "hatte",
    "du": "hattest",
    "wir": "hatten",
    "ihr": "hattet"
  },
  "war": {
    "ich": "war",
    "du": "warst",
    "wir": "waren",
    "ihr": "wart"
  },
  "wollte": {
    "ich": "wollte",
    "du": "wolltest",
    "wir": "wollten",
    "ihr": "wolltet"
  },
  "tat": {
    "ich": "tat",
    "du": "tatest",
    "wir": "taten",
    "ihr": "tatet"
  },
  "machte": {
    "ich": "machte",
    "du": "machtest",
    "wir": "machten",
    "ihr": "machtet"
  },
  "kam": {
    "ich": "kam",
    "du": "kamst",
    "wir": "kamen",
    "ihr": "kamt"
  },
  "ging": {
    "ich": "ging",
    "du": "gingst",
    "wir": "gingen",
    "ihr": "gingt"
  },
  "f\xFChrte": {
    "ich": "f\xFChrte",
    "du": "f\xFChrtest",
    "wir": "f\xFChrten",
    "ihr": "f\xFChrtet"
  },
  "schloss": {
    "ich": "schloss",
    "du": "schlossest",
    "wir": "schlossen",
    "ihr": "schlosst"
  },
  "fragte": {
    "ich": "fragte",
    "du": "fragtest",
    "wir": "fragten",
    "ihr": "fragtet"
  },
  "begriff": {
    "ich": "begriff",
    "du": "begriffst",
    "wir": "begriffen",
    "ihr": "begrifft"
  },
  "stellt": {
    "ich": "stelle",
    "du": "stellst",
    "wir": "stellen"
  },
  "erkennt": {
    "ich": "erkenne",
    "du": "erkennst",
    "wir": "erkennen"
  },
  "zeigt": {
    "ich": "zeige",
    "du": "zeigst",
    "wir": "zeigen"
  },
  "greift": {
    "ich": "greife",
    "du": "greifst",
    "wir": "greifen"
  },
  "legt": {
    "ich": "lege",
    "du": "legst",
    "wir": "legen"
  },
  "betrachtet": {
    "ich": "betrachte",
    "du": "betrachtest",
    "wir": "betrachten"
  },
  "setzt": {
    "ich": "setze",
    "du": "setzt",
    "wir": "setzen"
  },
  "merkt": {
    "ich": "merke",
    "du": "merkst",
    "wir": "merken"
  },
  "pr\xFCft": {
    "ich": "pr\xFCfe",
    "du": "pr\xFCfst",
    "wir": "pr\xFCfen"
  }
};

// src/generation/verbconj.ts
var VERB_TOKEN_RE = new RegExp("\\b(" + Object.keys(VERB_CONJ).join("|") + ")\\b", "i");

// src/generation/wordcls.ts
var ICH_DU_HAND = {
  sehe: "sieht",
  siehst: "sieht",
  gehe: "geht",
  gehst: "geht",
  komme: "kommt",
  kommst: "kommt",
  finde: "findet",
  findest: "findet",
  glaube: "glaubt",
  glaubst: "glaubt",
  lebe: "lebt",
  lebst: "lebt",
  liege: "liegt",
  liegst: "liegt",
  sitze: "sitzt",
  lese: "liest",
  liest: "liest",
  schlafe: "schl\xE4ft",
  schl\u00E4fst: "schl\xE4ft",
  laufe: "l\xE4uft",
  l\u00E4ufst: "l\xE4uft",
  falle: "f\xE4llt",
  f\u00E4llst: "f\xE4llt",
  breche: "bricht",
  brichst: "bricht",
  rufe: "ruft",
  rufst: "ruft",
  weine: "weint",
  weinst: "weint",
  lache: "lacht",
  lachst: "lacht",
  sp\u00FCre: "sp\xFCrt",
  sp\u00FCrst: "sp\xFCrt",
  atme: "atmet",
  atmest: "atmet",
  singe: "singt",
  singst: "singt",
  \u00F6ffne: "\xF6ffnet",
  \u00F6ffnest: "\xF6ffnet",
  erinnere: "erinnert",
  erinnerst: "erinnert",
  erkenne: "erkennt",
  erkennst: "erkennt",
  zerbreche: "zerbricht",
  zerbrichst: "zerbricht",
  stolpere: "stolpert",
  stolperst: "stolpert",
  verharre: "verharrt",
  verharrst: "verharrt",
  wandere: "wandert",
  wanderst: "wandert",
  zittere: "zittert",
  zitterst: "zittert",
  fl\u00FCstere: "fl\xFCstert",
  fl\u00FCsterst: "fl\xFCstert",
  wundere: "wundert",
  wunderst: "wundert",
  z\u00F6gere: "z\xF6gert",
  z\u00F6gerst: "z\xF6gert",
  erwache: "erwacht",
  erwachst: "erwacht",
  verschwinde: "verschwindet",
  verschwindest: "verschwindet",
  begreife: "begreift",
  begreifst: "begreift",
  verstehe: "versteht",
  verstehst: "versteht",
  bleibe: "bleibt",
  bleibst: "bleibt",
  ziehe: "zieht",
  ziehst: "zieht"
};
var ICH_DU_ZU_ER = (() => {
  const m = {};
  for (const [dritte, formen] of Object.entries(VERB_CONJ)) {
    for (const p of ["ich", "du", "wir", "ihr"]) {
      const f = formen[p];
      if (f && !m[f]) m[f] = dritte;
    }
  }
  return { ...m, ...ICH_DU_HAND };
})();

// src/features/livepools.ts
var LP_KEY = "divergenz_live_pools_v1";
var LP_CAP = 300;
var LIVE_W = { schatz: 3, korpus: 2, gen: 1 };
var STOP_NOUN = /* @__PURE__ */ new Set([
  "Ich",
  "Er",
  "Sie",
  "Es",
  "Wir",
  "Ihr",
  "Du",
  "Man",
  "Herr",
  "Frau",
  "Herrn",
  "Jahr",
  "Jahre",
  "Jahren",
  "Mal",
  "Weise",
  "Art",
  "Teil",
  "Ende",
  "Anfang",
  "Seite",
  "Stelle"
]);
var ART_NOM = {
  ein: "ein",
  einen: "ein",
  einem: "ein",
  eines: "ein",
  eine: "eine",
  einer: "eine"
};
var PREP = /* @__PURE__ */ new Set([
  "auf",
  "aus",
  "vor",
  "in",
  "mit",
  "ohne",
  "gegen",
  "durch",
  "von",
  "zu",
  "bei",
  "nach",
  "\xFCber",
  "unter",
  "um",
  "wie",
  "als",
  "zwischen"
]);
var clip = (s) => s.replace(/^[^A-Za-zÄÖÜäöüß]+|[^A-Za-zÄÖÜäöüß]+$/g, "");
var isNoun = (w) => /^[A-ZÄÖÜ][A-Za-zÄÖÜäöüß-]{3,}$/.test(w) && !STOP_NOUN.has(w) && w.length <= 24;
function extractPhrases(text) {
  const src = (text || "").replace(/\s+/g, " ").trim();
  if (!src) return [];
  const out = /* @__PURE__ */ new Set();
  for (const sentence of src.split(/[.!?…]+\s+/)) {
    const toks = sentence.split(" ").map(clip).filter(Boolean);
    for (let i = 0; i < toks.length; i++) {
      const w = toks[i];
      if (!isNoun(w)) continue;
      const p1 = i >= 1 ? toks[i - 1].toLowerCase() : "";
      const p2 = i >= 2 ? toks[i - 2].toLowerCase() : "";
      const art = ART_NOM[p1] || (/^[a-zäöüß-]{4,}$/.test(p1) ? ART_NOM[p2] : void 0);
      if (art) {
        out.add(art + " " + w);
        continue;
      }
      if (PREP.has(p1)) out.add(w);
    }
  }
  return [...out];
}
function loadLive() {
  try {
    const v = JSON.parse(localStorage.getItem(LP_KEY) || "[]");
    return Array.isArray(v) ? v.filter((x) => x && typeof x.t === "string") : [];
  } catch {
    return [];
  }
}
function saveLive(list) {
  safeSet(LP_KEY, JSON.stringify(list), "Lebendige Pools");
}
function feedLivePools(text, weight) {
  const phrases = extractPhrases(text);
  if (!phrases.length) return;
  const list = loadLive();
  const idx = new Map(list.map((e, i) => [e.t, i]));
  const now = Date.now();
  for (const p of phrases) {
    const at = idx.get(p);
    if (at === void 0) {
      list.push({ t: p, n: weight, d: now });
      idx.set(p, list.length - 1);
    } else {
      list[at].n += weight;
      list[at].d = now;
    }
  }
  if (list.length > LP_CAP) {
    list.sort((a, b) => b.n - a.n || b.d - a.d);
    list.length = LP_CAP;
  }
  saveLive(list);
}

// src/corpus.ts
function loadPersistentCorpus() {
  try {
    return localStorage.getItem(STORAGE_CORPUS) || "";
  } catch {
    return "";
  }
}
function savePersistentCorpus(text) {
  safeSet(STORAGE_CORPUS, text, "Korpus");
}
var GERUEST_ZEILE = /^\s*(Faktenkasten\b|Kurz gemeldet\s*$|Fiktive Zeitung\b|Zeitzeichen\s*[·|]|Nr\.\s*\d+\s*[·|]|UNABHÄNGIG\b|SEQUENZ\s*—|(?:WER|WO|WANN|WAS|GESAMTLÄNGE)\s*:)/;
function corpusSanitize(text) {
  let s = (text ?? "").toString();
  s = s.split(/\r?\n/).filter((z) => !/^\s*(SEQUENZ\s*—|(?:WER|WO|WANN|WAS|GESAMTLÄNGE)\s*:)/.test(z)).map((z) => z.replace(/^\s*(?:Shot\s*\d+\s*\([^)]*\)|(?:DE|EN)\s*:)\s*/, "")).join("\n");
  s = s.replace(/\([^()]*\)/g, " ");
  s = s.replace(/\b(?:gegen|um|ab|seit|bis)\s+\d{1,2}:\d{2}\b\s*(?:—|–)?\s*/gi, "");
  s = s.replace(/\b\d{1,2}:\d{2}\b\s*—\s*/g, "");
  s = s.replace(/\b(Schluss|Notiz|Rand|Gestern|Jetzt|Später|Drei Tage später)\s*—\s*/g, "");
  s = s.replace(/\bSZENE:\s*/g, "");
  s = s.split(/\r?\n/).filter((z) => !GERUEST_ZEILE.test(z)).join("\n");
  s = s.replace(/Faktenkasten\s*·[^\n]*?(?:\.(?=\s+[A-ZÄÖÜ])|$)/g, " ");
  s = s.replace(/—\s*(?=[.—])/g, "");
  s = s.replace(/\.{2,}/g, ".");
  s = s.replace(/\s+/g, " ").trim();
  return s;
}
function corpusHygiene(text) {
  const src = corpusSanitize(text || "");
  const sentences = src.split(/(?<=[.!?…])\s+/).map((x) => x.trim()).filter(Boolean);
  const charsBefore = (text || "").length;
  const seen = /* @__PURE__ */ new Set();
  const kept = [];
  let duplicates = 0;
  for (const raw of sentences) {
    const letters = (raw.match(/[a-zäöüßA-ZÄÖÜ]/g) || []).length;
    const words = raw.match(/[a-zäöüßA-ZÄÖÜ]{2,}/g) || [];
    if (words.length < 4) continue;
    if (letters / raw.length < 0.45) continue;
    if (!words.some((w) => /[aeiouäöüy]/i.test(w))) continue;
    const upper = words.filter((w) => /^[A-ZÄÖÜ]/.test(w)).length;
    if (words.length < 8 && upper / words.length > 0.7) continue;
    const norm = raw.toLowerCase().replace(/\s+/g, " ");
    if (seen.has(norm)) {
      duplicates++;
      continue;
    }
    seen.add(norm);
    kept.push(/[.!?…]$/.test(raw) ? raw : raw + ".");
  }
  let out = kept.join(" ");
  if (out.length > CORPUS_MAX) {
    out = out.slice(out.length - CORPUS_MAX);
    const cut = out.indexOf(" ");
    if (cut > 0) out = out.slice(cut + 1);
  }
  return { text: out, stats: {
    sentencesBefore: sentences.length,
    sentencesAfter: kept.length,
    removed: sentences.length - kept.length,
    duplicates,
    charsBefore,
    charsAfter: out.length
  } };
}
var SELBSTREINIGUNG_KEY = "dm_korpus_selbstreinigung_v1";
function selbstreinigungAn() {
  try {
    const v = localStorage.getItem(SELBSTREINIGUNG_KEY);
    return v === null ? true : v === "1";
  } catch {
    return true;
  }
}
function setzeSelbstreinigung(an) {
  try {
    localStorage.setItem(SELBSTREINIGUNG_KEY, an ? "1" : "0");
  } catch {
  }
}
var letzte = null;
function letzteReinigung() {
  return letzte;
}
function appendToPersistentCorpus(textToAdd) {
  const add = corpusSanitize(clean(textToAdd));
  if (!add) return;
  try {
    feedLivePools(add, LIVE_W.korpus);
  } catch {
  }
  let corpus = loadPersistentCorpus();
  const sep = corpus.trim().length ? "\n\n" : "";
  corpus = corpus + sep + add;
  if (corpus.length > CORPUS_MAX) {
    corpus = corpus.slice(corpus.length - CORPUS_MAX);
    const cut = corpus.indexOf("\n\n");
    if (cut > 0 && cut < 5e3) corpus = corpus.slice(cut + 2);
  }
  if (selbstreinigungAn()) {
    const h = corpusHygiene(corpus);
    if (h.stats.removed > 0 || h.stats.duplicates > 0) corpus = h.text;
    letzte = { ...h.stats, zeit: (/* @__PURE__ */ new Date()).toLocaleTimeString("de-DE") };
  }
  savePersistentCorpus(corpus);
}

// test/selbstreinigung.ts
var dom = new import_jsdom.JSDOM("<!doctype html><html><body></body></html>", { url: "https://x.test/" });
globalThis.localStorage = dom.window.localStorage;
var fails = [];
var geprueft = 0;
var bestanden = 0;
var ist = (name, wert, soll) => {
  geprueft++;
  if (wert === soll) bestanden++;
  else fails.push(`${name}: \u201E${String(wert)}\u201C \u2014 erwartet \u201E${String(soll)}\u201C`);
};
var wahr = (name, b, zusatz = "") => ist(name + (zusatz ? ` (${zusatz})` : ""), b, true);
var zaehl = (satz) => (loadPersistentCorpus().match(new RegExp(satz.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g")) || []).length;
wahr("Vorgabe: an", selbstreinigungAn());
savePersistentCorpus("");
appendToPersistentCorpus("Der F\xE4hrmann z\xE4hlt am Morgen die Ruder. Ein Riemen fehlt seit dem letzten Sturm. Das Wasser steht still wie ein Gedanke.");
appendToPersistentCorpus("Der F\xE4hrmann z\xE4hlt am Morgen die Ruder. Die Glocke am Steg schl\xE4gt von allein. Ein Riemen fehlt seit dem letzten Sturm.");
ist("doppelte S\xE4tze bleiben nur einmal", zaehl("Der F\xE4hrmann z\xE4hlt am Morgen die Ruder"), 1);
ist("auch der zweite Doppelg\xE4nger", zaehl("Ein Riemen fehlt seit dem letzten Sturm"), 1);
wahr("die neuen S\xE4tze sind da", zaehl("Die Glocke am Steg schl\xE4gt von allein") === 1);
wahr("die letzte Reinigung ist abrufbar", !!letzteReinigung() && letzteReinigung().duplicates >= 1);
setzeSelbstreinigung(false);
ist("Schalter aus wird gehalten", selbstreinigungAn(), false);
appendToPersistentCorpus("Der F\xE4hrmann z\xE4hlt am Morgen die Ruder. Noch ein Satz f\xFCr den Korpus hier.");
ist("aus: Duplikate bleiben stehen", zaehl("Der F\xE4hrmann z\xE4hlt am Morgen die Ruder"), 2);
setzeSelbstreinigung(true);
appendToPersistentCorpus("Ein weiterer Satz kommt hinzu und r\xE4umt auf.");
ist("wieder an: die n\xE4chste Zugabe r\xE4umt auch Altes auf", zaehl("Der F\xE4hrmann z\xE4hlt am Morgen die Ruder"), 1);
savePersistentCorpus("");
var q = (0, import_fs.readFileSync)("src/ui/korpusView.ts", "utf8");
wahr("der Korpus-Reiter hat den Schalter", /"korp-selbstreinigung"/.test(q) && /Selbstreinigung: Duplikate und Bruchstücke automatisch entfernen/.test(q));
wahr("und zeigt die letzte Reinigung", /zuletzt \$\{l\.zeit\}: \$\{l\.removed\} entfernt/.test(q));
var c = (0, import_fs.readFileSync)("src/corpus.ts", "utf8");
wahr("alle Zug\xE4nge gehen durch appendToPersistentCorpus \u2014 dort sitzt die Reinigung", /if \(selbstreinigungAn\(\)\) \{\s*\n\s*const h = corpusHygiene\(corpus\);/.test(c));
console.log(`Pr\xFCfstand Selbstreinigung \u2014 ${geprueft} Pr\xFCfungen, ${bestanden} bestanden`);
var proc = globalThis;
if (fails.length) {
  console.error(`
\u274C Selbstreinigung: ${fails.length} Fehler:`);
  fails.forEach((f) => console.error("  - " + f));
  proc.process?.exit(1);
} else console.log(`
\u2705 Selbstreinigung: alle ${geprueft} Pr\xFCfungen bestanden.`);
