// Hilfe-Tab: erkl\u00e4rt Tabs, Studio-Bedienelemente und Funktionen.
import { el } from "./dom";
import { VERSION } from "../version";

type Item = [string, string];
function section(title: string, rows: Item[]): HTMLElement {
  const ul = el("ul", { class: "help-list" });
  rows.forEach(([k, v]) => ul.append(el("li", {}, el("b", {}, k), " \u2014 " + v)));
  return el("div", { class: "help-sec" }, el("h3", {}, title), ul);
}

export function mountHelp(root: HTMLElement): void {
  root.innerHTML = "";
  const wrap = el("div", { class: "help" });
  wrap.append(el("p", { class: "muted" }, `Divergenzmaschine v${VERSION} \u2014 was die Bedienelemente tun.`));
  wrap.append(section("Kontextzeile (Wo / Wann / Wer / Was)", [["Wo? / Wann? / Wer? / Was passiert?", "die vier Grundangaben, aus denen jede Story gebaut wird. Frei tippen. Bei \"Wer?\" ergeben mehrere durch Komma getrennte Namen einen Dialog (reihum); eine Beschreibung mit Relativsatz z\u00e4hlt als eine Person."], ["Kontext w\u00fcrfeln", "f\u00fcllt Wo/Wann/Wer/Was zuf\u00e4llig aus den Kontext-Pools."], ["Kontext merken", "aktivierbarer Schalter: sichert die aktuellen vier Felder und l\u00e4dt sie bei jedem Start wieder. Erneut klicken schaltet aus und l\u00f6scht den gespeicherten Kontext."]]));
  wrap.append(section("Preset \u00b7 Ton \u00b7 Form", [["Preset", "die aktive Wortbank (eingebaut oder eigene). Beim Start zuf\u00e4llig gew\u00e4hlt; Wechsel l\u00e4dt die Wortbank sofort."], ["Ton", "f\u00e4rbt den Text ein (Einleitung + verteilte Einsch\u00fcbe). Neutral f\u00fcgt nichts hinzu."], ["Form", "Textformat: Prosa (ein Erz\u00e4hler berichtet), Prosagedicht, Gedicht-Strang, Reim, Haiku, Szene/Dialog (B\u00fchnentext mit Sprecherzeilen und Regieanweisungen), Multi-Shot (Video). Merksatz: Prosa erz\u00e4hlt, Szene/Dialog zeigt. Zeilen-/Versformen werden von der Ton-Einf\u00e4rbung ausgenommen."]]));
  wrap.append(section("Aktionen", [["Generieren", "erzeugt aus den aktuellen Angaben und Einstellungen eine neue Story."], ["Variante", "sofort eine weitere Zufallsvariante mit unver\u00e4nderten Einstellungen."], ["W\u00fcrfeln", "w\u00fcrfelt alle Stil-Parameter neu (Ton, Form, Struktur, Modus, Perspektive, Rhythmus, Instabilit\u00e4t, Markov, Disruptor, Varianz, Stil, Preset) \u2014 l\u00e4sst Wo/Wann/Wer/Was unangetastet."], ["Kopieren", "kopiert den angezeigten Text in die Zwischenablage."], ["Merken", "legt den Text dauerhaft in die Schatzkammer (bis 100 Texte) und f\u00fcttert damit den Korpus."], ["Lesen", "Vollbild-Lesemodus mit Werkzeugleiste: A\u2212/A+ (Schriftgr\u00f6\u00dfe), Kopieren, Merken, Vorlesen."], ["Vorlesen", "liest den Text per Browser-Sprachausgabe auf Deutsch vor (offline)."], ["Textl\u00e4nge", "Ziel-Wortzahl (40\u2013300): steuert bei Prosa das K\u00fcrzen/Auff\u00fcllen, bei Szene/Dialog die Rundenzahl."]]));
  wrap.append(section("Stärke der 4W (nur Prosa, experimentell)", [["Wo / Wann / Wer / Was", "je ein kleiner Regler direkt unter jedem 4W-Feld, nur bei Form Prosa sichtbar. Reines Hochregeln: je h\u00f6her ein Regler, desto mehr S\u00e4tze \u00fcber diese Dimension werden eingewoben (mehr Ort-Atmosph\u00e4re, mehr Zeit-Rahmung, mehr \u00fcber die Figur oder mehr Handlung). Standard 0 = neutral. Die Gesamtl\u00e4nge bleibt \u00fcber den Textl\u00e4ngen-Regler stabil; die Gewichtung verschiebt die Verteilung. Wirkt in Echtzeit."]]));
  wrap.append(section("Werkzeugkasten (aufklappbar)", [["Schrift \u00b7 Gr\u00f6\u00dfe", "Schriftart (Serif/Times/Sans/Mono) und Gr\u00f6\u00dfe der Ausgabe; wird lokal gemerkt."], ["Struktur", "Erz\u00e4hlform: Auto (zuf\u00e4llig), Linear, Reverse, Kreis, Fragment, Objekt."], ["Modus", "Realit\u00e4tsmodus (z. B. b\u00fcrokratisch, technologisch, mythisch, absurd \u2026)."], ["Perspektive", "Ich-, Du- oder Er/Sie-Erz\u00e4hler; Verben werden passend konjugiert."], ["Rhythmus \u00b7 Disruptor \u00b7 Instabilit\u00e4t", "steuern Satzl\u00e4ngen-Variation, gezielte Br\u00fcche und die Figuren-Instabilit\u00e4t."], ["Markov", "Anteil, in dem der offline gelernte Markov-Generator (Korpus) mitmischt."], ["Varianz \u00b7 Stil \u00b7 Sprachschliff", "Variationsgrad, Schliff-Stil und die automatische Gl\u00e4ttung bei der Generierung."], ["Video: Shots / Sekunden", "nur bei Form Multi-Shot: Anzahl der Einzelszenen und Ziel-Gesamtl\u00e4nge."]]));
  wrap.append(section("Test & Ranking (im Studio, aufklappbar)", [["Probe (50)", "generiert 50 Varianten und meldet auff\u00e4llige/doppelte."], ["Ranking (50)", "bewertet 50 Varianten offline (L\u00e4ngentreue, Wortvielfalt, Satzrhythmus, wenig Wiederholung) und sortiert sie."], ["KI-Ranking (50)", "l\u00e4sst Claude alle Varianten literarisch bewerten (Originalit\u00e4t, Koh\u00e4renz, Sprache, Sog). Braucht einen API-Schl\u00fcssel."], ["Platz 1 / 2 / 3 und Rang-Slider", "laden Platz 1\u20133 bzw. bl\u00e4ttern per Slider durch alle R\u00e4nge."]]));
  wrap.append(section("Tabs", [["Ideen", "kurze Pr\u00e4missen statt fertiger Storys; \u2192 Studio \u00fcbernimmt eine Idee als Kontext."], ["Schatzkammer", "die mit gemerkten Lieblingstexte: ansehen, ins Studio laden, l\u00f6schen, als TXT exportieren."], ["Welt", "Weltensimulator (Figuren, Orte, Zeitleiste) und Omnikognition: ein Wahrnehmungs-Modus, der aus dem Profil eines Lebewesens (Sinne, Zeit, Selbstmodell \u2026) Perspektive, Rhythmus und Bildwelt formt und ins Studio \u00fcbertr\u00e4gt \u2014 offline oder von der KI geschrieben."], ["Wortbank", "Presets, Auto-Mix, Listen-Editor (7 Kategorien), Mutation, JSON-Import/Export, Als Preset speichern."], ["Korpus", "eigener Trainingstext f\u00fcr den Markov-Generator; dauerhaft im Browser gespeichert, TXT-Export."], ["Oszilloskop", "Satzrhythmus-Analyse eines Textes; aus Generator l\u00e4dt die aktuelle Generierung."], ["KI", "API-Schl\u00fcssel/Modell hinterlegen, KI-Wortbank erzeugen, und Ausarbeiten: den letzten Text oder einen Schatzkammer-Text auf ca. 500/750/1000 W\u00f6rter entfalten (Original + KI-Ausarbeitung nebeneinander, je mit Kopieren)."]]));
  wrap.append(section("Projekt (oben rechts)", [["Speichern", "sichert das ganze Projekt (Wortbank, eigene Presets, Korpus, Einstellungen) als JSON-Datei."], ["Laden", "liest eine zuvor gespeicherte Projekt-JSON wieder ein und aktualisiert die Ansicht."]]));
  root.append(wrap);
}
