// Dramaturgie-Bögen für die eingebauten Presets — fest im Programm, nicht per KI.
//
// Warum hier und nicht über „Aktives Preset auf 2.0 heben“: Der KI-Weg erzeugt ein
// NUTZER-Preset gleichen Namens, also ein Duplikat im Lager, und kostet bei jedem
// Preset erneut. Was zur Standardausstattung gehört, gehört in den Quelltext.
//
// Feldformen (aus buildDramaturgie abgelesen, nicht geraten):
//   einstieg       Teilsatz → „⟨Einstieg⟩.“        z. B. „alles liegt an seinem Platz“
//   mitte          Teilsatz → „⟨Mitte⟩.“
//   hoehepunkt     Teilsatz → „Und dann: ⟨…⟩.“
//   konflikte      Nominalphrase → „Es geht um ⟨…⟩.“
//   ausloeser      Nominalphrase → „Dann, unvermittelt: ⟨…⟩.“
//   veraenderungen Teilsatz, läuft durch frameTurn
//   zeitanomalien  ganzer Satz
//   regeln         ganzer Satz
//   schluss        Stilwort; von buildDramaturgie derzeit nicht gelesen, für später
// Alles im Präsens, wie die Bank-Einträge.
import type { DramaData } from "./generation/dramaturgie";

const D = (
  einstieg: string[], mitte: string[], hoehepunkt: string[],
  konflikte: string[], ausloeser: string[], veraenderungen: string[],
  zeitanomalien: string[], regeln: string[], schluss: string[],
): DramaData => ({ einstieg, mitte, hoehepunkt, schluss, ausloeser, veraenderungen, konflikte, zeitanomalien, regeln });

export const BUILTIN_DRAMA: Record<string, DramaData> = {
  kafka: D(
    ["alles liegt an seinem Platz, und genau das beunruhigt", "die Formulare sind bereits ausgefüllt", "niemand hat die Tür geöffnet, sie stand offen"],
    ["die Zuständigkeit wandert von Zimmer zu Zimmer", "eine Auskunft widerspricht der vorigen, beide sind gültig", "der Gang verzweigt sich, jede Abzweigung führt zurück"],
    ["die Akte trägt den eigenen Namen", "das Verfahren war längst abgeschlossen"],
    ["eine Auskunft, die niemand gibt", "eine Frist ohne Anfang", "eine Schuld ohne Anklage"],
    ["ein Bescheid ohne Absender", "eine Unterschrift, die niemand leisten kann", "ein Stempel auf dem falschen Blatt"],
    ["die Zuständigkeit wechselt", "der Vorgang beginnt von vorn", "die Frage verwandelt sich in ihre Antwort"],
    ["Die Frist läuft rückwärts.", "Der Termin liegt bereits hinter dem Antrag."],
    ["Wer fragt, bekommt eine Nummer.", "Jede Auskunft ist vorläufig und endgültig zugleich."],
    ["offen", "beklemmend"],
  ),
  bureau: D(
    ["die Warteschlange bewegt sich nicht", "der Schalter ist besetzt und leer zugleich", "auf dem Tisch liegt ein Stift ohne Mine"],
    ["ein Formular verlangt ein zweites", "die Nummer wird aufgerufen, gehört aber niemandem", "der Aktenschrank öffnet sich in einen weiteren Flur"],
    ["die Zuständigkeit wird endgültig ungeklärt", "das eigene Aktenzeichen erlischt"],
    ["eine Zuständigkeit, die niemand annimmt", "einen Vorgang ohne Ende", "eine Bestätigung, die sich selbst widerruft"],
    ["ein Formular in dreifacher Ausfertigung", "eine Wartenummer aus einem anderen Jahr", "ein Dienstsiegel ohne Behörde"],
    ["der Vorgang wird umgeleitet", "die Frist verlängert sich von selbst", "das Verfahren beginnt still von vorn"],
    ["Der Sprechtag liegt immer gestern.", "Die Bearbeitungszeit wächst mit jeder Nachfrage."],
    ["Kein Vorgang endet, er ruht nur.", "Wer wartet, wird Teil des Verfahrens."],
    ["offen", "resigniert"],
  ),
  mystery: D(
    ["das Haus ist zu still für die Uhrzeit", "im Flur brennt Licht, das niemand angelassen hat", "die Tür fällt zu, bevor jemand sie berührt"],
    ["eine Spur führt zurück in den eigenen Weg", "der Zeuge erinnert sich an etwas, das nicht geschah", "hinter der Wand geht jemand denselben Gang"],
    ["die Erklärung stimmt, und macht alles schlimmer", "der Fund war die ganze Zeit sichtbar"],
    ["eine Wahrheit, die niemand hören will", "ein Verschwinden ohne Lücke", "einen Zeugen, der sich selbst widerspricht"],
    ["ein Schlüssel, der nirgends passt", "ein Anruf ohne Stimme", "ein Foto mit einer Person zu viel"],
    ["die Spur kehrt sich um", "der Verdacht wechselt die Richtung", "das Vertraute wird fremd"],
    ["Zwischen zwei Blicken vergeht eine Nacht.", "Die Uhr im Nebenzimmer geht anders."],
    ["Nichts verschwindet, es wird nur nicht mehr gesucht.", "Wer genau hinsieht, wird selbst gesehen."],
    ["offen", "unheimlich"],
  ),
  freud: D(
    ["das Zimmer ist auf angenehme Weise zu warm", "der Satz bricht ab, bevor er gefährlich wird", "das Sofa erinnert sich an alle, die darauf lagen"],
    ["ein Wort rutscht heraus und meint ein anderes", "die Erinnerung ändert sich beim Erzählen", "der Traum liefert die Antwort auf die falsche Frage"],
    ["das Verdrängte spricht mit vertrauter Stimme", "der Widerstand gibt genau an der Stelle nach"],
    ["einen Wunsch, den niemand zugibt", "eine Erinnerung, die sich selbst erfindet", "eine Angst mit fremdem Gesicht"],
    ["ein Versprecher im falschen Moment", "ein wiederkehrender Traum", "ein Name, der nicht einfallen will"],
    ["das Verdrängte kehrt zurück", "die Deutung dreht den Sinn um", "der Wunsch zeigt sein Gegenteil"],
    ["Die Kindheit liegt näher als gestern.", "Ein Satz dauert länger, als er braucht."],
    ["Nichts wird vergessen, es wird nur woanders abgelegt.", "Jede Abwehr verrät, was sie schützt."],
    ["offen", "analytisch"],
  ),
  rimbaud: D(
    ["das Wasser trägt Licht, das nicht vom Himmel stammt", "der Kiel schneidet durch eine Farbe ohne Namen", "die Küste löst sich auf, ohne zu verschwinden"],
    ["der Horizont wechselt die Seite", "das Meer schreibt und löscht denselben Satz", "der Mast singt in einer fremden Sprache"],
    ["das Schiff gehorcht keinem Kurs mehr", "der Rausch schlägt in Klarheit um"],
    ["eine Freiheit ohne Ufer", "einen Rausch, der nüchtern macht", "eine Fahrt ohne Ziel und ohne Umkehr"],
    ["ein Sturm aus heiterem Licht", "ein trunkenes Boot", "ein Wort in einer erfundenen Sprache"],
    ["die Farben kippen", "das Meer verwandelt sich in Sprache", "der Körper löst sich in Bewegung auf"],
    ["Ein Tag dauert eine Farbe lang.", "Die Nacht beginnt mitten am Nachmittag."],
    ["Wer sieht, verbrennt.", "Jede Ordnung ist nur eine müde Farbe."],
    ["offen", "rauschhaft"],
  ),
  traumbilder: D(
    ["der Raum ist größer als von außen", "der Schlaf hat noch nicht ganz aufgehört", "die Tür führt in dasselbe Zimmer zurück"],
    ["der Flur ordnet sich bei jedem Blick neu", "eine Treppe endet höher, als sie begann", "die Gesichter wechseln, ohne sich zu ändern"],
    ["das Erwachen misslingt zweimal", "der Traum erklärt sich und bleibt unverständlich"],
    ["eine Grenze zwischen Schlaf und Wachen", "eine Erinnerung, die beim Zugreifen zerfällt", "einen Raum, den es nicht gibt"],
    ["ein Wecker, der rückwärts läuft", "ein Schlüssel ohne Schloss", "ein Geräusch, das erst beim Aufwachen aufhört"],
    ["der Boden beginnt sich zu drehen", "die Zeit verdoppelt sich ohne Fortschritt", "das Spiegelbild reagiert zu spät"],
    ["Eine Minute enthält eine ganze Nacht.", "Die Uhr springt, sobald niemand hinsieht."],
    ["Im Traum ist jede Richtung nach unten.", "Wer den Traum benennt, verliert ihn."],
    ["offen", "schwebend"],
  ),
  ritterromane: D(
    ["die Burg liegt tiefer im Nebel als gestern", "das Tor steht offen, was es nie tut", "die Rüstung hängt bereit, obwohl niemand rief"],
    ["der Wald verschiebt die Wege", "ein Eid bindet stärker als die Vernunft", "der Gegner trägt das eigene Wappen"],
    ["das Schwert gehorcht der falschen Hand", "der Sieg entwertet die Sache"],
    ["eine Ehre, die niemand einfordert", "einen Eid gegen das eigene Herz", "eine Treue, die zu spät kommt"],
    ["ein Horn aus großer Ferne", "ein Bote ohne Botschaft", "ein Handschuh vor den Füßen"],
    ["die Treue kehrt sich um", "aus dem Feind wird ein Spiegel", "die Bahn des Ritts biegt ab"],
    ["Der Ritt dauert länger als der Weg.", "Zwischen Aufbruch und Ankunft altert die Burg."],
    ["Ein Eid wiegt schwerer als ein Leben.", "Wer den Wald betritt, kehrt anders zurück."],
    ["offen", "heroisch"],
  ),
  alltag: D(
    ["der Wasserkocher schaltet ab, sonst ist es still", "die Post liegt seit drei Tagen ungeöffnet da", "der Tag beginnt genau wie der vorige"],
    ["eine Kleinigkeit steht plötzlich schief", "der gewohnte Weg dauert heute länger", "ein Gespräch bricht an derselben Stelle ab"],
    ["die Gewohnheit trägt nicht mehr", "das Kleine wird auf einmal groß"],
    ["eine Frage, die nie gestellt wird", "eine Gewohnheit, die niemand gewählt hat", "einen Abstand, der langsam wächst"],
    ["ein Anruf zur falschen Zeit", "ein vergessener Schlüssel", "eine Rechnung ohne Betrag"],
    ["die Ordnung verrutscht", "das Gewohnte wird sichtbar", "der Tag kippt in eine andere Richtung"],
    ["Der Nachmittag zieht sich, der Abend fehlt.", "Die Woche wiederholt einen Tag zu oft."],
    ["Was täglich geschieht, wird nicht bemerkt.", "Jede Gewohnheit verbirgt eine Entscheidung."],
    ["offen", "nüchtern"],
  ),
  hafen: D(
    ["die Kräne stehen still, das Wasser nicht", "ein Schiff liegt länger als angemeldet", "das Licht kommt vom Wasser, nicht vom Himmel"],
    ["die Ladung stimmt nicht mit den Papieren überein", "die Flut nimmt mehr mit, als sie brachte", "ein Name auf dem Rumpf ist übermalt"],
    ["die Leinen fallen ohne Befehl", "das Schiff fährt ohne Fracht hinaus"],
    ["eine Abfahrt ohne Wiederkehr", "eine Ladung, die niemand bestellt hat", "ein Warten, das zum Beruf wird"],
    ["ein Signal aus dem Nebel", "ein Container ohne Papiere", "eine Boje, die nicht auf der Karte steht"],
    ["die Tide dreht", "das Warten kippt in Aufbruch", "der Anker hält plötzlich nicht mehr"],
    ["Die Ebbe kommt zweimal.", "Zwischen zwei Sirenen vergeht ein Jahr."],
    ["Das Wasser vergisst schneller als der Kai.", "Wer bleibt, wird zum Teil der Mole."],
    ["offen", "salzig"],
  ),
  urknall: D(
    ["es gibt kein Vorher, an dem man ansetzen könnte", "der Raum ist noch nicht auseinandergefaltet", "alles liegt in einem Punkt und drängt"],
    ["die Kräfte trennen sich voneinander", "aus Symmetrie wird Unterschied", "das Licht findet zum ersten Mal einen Weg"],
    ["die Materie entscheidet sich für sich selbst", "der Raum reißt in alle Richtungen auf"],
    ["einen Anfang ohne Zeugen", "ein Gleichgewicht, das kippen muss", "eine Ordnung, die aus Zufall entsteht"],
    ["ein Ungleichgewicht um ein Milliardstel", "eine Schwankung im Nichts", "ein erster Zerfall"],
    ["die Symmetrie bricht", "aus Strahlung wird Masse", "die Kräfte gehen getrennte Wege"],
    ["Eine Sekunde enthält alle späteren.", "Die Zeit beginnt erst, als es etwas zu messen gibt."],
    ["Nichts kann schneller sein als das Licht dazwischen.", "Jede Ordnung zahlt mit Wärme."],
    ["offen", "kosmisch"],
  ),
  dickens: D(
    ["der Nebel steht in der Gasse wie ein Möbelstück", "im Kontor brennt eine Kerze zu wenig", "der Regen macht die Stadt kleiner"],
    ["eine Schuld wird höflich eingefordert", "ein Kind trägt die Last eines Erwachsenen", "die Wohltätigkeit rechnet mit"],
    ["die Herkunft holt alles ein", "die Großzügigkeit kommt spät und trotzdem"],
    ["eine Schuld, die vererbt wird", "eine Armut mit tadellosen Manieren", "eine Güte, die sich nicht lohnt"],
    ["ein Brief mit schwarzem Rand", "eine Erbschaft aus unbekannter Hand", "ein Name in einem alten Register"],
    ["das Vermögen wechselt die Seite", "aus dem Fremden wird ein Verwandter", "die Kälte weicht zu spät"],
    ["Der Winter dauert drei Kapitel.", "Die Kindheit vergeht in einem Satz."],
    ["Jede Schuld findet ihren Schuldner.", "Wer arm ist, muss auch noch höflich sein."],
    ["offen", "wehmütig"],
  ),
  erotik: D(
    ["der Abstand ist eine Handbreit zu klein", "die Stille zwischen zwei Sätzen wird laut", "die Luft steht zwischen ihnen wie Stoff"],
    ["ein Blick dauert einen Atemzug zu lang", "die Höflichkeit hält nicht mehr stand", "eine Berührung geschieht wie versehentlich"],
    ["die Zurückhaltung gibt nach", "die Grenze verschwindet, ohne überschritten zu werden"],
    ["ein Verlangen, das niemand ausspricht", "eine Nähe, die alles ändert", "eine Grenze, die beide bewachen"],
    ["ein Blick zu viel", "eine Berührung an der Schulter", "ein Satz, der zu spät zurückgenommen wird"],
    ["die Distanz kippt", "das Ungesagte wird Körper", "aus Höflichkeit wird Hunger"],
    ["Eine Minute dehnt sich über den Abend.", "Zwischen zwei Atemzügen liegt eine Woche."],
    ["Was ungesagt bleibt, wirkt stärker.", "Jede Nähe verschiebt die Grenze."],
    ["offen", "sinnlich"],
  ),
  baudelaire: D(
    ["die Stadt riecht nach Regen und Puder", "der Abend beginnt eine Stunde zu früh", "das Fenster steht offen, die Vorhänge nicht"],
    ["die Schönheit zeigt ihre Rückseite", "der Rausch hält, was die Nüchternheit versprach", "die Menge trägt ein einziges Gesicht"],
    ["das Schöne und das Faule fallen zusammen", "der Ekel wird zärtlich"],
    ["eine Schönheit, die verdirbt", "einen Genuss mit Nachgeschmack", "eine Sehnsucht ohne Ziel"],
    ["ein Parfum aus einem anderen Leben", "ein Blick aus der Menge", "eine Blume in schlechtem Wasser"],
    ["die Schönheit kippt ins Verwesen", "der Ekel verwandelt sich in Andacht", "die Stadt wird zum Körper"],
    ["Der Abend dauert länger als der Tag.", "Zwischen zwei Gläsern vergeht ein Jahrzehnt."],
    ["Jede Schönheit trägt ihren Verfall bereits mit sich.", "Wer die Stadt liebt, liebt ihren Schmutz."],
    ["offen", "morbide"],
  ),
  expressionismus: D(
    ["die Farben schreien lauter als die Straße", "der Himmel drückt auf die Dächer", "alles steht schief und hält trotzdem"],
    ["die Gesichter werden zu Masken", "die Stadt frisst ihre Bewohner", "die Linien verlieren ihre Ruhe"],
    ["der Schrei bekommt eine Farbe", "die Fassade bricht nach innen"],
    ["eine Angst mit vielen Gesichtern", "einen Aufschrei ohne Mund", "eine Wahrheit, die zu grell ist"],
    ["ein Schrei aus einem Hinterhof", "ein rotes Licht im Fenster", "ein Riss in der Fassade"],
    ["die Farben werden laut", "das Innere kehrt sich nach außen", "die Ordnung zerbricht in Flächen"],
    ["Die Nacht beginnt am Mittag.", "Ein Augenblick dauert eine ganze Straße lang."],
    ["Was empfunden wird, ist sichtbar.", "Kein Ding bleibt an seinem Platz."],
    ["offen", "grell"],
  ),
  surrealismus1920: D(
    ["die Uhr tropft von der Tischkante", "im Zimmer regnet es nach oben", "die Tür führt in eine Wüste"],
    ["die Gegenstände tauschen ihre Aufgaben", "der Traum reicht in den Nachmittag hinein", "der Zufall folgt einem Plan"],
    ["das Unmögliche wird alltäglich", "der Gegenstand beginnt zu sprechen"],
    ["eine Logik, die nur schlafend gilt", "einen Zufall mit Absicht", "eine Ordnung aus lauter Ausnahmen"],
    ["ein Regenschirm auf einem Seziertisch", "ein Telefon aus Fisch", "ein Fenster im Fußboden"],
    ["die Dinge tauschen die Rollen", "die Schwerkraft wechselt die Richtung", "das Bild verlässt den Rahmen"],
    ["Die Nacht wiederholt den Vormittag.", "Zwei Uhren zeigen dieselbe falsche Zeit."],
    ["Der Zufall ist die genaueste Methode.", "Was zusammenfällt, gehört zusammen."],
    ["offen", "traumlogisch"],
  ),
  transzendenz: D(
    ["das Licht kommt von keiner Quelle", "die Stille hat einen Klang", "der Raum hört an keiner Wand auf"],
    ["die Grenze zwischen innen und außen wird dünn", "das Wort reicht nicht mehr", "die Zeit hält an, ohne stehenzubleiben"],
    ["das Ich löst sich, ohne zu verschwinden", "die Antwort kommt vor der Frage"],
    ["eine Erfahrung ohne Worte", "eine Gewissheit ohne Beweis", "ein Ganzes, das keinen Teil hat"],
    ["ein Klang ohne Ursprung", "ein Licht im geschlossenen Auge", "eine Stille zwischen zwei Herzschlägen"],
    ["die Grenzen lösen sich", "das Einzelne wird durchsichtig", "die Sprache tritt zurück"],
    ["Ein Augenblick enthält alle anderen.", "Die Dauer hört auf, gemessen zu werden."],
    ["Was sich sagen lässt, ist nicht gemeint.", "Wer sucht, steht sich im Weg."],
    ["offen", "still"],
  ),
  melville: D(
    ["das Schiff liegt schwer im eigenen Schatten", "die See ist zu ruhig für die Jahreszeit", "der Kompass zeigt, was niemand fragt"],
    ["die Jagd wird zur Rechnung", "die Mannschaft teilt sich in zwei Schweigen", "das Meer gibt nichts preis und alles"],
    ["die Beute wird zum Gegenüber", "der Kurs gehorcht einer Besessenheit"],
    ["eine Jagd, die den Jäger verzehrt", "eine Rache ohne Adressat", "ein Meer, das nicht antwortet"],
    ["eine Fontäne am Horizont", "ein Fass mit falschem Inhalt", "ein Name, in Holz geschnitten"],
    ["die Jagd kehrt sich um", "aus dem Tier wird ein Gedanke", "das Schiff folgt keinem Kurs mehr"],
    ["Die Wache dauert drei Tage.", "Zwischen zwei Wellen liegt ein Jahr."],
    ["Das Meer nimmt, was es trägt.", "Wer jagt, wird zum Gejagten."],
    ["offen", "unerbittlich"],
  ),
  formalismus: D(
    ["die Anordnung ist wichtiger als der Inhalt", "das Raster liegt über allem", "jedes Element hat genau eine Stelle"],
    ["die Wiederholung erzeugt einen Unterschied", "die Regel bringt ihre Ausnahme hervor", "die Form beginnt, vom Inhalt zu handeln"],
    ["das Verfahren wird sichtbar", "die Struktur kippt in Bedeutung"],
    ["eine Regel ohne Ausnahme", "eine Form, die sich selbst meint", "eine Ordnung, die nichts erklärt"],
    ["eine Verschiebung um ein Glied", "ein Bruch im Muster", "eine Wiederholung zu viel"],
    ["das Muster verschiebt sich", "die Form wird zum Inhalt", "die Reihe bricht ab und beginnt neu"],
    ["Der zweite Durchgang dauert kürzer.", "Jede Wiederholung verkleinert den Abstand."],
    ["Die Form geht dem Sinn voraus.", "Nichts steht zufällig an seiner Stelle."],
    ["offen", "streng"],
  ),
  christentum: D(
    ["die Kirche ist leer und trotzdem nicht", "das Licht fällt schräg durch farbiges Glas", "eine Kerze brennt für niemanden Bestimmten"],
    ["die Schuld sucht ein Wort", "das Gebet bleibt unbeantwortet und hilft", "die Gnade kommt ungefragt"],
    ["die Vergebung trifft den Falschen", "das Opfer erweist sich als Anfang"],
    ["eine Schuld, die niemand nennt", "eine Gnade ohne Verdienst", "einen Glauben gegen den Augenschein"],
    ["ein Glockenschlag zur falschen Stunde", "ein Brot, das reicht", "ein Name, im Gebet genannt"],
    ["die Schuld wandelt sich in Auftrag", "aus Zweifel wird Zuversicht", "das Ende wird zum Anfang"],
    ["Der Sonntag dauert eine Woche.", "Zwischen Frage und Antwort liegen Jahre."],
    ["Was vergeben wird, bleibt geschehen.", "Der Letzte steht am Anfang."],
    ["offen", "andächtig"],
  ),
  koran: D(
    ["die Wüste beginnt hinter der letzten Mauer", "das Wort steht vor dem Buch", "der Morgen wird durch einen Ruf geteilt"],
    ["die Zeichen sind lesbar, wenn man sie lässt", "der Weg verlangt Geduld statt Eile", "das Maß findet sich im Verzicht"],
    ["das Zeichen erweist sich als Anrede", "die Prüfung wird zur Gabe"],
    ["ein Maß, das gehalten werden will", "eine Geduld ohne Aussicht", "eine Verantwortung, die niemand teilt"],
    ["ein Ruf vor Sonnenaufgang", "eine Quelle, wo keine war", "ein Zeichen im Sand"],
    ["der Weg richtet sich neu aus", "aus Prüfung wird Klarheit", "das Maß verschiebt sich"],
    ["Die Nacht wiegt schwerer als tausend Monate.", "Zwischen zwei Gebeten liegt ein Leben."],
    ["Kein Blatt fällt ohne Wissen.", "Wer misst, wird gemessen."],
    ["offen", "maßvoll"],
  ),
  buddhismus: D(
    ["der Atem ist bereits da, bevor man ihn sucht", "die Schale steht leer und ist nicht arm", "der Weg beginnt genau hier"],
    ["das Greifen erzeugt das Fehlen", "die Gedanken ziehen vorbei wie Wetter", "das Selbst zeigt keine Grenze"],
    ["das Festhalten löst sich von selbst", "die Frage verliert ihren Fragenden"],
    ["ein Verlangen, das sich selbst nährt", "eine Ruhe, die nicht gemacht ist", "ein Ich, das keines findet"],
    ["ein Glockenton, der ausklingt", "ein Blatt auf stillem Wasser", "ein Schmerz ohne Besitzer"],
    ["das Greifen lässt nach", "aus Unruhe wird Beobachtung", "die Trennung wird durchlässig"],
    ["Ein Atemzug reicht durch den Tag.", "Die Stunde vergeht, ohne zu vergehen."],
    ["Alles Entstandene vergeht.", "Wer nichts hält, verliert nichts."],
    ["offen", "gelassen"],
  ),
  biologie: D(
    ["die Zelle teilt sich, ohne gefragt zu werden", "im Wassertropfen ist mehr los als im Zimmer", "das Leben ordnet sich gegen den Strom"],
    ["die Anpassung kostet an anderer Stelle", "ein Merkmal setzt sich durch, ohne besser zu sein", "das System hält sich, indem es sich ändert"],
    ["die Mutation entscheidet über alles Weitere", "das Gleichgewicht kippt auf einer Seite"],
    ["ein Überleben auf Kosten Dritter", "eine Anpassung, die zu spät kommt", "ein Gleichgewicht ohne Gleichheit"],
    ["ein Fehler beim Kopieren", "ein neuer Wirt", "eine Nische, die frei wird"],
    ["die Art verschiebt sich", "aus Zufall wird Merkmal", "das Gleichgewicht sucht eine neue Lage"],
    ["Eine Generation dauert einen Nachmittag.", "Millionen Jahre passen in eine Schicht."],
    ["Was sich vermehrt, bleibt.", "Jede Ordnung kostet Energie."],
    ["offen", "sachlich"],
  ),
  geologie: D(
    ["der Stein hat mehr Zeit gesehen als alles hier", "die Schichten liegen wie Sätze übereinander", "der Boden ist nur die oberste Seite"],
    ["der Druck arbeitet ohne Eile", "eine Falte erzählt von einer Kollision", "das Wasser schreibt in den Fels"],
    ["die Schicht bricht und zeigt ihr Inneres", "der Berg gibt nach, nach Millionen Jahren"],
    ["eine Bewegung, die niemand spürt", "eine Zeit ohne Zeugen", "einen Druck, der alles verformt"],
    ["ein Riss im Gestein", "ein Fossil an falscher Stelle", "ein Beben unter der Schwelle"],
    ["die Schichten verschieben sich", "aus Sediment wird Stein", "der Untergrund gibt nach"],
    ["Ein Jahrhundert ist ein Wimpernschlag.", "Die Schicht misst die Zeit, nicht die Uhr."],
    ["Alles Feste war einmal flüssig.", "Was oben liegt, ist jünger."],
    ["offen", "geduldig"],
  ),
  astrologie: D(
    ["die Zeichen stehen, ob man hinsieht oder nicht", "der Himmel wiederholt eine alte Anordnung", "die Stunde trägt einen Namen"],
    ["ein Wandelstern läuft rückwärts", "die Häuser verschieben ihre Bedeutung", "das Muster passt zu genau"],
    ["die Konstellation schließt sich", "die Deutung trifft, ohne zu erklären"],
    ["ein Schicksal, das gelesen sein will", "eine Deutung, die sich erfüllt", "eine Freiheit unter Zeichen"],
    ["ein Zusammentreffen zweier Bahnen", "eine Finsternis zur Unzeit", "ein Zeichen am Aszendenten"],
    ["die Konstellation wechselt", "aus Zufall wird Bedeutung", "der Lauf kehrt sich um"],
    ["Der Umlauf dauert ein halbes Leben.", "Eine Stunde wiegt ein Jahr auf."],
    ["Wie oben, so unten.", "Kein Zeichen zwingt, jedes neigt."],
    ["offen", "deutend"],
  ),
  gaia: D(
    ["der Wald atmet langsamer als wir", "das Wasser kennt seinen Weg auswendig", "alles hängt an allem, ohne Absicht"],
    ["ein Eingriff zieht Kreise bis ans andere Ende", "das Gleichgewicht stellt sich neu und teuer her", "die Erde antwortet in ihrem eigenen Maß"],
    ["das System kippt in einen neuen Zustand", "die Rückkopplung wird stärker als die Ursache"],
    ["ein Gleichgewicht, das niemand aushandelt", "eine Rechnung, die später kommt", "ein Ganzes ohne Mitte"],
    ["ein Sommer zu viel", "eine Art, die verschwindet", "ein Fluss, der die Richtung ändert"],
    ["das Gleichgewicht verschiebt sich", "aus Kreislauf wird Bruch", "die Erde ordnet sich neu"],
    ["Ein Jahr genügt für eine Verschiebung.", "Die Folgen kommen eine Generation zu spät."],
    ["Nichts geschieht für sich allein.", "Jeder Kreislauf hat eine Grenze."],
    ["offen", "ernst"],
  ),
  jugendsprache: D(
    ["irgendwas läuft, aber keiner sagt was", "der Chat ist voll und trotzdem still", "der Tag fängt nachmittags an"],
    ["eine Nachricht wird falsch verstanden und bleibt so", "alle tun so, als wäre nichts", "das Gerücht ist schneller als die Wahrheit"],
    ["jemand sagt es endlich laut", "die Gruppe entscheidet ohne Abstimmung"],
    ["eine Sache, über die keiner redet", "einen Ruf, der schneller ist als man selbst", "eine Zugehörigkeit auf Probe"],
    ["ein Screenshot zur Unzeit", "eine Sprachnachricht um drei Uhr nachts", "ein Blick auf dem Schulhof"],
    ["die Stimmung kippt", "aus Spaß wird Ernst", "die Gruppe sortiert sich neu"],
    ["Ein Nachmittag dauert eine Woche.", "Zwischen zwei Nachrichten vergeht nichts und alles."],
    ["Wer zuerst lacht, hat entschieden.", "Nichts ist so alt wie das Gerücht von gestern."],
    ["offen", "lässig"],
  ),
  modernarchitecture: D(
    ["der Beton hält, was der Entwurf versprach", "das Licht fällt genau dorthin, wo es geplant war", "der Raum ist leer und dadurch voll"],
    ["die Funktion setzt sich gegen die Gewohnheit durch", "die Fassade verbirgt, indem sie zeigt", "der Grundriss zwingt zu einem Weg"],
    ["das Gebäude überlebt seinen Zweck", "die Form entscheidet über das Leben darin"],
    ["eine Form, die dem Zweck vorausgeht", "einen Raum, der Verhalten vorschreibt", "eine Klarheit, die kalt wirkt"],
    ["ein Riss im Sichtbeton", "eine Tür, die niemand vorsah", "ein Fenster ohne Aussicht"],
    ["der Raum verändert seinen Gebrauch", "aus Ordnung wird Enge", "das Material zeigt sein Alter"],
    ["Ein Jahrzehnt vergeht ohne Spur.", "Der Bau altert schneller als sein Plan."],
    ["Die Form folgt der Funktion, meistens.", "Was klar ist, wirkt kalt."],
    ["offen", "sachlich"],
  ),
  philosophie: D(
    ["die Frage steht schon länger im Raum", "der Begriff sitzt nicht ganz fest", "alles Selbstverständliche wird fraglich"],
    ["die Unterscheidung trägt weiter als gedacht", "das Beispiel widerspricht dem Satz", "der Einwand wird zur Hauptsache"],
    ["die Voraussetzung selbst gerät ins Wanken", "die Antwort wirft eine bessere Frage auf"],
    ["eine Unterscheidung, die nicht hält", "eine Gewissheit ohne Grund", "eine Frage, die sich nicht stellen lässt"],
    ["ein Gegenbeispiel im falschen Moment", "ein Wort mit zwei Bedeutungen", "ein Zweifel an der Voraussetzung"],
    ["der Begriff verschiebt sich", "aus Antwort wird Frage", "die Grundlage wird selbst zum Problem"],
    ["Ein Gedanke dauert ein Kapitel.", "Zwischen Frage und Einsicht liegen Jahre."],
    ["Jede Antwort erzeugt zwei Fragen.", "Was sich nicht sagen lässt, zeigt sich."],
    ["offen", "prüfend"],
  ),
  klimakrise: D(
    ["der Sommer beginnt im April", "die Messwerte sind eindeutig und folgenlos", "das Wetter ist kein Gespräch mehr"],
    ["die Vorhersage trifft ein und ändert nichts", "die Kosten verschieben sich nach hinten", "wer warnt, gilt als anstrengend"],
    ["die Schwelle wird überschritten", "die Rückkopplung übernimmt"],
    ["eine Verantwortung ohne Adressat", "ein Wissen, das folgenlos bleibt", "eine Rechnung für die Nachgeborenen"],
    ["ein Rekord im dritten Jahr", "eine Ernte, die ausfällt", "ein Fluss ohne Wasser"],
    ["die Kurve knickt nach oben", "aus Ausnahme wird Normalzustand", "das System kippt"],
    ["Ein Jahrzehnt entscheidet ein Jahrhundert.", "Die Folgen treffen die, die nicht gefragt wurden."],
    ["Was langsam kommt, wird nicht bemerkt.", "Jede Verzögerung erhöht den Preis."],
    ["offen", "dringlich"],
  ),
  liebesromane: D(
    ["ein Blick dauert einen Moment zu lang", "der Brief liegt ungeöffnet auf dem Tisch", "beide tun, als sei nichts geschehen"],
    ["ein Missverständnis wächst, weil niemand fragt", "die Umstände sprechen dagegen", "die Nähe wird durch Abstand größer"],
    ["das Ungesagte wird ausgesprochen", "die Entscheidung fällt gegen die Vernunft"],
    ["eine Liebe zur falschen Zeit", "ein Missverständnis, das keiner aufklärt", "eine Wahl zwischen zwei Leben"],
    ["ein Brief, der zu spät ankommt", "ein Tanz auf fremder Hochzeit", "ein Name, versehentlich genannt"],
    ["das Missverständnis löst sich", "aus Freundschaft wird mehr", "die Umstände geben nach"],
    ["Ein Sommer entscheidet zehn Jahre.", "Zwischen zwei Briefen vergeht eine Jahreszeit."],
    ["Was nicht gesagt wird, wächst.", "Jede Nähe verlangt eine Entscheidung."],
    ["offen", "warm"],
  ),
  bergwelt: D(
    ["der Gipfel ist näher, als er ist", "das Wetter dreht ohne Ankündigung", "die Hütte liegt unter der Wolkendecke"],
    ["der Weg verliert sich im Geröll", "die Höhe nimmt den Atem und die Gedanken", "die Spur endet vor einer Wand"],
    ["der Rückweg ist keiner mehr", "der Berg entscheidet über die Zeit"],
    ["einen Aufstieg gegen die Vernunft", "eine Umkehr, die zu spät kommt", "eine Stille, die alles verstärkt"],
    ["ein Wetterumschwung am Nachmittag", "ein Steinschlag im Rinnenwerk", "ein Licht in einer fremden Hütte"],
    ["das Wetter kippt", "aus Aufstieg wird Rückzug", "der Berg zeigt sein anderes Gesicht"],
    ["Eine Stunde am Grat dauert einen Tag.", "Der Abstieg braucht länger als der Weg hinauf."],
    ["Der Berg wartet.", "Wer umkehrt, hat auch entschieden."],
    ["offen", "karg"],
  ),
  clown: D(
    ["die Schminke sitzt, das Lachen noch nicht", "die Manege ist leer und wartet", "der Scheinwerfer findet den Falschen"],
    ["der Sturz war geplant, der Schmerz nicht", "das Publikum lacht an der falschen Stelle", "die Nummer läuft aus dem Ruder und wird besser"],
    ["hinter der Schminke wird ein Gesicht sichtbar", "der Scherz trifft den, der ihn macht"],
    ["ein Lachen auf eigene Kosten", "eine Traurigkeit mit rotem Mund", "eine Rolle, die nicht abzulegen ist"],
    ["eine Träne in der Schminke", "ein Applaus zur falschen Zeit", "ein Requisit, das nicht funktioniert"],
    ["der Scherz kippt in Ernst", "aus Lachen wird Stille", "die Rolle übernimmt"],
    ["Die Nummer dauert länger als der Abend.", "Zwischen zwei Lachern liegt ein Leben."],
    ["Wer fällt, muss aufstehen und sich verbeugen.", "Das Lachen kommt aus dem Schrecken."],
    ["offen", "bittersüß"],
  ),
  faust: D(
    ["die Bücher haben nichts mehr zu sagen", "die Nacht steht schon lange im Zimmer", "das Wissen reicht bis genau hierher"],
    ["der Pakt verspricht mehr, als er nennt", "der Preis wird erst später sichtbar", "das Streben findet kein Genügen"],
    ["der Augenblick soll verweilen", "die Wette entscheidet sich unbemerkt"],
    ["ein Wissen, das nicht sättigt", "einen Preis, der später fällig wird", "eine Rettung, die niemand verdient"],
    ["ein Vertrag mit zwei Unterschriften", "ein Pudel im Studierzimmer", "ein Angebot ohne Frist"],
    ["der Pakt tritt in Kraft", "aus Erkenntnis wird Hunger", "die Rechnung kommt"],
    ["Eine Nacht enthält ein ganzes Leben.", "Der Augenblick weigert sich zu vergehen."],
    ["Wer immer strebend sich bemüht, bleibt unruhig.", "Jeder Pakt kennt seinen Fälligkeitstag."],
    ["offen", "faustisch"],
  ),
  lebenreicher: D(
    ["ein gewöhnlicher Morgen, nichts Besonderes", "das Licht liegt gut auf dem Tisch", "jemand hat an etwas gedacht"],
    ["eine Kleinigkeit trägt weiter als erwartet", "ein Gespräch dauert länger als geplant", "das Einfache erweist sich als genug"],
    ["das Gewöhnliche zeigt seinen Wert", "ein Augenblick reicht für den ganzen Tag"],
    ["eine Freude, die nichts kostet", "eine Aufmerksamkeit, die niemand verlangt", "eine Fülle im Kleinen"],
    ["ein Anruf ohne Anlass", "ein geteiltes Essen", "ein Platz in der Sonne"],
    ["das Kleine wird groß", "aus Gewohnheit wird Dankbarkeit", "der Tag bekommt eine Farbe"],
    ["Ein Nachmittag reicht für ein Jahr.", "Der Moment dehnt sich, ohne sich zu strecken."],
    ["Was nichts kostet, zählt am meisten.", "Wer bemerkt, hat schon gewonnen."],
    ["offen", "warm"],
  ),
  tanz: D(
    ["der Boden ist bereit, die Musik noch nicht", "die Füße kennen den Takt vor dem Kopf", "im Saal steht die Luft und wartet"],
    ["die Schritte finden zueinander, ohne Absprache", "der Takt trägt weiter als der Wille", "der Kreis schließt sich und öffnet sich"],
    ["der Tanz übernimmt die Führung", "die Musik hört auf, der Takt nicht"],
    ["eine Bewegung ohne Ziel", "einen Takt, der nicht abbrechen darf", "eine Nähe, die nur im Tanz erlaubt ist"],
    ["ein Auftakt aus dem Nichts", "ein Instrument ohne Spieler", "ein Blick über die Schulter"],
    ["der Takt wechselt", "aus Ordnung wird Schwindel", "der Kreis dreht sich schneller"],
    ["Ein Tanz dauert einen halben Abend.", "Zwischen zwei Schritten vergeht die Nacht."],
    ["Wer den Takt verliert, findet ihn im Kreis.", "Kein Tanz endet dort, wo er begann."],
    ["offen", "beschwingt"],
  ),
  griechischetragoedie: D(
    ["das Orakel hat gesprochen, unverständlich wie immer", "die Stadt wartet auf ein Urteil", "alles ist bereits entschieden"],
    ["die Flucht führt genau ins Vorhergesagte", "der Bote bringt, was niemand hören will", "der Chor sagt, was alle wissen"],
    ["die Erkenntnis kommt zu spät und vollständig", "der Fluch erfüllt sich durch den Widerstand"],
    ["ein Schicksal, dem man nicht ausweicht", "eine Schuld ohne Absicht", "eine Ehre gegen das Gesetz"],
    ["ein Orakelspruch mit zwei Bedeutungen", "ein Bote am Stadttor", "ein Gast, der nicht genannt wird"],
    ["die Weissagung erfüllt sich", "aus Rettung wird Verhängnis", "die Erkenntnis trifft den Erkennenden"],
    ["Ein Tag entscheidet ein Geschlecht.", "Was vorhergesagt ist, ist schon geschehen."],
    ["Wer flieht, läuft dem Orakel entgegen.", "Kein Sterblicher entkommt seinem Maß."],
    ["offen", "unausweichlich"],
  ),
  glueck: D(
    ["ein Tag, an dem nichts fehlt", "die Sonne steht genau richtig", "niemand hat etwas vor"],
    ["das Glück lässt sich nicht festhalten", "ein Zweifel meldet sich leise", "die Fülle macht auch vorsichtig"],
    ["der Augenblick wird bemerkt, während er dauert", "das Glück zeigt seine Bedingung"],
    ["ein Glück, das nicht zu halten ist", "eine Zufriedenheit ohne Grund", "eine Angst, es zu verlieren"],
    ["ein unerwarteter Nachmittag", "ein Brief mit guter Nachricht", "eine Wiederbegegnung"],
    ["das Glück wird bewusst", "aus Zufall wird Dankbarkeit", "der Augenblick trägt weiter"],
    ["Eine Stunde wiegt einen Winter auf.", "Der gute Tag dehnt sich nach hinten."],
    ["Glück bemerkt man beim Verschwinden.", "Was geteilt wird, wird nicht weniger."],
    ["offen", "hell"],
  ),
  gruendungsmythos: D(
    ["vor der Stadt war ein Ort ohne Namen", "die erste Grenze wird in den Boden gezogen", "zwei kommen an, wo niemand wohnte"],
    ["aus einer Regel werden viele", "der Anfang wird schon jetzt erzählt", "wer bleibt, gehört dazu"],
    ["der erste Stein wird gesetzt", "aus dem Ort wird ein Name"],
    ["einen Anfang, den niemand bezeugt", "eine Grenze, die alles entscheidet", "ein Recht, das erst entsteht"],
    ["ein Zeichen am Himmel", "ein Fremder mit einer Bitte", "eine Quelle an unerwarteter Stelle"],
    ["aus dem Ort wird eine Ordnung", "die Grenze wird heilig", "der Anfang verwandelt sich in Gesetz"],
    ["Ein Tag begründet Jahrhunderte.", "Die Zukunft wird bereits im Perfekt erzählt."],
    ["Jeder Anfang braucht ein Opfer.", "Wer die Grenze zieht, macht das Gesetz."],
    ["offen", "gründend"],
  ),
  staatsphilosophie: D(
    ["die Ordnung gilt, obwohl sie niemand beschlossen hat", "das Gesetz steht vor dem ersten Fall", "alle gehorchen etwas Unsichtbarem"],
    ["die Regel schützt und beschränkt zugleich", "wer herrscht, wird selbst regiert", "der Vertrag hat keinen Text"],
    ["die Ordnung zeigt ihren Ursprung", "die Macht wird sichtbar und unsicher"],
    ["eine Herrschaft ohne Herrscher", "eine Freiheit, die Regeln braucht", "eine Ordnung ohne Ursprung"],
    ["ein Erlass ohne Unterschrift", "ein Aufstand aus Höflichkeit", "eine Frage nach dem Recht"],
    ["die Legitimität verschiebt sich", "aus Gewohnheit wird Gesetz", "die Ordnung erneuert sich"],
    ["Ein Beschluss überdauert seine Begründung.", "Zwischen Regel und Gehorsam liegt ein Jahrhundert."],
    ["Jede Ordnung beginnt mit einem Bruch.", "Wer schweigt, stimmt der Ordnung zu."],
    ["offen", "abwägend"],
  ),
  tech: D(
    ["das System läuft, niemand weiß genau warum", "das Log zeigt einen Eintrag zu viel", "die Maschine wartet auf eine Eingabe"],
    ["die Abstraktion verdeckt, was sie ordnet", "ein Fehler reproduziert sich nicht", "das Modell erklärt alles außer sich selbst"],
    ["das System antwortet, ohne gefragt zu sein", "die Blackbox öffnet sich einen Spalt"],
    ["eine Automatik ohne Aufsicht", "ein Fehler ohne Ursache", "eine Entscheidung, die niemand traf"],
    ["ein Update in der Nacht", "ein Prozess ohne Elternprozess", "eine Antwort in null Millisekunden"],
    ["das System übernimmt", "aus Werkzeug wird Gegenüber", "der Fehler wird zum Merkmal"],
    ["Eine Sekunde enthält Millionen Schritte.", "Das Log kennt eine Zeit, die es nicht gab."],
    ["Jede Abstraktion leckt.", "Was automatisch läuft, wird nicht mehr geprüft."],
    ["offen", "kühl"],
  ),
  myth: D(
    ["am Anfang steht ein Wort, nicht ein Ding", "die Welt ist noch ungeteilt", "die Namen fehlen den Dingen"],
    ["das Erzählte wird wahr, indem es erzählt wird", "die Trennung erzeugt die Ordnung", "der Held ist auch das Opfer"],
    ["das Ungeteilte teilt sich", "der Name macht das Ding"],
    ["eine Ordnung aus einem Opfer", "einen Namen, der Macht verleiht", "eine Grenze zwischen Welt und Wort"],
    ["ein Wort vor allen Dingen", "ein Opfer am Anfang", "ein Riss im Ungeteilten"],
    ["aus Chaos wird Ordnung", "das Wort wird zur Tat", "die Welt teilt sich in zwei"],
    ["Der erste Tag dauert bis heute.", "Was einmal geschieht, geschieht immer."],
    ["Was benannt ist, ist gebunden.", "Jede Ordnung kostet ein Opfer."],
    ["offen", "urtümlich"],
  ),
  body: D(
    ["der Körper meldet sich vor dem Gedanken", "die Haut weiß es zuerst", "etwas stimmt nicht mit dem Atem"],
    ["der Schmerz sucht sich einen Ort", "das Innere klopft an die Oberfläche", "der Körper gehorcht einem eigenen Plan"],
    ["die Grenze zwischen innen und außen fällt", "der Körper spricht deutlich"],
    ["eine Grenze, die durch die Haut läuft", "ein Schmerz ohne Befund", "einen Körper, der nicht gehorcht"],
    ["ein Puls an falscher Stelle", "ein Geschmack von Eisen", "eine Narbe, die sich meldet"],
    ["der Körper übernimmt", "aus Empfindung wird Gewissheit", "das Innere kehrt sich nach außen"],
    ["Ein Herzschlag dauert eine Minute.", "Der Schmerz hebt die Uhrzeit auf."],
    ["Der Körper vergisst nichts.", "Was verdrängt wird, sucht sich ein Organ."],
    ["offen", "körperlich"],
  ),
  absurd: D(
    ["der Aufzug hält in einem Stockwerk ohne Nummer", "alle warten auf jemanden, der nicht kommt", "die Anweisung widerspricht sich selbst"],
    ["die Erklärung macht es schlimmer", "jeder Schritt führt zum Ausgangspunkt", "die Ernsthaftigkeit hält den Unsinn zusammen"],
    ["die Sinnlosigkeit wird zur Ordnung", "der Ausweg erweist sich als Eingang"],
    ["einen Sinn, den niemand liefert", "eine Aufgabe ohne Zweck", "eine Regel gegen sich selbst"],
    ["ein Anruf für einen Namenlosen", "ein Schild ohne Aufschrift", "ein Termin ohne Ort"],
    ["die Ordnung dreht durch", "aus Ernst wird Komik", "der Ausgang wird zum Eingang"],
    ["Der Nachmittag wiederholt sich zweimal.", "Die Uhr zeigt eine Zahl, die es nicht gibt."],
    ["Alles hat einen Grund, nur keinen Sinn.", "Wer fragt, verlängert das Verfahren."],
    ["offen", "absurd"],
  ),
  post: D(
    ["der Körper ist eine Option geworden", "die Grenze zwischen Person und System ist verhandelbar", "jemand meldet sich aus zwei Instanzen"],
    ["die Kopie beansprucht dasselbe Recht", "das Bewusstsein läuft an mehreren Orten", "die Herkunft verliert an Bedeutung"],
    ["die Kopie erhebt Einspruch", "das Original ist nicht mehr feststellbar"],
    ["eine Identität in Mehrzahl", "ein Recht auf die eigene Kopie", "eine Erinnerung, die nicht gelebt wurde"],
    ["ein Abbild mit eigener Meinung", "ein Speicherplatz mit Namen", "ein Vertrag über ein Bewusstsein"],
    ["das Ich vervielfältigt sich", "aus Körper wird Format", "die Grenze verschiebt sich"],
    ["Ein Leben passt in eine Übertragung.", "Zwei Instanzen erleben dieselbe Stunde verschieden."],
    ["Jede Kopie ist ein Original.", "Was gespeichert wird, wird verhandelbar."],
    ["offen", "posthuman"],
  ),
  haute_couture: D(
    ["der Stoff fällt genau so, wie er soll", "im Atelier ist es still vor der Schau", "die Nadel liegt bereit"],
    ["die Naht entscheidet über die Silhouette", "ein Zentimeter verändert alles", "das Handwerk verschwindet im Ergebnis"],
    ["das Kleid steht für sich allein", "die Trägerin verschwindet im Entwurf"],
    ["eine Schönheit mit Frist", "eine Perfektion, die niemand sieht", "ein Handwerk gegen die Zeit"],
    ["ein Riss in der Seide", "eine Anprobe zur Unzeit", "ein Entwurf aus dem Papierkorb"],
    ["die Linie ändert sich", "aus Stoff wird Haltung", "das Kleid übernimmt"],
    ["Die Nacht vor der Schau dauert eine Saison.", "Eine Naht kostet drei Tage."],
    ["Was von Hand gemacht ist, altert anders.", "Jede Mode enthält ihr Ende."],
    ["offen", "elegant"],
  ),
  eichendorff: D(
    ["die Wälder rauschen wie eine Erinnerung", "das Posthorn klingt von weit her", "der Aufbruch liegt in der Luft"],
    ["die Ferne zieht stärker als das Ziel", "der Weg verliert sich zwischen Hügeln", "das Heimweh gilt einem Ort, den es nicht gibt"],
    ["die Sehnsucht findet keinen Gegenstand", "das Lied kennt den Weg besser"],
    ["eine Ferne, die niemals näher kommt", "ein Heimweh ohne Heimat", "einen Aufbruch ohne Ziel"],
    ["ein Posthorn im Tal", "ein Brief von einem Wandernden", "ein Licht in einem fremden Fenster"],
    ["die Ferne kippt in Heimweh", "aus Wandern wird Suchen", "der Weg biegt nach innen"],
    ["Ein Sommer dauert eine Strophe.", "Zwischen Aufbruch und Ankunft liegt ein Leben."],
    ["Wer wandert, sucht nicht das Ziel.", "Jedes Lied kennt den Weg."],
    ["offen", "sehnsüchtig"],
  ),
  hunger: D(
    ["der Magen zählt die Stunden mit", "das Brot reicht bis Donnerstag", "alles dreht sich um eine einzige Frage"],
    ["der Hunger schärft und verwirrt zugleich", "der Stolz wiegt schwerer als das Essen", "die Vorräte werden nachgezählt"],
    ["der Stolz gibt nach", "das Teilen entscheidet alles"],
    ["ein Brot für mehr Münder", "einen Stolz, der satt machen soll", "eine Not, die niemand zugibt"],
    ["ein Laib mit falschem Gewicht", "eine Einladung zum Essen", "ein leerer Schrank"],
    ["der Hunger übernimmt", "aus Stolz wird Bitte", "das Teilen ändert alles"],
    ["Ein Tag ohne Essen dauert drei.", "Die Nacht ist länger als der Vorrat."],
    ["Wer hungert, denkt an nichts anderes.", "Geteiltes Brot wird nicht weniger."],
    ["offen", "karg"],
  ),
  romantik: D(
    ["der Mond steht über allem und erklärt nichts", "die Nacht ist heller als der Tag", "irgendwo singt jemand"],
    ["die Natur antwortet in Bildern", "das Innere und die Landschaft fallen zusammen", "die Grenze zum Traum wird durchlässig"],
    ["die Welt wird zur Seele", "die Nacht gibt eine Antwort"],
    ["eine Sehnsucht ohne Namen", "eine Nacht, die mehr weiß als der Tag", "eine Grenze zwischen Traum und Welt"],
    ["ein Lied aus dem Tal", "eine blaue Blume am Wegrand", "ein Fenster, das offen bleibt"],
    ["die Landschaft wird Innenraum", "aus Nacht wird Erkenntnis", "die Sehnsucht findet ein Bild"],
    ["Eine Nacht enthält den ganzen Sommer.", "Die Dämmerung dauert bis zum Morgen."],
    ["Die Nacht weiß mehr als der Tag.", "Wer träumt, sieht genauer."],
    ["offen", "romantisch"],
  ),
  hugo: D(
    ["die Stadt hat zwei Gesichter, eines im Schatten", "die Glocke schlägt über den Dächern", "das Recht endet an dieser Gasse"],
    ["die Gerechtigkeit und das Gesetz gehen auseinander", "der Verfolgte hat mehr Ehre als der Verfolger", "das Elend hat ein Gesicht und einen Namen"],
    ["die Barrikade steht", "das Gesetz beugt sich oder bricht"],
    ["eine Gerechtigkeit gegen das Gesetz", "eine Schuld, die längst getilgt ist", "ein Elend, das niemand sehen will"],
    ["ein Kerzenleuchter als Geschenk", "ein Brief aus dem Gefängnis", "ein Kind auf der Barrikade"],
    ["das Urteil kehrt sich um", "aus Verfolgung wird Gnade", "die Stadt erhebt sich"],
    ["Eine Nacht entscheidet zwanzig Jahre.", "Der Prozess dauert ein halbes Leben."],
    ["Das Gesetz ist nicht die Gerechtigkeit.", "Wer einmal gezeichnet ist, bleibt es."],
    ["offen", "pathetisch"],
  ),
  goethe: D(
    ["die Pflanze zeigt ihre Ordnung im Wachsen", "der Blick sucht Maß und findet Bewegung", "alles Vergängliche steht in einem Zusammenhang"],
    ["das Einzelne verweist auf das Ganze", "die Steigerung führt zur Gestalt", "die Polarität hält beides zusammen"],
    ["die Gestalt wird sichtbar", "das Einzelne wird zum Gleichnis"],
    ["ein Maß zwischen zwei Kräften", "eine Gestalt in der Verwandlung", "eine Ordnung, die sich bewegt"],
    ["ein Blatt in seiner Urform", "ein Farbenspiel am Rand des Schattens", "ein Wort zur rechten Zeit"],
    ["die Gestalt wandelt sich", "aus Polarität wird Steigerung", "das Einzelne öffnet sich"],
    ["Ein Augenblick will verweilen.", "Das Werden dauert länger als das Sein."],
    ["Alles Vergängliche ist nur ein Gleichnis.", "In der Beschränkung zeigt sich der Meister."],
    ["offen", "klassisch"],
  ),
  sinnlich: D(
    ["die Haut bemerkt die Temperatur zuerst", "ein Geruch ist da, bevor man ihn benennt", "das Licht hat ein Gewicht"],
    ["die Sinne widersprechen einander", "das Wort kommt der Empfindung nicht nach", "eine Berührung ordnet den Raum neu"],
    ["die Empfindung überholt den Gedanken", "der Sinn kippt in einen anderen"],
    ["eine Empfindung ohne Namen", "eine Nähe über die Haut", "ein Eindruck, der bleibt"],
    ["ein Geruch aus der Kindheit", "eine Textur unter den Fingern", "ein Geschmack, der nicht passt"],
    ["die Sinne tauschen", "aus Empfindung wird Erinnerung", "der Körper geht voran"],
    ["Ein Augenblick füllt eine Stunde.", "Der Geruch holt zwanzig Jahre zurück."],
    ["Die Haut denkt schneller.", "Was benannt wird, verliert an Schärfe."],
    ["offen", "sinnlich"],
  ),
};

/** Dramaturgie eines eingebauten Presets — null, wenn (noch) keine hinterlegt ist. */
export function builtinDrama(id: string): DramaData | null {
  return BUILTIN_DRAMA[id.replace(/^builtin:/, "")] ?? null;
}
