export const CTX_WHO: string[] = [
 "Rubin",
 "eine Uhrmacherin",
 "ein pensionierter Richter",
 "die Tochter eines Leuchtturmwärters",
 "ein Spion im Ruhestand",
 "eine Archivarin",
 "Zwillinge, die sich nie begegnet sind",
 "ein Algorithmus mit Namen",
 "eine Falschmünzerin",
 "der letzte Zeuge",
 "ein Kartograph ohne Karten",
 "eine Chirurgin mit zitternden Händen",
 "ein Mönch, der das Schweigen gebrochen hat",
 "eine Diplomatin ohne Land",
 "ein Kind, das zu viel weiß",
 "zwei Fremde mit demselben Gesicht",
 "eine Bibliothekarin ohne Namen",
 "ein Boxer im Ruhestand",
 "die Witwe eines Uhrmachers",
 "ein Übersetzer für tote Sprachen",
 "eine Pilotin ohne Lizenz",
 "der Sohn eines Fälschers",
 "eine Nonne, die die Welt bereist hat",
 "ein Buchhalter mit doppeltem Gedächtnis",
 "die letzte Erbin eines Zirkus",
 "ein Fremder, der jeden Namen kennt",
 "eine Richterin im Exil",
 "ein Uhrmacher, der die Zeit hasst",
 "zwei Schwestern mit getauschten Leben",
 "ein Kind aus einer anderen Zeit"
];
export const CTX_WHERE: string[] = [
 "in Paris",
 "im Archiv",
 "am Fluss",
 "in einem verlassenen Bahnhof",
 "auf einem Frachtschiff",
 "in der Bibliothek der Universität",
 "an der Grenze zweier Länder",
 "in einem stillgelegten Bergwerk",
 "auf einem Friedhof bei Nacht",
 "in einer Anwaltskanzlei",
 "auf hoher See",
 "im Keller eines Museums",
 "in einer Telefonzelle",
 "auf einem Jahrmarkt",
 "in einem leerstehenden Krankenhaus",
 "auf dem Dach eines Hochhauses",
 "in einer Kirche ohne Gemeinde",
 "im Wartezimmer eines Arztes",
 "auf einem verlassenen Flughafen",
 "in einer Uhrmacherwerkstatt",
 "in einem Hotel ohne Gäste",
 "am Rand eines Vulkans",
 "in einer U-Bahn-Station um Mitternacht",
 "auf einem zugefrorenen See",
 "in einem Gewächshaus",
 "an Bord eines Zeppelins",
 "in einer verlassenen Fabrikhalle",
 "auf einem Leuchtturm",
 "in einem Spielsalon",
 "an einer verlassenen Tankstelle"
];
export const CTX_WHEN: string[] = [
 "1789",
 "im Winter",
 "kurz vor Mitternacht",
 "1917",
 "im Morgengrauen",
 "am Tag der Sonnenfinsternis",
 "2041",
 "während eines Generalstreiks",
 "am letzten Tag des Jahres",
 "im Jahr der großen Flut",
 "1348",
 "an einem Sonntagnachmittag",
 "während einer Belagerung",
 "im Moment des Erwachens",
 "kurz nach dem Krieg",
 "an ihrem Hochzeitstag",
 "im Jahr, als die Maschinen sprechen lernten",
 "1666",
 "im Hochsommer",
 "zwischen zwei Weltkriegen",
 "am Vorabend der Wahl",
 "im Jahr der Dürre",
 "kurz vor Sonnenaufgang",
 "während der Quarantäne",
 "1923",
 "am Tag ihrer Entlassung",
 "im letzten Sommer vor dem Umzug",
 "während eines Stromausfalls",
 "2099",
 "an dem Tag, an dem die Uhren stehen blieben"
];
export const CTX_WHAT: string[] = [
 "sucht eine Spur",
 "will verschwinden",
 "findet einen Brief, der nicht an sie gerichtet war",
 "verliert die Erinnerung an einen Namen",
 "tauscht die Identität mit einem Fremden",
 "entdeckt ein zweites Testament",
 "muss eine Entscheidung binnen einer Stunde treffen",
 "wird für tot erklärt",
 "bricht ein Versprechen aus Kindheitstagen",
 "findet eine Tür, die es nicht geben dürfte",
 "verrät einen alten Verbündeten",
 "erhält eine Nachricht aus der Zukunft",
 "verliert die Kontrolle über die eigene Stimme",
 "muss ein Geheimnis vor sich selbst verbergen",
 "kehrt an einen Ort zurück, den es nicht mehr gibt",
 "stiehlt ein Geständnis",
 "verwechselt zwei Wahrheiten",
 "wird von der eigenen Vergangenheit erpresst",
 "erkennt sich selbst in einem Fremden",
 "verliert eine Wette, die niemand sah",
 "bricht in ein leeres Haus ein",
 "wartet auf eine Antwort, die nie kommt",
 "zerstört einen Beweis aus Versehen",
 "übernimmt die Schuld eines anderen",
 "entdeckt, dass die Uhr rückwärts läuft",
 "schreibt einen Brief, den sie nie abschickt",
 "verliert den Glauben an das eigene Gedächtnis",
 "rettet einen Fremden und bereut es",
 "findet ihren eigenen Namen auf einer Liste",
 "muss eine Lüge zu Ende erzählen"
];
export const WHO_TWISTS: string[] = [
 "mit einem geliehenen Namen",
 "ohne Erinnerung an den gestrigen Tag",
 "auf der Flucht vor einem Versprechen",
 "mit zitternden Händen",
 "kurz vor dem Aufbruch",
 "voller ungestellter Fragen",
 "mit einem fremden Koffer",
 "zwischen zwei Loyalitäten",
 "mit einer alten Schuld im Gepäck",
 "ohne Papiere",
 "mit einem zweiten Gesicht",
 "mit einem halb vergessenen Auftrag",
 "im falschen Jahrzehnt geboren",
 "mit geliehener Stimme"
];
export const WHERE_TWISTS: string[] = [
 "wo die Uhren falsch gehen",
 "wo niemand nach Namen fragt",
 "wo nachts Licht brennt, obwohl niemand wohnt",
 "wo alle Türen offen stehen",
 "wo der Fluss rückwärts zu fließen scheint",
 "wo man Fremde sofort erkennt",
 "wo ein Zimmer seit Jahren verschlossen ist",
 "wo die Karten nicht stimmen",
 "wo jeder zweite Brief verloren geht",
 "wo das Echo eine Sekunde zu spät kommt",
 "wo der Winter nie ganz endet",
 "wo die Wände dünner sind, als man denkt"
];
export const WHEN_TWISTS: string[] = [
 "kurz nach der Sperrstunde",
 "in der Nacht der Inventur",
 "am Tag der letzten Fähre",
 "während eines Stromausfalls",
 "zwischen zwei Glockenschlägen",
 "am Vorabend einer Abreise",
 "in der Woche der Nebel",
 "als die Zeitungen schwiegen",
 "während des Jahrmarkts",
 "in der Stunde zwischen Hund und Wolf",
 "kurz bevor die Brücke gesperrt wird",
 "am Morgen nach dem Fest"
];
export const WHAT_TWISTS: string[] = [
 "ohne zu wissen, warum",
 "obwohl alle abraten",
 "zum dritten und letzten Mal",
 "gegen ein altes Versprechen",
 "für jemanden, der nie danach gefragt hat",
 "mit den falschen Werkzeugen",
 "unter falschem Namen",
 "bevor es ein anderer tut",
 "aus einem Grund, der erst am Ende zählt",
 "heimlich, zwischen zwei Pflichten",
 "und zahlt dafür einen stillen Preis",
 "als wäre nichts geschehen"
];
