// Genus-Tabelle, zweiter Teil — aus der Abdeckungsmessung 4.331.1.
//
// Gemessen: Von 3689 Nomen in Presets, Pools, Welt und Vorräten fand die
// Maschine für 2337 ein Genus (63 %); 1352 blieben ohne. Ohne Genus gibt es
// keinen Artikel („Kanalufer" statt „am Kanalufer"), keinen Akkusativ und
// keinen Dativ. Hier stehen die häufigsten der fehlenden Singulare mit
// ihrem Genus; Plurale, Namen und substantivierte Adjektive („das
// Offensichtliche") stehen nicht hier — die ersten beiden brauchen kein
// Genus, die dritten bekommen es aus der Endung -e (siehe Regel in
// declension.ts). Die Tabelle wird in NOUN_GENDER gemischt; ein Eintrag hier
// überschreibt keinen dort.
export const NOUN_GENDER_2: Record<string, "m" | "f" | "n"> = {
  // ── Häufigste ──
  ende: "n", jahr: "n", mal: "n", anfang: "m", leben: "n", auskunft: "f", welt: "f", frühjahr: "n", fall: "m",
  arbeit: "f", sache: "f", zufall: "m", form: "f", ziel: "n", kontrolle: "f", reihenfolge: "f", wissen: "n",
  post: "f", ernte: "f", geld: "n", mund: "m", schweigen: "n", wette: "f", schminke: "f", kurs: "m",
  original: "n", text: "m", gras: "n", warten: "n", ruhe: "f", mitte: "f", seide: "f", familie: "f", tiefe: "f",
  norden: "m", süden: "m", osten: "m", westen: "m", blut: "n", horizont: "m", ursache: "f", absicht: "f",
  wirt: "m", jagd: "f", herkunft: "f", essen: "n", rückkehr: "f", rahmen: "m", würde: "f", wäsche: "f",
  miete: "f", verlangen: "n", marke: "f", griff: "m", wache: "f", vernunft: "f", markt: "m", pegel: "m",
  halbdunkel: "n", rolle: "f", grad: "m", streben: "n", fach: "n", weise: "f", wipfel: "m", kohle: "f",
  lehne: "f", tide: "f", ruß: "m", idee: "f", gemeinde: "f", jahrhundert: "n", ernst: "m", betrag: "m",
  unterschied: "m", material: "n", annahme: "f", merkmal: "n", radio: "n", hitze: "f", herold: "m", grat: "m",
  kasse: "f", zoll: "m", heimweh: "n", laden: "m", fähre: "f", herzog: "m", inhalt: "m", titel: "m",
  problem: "n", sicht: "f", behörde: "f", winkel: "m", hilfe: "f", pass: "m", viertel: "n", jahrzehnt: "n",
  anrede: "f", rost: "m", ekel: "m", tat: "f", methode: "f", zwang: "m", heimkehr: "f", umkehr: "f", norm: "f",
  leere: "f", umlauf: "m", flamme: "f", einsicht: "f", messing: "n", personal: "n", widerspruch: "m",
  schluss: "m", stroh: "n", rang: "m", vieh: "n", garderobe: "f", güte: "f", anlass: "m", anwalt: "m", rat: "m",
  code: "m", bad: "n", handgelenk: "n", scheibe: "f", zustand: "m", eile: "f", saatgut: "n", fracht: "f",
  automat: "m", lehre: "f", ding: "n", verzicht: "m", zweck: "m", waffe: "f", blech: "n", trost: "m",
  versuch: "m", ironie: "f", dürre: "f", fest: "n", aufsicht: "f", kapitel: "n", aussicht: "f", absinth: "m",
  parfüm: "n", schmutz: "m", knick: "m", andacht: "f", spitze: "f", szene: "f", erfolg: "m", ausguck: "m",
  bord: "m", sieg: "m", klausel: "f", haupttext: "m", sachverhalt: "m", tinte: "f", stand: "m", wortlaut: "m",
  klinke: "f", kanzel: "f", verrat: "m", mulde: "f", februar: "m", parasit: "m", präparat: "n", wesen: "n",
  lava: "f", schwefel: "m", lauf: "m", spaß: "m", möbel: "n", büro: "n", hauptsache: "f", saat: "f", fehde: "f",
  porträt: "n", reue: "f", konfetti: "n", trapez: "n", narr: "m", truppe: "f", pudel: "m", jugend: "f",
  abschied: "m", bronze: "f", tempel: "m", geschlecht: "n", straßenanfang: "m", brauch: "m", wiederkehr: "f",
  hälfte: "f", pappe: "f", kante: "f", eintrag: "m", format: "n", giebel: "m", heimat: "f", armenkasse: "f",
  materie: "f", mensch: "m", glied: "n", betrieb: "m", müll: "m", kleingeld: "n", ruhm: "m", ritt: "m",
  schärfe: "f", ankunft: "f", symmetrie: "f", adressat: "m", kreislauf: "m", aufstieg: "m", fülle: "f",
  bitte: "f", brand: "m", waise: "f", gesang: "m", subjekt: "n", objekt: "n", moral: "f", schilf: "n",
  diagnose: "f", größe: "f", wahl: "f", sturz: "m", gischt: "f", ekstase: "f", becken: "n", putz: "m",
  minze: "f", samt: "m", pause: "f", knauf: "m", apotheke: "f", kostüm: "n", verstoß: "m", satzanfang: "m",
  sprint: "m", beule: "f", banane: "f", tapete: "f", galerie: "f", klöppel: "m", predigt: "f", zierrat: "m",
  wachwechsel: "m", wimpel: "m", rah: "f", streitfall: "m", docht: "m", wundmal: "n", pforte: "f", gebot: "n",
  flügel: "m", länge: "f", kamel: "n", achse: "f", schlegel: "m", affe: "m", nirwana: "n", alkohol: "m",
  instinkt: "m", balance: "f", aushub: "m", kalk: "m", röhre: "f", basalt: "m", salzsäure: "f", erdkruste: "f",
  schichtfolge: "f", sohle: "f", profil: "n", schneeschmelze: "f", orbit: "m", funkspruch: "m", meteorit: "m",
  stromausfall: "m", theorie: "f", nervengeflecht: "n", bodenprofil: "n", senke: "f", gebiet: "n", phase: "f",
  honorar: "n", kordel: "f", spind: "m", tonfall: "m", tempo: "n", schattenkante: "f", stahl: "m",
  graupappe: "f", stütze: "f", perspektive: "f", tank: "m", stillstand: "m", pumpe: "f", debatte: "f",
  bahre: "f", fackelruß: "m", kerbe: "f", türsturz: "m", groll: "m", seuche: "f", lunge: "f",
  pferdegeschirr: "n", zeltgestänge: "n", marsch: "m", schaumgummi: "m", knall: "m", zeltmitte: "f",
  trick: "m", wurf: "m", pult: "n", pentagramm: "n", handel: "m", rücktritt: "m", zimt: "m", akt: "m",
  schatz: "m", betrug: "m", kopfende: "n", parkett: "n", lack: "m", leib: "m", efeu: "m", anstand: "m",
  schafwolle: "f", milde: "f", wiege: "f", schar: "f", gunst: "f", volk: "n", staat: "m", antlitz: "n",
  fleck: "m", alibi: "n", kamera: "f", vorfall: "m", quelltext: "m", ritual: "n", schläfe: "f",
  wetterwechsel: "m", anzeige: "f", jahresende: "n", weile: "f", tüll: "m", schleppe: "f", bügel: "m",
  dampf: "m", kragen: "m", kerzenstummel: "m", klasse: "f", monatsende: "n", tausendstel: "n", durchlauf: "m",
  jahrtausend: "n", scheu: "f", taxi: "n", mittwoch: "m", erz: "n", diebstahl: "m", nachtwache: "f",
  schleuse: "f", übernahme: "f", luke: "f", spüle: "f", ampel: "f", sperrmüll: "m", speiche: "f", henkel: "m",
  routine: "f", mai: "m", wolle: "f", schluck: "m", biologie: "f", geologie: "f", astrologie: "f",
  philosophie: "f", krise: "f", tragödie: "f", urknall: "m", stift: "m", mine: "f", abwehr: "f", mole: "f",
  zerfall: "m", masse: "f", handbreit: "f", verfall: "m", tischkante: "f", beute: "f", rache: "f", fontäne: "f",
  zuversicht: "f", unruhe: "f", energie: "f", enge: "f", april: "m", rekord: "m", normalzustand: "m", höhe: "f",
  abstieg: "m", requisit: "n", schwindel: "m", orakelspruch: "m", erlass: "m", aufstand: "m", gehorsam: "m",
  blackbox: "f", silhouette: "f", mode: "f", not: "f", urform: "f", ruhestand: "m", schaden: "m", anlauf: "m",
  dienstjahr: "n", witwe: "f", ensemble: "n", kommune: "f", sekte: "f", rettungstrupp: "m", exil: "n",
  zentrale: "f", zensurbehörde: "f", doktortitel: "m", naturschutzgebiet: "n", boulevard: "m", hotel: "n",
  kino: "n", verkehr: "m", kellerclub: "m", kabine: "f", auto: "n", kaserne: "f", internat: "n",
  wahlkabine: "f", anstalt: "f", mittagspause: "f", choleraepidemie: "f", monarchie: "f", hungersnot: "f",
  null: "f", route: "f", kampagne: "f", karriere: "f", neuanfang: "m", sorte: "f", verhandlungssache: "f",
  folge: "f", ablauf: "m", strategie: "f", apparat: "m", psychopath: "m", variable: "f", empathie: "f",
  amsel: "f", schneefall: "m", abendrot: "n", wechsel: "m",
  // ── Nachschlag: Alltag, Körper, Haus, Natur, Amt ──
  auge: "n", name: "m", glaube: "m", wille: "m", gedanke: "m", friede: "m", funke: "m", käse: "m", junge: "m",
  kunde: "m", löwe: "m", hase: "m", bote: "m", zeuge: "m", riese: "m", rabe: "m", falke: "m", ochse: "m",
  bursche: "m", knabe: "m", neffe: "m", erbe: "m", buchstabe: "m", same: "m", schatten: "m", wagen: "m",
  boden: "m", garten: "m", ofen: "m", regen: "m", faden: "m", haken: "m", hafen: "m", morgen: "m", tropfen: "m",
  kissen: "n", zeichen: "n", kuchen: "m", knochen: "m", rücken: "m", segen: "m", bogen: "m", balken: "m",
  riegel: "m", ballen: "m", fels: "m", haus: "n", glas: "n", bus: "m", fluss: "m", kuss: "m", guss: "m",
  gruß: "m", fuß: "m", hass: "m", kompass: "m", atlas: "m", kreis: "m", preis: "m", eis: "n", reis: "m",
  gleis: "n", fleiß: "m", geheimnis: "n", ergebnis: "n", zeugnis: "n", bedürfnis: "n", verhältnis: "n",
  ereignis: "n", erlebnis: "n", bündnis: "n", hindernis: "n", gefängnis: "n", wildnis: "f", finsternis: "f",
  fenster: "n", zimmer: "n", wasser: "n", messer: "n", feuer: "n", kupfer: "n", silber: "n", pulver: "n",
  wetter: "n", alter: "n", ufer: "n", lager: "n", opfer: "n", muster: "n", kloster: "n", register: "n",
  theater: "n", fieber: "n", leder: "n", futter: "n", gitter: "n", ruder: "n", wunder: "n", orchester: "n",
  zepter: "n", semester: "n", polster: "n", pflaster: "n", laster: "n", meter: "m", liter: "m", zentrum: "n",
  datum: "n", museum: "n", tür: "f", hand: "f", stern: "m", schritt: "m", brief: "m", weg: "m", stimme: "f",
  spur: "f", lippe: "f", frage: "f", perle: "f", glocke: "f", uhr: "f", herz: "n", dach: "n", straße: "f",
  regel: "f", vorrat: "m", schicht: "f", schaf: "n", nummer: "f", schuh: "m", grenze: "f", gutachten: "n",
  satz: "m", wort: "n", seele: "f", teil: "m", blume: "f", richtung: "f", monat: "m", zahn: "m", ort: "m",
  wand: "f", vorhang: "m", umstand: "m", sandsack: "m", kraft: "f", bein: "n", kanal: "m", sinn: "m",
  netz: "n", pflasterstein: "m", handschuh: "m", protokoll: "n", system: "n", kreidestrich: "m",
  bruchteil: "m", tor: "n", kran: "m", beweis: "m", nacht: "f", stadt: "f", grund: "m", zug: "m", riff: "n",
  plakat: "n", baum: "m", erbgang: "m", exemplar: "n", symptom: "n", plan: "m", umriss: "m", riss: "m",
  bahngleis: "n", regal: "n", blick: "m", bergpass: "m", faust: "f", stuhl: "m", freund: "m", stamm: "m",
  tanzschuh: "m", dienst: "m", maß: "n", arm: "m", kinderhand: "f", tisch: "m", seil: "n", frachtbrief: "m",
  termin: "m", formular: "n", messwert: "m", gegenstand: "m", vogel: "m", exponat: "n", fahrgast: "m",
  meer: "n", anruf: "m", vorschlag: "m", punkt: "m", boot: "n", paar: "n", gast: "m", stein: "m", stunde: "f",
  minute: "f", tag: "m", woche: "f", seite: "f", farbe: "f", papier: "n", nachbar: "m", wolke: "f", zeug: "n",
  kind: "n", mann: "m", frau: "f", vater: "m", mutter: "f", bruder: "m", schwester: "f", sohn: "m",
  tochter: "f", herr: "m", dame: "f", lehrer: "m", arzt: "m", pfarrer: "m", priester: "m", könig: "m",
  königin: "f", kaiser: "m", soldat: "m", bauer: "m", fischer: "m", bäcker: "m", schneider: "m", schmied: "m",
  müller: "m", jäger: "m", hirte: "m", knecht: "m", magd: "f", wächter: "m", richter: "m", händler: "m",
  fremde: "m", kurier: "m", agent: "m", spion: "m", dieb: "m", räuber: "m", mörder: "m", opferlamm: "n",
  engel: "m", teufel: "m", geist: "m", gott: "m", göttin: "f", heiliger: "m", mönch: "m", nonne: "f",
  abt: "m", bischof: "m", papst: "m", ritter: "m", knappe: "m", graf: "m", gräfin: "f", fürst: "m",
  prinz: "m", prinzessin: "f", zauberer: "m", hexe: "f", drache: "m", zwerg: "m", elf: "m", troll: "m",
  wolf: "m", bär: "m", fuchs: "m", hirsch: "m", reh: "n", pferd: "n", hund: "m", katze: "f", maus: "f",
  ratte: "f", schlange: "f", fisch: "m", möwe: "f", taube: "f", krähe: "f", eule: "f", biene: "f",
  fliege: "f", spinne: "f", käfer: "m", schmetterling: "m", wurm: "m", ameise: "f", frosch: "m", kröte: "f",
  eidechse: "f", schwan: "m", ente: "f", gans: "f", huhn: "n", hahn: "m", kuh: "f", stier: "m", ziege: "f",
  esel: "m", schwein: "n", lamm: "n",
  // Schwache Maskulina auf -e, die die -e→f-Regel sonst fälschlich fängt
  kollege: "m", experte: "m", matrose: "m", pate: "m", sklave: "m", laie: "m", insasse: "m", gatte: "m",
  bulle: "m", schurke: "m", geselle: "m", gefährte: "m", genosse: "m", komplize: "m", jude: "m", zar: "m",
  franzose: "m", chinese: "m", russe: "m", grieche: "m", türke: "m", ire: "m", schwede: "m", däne: "m",
  psychologe: "m", biologe: "m", geologe: "m", soziologe: "m", archäologe: "m", philosoph: "m",
  // Neutra auf -e
  interesse: "n", gebäude: "n", gemälde: "n", gebirge: "n", getreide: "n", gefolge: "n", gelände: "n",
  gewebe: "n", gewölbe: "n", getriebe: "n", gefüge: "n", gelage: "n", gerede: "n", gehege: "n", gewerbe: "n",
};
