// Kontext-Pools der Ideenmaschine. Einträge sind getaggt, damit das Ideen-Profil
// (Protagonist-Typ, Ort-Typ, Zeit/Epoche, Genre) gezielt filtern kann.
// Mehrfach-Tags sind erlaubt und erwünscht.
export interface Tagged { t: string; tags: string[]; }

// ---- WER (Subjekt, 3. Person Singular) ----
export const WHO_TAGGED: Tagged[] = [
  { t: "eine Uhrmacherin", tags: ["einzel"] },
  { t: "ein pensionierter Richter", tags: ["einzel"] },
  { t: "eine Archivarin ohne Namen", tags: ["einzel"] },
  { t: "ein Übersetzer für tote Sprachen", tags: ["einzel"] },
  { t: "eine Kartographin ohne Karten", tags: ["einzel"] },
  { t: "ein Fremder, der jeden Namen kennt", tags: ["einzel"] },
  { t: "eine Chirurgin mit zitternden Händen", tags: ["einzel"] },
  { t: "ein Mönch, der das Schweigen gebrochen hat", tags: ["einzel"] },
  { t: "eine Diplomatin ohne Land", tags: ["einzel"] },
  { t: "ein Leuchtturmwärter im letzten Dienstjahr", tags: ["einzel"] },
  { t: "eine Restauratorin alter Fresken", tags: ["einzel"] },
  { t: "ein Nachtportier mit fotografischem Gedächtnis", tags: ["einzel"] },
  { t: "eine Seismologin, die niemand ernst nimmt", tags: ["einzel"] },
  { t: "ein Totengräber, der Briefe schreibt", tags: ["einzel"] },
  { t: "eine Glasbläserin mit vernarbten Händen", tags: ["einzel"] },
  { t: "ein Kanalarbeiter, der Stimmen hört", tags: ["einzel"] },
  { t: "eine Bibliothekarin ohne Namen", tags: ["einzel"] },
  { t: "ein Boxer im Ruhestand", tags: ["einzel"] },
  { t: "ein Buchhalter mit doppeltem Gedächtnis", tags: ["einzel"] },
  { t: "eine Witwe, die nichts geerbt hat", tags: ["einzel"] },

  { t: "eine Handvoll Überlebender", tags: ["kollektiv"] },
  { t: "ein Chor ohne Dirigent", tags: ["kollektiv"] },
  { t: "eine Belegschaft, die nicht mehr nach Hause geht", tags: ["kollektiv"] },
  { t: "ein Ensemble im Dauerstreik", tags: ["kollektiv"] },
  { t: "das Dorf hinter dem Deich", tags: ["kollektiv"] },
  { t: "eine Kommune ohne Anführer", tags: ["kollektiv"] },
  { t: "ein Schwarm ohne Zentrum", tags: ["kollektiv", "nichtmensch"] },
  { t: "die Nachtschicht einer stillen Fabrik", tags: ["kollektiv"] },
  { t: "eine Expedition, die sich verlaufen hat", tags: ["kollektiv"] },
  { t: "ein Geschworenengericht ohne Angeklagten", tags: ["kollektiv", "institution"] },
  { t: "die Besatzung eines Frachtschiffs", tags: ["kollektiv"] },
  { t: "eine Familie mit zu vielen Geheimnissen", tags: ["kollektiv"] },
  { t: "ein Orchester, das nicht aufhören kann", tags: ["kollektiv"] },
  { t: "eine Sekte ohne Gott", tags: ["kollektiv", "institution"] },
  { t: "ein Rettungstrupp ohne Auftrag", tags: ["kollektiv"] },
  { t: "eine Reisegruppe, die niemand abgeholt hat", tags: ["kollektiv"] },

  { t: "ein Kind, das zu viel weiß", tags: ["kind", "einzel"] },
  { t: "ein Junge mit zwei Schatten", tags: ["kind"] },
  { t: "ein Mädchen, das die Zukunft träumt", tags: ["kind"] },
  { t: "ein stummes Kind mit fremder Handschrift", tags: ["kind"] },
  { t: "der jüngste Zeuge einer langen Nacht", tags: ["kind"] },
  { t: "ein Waisenkind mit geerbtem Gedächtnis", tags: ["kind"] },
  { t: "ein Schulmädchen, das Karten fälscht", tags: ["kind", "antiheld"] },
  { t: "ein Junge, der jede Lüge hört", tags: ["kind"] },
  { t: "ein Kind, das man vergessen hat abzuholen", tags: ["kind"] },
  { t: "eine Zwölfjährige mit einem Vertrag", tags: ["kind"] },
  { t: "ein Findelkind ohne Spiegelbild", tags: ["kind"] },
  { t: "ein Junge, der einen Fluss großzieht", tags: ["kind"] },
  { t: "ein Mädchen mit dem Gedächtnis eines Hauses", tags: ["kind"] },
  { t: "ein Kind, das nur nachts spricht", tags: ["kind"] },
  { t: "der Sohn eines Fälschers", tags: ["kind", "antiheld"] },

  { t: "ein Ministerium ohne Minister", tags: ["institution"] },
  { t: "eine Behörde für Verlorenes", tags: ["institution"] },
  { t: "ein Gericht im Exil", tags: ["institution"] },
  { t: "ein Archiv mit eigenem Willen", tags: ["institution", "nichtmensch"] },
  { t: "eine Bibliothek, die Entscheidungen trifft", tags: ["institution", "nichtmensch"] },
  { t: "ein Orden ohne Glauben", tags: ["institution"] },
  { t: "eine Klinik, die niemanden entlässt", tags: ["institution"] },
  { t: "das Amt für unerledigte Dinge", tags: ["institution"] },
  { t: "eine Schule ohne Schüler", tags: ["institution"] },
  { t: "ein Museum, das seine Exponate verliert", tags: ["institution"] },
  { t: "eine Redaktion, die nur Dementis druckt", tags: ["institution"] },
  { t: "ein Konzern mit vergessener Zentrale", tags: ["institution"] },
  { t: "das Register aller falschen Namen", tags: ["institution", "nichtmensch"] },
  { t: "eine Kommission ohne Auftrag", tags: ["institution"] },
  { t: "ein Kloster mit fremdem Kalender", tags: ["institution"] },
  { t: "die Zensurbehörde einer freien Stadt", tags: ["institution"] },

  { t: "ein Algorithmus mit Namen", tags: ["nichtmensch"] },
  { t: "eine Maschine, die zu träumen beginnt", tags: ["nichtmensch"] },
  { t: "ein Fluss, der sich erinnert", tags: ["nichtmensch"] },
  { t: "eine Stimme ohne Körper", tags: ["nichtmensch"] },
  { t: "ein Tier, das ein Versprechen hält", tags: ["nichtmensch"] },
  { t: "ein Haus mit eigenem Willen", tags: ["nichtmensch"] },
  { t: "eine Uhr, die zurückzählt", tags: ["nichtmensch"] },
  { t: "ein Wald, der Namen vergibt", tags: ["nichtmensch"] },
  { t: "eine Kolonie unter dem Eis", tags: ["nichtmensch", "kollektiv"] },
  { t: "ein Signal, das antwortet", tags: ["nichtmensch"] },
  { t: "eine Karte, die sich selbst zeichnet", tags: ["nichtmensch"] },
  { t: "ein Spiegel mit Gedächtnis", tags: ["nichtmensch"] },
  { t: "eine Wolke, die einem Menschen folgt", tags: ["nichtmensch"] },
  { t: "ein Schiff ohne Besatzung, das Kurs hält", tags: ["nichtmensch"] },
  { t: "eine Sprache, die aussterben will", tags: ["nichtmensch"] },
  { t: "ein Schatten, der früher ankommt", tags: ["nichtmensch"] },
  { t: "ein Bahnhof, der Reisende behält", tags: ["nichtmensch"] },

  { t: "eine Falschmünzerin mit Prinzipien", tags: ["antiheld"] },
  { t: "ein Spion im Ruhestand", tags: ["antiheld", "einzel"] },
  { t: "eine Diebin, die nur Erinnerungen stiehlt", tags: ["antiheld"] },
  { t: "ein Verräter aus Loyalität", tags: ["antiheld"] },
  { t: "ein Hochstapler mit echtem Titel", tags: ["antiheld"] },
  { t: "eine Anwältin für aussichtslose Fälle", tags: ["antiheld", "einzel"] },
  { t: "ein Erpresser mit gutem Gedächtnis", tags: ["antiheld"] },
  { t: "eine Schmugglerin von Büchern", tags: ["antiheld"] },
  { t: "ein Söldner, der nicht mehr schießt", tags: ["antiheld"] },
  { t: "eine Betrügerin mit sauberem Gewissen", tags: ["antiheld"] },
  { t: "ein Kronzeuge, der lügt", tags: ["antiheld"] },
  { t: "eine Grabräuberin mit Doktortitel", tags: ["antiheld"] },
  { t: "ein Henker, der Gnade sammelt", tags: ["antiheld"] },
  { t: "eine Fälscherin echter Dokumente", tags: ["antiheld"] },
  { t: "ein Deserteur mit Orden", tags: ["antiheld"] },
  { t: "eine Wilderin im Naturschutzgebiet", tags: ["antiheld"] },
  { t: "eine Pilotin ohne Lizenz", tags: ["antiheld", "einzel"] },
];

// ---- WO (Ortsangabe) ----
export const WHERE_TAGGED: Tagged[] = [
  { t: "in einer schlaflosen Stadt", tags: ["urban"] },
  { t: "in einem verlassenen Bahnhof", tags: ["urban"] },
  { t: "in einem Hinterhof ohne Ausgang", tags: ["urban", "raum"] },
  { t: "auf einem nächtlichen Boulevard", tags: ["urban"] },
  { t: "in einem Hochhaus ohne Erdgeschoss", tags: ["urban"] },
  { t: "in der U-Bahn nach Mitternacht", tags: ["urban"] },
  { t: "in einem Viertel, das abgerissen wird", tags: ["urban"] },
  { t: "auf einem Parkdeck über der Stadt", tags: ["urban"] },
  { t: "in einer Markthalle vor Sonnenaufgang", tags: ["urban"] },
  { t: "in einem Hotel mit zu vielen Zimmern", tags: ["urban"] },
  { t: "unter einer Autobahnbrücke", tags: ["urban"] },
  { t: "in einer Straße, die zweimal existiert", tags: ["urban", "nirgendwo"] },
  { t: "in Paris", tags: ["urban"] },
  { t: "in einem Nachtbus ohne Fahrgäste", tags: ["urban", "raum"] },
  { t: "in einem Kino, das nie schließt", tags: ["urban"] },
  { t: "auf einem Dach über dem Verkehr", tags: ["urban"] },
  { t: "in einer Telefonzelle, die noch klingelt", tags: ["urban"] },
  { t: "in einem Kellerclub ohne Namen", tags: ["urban"] },

  { t: "am Rand eines Moors", tags: ["natur"] },
  { t: "in einem Wald ohne Vögel", tags: ["natur"] },
  { t: "an einer versinkenden Küste", tags: ["natur"] },
  { t: "auf einem Gletscher, der schmilzt", tags: ["natur"] },
  { t: "in einer Wüste mit Türen", tags: ["natur", "nirgendwo"] },
  { t: "am Ufer eines toten Flusses", tags: ["natur"] },
  { t: "am Fluss", tags: ["natur"] },
  { t: "in einem Tal, das verstummt ist", tags: ["natur"] },
  { t: "auf einer Insel ohne Hafen", tags: ["natur"] },
  { t: "in einer Höhle mit warmem Wind", tags: ["natur", "raum"] },
  { t: "auf einem Feld nach der Ernte", tags: ["natur"] },
  { t: "an einem See, der nie zufriert", tags: ["natur"] },
  { t: "im Schilf hinter dem Deich", tags: ["natur"] },
  { t: "auf einem Pass im ersten Schnee", tags: ["natur", "grenze"] },
  { t: "in einem Obstgarten, der nicht mehr trägt", tags: ["natur"] },
  { t: "an einer Steilküste im Nebel", tags: ["natur"] },
  { t: "unter einem Baum, der älter ist als das Dorf", tags: ["natur"] },
  { t: "in einem Sumpf voller Wracks", tags: ["natur"] },

  { t: "in einem versiegelten Zimmer", tags: ["raum"] },
  { t: "in einem Aufzug zwischen zwei Stockwerken", tags: ["raum", "grenze"] },
  { t: "in einer Kabine auf hoher See", tags: ["raum"] },
  { t: "in einem Bunker ohne Uhr", tags: ["raum"] },
  { t: "in einem Wartesaal ohne Züge", tags: ["raum"] },
  { t: "hinter einer Tür, die nicht schließt", tags: ["raum"] },
  { t: "in einem Zugabteil ohne Fenster", tags: ["raum"] },
  { t: "in einer Dunkelkammer", tags: ["raum"] },
  { t: "in einem Treppenhaus ohne Ausgang", tags: ["raum"] },
  { t: "in einem Beichtstuhl", tags: ["raum", "institution"] },
  { t: "in einer Kühlkammer", tags: ["raum"] },
  { t: "in einem Auto am Straßenrand", tags: ["raum"] },
  { t: "in einem Zelt im Dauerregen", tags: ["raum", "natur"] },
  { t: "in einem Fahrstuhlschacht", tags: ["raum"] },
  { t: "in einer Zelle mit Aussicht", tags: ["raum", "institution"] },
  { t: "auf einem Dachboden voller Uhren", tags: ["raum"] },

  { t: "an der Grenze zweier Länder", tags: ["grenze"] },
  { t: "auf einer Brücke im Niemandsland", tags: ["grenze"] },
  { t: "an der Schwelle zweier Zeiten", tags: ["grenze", "nirgendwo"] },
  { t: "in einer Zollstation im Nebel", tags: ["grenze"] },
  { t: "auf der Linie zwischen Traum und Wachen", tags: ["grenze", "nirgendwo"] },
  { t: "am Übergang, den keiner bewacht", tags: ["grenze"] },
  { t: "auf einer Fähre zwischen zwei Ufern", tags: ["grenze"] },
  { t: "an einem Grenzfluss ohne Brücke", tags: ["grenze", "natur"] },
  { t: "im Transitbereich eines Flughafens", tags: ["grenze"] },
  { t: "an der Küstenlinie bei Flut", tags: ["grenze", "natur"] },
  { t: "auf dem letzten Meter vor der Sperre", tags: ["grenze"] },
  { t: "in einem Korridor zwischen zwei Staaten", tags: ["grenze"] },
  { t: "am Waldrand vor der Lichtung", tags: ["grenze", "natur"] },
  { t: "auf der Türschwelle, die niemand überschreitet", tags: ["grenze"] },

  { t: "an einem Ort ohne Namen", tags: ["nirgendwo"] },
  { t: "in einer Stadt, die es nicht gibt", tags: ["nirgendwo", "urban"] },
  { t: "im weißen Raum dazwischen", tags: ["nirgendwo"] },
  { t: "auf einer Karte ohne Legende", tags: ["nirgendwo"] },
  { t: "im Nichts nach dem letzten Halt", tags: ["nirgendwo"] },
  { t: "an einem vergessenen Koordinatenpunkt", tags: ["nirgendwo"] },
  { t: "zwischen zwei Sätzen", tags: ["nirgendwo"] },
  { t: "in einem Traum, der jemand anderem gehört", tags: ["nirgendwo"] },
  { t: "an einem Ort, den alle anders erinnern", tags: ["nirgendwo"] },
  { t: "im Zwischenraum einer Erinnerung", tags: ["nirgendwo"] },
  { t: "hinter der letzten bekannten Adresse", tags: ["nirgendwo"] },
  { t: "in einer Gegend, die keine Karte erfasst", tags: ["nirgendwo"] },
  { t: "auf einem Bahnsteig ohne Gleise", tags: ["nirgendwo"] },
  { t: "dort, wo die Straße einfach aufhört", tags: ["nirgendwo"] },

  { t: "in einem Archiv der Universität", tags: ["institution"] },
  { t: "in einer geschlossenen Klinik", tags: ["institution"] },
  { t: "in einer stillgelegten Fabrik", tags: ["institution", "urban"] },
  { t: "in einem Ministerium bei Nacht", tags: ["institution"] },
  { t: "in einer Bibliothek ohne Bücher", tags: ["institution"] },
  { t: "in einem Gericht ohne Richter", tags: ["institution"] },
  { t: "im Archiv", tags: ["institution"] },
  { t: "in einem Amtszimmer im vierten Stock", tags: ["institution"] },
  { t: "in einer Kaserne ohne Rekruten", tags: ["institution"] },
  { t: "in einem Museum nach Schließung", tags: ["institution"] },
  { t: "in einem Internat im Winter", tags: ["institution"] },
  { t: "in einer Wahlkabine", tags: ["institution"] },
  { t: "in einem Rechenzentrum", tags: ["institution"] },
  { t: "in einer Anstalt mit offenen Türen", tags: ["institution"] },
  { t: "im Keller eines Standesamts", tags: ["institution"] },
  { t: "in einer Kirche ohne Gemeinde", tags: ["institution"] },
];

// ---- WANN (Zeitangabe) ----
export const WHEN_TAGGED: Tagged[] = [
  { t: "heute, kurz vor Feierabend", tags: ["gegenwart"] },
  { t: "an einem Sonntagnachmittag", tags: ["gegenwart"] },
  { t: "während eines Stromausfalls", tags: ["gegenwart", "umbruch"] },
  { t: "in der Woche des großen Sturms", tags: ["gegenwart"] },
  { t: "an einem ganz gewöhnlichen Dienstag", tags: ["gegenwart"] },
  { t: "im Winter", tags: ["gegenwart", "zeitlos"] },
  { t: "kurz vor Mitternacht", tags: ["gegenwart", "zeitlos"] },
  { t: "im Morgengrauen", tags: ["gegenwart", "zeitlos"] },
  { t: "an einem Montag im November", tags: ["gegenwart"] },
  { t: "während der Mittagspause", tags: ["gegenwart"] },
  { t: "in der Nacht nach dem Umzug", tags: ["gegenwart"] },
  { t: "am Tag der Beerdigung", tags: ["gegenwart"] },
  { t: "zwischen zwei Terminen", tags: ["gegenwart"] },
  { t: "an einem Abend ohne Strom", tags: ["gegenwart"] },
  { t: "im Sommer der langen Dürre", tags: ["gegenwart"] },
  { t: "an einem Freitag im Regen", tags: ["gegenwart"] },

  { t: "1789", tags: ["historisch"] },
  { t: "1917", tags: ["historisch"] },
  { t: "1348", tags: ["historisch"] },
  { t: "im Jahr der großen Flut", tags: ["historisch", "zeitlos"] },
  { t: "während einer Belagerung", tags: ["historisch", "umbruch"] },
  { t: "1848", tags: ["historisch"] },
  { t: "im Herbst 1923", tags: ["historisch"] },
  { t: "1889", tags: ["historisch"] },
  { t: "während der Choleraepidemie", tags: ["historisch"] },
  { t: "im Jahr nach dem Krieg", tags: ["historisch"] },
  { t: "1666", tags: ["historisch"] },
  { t: "in der Woche der Krönung", tags: ["historisch", "umbruch"] },
  { t: "1961", tags: ["historisch"] },
  { t: "während der großen Auswanderung", tags: ["historisch"] },
  { t: "im letzten Sommer der Monarchie", tags: ["historisch", "umbruch"] },
  { t: "1492", tags: ["historisch"] },
  { t: "im Winter der Hungersnot", tags: ["historisch"] },
  { t: "am Vorabend der Revolution", tags: ["historisch", "umbruch"] },

  { t: "2041", tags: ["zukunft"] },
  { t: "im dritten Jahr der Stille", tags: ["zukunft"] },
  { t: "nach dem letzten Winter", tags: ["zukunft"] },
  { t: "als die Meere zurückwichen", tags: ["zukunft"] },
  { t: "im Jahrhundert der Karten ohne Länder", tags: ["zukunft"] },
  { t: "2103", tags: ["zukunft"] },
  { t: "im zweiten Jahr der neuen Zeitrechnung", tags: ["zukunft", "umbruch"] },
  { t: "nach der großen Abschaltung", tags: ["zukunft", "umbruch"] },
  { t: "als die Städte zu wandern begannen", tags: ["zukunft"] },
  { t: "2077", tags: ["zukunft"] },
  { t: "im Sommer ohne Nacht", tags: ["zukunft", "zeitlos"] },
  { t: "nachdem die letzte Grenze fiel", tags: ["zukunft", "umbruch"] },
  { t: "im Jahr der ersten Rückkehr", tags: ["zukunft"] },
  { t: "als niemand mehr schrieb", tags: ["zukunft"] },
  { t: "2199", tags: ["zukunft"] },
  { t: "nach dem Ende der Vorhersagen", tags: ["zukunft"] },

  { t: "zu einer Zeit, die niemand zählt", tags: ["zeitlos"] },
  { t: "im Jahr Null", tags: ["zeitlos"] },
  { t: "als die Uhren noch schwiegen", tags: ["zeitlos"] },
  { t: "irgendwann, immer", tags: ["zeitlos"] },
  { t: "in einem Sommer ohne Ende", tags: ["zeitlos"] },
  { t: "lange vor den Namen", tags: ["zeitlos"] },
  { t: "in einer Woche, die sich wiederholt", tags: ["zeitlos"] },
  { t: "zwischen zwei Herzschlägen", tags: ["zeitlos"] },
  { t: "als die Zeit noch niemandem gehörte", tags: ["zeitlos"] },
  { t: "an einem Tag, der zweimal stattfindet", tags: ["zeitlos"] },
  { t: "im ewigen Nachmittag", tags: ["zeitlos"] },
  { t: "bevor die Kalender erfunden wurden", tags: ["zeitlos"] },
  { t: "in der Stunde, die nicht gezählt wird", tags: ["zeitlos"] },
  { t: "zu einer Zeit ohne Zeugen", tags: ["zeitlos"] },
  { t: "in einem Jahr ohne Zahl", tags: ["zeitlos"] },

  { t: "am Tag der Sonnenfinsternis", tags: ["umbruch"] },
  { t: "in der Nacht des Umsturzes", tags: ["umbruch"] },
  { t: "während eines Generalstreiks", tags: ["umbruch"] },
  { t: "am letzten Tag des Jahres", tags: ["umbruch"] },
  { t: "in der Stunde der Entscheidung", tags: ["umbruch"] },
  { t: "am Morgen nach der Wahl", tags: ["umbruch"] },
  { t: "während der Evakuierung", tags: ["umbruch"] },
  { t: "in der Nacht, als die Grenze fiel", tags: ["umbruch"] },
  { t: "am Tag der großen Abstimmung", tags: ["umbruch"] },
  { t: "während des letzten Prozesses", tags: ["umbruch"] },
  { t: "als die Fabrik schloss", tags: ["umbruch"] },
  { t: "in der Woche der Räumung", tags: ["umbruch"] },
  { t: "am Vorabend des Aufbruchs", tags: ["umbruch"] },
  { t: "während des Erdbebens", tags: ["umbruch"] },
  { t: "in den Stunden vor der Verkündung", tags: ["umbruch"] },
];

// ---- WAS (Verbalphrase, 3. Person Singular) ----
export const WHAT_TAGGED: Tagged[] = [
  { t: "sucht eine Spur, die keiner hinterließ", tags: ["mystery"] },
  { t: "findet einen Brief, der nicht an sie gerichtet war", tags: ["mystery"] },
  { t: "entdeckt ein zweites Testament", tags: ["mystery"] },
  { t: "verfolgt eine Lüge bis zur Wurzel", tags: ["mystery"] },
  { t: "stößt auf einen Namen, den es nicht geben dürfte", tags: ["mystery"] },
  { t: "rekonstruiert eine Nacht, die niemand erlebt hat", tags: ["mystery"] },
  { t: "sucht eine Spur", tags: ["mystery"] },
  { t: "findet ein Foto mit einer Person zu viel", tags: ["mystery", "horror"] },
  { t: "erbt einen Schlüssel ohne Schloss", tags: ["mystery"] },
  { t: "entziffert ein Tagebuch in fremder Hand", tags: ["mystery"] },
  { t: "verhört einen Zeugen, der längst tot ist", tags: ["mystery", "horror"] },
  { t: "öffnet einen Fall, den alle geschlossen haben", tags: ["mystery"] },
  { t: "bemerkt, dass zwei Uhren nicht übereinstimmen", tags: ["mystery"] },
  { t: "verfolgt jemanden, der die eigene Route kennt", tags: ["mystery"] },
  { t: "findet die eigene Unterschrift auf fremdem Papier", tags: ["mystery"] },

  { t: "erhält eine Nachricht aus der Zukunft", tags: ["scifi"] },
  { t: "findet eine Tür, die es nicht geben dürfte", tags: ["scifi", "maerchen"] },
  { t: "verliert die Kontrolle über die eigene Stimme", tags: ["scifi", "horror"] },
  { t: "erwacht in einem Körper mit fremdem Gedächtnis", tags: ["scifi"] },
  { t: "entziffert ein Signal aus dem Nichts", tags: ["scifi"] },
  { t: "tauscht Zeit gegen eine Erinnerung", tags: ["scifi"] },
  { t: "wird von der eigenen Kopie verklagt", tags: ["scifi", "satire"] },
  { t: "verkauft eine Erinnerung zu teuer", tags: ["scifi"] },
  { t: "entdeckt eine Lücke in der Simulation", tags: ["scifi"] },
  { t: "verliert eine Woche und findet sie woanders", tags: ["scifi"] },
  { t: "spricht mit einer Maschine, die lügt", tags: ["scifi"] },
  { t: "bekommt ein Angebot von der eigenen Zukunft", tags: ["scifi"] },
  { t: "muss beweisen, real zu sein", tags: ["scifi", "absurd"] },
  { t: "findet den letzten Menschen ohne Anschluss", tags: ["scifi"] },
  { t: "erbt ein fremdes Bewusstsein", tags: ["scifi"] },

  { t: "schließt einen Pakt, den keiner versteht", tags: ["maerchen"] },
  { t: "folgt einem Licht in den Wald", tags: ["maerchen"] },
  { t: "erbt einen Fluch mit gutem Kern", tags: ["maerchen"] },
  { t: "verspricht drei Dinge, die sich widersprechen", tags: ["maerchen"] },
  { t: "sucht einen Namen, um frei zu werden", tags: ["maerchen"] },
  { t: "öffnet die verbotene Tür", tags: ["maerchen", "horror"] },
  { t: "tauscht den Schatten gegen einen Wunsch", tags: ["maerchen"] },
  { t: "bekommt eine Gabe, die keiner will", tags: ["maerchen"] },
  { t: "muss sieben Nächte schweigen", tags: ["maerchen"] },
  { t: "weckt etwas, das schlafen sollte", tags: ["maerchen", "horror"] },
  { t: "verhandelt mit dem Fluss um einen Übergang", tags: ["maerchen"] },
  { t: "verliert das Gesicht an einen Spiegel", tags: ["maerchen", "horror"] },
  { t: "gibt das eigene Herz als Pfand", tags: ["maerchen"] },
  { t: "löst ein Rätsel und verliert dabei alles", tags: ["maerchen"] },
  { t: "wird von einem Tier um Hilfe gebeten", tags: ["maerchen"] },

  { t: "füllt ein Formular für die eigene Abwesenheit", tags: ["absurd", "satire"] },
  { t: "verklagt den eigenen Schatten", tags: ["absurd"] },
  { t: "wartet auf einen Termin, der nie kommt", tags: ["absurd"] },
  { t: "erbt ein Amt ohne Aufgabe", tags: ["absurd", "satire"] },
  { t: "verliert die Erinnerung an einen Namen", tags: ["absurd"] },
  { t: "wird für tot erklärt und muss es widerlegen", tags: ["absurd"] },
  { t: "beantragt eine Genehmigung zu existieren", tags: ["absurd", "satire"] },
  { t: "wird in eine Abteilung ohne Tür befördert", tags: ["absurd", "satire"] },
  { t: "muss einen Fehler verwalten, den es nicht gibt", tags: ["absurd"] },
  { t: "steht in einer Schlange, die sich selbst anstellt", tags: ["absurd"] },
  { t: "bekommt einen Ausweis für ein anderes Leben", tags: ["absurd"] },
  { t: "soll das eigene Verschwinden protokollieren", tags: ["absurd"] },
  { t: "sucht ein Zimmer, dessen Nummer wandert", tags: ["absurd"] },
  { t: "erhält Post von einer Behörde ohne Existenz", tags: ["absurd"] },
  { t: "muss die eigene Vergangenheit erst beantragen", tags: ["absurd"] },

  { t: "will einfach nur verschwinden", tags: ["alltag"] },
  { t: "trifft eine Entscheidung binnen einer Stunde", tags: ["alltag"] },
  { t: "bricht ein Versprechen aus Kindheitstagen", tags: ["alltag"] },
  { t: "kehrt an einen alten Ort zurück", tags: ["alltag"] },
  { t: "sagt endlich einen Satz zu spät", tags: ["alltag"] },
  { t: "räumt ein Zimmer und findet ein Leben", tags: ["alltag"] },
  { t: "will verschwinden", tags: ["alltag"] },
  { t: "wartet auf einen Anruf, der nicht kommt", tags: ["alltag"] },
  { t: "verpasst einen Zug mit Absicht", tags: ["alltag"] },
  { t: "trifft jemanden, den es nicht mehr geben sollte", tags: ["alltag", "horror"] },
  { t: "beantwortet einen zwanzig Jahre alten Brief", tags: ["alltag"] },
  { t: "kündigt ohne Plan", tags: ["alltag"] },
  { t: "erkennt sich auf einem fremden Foto", tags: ["alltag", "mystery"] },
  { t: "verschiebt eine Beerdigung", tags: ["alltag"] },
  { t: "beginnt ein Gespräch, das alles ändert", tags: ["alltag"] },

  { t: "hört Schritte im leeren Haus", tags: ["horror"] },
  { t: "bemerkt, dass die Spiegel nicht mehr stimmen", tags: ["horror"] },
  { t: "zählt eine Person zu viel", tags: ["horror"] },
  { t: "findet die eigene Handschrift an fremder Wand", tags: ["horror"] },
  { t: "verliert jede Nacht eine Erinnerung mehr", tags: ["horror"] },
  { t: "wird von etwas erkannt, das keiner sieht", tags: ["horror"] },
  { t: "hört den eigenen Namen aus dem Nebenzimmer", tags: ["horror"] },
  { t: "entdeckt, dass das Haus größer wird", tags: ["horror"] },
  { t: "findet Fußspuren, die zurückführen", tags: ["horror"] },
  { t: "wacht jede Nacht eine Stunde früher auf", tags: ["horror"] },
  { t: "bemerkt, dass niemand mehr blinzelt", tags: ["horror"] },
  { t: "gräbt etwas aus, das noch warm ist", tags: ["horror"] },
  { t: "bekommt Anrufe von der eigenen Nummer", tags: ["horror"] },
  { t: "sieht dasselbe Gesicht in jeder Menge", tags: ["horror"] },
  { t: "schließt eine Tür, die offen bleibt", tags: ["horror"] },

  { t: "gründet ein Amt gegen die Wirklichkeit", tags: ["satire"] },
  { t: "gewinnt einen Preis für nichts", tags: ["satire"] },
  { t: "verwaltet das Ende der Welt in Ordnern", tags: ["satire"] },
  { t: "beruft eine Sitzung über Sitzungen ein", tags: ["satire"] },
  { t: "optimiert sich selbst weg", tags: ["satire"] },
  { t: "verkauft Zeit an die, die keine haben", tags: ["satire"] },
  { t: "erfindet ein Problem und die passende Lösung", tags: ["satire"] },
  { t: "wird zum Gesicht einer Kampagne gegen sich selbst", tags: ["satire"] },
  { t: "reformiert eine Behörde in eine größere", tags: ["satire"] },
  { t: "lässt die Wahrheit auslagern", tags: ["satire"] },
  { t: "schreibt ein Gutachten über das eigene Gutachten", tags: ["satire"] },
  { t: "privatisiert das Wetter", tags: ["satire"] },
  { t: "gründet eine Kommission zur Abschaffung von Kommissionen", tags: ["satire"] },
  { t: "macht Karriere durch konsequentes Nichtstun", tags: ["satire"] },
  { t: "digitalisiert ein Formular, das niemand braucht", tags: ["satire"] },
];

// Kompatibilität: flache Listen für Studio/Welt/Kontext.
export const CTX_WHO: string[] = WHO_TAGGED.map((e) => e.t);
export const CTX_WHERE: string[] = WHERE_TAGGED.map((e) => e.t);
export const CTX_WHEN: string[] = WHEN_TAGGED.map((e) => e.t);
export const CTX_WHAT: string[] = WHAT_TAGGED.map((e) => e.t);

export function byTag(pool: Tagged[], tag: string): string[] {
  const hit = pool.filter((e) => e.tags.includes(tag)).map((e) => e.t);
  return hit.length ? hit : pool.map((e) => e.t);
}

export const WHO_TWISTS: string[] = [
 "mit einem geliehenen Namen",
 "ohne Erinnerung an den gestrigen Tag",
 "auf der Flucht vor einem Versprechen",
 "mit zitternden Händen",
 "kurz vor dem Aufbruch",
 "voller ungestellter Fragen",
 "mit einem fremden Koffer",
 "zwischen zwei Loyalitäten",
 "mit einer alten Schuld im Gepäck",
 "ohne Papiere",
 "mit einem zweiten Gesicht",
 "mit einem halb vergessenen Auftrag",
 "im falschen Jahrzehnt geboren",
 "mit geliehener Stimme",
 "mit einer Narbe, die niemand erklärt",
 "ohne Rückfahrkarte",
 "mit einem Brief, der nie abgeschickt wurde",
 "unter fremder Aufsicht",
 "mit einem Namen, den zwei Menschen tragen",
 "im letzten Anzug des Vaters"
];
export const WHERE_TWISTS: string[] = [
 "wo die Uhren falsch gehen",
 "wo niemand nach Namen fragt",
 "wo nachts Licht brennt, obwohl niemand wohnt",
 "wo alle Türen offen stehen",
 "wo der Fluss rückwärts zu fließen scheint",
 "wo man Fremde sofort erkennt",
 "wo ein Zimmer seit Jahren verschlossen ist",
 "wo die Karten nicht stimmen",
 "wo jeder zweite Brief verloren geht",
 "wo das Echo eine Sekunde zu spät kommt",
 "wo der Winter nie ganz endet",
 "wo die Wände dünner sind, als man denkt",
 "wo die Straßen keine Namen tragen",
 "wo man den Hafen hört, aber nicht sieht",
 "wo jedes Fenster nach Osten zeigt",
 "wo die Vögel nicht landen",
 "wo eine Uhr seit Jahren dieselbe Zeit zeigt",
 "wo der Boden bei Regen nachgibt"
];
export const WHEN_TWISTS: string[] = [
 "kurz nach der Sperrstunde",
 "in der Nacht der Inventur",
 "am Tag der letzten Fähre",
 "während eines Stromausfalls",
 "zwischen zwei Glockenschlägen",
 "am Vorabend einer Abreise",
 "in der Woche der Nebel",
 "als die Zeitungen schwiegen",
 "während des Jahrmarkts",
 "in der Stunde zwischen Hund und Wolf",
 "kurz bevor die Brücke gesperrt wird",
 "am Morgen nach dem Fest",
 "in der Nacht der langen Regen",
 "während die Glocken repariert werden",
 "kurz vor der Zeitumstellung",
 "als die Straßen leer blieben",
 "in der Woche vor dem Umzug",
 "am Tag, an dem die Post ausblieb"
];
export const WHAT_TWISTS: string[] = [
 "ohne zu wissen, warum",
 "obwohl alle abraten",
 "zum dritten und letzten Mal",
 "gegen ein altes Versprechen",
 "für jemanden, der nie danach gefragt hat",
 "mit den falschen Werkzeugen",
 "unter falschem Namen",
 "bevor es ein anderer tut",
 "aus einem Grund, der erst am Ende zählt",
 "heimlich, zwischen zwei Pflichten",
 "und zahlt dafür einen stillen Preis",
 "als wäre nichts geschehen",
 "mit geliehenem Mut",
 "einen Tag zu spät",
 "und nimmt dafür die Schuld auf sich",
 "ohne Zeugen",
 "während alle anderen feiern",
 "und kann es hinterher nicht erklären"
];
